### ISSUE TITLE
Long running code then attempting to delete an array results in a race condition.

### ISSUE THREAD

**Issue by Alexander1994** [WebAssembly/binaryen#1003]
I am hacking together a large scale minesweeper game in web assembly.
```
void Minefield::addMines(int clickX, int clickY) {
  int* mineRange = getSurroundingMineRange(clickX, clickY);
  int startX = mineRange[2], endX = mineRange[3], startY = mineRange[0], endY = mineRange[1];
  srand(time(NULL));
  int x, y, i = 0;
  while (i < mineCount) {
    x = rand() % width;
    y = rand() % height;
    if (!minefield[y][x].isMineInField() &&
        ( y < startX || y > endX ||
          x < startY || x > endY ) ){
      minefield[y][x].setMineInField();
      incSurroundingMineCount(x,y);
      i++;
    }
  }
  printf("I do\n");
  delete [] mineRange;
  printf("I don't run\n");
}
```
The above code randomly adds a mine to the field outside of the first click range (scales very poorly with the number of mines).  I noticed though as I increased the number of mines in the field the program would crash at `delete [] mineRange;` The bug looks like a race condition where it only crashed if the loop went on for so long. As soon as I moved the delete statement above the loop. it worked fine. Below is the stack trace.
```
Uncaught abort() at Error
    at jsStackTrace (http://127.0.0.1:8000/main.js:1125:13)
    at stackTrace (http://127.0.0.1:8000/main.js:1142:12)
    at Object.abort (http://127.0.0.1:8000/main.js:2968:44)
    at _abort (http://127.0.0.1:8000/main.js:2173:22)
    at  (<WASM>[155]+93)
    at  (<WASM>[161]+11)
    at  (<WASM>[162]+11)
    at  (<WASM>[90]+593)
    at  (<WASM>[59]+58)
    at Module._addMines (http://127.0.0.1:8000/main.js:2688:86)
```
```
  void EMSCRIPTEN_KEEPALIVE addMines(int x, int y) { // coordinates for first click
    minefield->addMines(x, y);
  }
```
The project is available for further inspection on my profile.

**Comment by kripken** [comment]
To debug this, I'd start with building with `-g` so the stack trace is more useful. And see [these options](http://kripken.github.io/emscripten-site/docs/porting/Debugging.html#compiler-settings).

**Comment by Alexander1994** [comment]
Sigh, I can no longer replicate it. The code works just fine. Should probably just close it. I tried all yesterday to get that code to work but it always crashed when the loop went on for a certain period of time then encountered the delete statement. I am rewritting that part of my codebase anyways. It just looked like a pretty big bug to me.

**Comment by kripken** [comment]
Ok. If you can get a reproducible testcase, please reopen or file another issue.
