### ISSUE TITLE
s2wasm: Getting "[[bad mustMatch:]]" parse error

### ISSUE THREAD

**Issue by meta221** [WebAssembly/binaryen#1026]
I tried running s2wasm on the attached file and received the following error:
```
<< h_errno >>
[[bad mustMatch:]]:
==========
.comm   h_errno,4,2
        .type   .L__res_msend_rc.sa,@object # @__re
==========
fish: “s2wasm libc.s” terminated by signal SIGABRT (Abort)
```
I created the file by running `llc` on the `~/.emscripten_cache/asmjs/libc.bc` file that emscripten generates when compiling.

I compiled LLVM from source from the [LLVM mirror repo](https://github.com/llvm-mirror/llvm) on the master branch with commit hash: d6cdc20e21c4ca0a0c9c80c1953784d41c930e2d.

I compiled binaryen from source from the master branch.

I ran `llc` like so:
`$PATH_TO_LLVM/bin/llc -march wasm32 ~/.emscripten_cache/asmjs/libc.bc`

[libc.txt](https://github.com/WebAssembly/binaryen/files/1031953/libc.txt)

**Comment by jgravelle-google** [comment]
So the `asmjs` folder in the emscripten cache is for the asm.js pipeline. Meaning that `libc.bc` was built with the `asmjs-unknown-emscripten` target triple, whereas s2wasm expects the `wasm32-unknown-unknown` triple. So I wouldn't expect that to work.

Of note is that Emscripten supports running the wasm LLVM backend + s2wasm pipeline, https://github.com/kripken/emscripten/wiki/New-WebAssembly-Backend . It uses `~/.emscripten_cache/wasm/` as its cache folder.

**Comment by meta221** [comment]
Thank you very much. I compiled wasm/libc.bc using Emscripten's new WebAssembly backend and it did work.

Although shouldn't every output of llc when it is targeting the "wasm32" architecture be valid for s2wasm to consume?

**Comment by jgravelle-google** [comment]
In theory, probably. In practice, it'll be processing patterns we don't expect, so who knows.
