### ISSUE TITLE
wast to wasm

### ISSUE THREAD

**Issue by pannous** [WebAssembly/binaryen#1044]
What is the new mechanism to convert wast to wasm in js?

 these old approaches don't work anymore:
``` 
Binaryen = require('binaryen.js')
parser = new Binaryen.SExpressionParser(input);
wasm_buffer=Binaryen.compileWast(wast)
```

**Comment by dcodeIO** [comment]
Documentation for the JS-API can be found [at this location](https://github.com/WebAssembly/binaryen/blob/master/docs/binaryen.js.Markdown).

```js
var binaryen = require("binaryen");
var myModule = binaryen.readBinary(input);
var wastString = myModule.emitText();
```

**Comment by pannous** [comment]
Thanks,  the answer seems to be
```
Binaryen = require('binaryen.js')
wast=`(module
  (func $addTwo (param i32 i32) (result i32)
    (i32.add
      (get_local 0)
      (get_local 1)))
(export "addTwo" (func $addTwo))
)`
module=new Binaryen.Module(wast)
module.emitBinary()
```
 unfortunately it hangs here without an error message

**Comment by dcodeIO** [comment]
Hmm, it [doesn't seem that the constructor accepts an argument](https://github.com/WebAssembly/binaryen/blob/master/src/binaryen-c.cpp#L108).

**Comment by pannous** [comment]
sorry I must be blind,  I can't find the proper way to do it.
Going with https://github.com/ewasm/wast2wasm / wabt.js for now

**Comment by kripken** [comment]
Looks like the C API (and binaryen.js) don't have a way to parse the s-expression format yet. We can add it if it would be useful.

Note btw that the text formats that wabt and binaryen parse are not identical. wabts is the official wasm text format, which supports stack machine syntax and so has less structure, while binaryen's text format is closer to a previous version of wasm's text format, without stack machine syntax, and that validates structure fully. For simple things you might not notice a difference though.

**Comment by pannous** [comment]
'not yet' is funny, it did already work before with the methods mention above (`Binaryen.SExpressionParser(wast)` and `Binaryen.compileWast(wast)`)

**Comment by kripken** [comment]
Sorry about that, we did a major rewrite of binaryen.js, from the C++ API to C API. This fixed many issues, but the C API itself is not yet complete, so some things regressed as well.

**Comment by kripken** [comment]
Here's a PR to add text parsing to C API and binaryen.js: #1050

**Comment by pannous** [comment]
beautiful!

`Binaryen.parseText()` now works ++
