### ISSUE TITLE
No way to provide input for stdin

### ISSUE THREAD

**Issue by AlgorithMan-de** [WebAssembly/binaryen#1060]
I'm not sure I'm right here. I have compiled the following small example
```
#include <iostream>
int main(int argc, char** argv)
{
    std::string name;
    std::cin >> name;
    std::cout << "Hello " << name << "!" << std::endl;
    return 0;
}
```
to WebAssembly, using emscripten. When I run it in chrome, it calls `window.prompt` for the stdin input (btw - this is repeated until I click cancel? I find that confusing for the user).

I want to feed the program with text from a textarea instead and tried providing a `Module` object that has a `read` method. Looking at the code
```
else if (ENVIRONMENT_IS_WEB || ENVIRONMENT_IS_WORKER) {
  Module['read'] = function shell_read(url) {
    ...
```
from the initialization, this seems to make perfect sense, but it doesn't work. Digging deeper, I have found that in the construction of `TTY.default_tty_ops.get_char`, the call to `window.prompt` is hard coded, so it seems to me that it is impossible to provide data to stdin in any other way except by replacing `window.prompt` which seems extremely hackish to me.

I helped myself by adding an additional case
```
            } else if (typeof Module['read'] == 'function') {
              result = Module['read']();
```
in `TTY.default_tty_ops.get_char`, before the
```
            } else if (typeof window != 'undefined' &&
              typeof window.prompt == 'function') {
```
and this solves my problem.

Removing my custom `Module.read` though reveals some strange behavior - the default implementation of `Module.read` gets its data from an XmlHttpRequest? Is `Module.read` intended for something different (like loading dependencies)? But the other implementations (for `ENVIRONMENT_IS_NODE` and such) seem to indicate that it _is_ for reading from stdin...?

**Comment by kripken** [comment]
I think the recommended way is to define stdin, see http://kripken.github.io/emscripten-site/docs/api_reference/Filesystem-API.html#setting-up-standard-i-o-devices https://stackoverflow.com/questions/32912129/providing-stdin-to-an-emscripten-html-program

**Comment by AlgorithMan-de** [comment]
I had read the stackoverflow discussion - doing the `FS.init ` didn't seem like it would work, given the hardcoded `window.prompt` in `TTY.default_tty_ops.get_char`, so I hadn't tried it. Now that I did, it works without editing hello.js :+1:
I think though, that the generated `hello.html` should provide an implementation that shows how to do it (it can do `function stdin(){return window.prompt('Input:');}` by default, even if it's redundant - just to have an example).

I also think the svg and the css should go in separate files, because the hello.html becomes so big just because of these 2, it's intimidating - it looks like it's to complicated to understand, so it discourages you from reading and modifying it to your needs.

**Comment by jimmywarting** [comment]
is it possible to use whatwg streams somehow for stdin & stdout?

**Comment by vadimkantorov** [comment]
@kripken Is it possible to define `stdin` on `Module` object without calling `FS.init` in `preInit`?

**Comment by kripken** [comment]
@vadimkantorov I think `FS.init` is necessary to initialize things. It will create the standard streams for example, so I think `stdin` would not be available without calling it.

**Comment by vadimkantorov** [comment]
I've tried. It works just with defining a `stdin` function in the module config object. If there was a way for providing a Uint8Array as stdin (for non-interactive cases), it would probably be even more performant, as dozens of thousands of function calls are not needed then.
