### ISSUE TITLE
Failed to compile LLVM from source on Ubuntu

### ISSUE THREAD

**Issue by OughtImpliesCan** [WebAssembly/binaryen#1078]
Installed virtual box on a windows machine, booting from the latest .iso of Ubuntu from the official Ubuntu download pages:

https://www.ubuntu.com/download

and I'm following the instructions of how to compile LLVM from source that can be found here:

http://webassembly.org/getting-started/developers-guide/

and I'm using these terminal commands (in order):

sudo apt install git
sudo apt install cmake
sudo apt install build-essential
git clone https://github.com/juj/emsdk.git
cd emsdk
./emsdk install sdk-incoming-64bit binaryen-master-64bit

but I'm getting a "Installation Failed" at 54% of whatever process it was at, screen shot can be found here:

https://drive.google.com/file/d/0BwA2KVlVFTQteVJqNWNYX0VOY0Izdk5XOGFaS01ocVF3WjI0/view?usp=sharing

First time I thought it was a lack of storage allocated to Ubuntu so I set the VM to have 50 GB of dedicated space but here we are again... any ideas?

**Comment by brion** [comment]
How much RAM is assigned to the VM? Linking the big LLVM & clang libs is very memory-intensive, and will likely fail if you only have 1 or 2 GB assigned. I've had good luck with 4GB VMs.

**Comment by OughtImpliesCan** [comment]
Just added 4 GB of RAM and these commands into a terminal:

cd emsdk
./emsdk install sdk-incoming-64bit binaryen-master-64bit

initialized to that 54% and now says it's linking but no other messages have been logged to the terminal for about five minutes now, might give it another five minutes but if all else fails I can just wipe this VM and start over with the 50 GB of storage and 4 GB of RAM and see what happens.  Any suggestions?

**Comment by weitjong** [comment]
I believe 4GB is still not enough and build process started to swap, and that killing the performance. You can use the "free -h" command in another terminal to confirm this.

**Comment by OughtImpliesCan** [comment]
Starting over at 4 GB of RAM did the trick, thanks!

**Comment by juj** [comment]
The `signal 9 killed` message seems to always have been due to running out of memory. Sounds like this was fixed, so let me close as resolved.
