### ISSUE TITLE
wasm-as: not naming imports

### ISSUE THREAD

**Issue by JSStats** [WebAssembly/binaryen#108]
Seeing bad code detected as missing a name on an import.

**Comment by kripken** [comment]
More details are needed in bug reports like this, specifically: what input are you providing? What is the output you see, and what is wrong with it? It's usually better to just provide these details in the initial report.

`wasm-as` is tested in check.py, with example outputs in `test/*.fromBinary`. Those have imports which look ok to me.

**Comment by JSStats** [comment]
Track it down to the function signature-index and decl-flags being used in the wrong order. The fix would be to just flip their order in readFunctions and writeFunctions.  The design document has these backyards compared to the v8 reference implementation and the sexpr-wasm-prototype - already noted this at https://github.com/WebAssembly/design/issues/497. I recall encountering issues in the design document but noting move in particular, so practically comparison with the sexpr-wasm-prototype output and v8 testing might be needed.

**Comment by kripken** [comment]
I don't understand how changing the order of those two fields would solve something to do with imports not being named?

**Comment by JSStats** [comment]
The input was corrupted, misunderstood.
