### ISSUE TITLE
Calling imported functions using binaryen.js always fails to validate

### ISSUE THREAD

**Issue by dcodeIO** [WebAssembly/binaryen#1080]
Basically, I have the following simple module:

```s
(module
 (type $v (func))
 (import "env" "fn" (func $fn))
 (memory $0 0)
 (export "main" (func $main))
 (func $main (type $v)
  (call $fn)
 )
)
```

I created it using binaryen.js, using this code:

```ts
var module = new binaryen.Module();

var signature = module.addFunctionType("v", binaryen.none, []);
module.addImport("fn", "env", "fn", signature);

module.addFunction("main", signature, [], module.block("", [
  module.call("fn", [], binaryen.none)
]));
module.addExport("main", "main");

console.log(module.emitText());

module.validate(); // fails
```

Calling `Module#validate()` always fails when calling an imported function like this, with the following error:

```
[wasm-validator error in function $main] unexpected false: call target must exist, on
(call $fn)
```

Is that a usage error on my side or did I stumble over an issue here?

**Comment by kripken** [comment]
This is a confusing thing that we should document better. Wasm has just a Call node, while Binaryen IR has separate Call and CallImport. In this example, it works with `module.callImport`. Better docs and error reporting in #1081.

**Comment by dcodeIO** [comment]
Thanks, that makes sense. For what it's worth, [this markdown file](https://github.com/WebAssembly/binaryen/blob/master/docs/binaryen.js.Markdown) documents a second `call` function named just like the first, that's why I got it wrong (assumed this had been merged).

**Comment by kripken** [comment]
Thanks, yeah, that's a typo. Will fix in that PR.
