### ISSUE TITLE
Tracking the lastest llvm backend .s output

### ISSUE THREAD

**Issue by JSStats** [WebAssembly/binaryen#109]
Noticed that asm2wasm has not worked for a few days. Seems due to the significant changes to blocks and labels.

**Comment by kripken** [comment]
Bug reports like this would be more useful with details. What error do you see? What platform? Which revision?

asm2wasm is tested in check.py, which passes - you can see on the travis-ci link on the [main binaryen page](https://github.com/WebAssembly/binaryen). It also passes for me locally.

**Comment by JSStats** [comment]
@kripken noted off-list that the problem was caused by an 'address taken but is not implemented' and the failure occurred trying to convert only .s file of a larger project, thank you. So the lesson is to not expect to be able to convert individual .s files to wast. That also seems to make wast/wasm not suitable as an 'object code' format even for pieces of statically linked code, but I guess that is fine because the bc will be linked.
