### ISSUE TITLE
Binary writer bug

### ISSUE THREAD

**Issue by DiamondLovesYou** [WebAssembly/binaryen#1097]
Hello all,

I've discovered a bug in `WasmBinaryWriter` which causes the binary reader to not have enough expressions to pop ("attempted pop from empty stack"). Chrome and FF also emit similar errors. The module also passes all verification.

One may reproduce with [this file](https://gist.githubusercontent.com/DiamondLovesYou/d5fbf3865a2bf5f6a36cf3ddc66efcc8/raw/aba9535c8a3828ca15041787be2b8883503fbcc6/libc.wast): `wasm-opt libc.wast -o libc.wasm && wasm-dis libc.wasm -o /dev/null`.

I've tried to dig into this, but I've thus far come up empty. I'd really appreciate help tracking this down!

**Comment by kripken** [comment]
When I do `bin/wasm-opt libc.wast -o libc.wasm` on that file, I get
````
wasm-as: /home/alon/Dev/binaryen/src/wasm/wasm-binary.cpp:348: uint32_t wasm::WasmBinaryWriter::getFunctionIndex(wasm::Name): Assertion `mappedFunctions.count(name)' failed.
````
Investigating, it is trying to find what to do for `$exp`. And that function seems to be used in the table, but not imported or defined, so the wasm file looks invalid. How was it created?

(And what version of binaryen did you use? Odd that you saw another error.)

**Comment by DiamondLovesYou** [comment]
I'm building a dynamic linker for wasm, so I've made a few changes to the way s2wasm links and is the reason you see a different error (and I forgot). Let me see what code I can submit PRs for (waiting to hear back..).

In this specific case, the function ptr will be set in the table after the module is instantiated.

However I'm surprised `exp` isn't in this `libc` code (it's the libc `embuilder.py` produces in the cache). I'm not using (most of) Emscripten for this work, I've reused a previous [project](https://github.com/DiamondLovesYou/pnacl-clang-driver) of mine as a driver, and am only reusing the system libraries from Emscripten. It looks like most of the math functions are defined in `wasm-libc.bc`, so it looks like I'll have to add that library to what's distributed with the rest of LLVM (which is what I'm currently porting to WebAssembly). It wasn't your intention, but nice catch, thanks!

**Comment by DiamondLovesYou** [comment]
I should add that this issue happens on every LLVM shared component built, not just on the `libc` I've provided.

**Comment by binji** [comment]
Can you include a link to the generated wasm file? That will make it easier to see what is failing.

**Comment by DiamondLovesYou** [comment]
Sure: https://gist.github.com/DiamondLovesYou/d5fbf3865a2bf5f6a36cf3ddc66efcc8/raw/5ebe3567b4de506d79813ca2423e4e85b457a1b5/libc.wasm

**Comment by binji** [comment]
There are a number of issues with this file, so it's hard to tell. Just trying to read it via wast2wasm or wasm-objdump fails because of an out-of-range index on a function call. Disabling that error manually, there seems to be issues with the name section too. Disabling that produces a huge number of type checking errors:

```
libc.wasm:0003aa5: error: type stack size too small at call. got 2, expected at least 4
libc.wasm:0003ab4: error: type stack size too small at call. got 2, expected at least 4
...
```

Cross-referencing these against wasm-objdump output:
```
003a82 func[0]:
 003a8a: 02 7f                      | block i32
 003a8c: 41 00                      |   i32.const 0
 003a8e: 41 00                      |   i32.const 0
 003a90: 28 02 04                   |   i32.load 2 4
 003a93: 41 10                      |   i32.const 16
 003a95: 6b                         |   i32.sub
 003a96: 22 01                      |   tee_local 1
 003a98: 36 02 04                   |   i32.store 2 4
 003a9b: 20 01                      |   get_local 1
 003a9d: 20 00                      |   get_local 0
 003a9f: 28 02 3c                   |   i32.load 2 60
 003aa2: 10 ee 09                   |   call 1262
 003aa5: 36 02 00                   |   i32.store 2 0
 003aa8: 41 06                      |   i32.const 6
 003aaa: 20 01                      |   get_local 1
 003aac: 41 00                      |   i32.const 0
 003aae: 11 02 00                   |   call_indirect 2 0
 003ab1: 10 cc 01                   |   call 204
 003ab4: 21 00                      |   set_local 0
 003ab6: 41 00                      |   i32.const 0
 003ab8: 20 01                      |   get_local 1
 003aba: 41 10                      |   i32.const 16
 003abc: 6a                         |   i32.add
 003abd: 36 02 04                   |   i32.store 2 4
 003ac0: 20 00                      |   get_local 0
 003ac2: 0b                         | end
 003ac3: 0b                         | end
```

Here are the relevant signatures:
```
 - func[204] sig=31
 - func[1262] sig=78

 - type[31] (i32, i32, i32, i32) -> i64
 - type[78] (f64, i32, i32, i32) -> i32
```

If I had to guess, I think your linker is not properly remapping function or type indexes.

**Comment by DiamondLovesYou** [comment]
That has been an issue additionally. I'll look into this. However, wouldn't those incorrect indexes be caught by the verifier?

**Comment by binji** [comment]
I don't think the bad indexes can be caught any earlier than they currently are. There's nothing wrong with them as they are defined, just how they are actually used.

**Comment by froydnj** [comment]
Can we go ahead and close this, then, @binji?

**Comment by binji** [comment]
I don't really know enough about Binaryen to say if there's a problem here, but it seems this issue is stale. @DiamondLovesYou, feel free to reopen if this is in error.
