### ISSUE TITLE
Will multiple return values for functions, blocks, instructions work w/ binaryen?

### ISSUE THREAD

**Issue by binji** [WebAssembly/binaryen#1101]
We discussed today in the CG meeting about multiple return values, and are not certain about how these will work with the Binaryen AST. Any thoughts about this?

(See the current proposal here: https://github.com/WebAssembly/multi-value/blob/master/proposals/multi-value/Overview.md)

**Comment by kripken** [comment]
Hard to say offhand. Are there any numbers on the expected benefits to code size and/or perf? (the link mentions as motivation what this could allow, but not why allowing those things would help?) It would depend on that I think.

**Comment by binji** [comment]
I think some folks are guessing that it will have some benefit, but we would like to gather some data, which is why it would be useful to do experiments via binaryen if possible.

In particular, we were curious about the benefits of adding the `pick` operator, and fully generalized block signatures. The benefits of multiple return values is clearer.

**Comment by kripken** [comment]
Probably some simple experiment could try to estimate `pick`'s benefits, but to really measure it properly would take some more involved work. Another option that seems simpler is to take a platform that has pick (Java?) and see if it can be disabled/removed there, and how that affects code size.

Overall though, from a wasm optimizer's point of view, I think the less complexity the better - so we can focus more on fewer things. So all these proposed features sound somewhat concerning.

**Comment by binji** [comment]
I don't know anything about java bytecode, but I only see dups: https://en.wikipedia.org/wiki/Java_bytecode_instruction_listings. Still may be useful for experimentation, though.

**Comment by nomeata** [comment]
I would already be happier if the multi-value extension were supported just by `wasm-dis` :-)

**Comment by tlively** [comment]
@kripken and I discussed this a little while ago. We certainly need to support reading multivalue and writing multivalue as a stack IR optimization, but it’s unclear to what extent binaryen IR will natively support multivalue. I had an idea that was similar to YAML references and anchors that would turn the expression tree into a DAG while encapsulating shared references in special expression nodes that know how to deal with them, but that needs to be prototyped and thought about further.

**Comment by osa1** [comment]
I just tried this today with `wasm-opt version 114 (version_110-584-gcdb7aeab4)` and it looks like Binaryen now supports multiple returns in functions. With `wasm-opt -S` it shows this:

```wat
(type $type$64 (func (result (ref null $type$16) i32)))
...
(func $_testingMultipleReturns (type $type$64) (result (ref null $type$16) i32)
 (drop
  (call $print
   (global.get $global$10)
  )
 )
 (tuple.make
  (ref.null none)
  (i32.const 123)
 )
)
```

Should this issue be closed?
