### ISSUE TITLE
asm2wasm: incorrect translation of switch for big 64 bit values

### ISSUE THREAD

**Issue by pepyakin** [WebAssembly/binaryen#1109]
Source: https://github.com/rust-lang/rust/issues/42630#issuecomment-317270175

For example:

```javascript
function () {
  "use asm";

  var abort=env.abort;

  function main() {
    var $0 = i64(), $x = i64();
    $x = i64_const(0,0);
    $0 = $x;
    switch (i64($0)) {
      case i64_const(0,2146435072):  {
          abort();
	  break;
      }
      default: {
        return;
      }
    }
  }
  return { main: main };
}
```

gets translated to

```
(module
 (type $FUNCSIG$v (func))
 (import "env" "abort" (func $abort))
 (import "env" "memory" (memory $0 256 256))
 (import "env" "table" (table 0 0 anyfunc))
 (import "env" "memoryBase" (global $memoryBase i32))
 (import "env" "tableBase" (global $tableBase i32))
 (export "main" (func $main))
 (func $main
  (local $$0 i64)
  (local $$x i64)
  (set_local $$x
   (i64.const 0)
  )
  (set_local $$0
   (get_local $$x)
  )
  (block $switch
   (block $switch-default
    (block $switch-case
     (br_table $switch-case $switch-default
      (i32.wrap/i64
       (i64.sub
        (get_local $$0)
        (i64.const 9218868437227405312)
       )
      )
     )
    )
    (block
     (call $abort)
     (br $switch)
    )
   )
   (return)
  )
 )
)
```

IIUC, `i32.wrap/i64` takes i64 and trunctates it to only lower 32 bits. So in this case, result of `i32.wrap/i64` will be `0`, meaning first switch-case will be taken and then program aborted.

**Comment by kripken** [comment]
Thanks for reporting, proposed fix in #1111. This makes it check if the offset condition has any upper bits, in which case it branches to the default. Does the output look ok to you?
````
 (func $main
  (local $$0 i64)
  (local $$x i64)
  (local $2 i64)
  (set_local $$x
   (i64.const 0)
  )
  (set_local $$0
   (get_local $$x)
  )
  (block $switch
   (block $switch-default
    (block $switch-case
     (br_table $switch-case $switch-default
      (i32.wrap/i64
       (block (result i64)
        (set_local $2
         (i64.sub
          (get_local $$0)
          (i64.const 9218868437227405312)
         )
        )
        (br_if $switch-default
         (i32.wrap/i64
          (i64.shr_u
           (get_local $2)
           (i64.const 32)
          )
         )
        )
        (get_local $2)
       )
      )
     )
    )
    (block
     (call $abort)
     (br $switch)
    )
   )
   (return)
  )
 )
````

**Comment by pepyakin** [comment]
Looks good to me. However, I would like to validate this PR on the [original case](https://github.com/rust-lang/rust/issues/42630#issuecomment-317251311). But I'm not sure how I can build emscripten with binaryen on #1111 branch...

**Comment by kripken** [comment]
To validate, check out and build binaryen manually. Then set the env var `BINARYEN` to point to the the dir containing binaryen when running emcc.

**Comment by pepyakin** [comment]
Is there any way to pass this to rustc? 
`BINARYEN` env var doesn't work (

**Comment by kripken** [comment]
Hmm, I don't know how rustc works. But if the env var fails, you can edit the `~/.emscripten` file to point `BINARYEN_ROOT` to the dir you have binaryen. (Unless rustc customizes the location of the `.emscripten` file? Probably it doesn't but I'm not sure.)

**Comment by pepyakin** [comment]
Yep, that worked, thank you! 
Can confirm that the original case is valid!

**Comment by kripken** [comment]
Thanks for confirming, merged.
