### ISSUE TITLE
Is it possible to compile binaryen.js to wasm 

### ISSUE THREAD

**Issue by nidin** [WebAssembly/binaryen#1112]

**Comment by kripken** [comment]
Yes, just adding `-s WASM=1` should do that. The only reasons we don't do it now is we want it to work in JS shells even if wasm isn't present (e.g. older node.js), and it means a separate file on the side, as opposed to a single file for everything.

**Comment by nidin** [comment]
Perfect👍🏻. Thanks for the quick response 🙂
