### ISSUE TITLE
s to wasm testing

### ISSUE THREAD

**Issue by getsidd** [WebAssembly/binaryen#1137]
Hi,
This is Surya. I'm using LLVM + binaryen to convert a c file to an s file and then s to wasm. I want to run some tests for the binaryen tool chain. But in the tests folder under llvm_generated, its only testing from s->wast. Is there any way i can test s->wast->wasm. For the last bit, i would need to have the correct wasm files to the corresponding s files to check whether the tool wasm-as is working properly. I'm not able to find the right wasm files. Any help is appreciated.

**Comment by kripken** [comment]
You can use `wasm-as` to convert a wast file to a wasm file.

**Comment by getsidd** [comment]
Hey kripken,

Yes, i can do that but i want to test wasm-as. So in order to validate the output from wasm-as i would need to have a reference wasm file to check with right. I was wondering if i can find something like that to test it.

**Comment by kripken** [comment]
There isn't another way that I can think of to get a reference wasm. The best we can do is wasm-as. (If we wanted to add those tests to the main repo, that's what we'd do, run wasm-as and check those in, consider them as references, and then it would protect against regressions later.)

**Comment by getsidd** [comment]
Cool. Thanks, I'll use wasm-as.
