### ISSUE TITLE
Support BINARYEN_TRAP_MODEs for upstream wasm backend

### ISSUE THREAD

**Issue by dschuff** [WebAssembly/binaryen#1143]
Currently the implementation of clamping and JS mode for trapping float->int conversions and division is in asm2wasm. But it we should support this functionality with the wasm backend as well. Probably we can just move the implementation from asm2wasm into a Binaryen pass, and support it in s2wasm as well.

**Comment by jgravelle-google** [comment]
Supported in https://github.com/WebAssembly/binaryen/pull/1168 and https://github.com/WebAssembly/binaryen/pull/1210
