### ISSUE TITLE
s2wasm --global-endpoint as opposite to --global-base

### ISSUE THREAD

**Issue by Joffrey** [WebAssembly/binaryen#1144]
For some reasons, I would like to be able to store data from a javascript perspective in the «heap» (WebAssembly.Memory.Buffer).
But I cannot properly establish where I can start to instance my memory dynamically from javascript, the global values are stored in the heap and a --global-end parameter for s2wasm could be great. We should be able to set a position in the memory where the global cannot overflow (it can involves some warnings message during s2wasm processing...).

**Comment by Joffrey** [comment]
I close this issue because a possible (and enough) workaround is about the .stack symbol provided by s2wasm.

Thanks to Derek Schuff.

```
00:16:16        dschuff | oh btw, for the .stack thing, you might be able  
                        | to declare a .stack extern in your C code and    
                        | have get get resolved by s2wasm                  
```

**Comment by dschuff** [comment]
Just for posterity, the details are that you specify the stack size with s2wasm's `--allocate-stack` flag, so the end of the stack space is `.stack` plus whatever you specify the stack size to be.
