### ISSUE TITLE
Deployment of static binaries to GH releases does not work due to wrong API token

### ISSUE THREAD

**Issue by jirutka** [WebAssembly/binaryen#1146]
https://travis-ci.org/WebAssembly/binaryen/jobs/267886940#L992:

> Dpl does not have permission to upload assets. Make sure your token contains the repo or public_repo scope.
> failed to deploy

**Comment by kripken** [comment]
Thanks for noticing. Strange, I thought we checked this worked properly when we added it, but I guess not...

Looking quickly now, I don't see anything obviously wrong, and I don't have time to investigate this in depth. Opened #1160 to remove this stage until we can find time to figure this out.

**Comment by jirutka** [comment]
No, we didn’t, I cannot check your token for you… Most likely you didn’t select the scope `public_repo` when creating the token. So you have to go to https://github.com/settings/tokens, Edit the token and select scope public_repo.

**Comment by jirutka** [comment]
After that you should restart the failed Deploy jobs in https://travis-ci.org/WebAssembly/binaryen/builds/267886933.

**Comment by kripken** [comment]
I meant, I thought that the error in the logs that you noticed now wasn't in existence back then. Strange how it was missed...

Thanks, I edited the token now and restarted one of those jobs to see how it works.

**Comment by kripken** [comment]
Looks like it's working...

**Comment by jirutka** [comment]
Yeah, this is already fixed.
