### ISSUE TITLE
Crash in wasm-opt on certain optimisation levels

### ISSUE THREAD

**Issue by conrad-watt** [WebAssembly/binaryen#1149]
The attached (small) wast file crashes wasm-opt for any optimisation level other than O0 or O1.

[test.wast.zip](https://github.com/WebAssembly/binaryen/files/1257807/test.wast.zip)

Tested with the current head of master.

Reproduction steps:
Run
wasm-opt test.wast -O

Output:
wasm-opt: ../src/ast/block-utils.h:47: wasm::Expression* wasm::BlockUtils::simplifyToContents(wasm::Block*, T*, bool) [with T = wasm::Vacuum]: Assertion `isConcreteWasmType(block->type) && singleton->type == unreachable' failed.
Aborted (core dumped)

**Comment by kripken** [comment]
Thanks! Interesting that the fuzzer didn't find this, I'll need to figure out why.

Fix in d199aafed128cdf52de229aba4cf4c6769929e71 on the `fuzz` branch. That's waiting on another branch to land first.

**Comment by conrad-watt** [comment]
Fixed by #1154.Thanks!
