### ISSUE TITLE
Question regarding versioning

### ISSUE THREAD

**Issue by dcodeIO** [WebAssembly/binaryen#1156]
For my binaryen.js buildbot I am currently using the emscripten tags (i.e. 1.37.20) as the package's version, which is probably wrong. So I am wondering about the meaning of "version_37" in a major.minor.build way. Is that 0.0.37 or is it safe to assume 37.0.0? And should I use that instead?

**Comment by kripken** [comment]
The two version numbers are actually independent. Binaryen version_37 is just a tag on binaryen, usually done when it seems stable and a good time for other projects (including emscripten) to update. The idea is to keep binaryen independent of emscripten (which is just one user of binaryen).

In emscripten, we update the binaryen port when a new binaryen version is tagged. This is independent of emscripten version changes.

**Comment by dcodeIO** [comment]
I see. So, if you'd publish current binaryen.js to npm, what version number (A.B.C form) would you use? 0.0.37 ? 37.0.0 ?

**Comment by kripken** [comment]
I haven't thought that far ;) Open to ideas.

**Comment by dcodeIO** [comment]
Well, [currently](https://www.npmjs.com/package/binaryen) the buildbot is using 1.37.20. Suggesting to change that to 37.0.0 and go with the version tag from now on. However, that'll pretty much prevent any future versioning changes, at least for this exact package. That's why I'm asking - don't want to mess this up.

**Comment by kripken** [comment]
Got it. Then yeah, makes sense to move to 37.0.0. (And maybe someday we'll have a use for the minor numbers, if we have bugfix-only updates etc.; for now each update can change APIs.)

**Comment by dcodeIO** [comment]
Great, thanks!
