### ISSUE TITLE
Travis CI build resources

### ISSUE THREAD

**Issue by binji** [WebAssembly/binaryen#1161]
It seems that Travis jobs are queuing for quite a bit longer now. I read somewhere that we get 5 concurrent jobs per organization. Our jobs used to be reasonably fast all around (~7 min), but now the alpine builds seem to be ~40 min for 3 of the jobs. Perhaps we shouldn't run these for each PR + branch -- can we make these periodic builds instead?

**Comment by kripken** [comment]
Yeah, that sounds bad. I guess [cron jobs](https://docs.travis-ci.com/user/cron-jobs/) is the way to do that?

**Comment by binji** [comment]
Looks like the `ppc64le` build on master is timing out after 6 hours.

**Comment by binji** [comment]
Hm, don't know what changed but it looks like those builds are finishing now.
