### ISSUE TITLE
Errors on clang due to implicit fallthrough in switch statements

### ISSUE THREAD

**Issue by JohnSully** [WebAssembly/binaryen#1164]
I'm building with a development build of clang.  It provides the following warning:

When building I get the following errors:
/home/john/repos/binaryen/src/wasm/wasm-s-parser.cpp:871:9: error: this statement may fall through [-Werror=implicit-fallthrough=]
if (!strncmp(str, "wake", strlen("wake"))) return makeAtomicWake(s);

I created a patch here, however it is clang specific and ultimately not the correct fix.
https://github.com/WebAssembly/binaryen/pull/1162

**Comment by dschuff** [comment]
This should be fixed with #1196
