### ISSUE TITLE
wasm-opt failing on a read access violation

### ISSUE THREAD

**Issue by Markyparky56** [WebAssembly/binaryen#1228]
Using a fresh compile of the latest commit, but have also tested the last 3 tagged releases ([1.37.22](https://github.com/WebAssembly/binaryen/commit/a8da89653981bb37565981afc69104f918fea64a), [version_38](https://github.com/WebAssembly/binaryen/commit/8283229f6bccdcfa60d7613be10d0f93531fdd34), and [1.37.21](https://github.com/WebAssembly/binaryen/commit/d621116cada789d15c569385ea79a57ba534c08f)). 
Running wasm-opt on various .wat/.wast and .wasm files under windows consistently causes the program to open a window saying "wasm-opt has stopped working" and offers to close or debug the program. Attempting to debug with Visual Studio 2017 (having built binaryen with VS) opens up in pass.cpp, on line 288 with an unhandled exception

```
Exception Unhandled
Unhandled exception thrown: read access violation.
pass-> was 0xFFFFFFFFFFFFFFDF.
```

Depending on what I'm telling wasm-opt to try and do, the size of passes varies, from 26 with -O3, to just 1 when trying to run the wasm-opt example in the Readme (though, the lower-if-else pass has since been removed, so I subbed in the simplify-locals pass). 

I've tried running this on both large and small wasm/wast files, and on a tiny testcase (attached below).

Additionally attempting -O0 causes raises a Debug Assertion for `vector subscript out of range`.
Debugging takes me to line 100 of wasm-binary.cpp
```
std::move(&o[start + MaxLEB32Bytes], &o[start + MaxLEB32Bytes + size], &o[start + sizeFieldSize]);
```
This is likely because `start + MaxLEB32Bytes + size` evaluates to the total size of the vector, which is off the end. 

[latest.zip](https://github.com/WebAssembly/binaryen/files/1395760/latest.zip)

**Comment by kripken** [comment]
Is line 288 in pass.cpp the second line of this?
````
    for (auto* pass : passes) {
      if (pass->isFunctionParallel()) { // line 288 on master
        stack.push_back(pass);
      } else {
        flush();
        pass->run(this, wasm);
      }
    }
````
Very strange how that could be an invalid pointer.

As for the `move`, it should be valid - the last element is not copied, the range is `[first, last)` (i.e. does not include the last), http://en.cppreference.com/w/cpp/algorithm/move

So in both cases I'm puzzled. Maybe memory corruption somehow? Does VS have something like valgrind perhaps?

**Comment by Markyparky56** [comment]
Yes, that's the loop that Visual Studio keeps pointing me to with the exception. 

I build using the cmake commands
```
cmake -G "Visual Studio 15 2017 Win64" . && cmake --build .
```
Which I think defaults to Debug, looking at the .ilk and .pdb files it fills the bin folder with for each executable, but I also tried compiling specifying -DCMAKE_BUILD_TYPE=Release and RelWithDebInfo prior to making this and both of those still pointed me there. 

Not sure about valgrind, never heard of it let alone used it, any specific process you're looking for? 

I can add a watch to `passes` and take a look at it's contents. Doing this for wasm-opt on the wasm file from the testcase shows a std::vector of size 26, each of the elements (besides having a value/address) shows up as:
```
-		[0]	0x0000000000aafc80 {name=<Error reading characters of string.> }	wasm::Pass *
+		__vfptr	0xdddddddddddddddd {???, ???, ???, ???, ???, ???}	void * *
+		name	<Error reading characters of string.>	std::basic_string<char,std::char_traits<char>,std::allocator<char> >
````

Can't immediately wrangle cmake to build binaryen with mingw, as it gets stuck trying to compile a dummy executable, so can't check if it's a visual studio/msbuild/windows exclusive issue.
```
CMake Error at CMakeLists.txt:121 (if):
  if given arguments:

    "C:/binaryen_mingw/dummy" " PE32+ executable for MS Windows (console) Mono/.Net assembly

  " "MATCHES" "x86[-_]64"

  Unknown arguments specified
```

Going to see how it copes on my Windows 10 machine, which also has VS2017. Unfortunately don't have any *nix installations but given your puzzlement this feels like something which you haven't experienced before?

**Comment by Markyparky56** [comment]
Same issue on Windows 10, steps to reproduce:

```
git clone https://github.com/webassembly/binaryen.git
cd binaryen
cmake -G "Visual Studio 15 2017 Win64" .
cmake --build .
bin\wasm-opt test\passes\simplify-locals.wast --print 
```

**Comment by kripken** [comment]
valgrind is a linux tool that can detect memory corruptions of various forms. I thought I heard msvc had some memory corruption checks of its own.

We've received no other reports of complete breakage on windows, so perhaps this is a recent regression? Might be worth looking further back in the tags til you find one that works, then bisect.

**Comment by Markyparky56** [comment]
According to this [SO post](https://stackoverflow.com/questions/413477/is-there-a-good-valgrind-substitute-for-windows) Dr. Memory can achieve some of valgrind's functionality on windows, so ran the `wasm-opt test\passes\simplify-locals.wast --print` through it. 

Output:
```
Dr. Memory version 1.11.0 build 2 built on Aug 29 2016 02:41:18
Dr. Memory results for pid 3808: "wasm-opt.exe"
Application cmdline: "c:\binaryen\bin\wasm-opt.exe c:\binaryen\test\passes\simplify-locals.wast --print"
Recorded 115 suppression(s) from default C:\Program Files (x86)\Dr. Memory\bin64\suppress-default.txt

Error #1: UNADDRESSABLE ACCESS of freed memory: reading 0x00000000011feff0-0x00000000011feff8 8 byte(s)
# 0 wasm::PassRunner::run               [c:\binaryen\src\passes\pass.cpp:288]
# 1 main                                [c:\binaryen\src\tools\wasm-opt.cpp:177]
Note: @0:00:03.676 in thread 14320
Note: 0x00000000011feff0-0x00000000011feff8 overlaps memory 0x00000000011feff0-0x00000000011ff028 that was freed here:
Note: # 0 replace_operator_delete_nothrow                            [d:\drmemory_package\common\alloc_replace.c:2974]
Note: # 1 std::_Container_base12::~_Container_base12                 [c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.11.25503\include\xutility:116]
Note: # 2 std::_String_val<>::~_String_val<>
Note: # 3 std::_Compressed_pair<>::~_Compressed_pair<>
Note: # 4 std::_String_alloc<>::~_String_alloc<>                     [c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.11.25503\include\xstring:1742]
Note: # 5 std::basic_string<>::~basic_string<>                       [c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.11.25503\include\xstring:2247]
Note: instruction: mov    (%rax) -> %rax
```

wasm-opt then crashed as expected. 

Decided to step through wasm-opt, since VS does let you pass command line arguments when running the application with the debugger. The issue appears to arise between lines 176 and 177

```
PassRunner passRunner = options.getPassRunner(wasm);
passRunner.run();
```
Looking at `getPassRunner`, passes is fine until it returns passRunner
```
PassRunner getPassRunner(Module& wasm) {
  PassRunner passRunner(&wasm, passOptions);
  if (debug) passRunner.setDebug(true);
  for (auto& pass : passes) { // passes is a vector with 1 pass here 
    if (pass == DEFAULT_OPT_PASSES) {
      passRunner.addDefaultOptimizationPasses();
    } else {
      passRunner.add(pass); // Following this through adds a valid pass
    }
  }
  return passRunner; // Everything looks fine 
}
```
However, because we're returning a local its destructor gets called when we leave the function, which is defined as:
```
PassRunner::~PassRunner() {
  for (auto pass : passes) {
    delete pass;
  }
}
```
This deletes any passes stored, which is a good idea since those are pointers which would otherwise leak,  but seems to be fouling up the returned object. As a quick fix attempt I switched `getPassRunner` over to returning a pointer and deleting it after the call to `passRunner->run()` which seems to avoid it breaking. Additionally this seems to be the only call to `options.getPassRunner()` and seems to date back to [this commit](https://github.com/WebAssembly/binaryen/commit/c977ef7266b13a16d6abe26a38bd9098a02360ac)?

Sticking with that little fix, and trying to run `wasm-opt -O1` on the testcase.wat file, I'm back to the `vector subscript out of range` error in `WasmBinaryWriter::finishSection` with the std::move call I mentioned earlier. It's possible it may work without debug assertions in place, msvc is probably just especially prudent/pedantic, but I think you can use some pointer math to achieve the same?

Changing the [] lookup off the end of the vector to lookup at the end then add 1 to the reference in `finishSection`
```
// Before
std::move(&o[start + MaxLEB32Bytes], &o[start + MaxLEB32Bytes + size], &o[start + sizeFieldSize]);
// After
std::move(&o[start + MaxLEB32Bytes], &o[start + MaxLEB32Bytes + size-1]+1, &o[start + sizeFieldSize]);
```
And `writeFunctions`
```
// Before
std::move(&o[start], &o[start + size], &o[sizePos + sizeFieldSize]);
// After
std::move(&o[start], &o[start + size-1]+1, &o[sizePos + sizeFieldSize]);
```

Seems to work fine, no complaints or errors. Unfortunately the .end() iterator is not dereferencable, because `&*o.end()` looks so much nicer.

Apologies if this was rather rambling, but I just had it open as I worked my way through and recorded findings and changes.

**Comment by kripken** [comment]
Interesting stuff. Do you want to submit PRs with these fixes, and we can discuss in more detail in those?

**Comment by binji** [comment]
> This deletes any passes stored, which is a good idea since those are pointers which would otherwise leak, but seems to be fouling up the returned object.

Ah, looks like `PassRunner` needs a copy constructor. My guess is that gcc/clang are always optimizing using NRVO so the default copy constructor is never called.

> msvc is probably just especially prudent/pedantic, ...

Yes, I've seen similar things w/ MSVC and w/ ubsan. If you think about it, it makes sense. The MSVC vector has an operator[] that is doing bounds checks. It doesn't know that you're just taking the address of the end, it still has to access the end value.

You should be able to move the arithmetic outside of the `[]` to workaround, I think:
```
std::move(&o[start] + MaxLEB32Bytes, &o[start] + MaxLEB32Bytes + size, &o[start] + sizeFieldSize);
```

**Comment by Markyparky56** [comment]
Created a branch on a personal fork [here](https://github.com/Markyparky56/binaryen/tree/wasm-binary_std_move_msvc_vector_out_of_bounds_fix) with the std::move fix, which I can create a pull request for, is there anything I have to do before that?

For the PassRunner fix, a copy constructor may not be the easiest fix because of PassRunner's destructor and its vector of pointers to wasm::Pass objects, do you want me to create a pull request for the quick fix with a pointer or work out one for a copy constructor?

**Comment by kripken** [comment]
Thanks, please open a PR for the move issue. You should join the [community group](https://www.w3.org/community/webassembly/participants) before we merge it.

Good point about the passRunner issue. Maybe we should change the API there. I can look into that one.

**Comment by Markyparky56** [comment]
[std::move fix PR](https://github.com/WebAssembly/binaryen/pull/1233)

**Comment by kripken** [comment]
I opened #1234 for the PassRunner issue.

Side note, it would be good if we found a way to run tests on windows too. Right now our CI only checks that it builds.

**Comment by Markyparky56** [comment]
As another side note, while I was digging through wasm-opt, I noticed you declare a `std::vector<std::string> passes` in the main function, which is never used. Probably left over from a previous iteration.

**Comment by kripken** [comment]
Thanks, added to that PR.

**Comment by Markyparky56** [comment]
Since both the read access violation issue and the vector subscript out of range issue have been sorted, shall we close this issue?

**Comment by kripken** [comment]
Yes.
