### ISSUE TITLE
wasm-as: tableswitch has an incorrect number of targets in the encoding

### ISSUE THREAD

**Issue by JSStats** [WebAssembly/binaryen#123]
Seeing a off-by-one issue in the tableswitch output. The following also loses the default case when round-tipping wasm-as and wasm-dis - not sure if related.

```
(module
  (memory 0 0)
  (func $f1 (param $x i32) (result i32)
    (block $topmost
      (tableswitch $switch$0
        (i32.sub
          (get_local $x)
          (i32.const 1)
        )
        (table (case $switch-case$1) (case $switch-case$2)) (case $switch-case$1)
        (case $switch-case$1
          (br $topmost
            (i32.const 1)
          )
        )
        (case $switch-case$2
          (br $topmost
            (i32.const 2)
          )
        )
      )
      (i32.const 0)
    )
  )
)
```

Looking at the encoding demonstrates the problem:

sexp-prototype:
```
0000012: 08                                         ; OPCODE_TABLESWITCH
0000013: 0200                                       ; num cases
0000015: 0300                                       ; num targets  <<<<
0000017: 0000                                       ; case index
0000019: 0100                                       ; case index
000001b: 0000                                       ; case index
000001d: 41                                         ; OPCODE_I32_SUB
```

wasm-as:
```
08
0200
0200   ; num targets  <<<< wrong
0000
0100
41
```

**Comment by JSStats** [comment]
Sorry, also should have noted it drops the case index for the default at `0000019` abovr.

**Comment by kripken** [comment]
Well, there are 2 targets - so that part looks right?

There is also a default, and this is indeed lost in the binary format. But reading the spec document, I'm not clear on how exactly the default is encoded?

**Comment by kripken** [comment]
@titzer: is it possible that handling of the default in tableswitch is missing in the v8 binary format document?

**Comment by binji** [comment]
No, `num targets` includes the default, which is always last. So `num targets` must be >= 1.

**Comment by kripken** [comment]
Thanks, now I see. Fixed.
