### ISSUE TITLE
Possible mis-interpretation of import and export function names.

### ISSUE THREAD

**Issue by ghost** [WebAssembly/binaryen#124]
The encoding supports names for functions, and notes imports and exports. It does not appear to prohibit names on other functions, but imports and exports have both an external name and an internal label name which can be different but there is only support for one name - I expect it needs to be interpreted as the external name and that there is no support for naming the internal labels.

For example, in the following sexpr-wasm-prototype emits the "myfunc" name in the encoding, but wasm-as emits "f1" which would not be correct.

```
(module
  (memory 0 0)
  (export "myfunc" $f1)
  (func $f1 (param $x i32) (result i32)
    (i32.const 0)))
```

I suggest changing wasm-as to only emit names for the imports and exports and to use the external name string rather than the labels, and to wait until there is some debug support for naming the internal labels.

**Comment by binji** [comment]
That is correct, v8-native binary format only uses names for exporting and importing, not for internal names.

**Comment by kripken** [comment]
Makes sense.
