### ISSUE TITLE
Windows g++ breakage on bot

### ISSUE THREAD

**Issue by kripken** [WebAssembly/binaryen#1240]
https://ci.appveyor.com/project/WebAssembly/binaryen/build/1.0.3586/job/y71k1fu9ts8a2uhn
````
In file included from C:/projects/binaryen/src/tools/wasm-opt.cpp:36:0:
C:/projects/binaryen/src/tools/translate-to-fuzz.h: In member function 'wasm::Expression* wasm::TranslateToFuzzReader::makeConst(wasm::WasmType)':
C:/projects/binaryen/src/tools/translate-to-fuzz.h:1267:5: error: 'first' may be used uninitialized in this function [-Werror=maybe-uninitialized]
   T pickGivenNum(size_t num, T first, Args... args) {
     ^~~~~~~~~~~~
````
This seems like a compiler bug, as it is saying an argument to a function may be used uninitialized.

But this only happens on one of the windows runs, the one using g++ which was just updated to 7.2. I tested with 7.2 on linux and it does not hit that problem. So it seems specific to the platform somehow which is odd.

I don't see an easy way to downgrade the version on the [appveyor docs](https://www.appveyor.com/docs/build-environment/#mingw-msys-cygwin).

**Comment by binji** [comment]
It does seem like a bug, but perhaps it's a bug in the error reporting? Is there anything uninitialized in `TranslateToFuzzReader::makeConst`? Maybe the optimizer is making it lose track of where the uninitialized variable is defined.

**Comment by kripken** [comment]
Tracking it back through all the callers I don't see anything uninitialized anywhere that could feed into that param. In fact we always pass a constant into it, not even a variable. Very odd...

**Comment by kripken** [comment]
The only special thing I can see is that makeConst provides a template param, `pick<float>(..)` instead of all the other places which don't. I pushed a branch to test that theory.

**Comment by kripken** [comment]
This should now be worked around on master. But leaving this open since we don't understand this bug yet, and it would be good to see if it's something we should file for the compiler. If someone has a windows machine and some time, please see if you can reproduce this.

**Comment by kripken** [comment]
I gave this another shot and I did manage to reproduce it on my local machine. I reduced it and filed it for gcc: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=82800

Closing as we are not hit by the bug and it's been reported. If it returns (not sure exactly how we worked around it) we can reopen.
