### ISSUE TITLE
Error compiling to .wasm

### ISSUE THREAD

**Issue by blackjyn** [WebAssembly/binaryen#1255]
Hi. Im new to WASM .
When I tried to compile to .wasm I got this:
![compiletowasmerr](https://user-images.githubusercontent.com/6046191/32168018-8267e168-bd9d-11e7-92c1-e3274f623103.png)

I have NO problem when compile to ASM.js
Help?

**Comment by kripken** [comment]
Running with `EMCC_DEBUG=1` in the env should show more info, including the command that fails.

**Comment by blackjyn** [comment]
I set EMCC_DEBUG=1 in my env and got this:
![compilewasmerr](https://user-images.githubusercontent.com/6046191/32207759-abf7a336-be30-11e7-8258-f2c3a693d69e.png)

I noticed at this:

> DEBUG:root:check tells us to use asm.js backend
> DEBUG:root:using binaryen, with method: native-wasm
> DEBUG:root:asm2wasm (asm.js => WebAssembly): D:/DEVSDK/EMScripten/binaryen_v37\bin\asm2wasm x.temp.asm.js --total-memory=16777216 --emit-potential-traps -O1 --mem-init=x.js.mem --mem-base=1024 --wasm-only -o x.wasm

but what should I do?

**Comment by kripken** [comment]
Does the asm2wasm executable exist at that path there? (Also, are the slashes+reverse slashes ok on windows?)

**Comment by blackjyn** [comment]
Well, My problem got fixed by updating to the latest
Thank you for bundling precompiled binaries for Windows
