### ISSUE TITLE
fatal error: UTF-16

### ISSUE THREAD

**Issue by extremety1989** [WebAssembly/binaryen#1265]
as i try to compile 
emcc  ConsoleApplication1.cpp -s WASM=1

i got this error 
fatal error: UTF-16 (LE) byte order mark detected in 'ConsoleApplication1.cpp', but encoding is not supported
1 error generated.
ERROR:root:compiler frontend failed to generate LLVM bitcode, halting

here is my c++ file that i want to compile
#include "stdafx.h"

#include <stdlib.h>
#include <iostream>
#include "mysql_connection.h"

#include <cppconn/driver.h>
#include <cppconn/exception.h>
#include <cppconn/resultset.h>
#include <cppconn/statement.h>
#include <cppconn/prepared_statement.h>

using namespace std;
string username;
string userpass;
int main(void)
{
	cin >> username;
	cin >> userpass;
	try {
		sql::Driver *driver;
		sql::Connection *con;
		sql::Statement *stmt;
		sql::ResultSet *res;
		sql::PreparedStatement *pstmt;

		driver = get_driver_instance();
		con = driver->connect("tcp://127.0.0.1:3306/test", "root", "");
		con->setSchema("test");
		stmt = con->createStatement();
		delete stmt;
			pstmt = con->prepareStatement("INSERT INTO test (username,password) VALUES (?,?)");
			pstmt->setString(1,username.c_str());
			pstmt->setString(2,userpass.c_str());
		    pstmt->executeUpdate();
		    delete pstmt;
		pstmt = con->prepareStatement("SELECT id,username,password FROM test ORDER BY id ASC");
		res = pstmt->executeQuery();
		res->afterLast();
		while (res->previous())
			cout <<"ID :" <<res->getInt("id") << "  Username :" << res->getString("username").c_str() 
			<< "  Password :" << res->getString("password").c_str() << endl;
		delete pstmt;
		delete con;

	}
	catch (sql::SQLException &e) {
		cout << "SQLState: " << e.getSQLState()<< endl;
	}

	cout << endl;

	return 0;
}

**Comment by kripken** [comment]
That error is from clang, so you will probably see the same error when you use clang to build natively (without emscripten/binaryen). I don't know if it's a bug or not in clang, though.
