### ISSUE TITLE
wasm-as: wrong opcodes for f64.convert_s/i32 and f64.convert_u/i32

### ISSUE THREAD

**Issue by JSStats** [WebAssembly/binaryen#128]
Consider:
```
(module
  (memory 0 0)
  (func $f1 (param $i1 i32) (result f64)
    (block $topmost
      (f64.add
       (f64.convert_s/i32 (get_local $i1))
       (f64.convert_u/i32 (get_local $i1))
      ))))
```

wasm-as emits opcode `0x9e` for `f64.convert_s/i32` and opcode `a0` for `f64.convert_u/i32`, whereas sexpr-wasm-prototype emits opcodes  `0xae` and `0xaf` respectively.

**Comment by kripken** [comment]
I copied those values from the spec, and double-checked them now - they look right to me in binaryen. Perhaps a mistake or sexpr-wasm-prototype? Or the spec changed? @binji

**Comment by binji** [comment]
Looking at the v8 source https://chromium.googlesource.com/v8/v8/+/master/src/wasm/wasm-opcodes.h#229:
```
...
  V(I32SConvertF64, 0x9e, i_d)    \
  V(I32UConvertF32, 0x9f, i_f)    \
  V(I32UConvertF64, 0xa0, i_d)    \
```

0x9e is i32.convert_s/f64 and 0xa0 is i32.convert_u/f64. The v8 opcode enums have the output type on the left.

**Comment by JSStats** [comment]
Caught by the kitchen_sink test and noted along with a few other issues in https://github.com/WebAssembly/binaryen/issues/138
