### ISSUE TITLE
Could binaryen itself be compiled to wasm?

### ISSUE THREAD

**Issue by justinmchase** [WebAssembly/binaryen#1308]
Suppose you wanted to run this in the browser and dynamically compile, is that possible?

**Comment by kripken** [comment]
Yes, that's what `binaryen.js` is (in the `bin/`folder). Some examples of using it in JS appear in `tests/binaryen.js`.

**Comment by kripken** [comment]
(That's compiled to asm.js currently, but compiling to wasm would be just changing a flag.)

**Comment by justinmchase** [comment]
Oh interesting, I thought it was running as a nodejs binary module. 👍
