### ISSUE TITLE
Multiple br_if to br_table optimization

### ISSUE THREAD

**Issue by dcodeIO** [WebAssembly/binaryen#1309]
In switches, instead of generating proper `br_tables`, which requires constant evaluation of the conditions beforehand, I am currently generating one `br_if` per condition. As mentioned previously, I am trying to re-use as much of Binaryen as possible, e.g., the precompute pass.

For example:

```ts
switch ($local1) {
  case 0:
    ...
  case 1:
    ...
}
```

Becomes:

```s
(br_if $case0$1.1
  (i32.eq
    (get_local $1)
    (i32.const 0)
  )
)
(br_if $case2$1.1
  (i32.eq
    (get_local $1)
    (i32.const 1)
  )
)
```

While the example uses just constants, using globals (that might be constant) or binary ops is quite common in TypeScript-like languages. Might this be something Binaryen could optimize to `br_table`s eventually, after precomputing, or is that something the compiler should do right away in your opinion?

One advantage of having this in Binaryen is that it could honor `-Oz` to reduce free space in between table values, or generate larger tables with `-O3` or something.

**Comment by kripken** [comment]
Makes sense to do this. However, wasm switches can only support comparing something to a constant, so only the `get_local` part could be generalized. (Maybe the `eq` too, to support ranges?)

This might actually already work if you run the `rereloop` pass, as it reduces to a CFG and recreates control flow. However, I believe the relooper doesn't convert to a switch, only from it, currently. We'd need to investigate if it's better to improve that or to directly match the pattern you wrote.

**Comment by dcodeIO** [comment]
> However, wasm switches can only support comparing something to a constant, so only the get_local part could be generalized

In my case, most of the pattern, except `$target-label` and `$case-value` (possibly constant) is always the same:

```s
(br_if $target-label
  (i32.eq
    $always-the-same-condition
    $case-value
  )
)
```

**Comment by kripken** [comment]
What is `$case_value`? Is it `(get_local $case-value)`? If it's not a constant, it can't be in a `br_table`, it just has a list of indexes and where to jump to. If the common case isn't a constant, this can't be optimized.

In theory nonconstant ones can be optimized by doing some math at runtime, but you don't know the range of the values, so I don't see how.

**Comment by dcodeIO** [comment]
The common case is either a constant

```js
  case 2:
```

or constant global

```js
  case Token.DOT:
```

but it might also be something like

```js
  case 1<<2:
```

that becomes a constant after precompute. Hence, when precompute has been performed already, all of these should be constants.

**Comment by kripken** [comment]
Oh ok, now I see, thanks. Makes sense.

Pretty simple optimization, I think, I'll get to this later today.

**Comment by dcodeIO** [comment]
Closing as this has landed.
