### ISSUE TITLE
s2wasm broken by recent llvm change

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/binaryen#1311]
Looks like this change causes for issues with s2wasm:
https://reviews.llvm.org/rL319186

e.g.:
./tests/runner.py binaryen2.test_unistd_unlink

Which ends up basically failing like this:

../binaryen-out/bin/s2wasm --emscripten-glue --global-base=1024 --initial-memory=16777216 -l /usr/local/google/home/sbc/.emscripten_cache/wasm/wasm_libc_rt.a -l /usr/local/google/home/sbc/.emscripten_cache/wasm/wasm_compiler_rt.a --trap-mode=allow emcc-llvm-backend-output.s s2wasm: /usr/local/google/home/sbc/dev/wasm/binaryen/src/wasm.h:221: T* wasm::Expression::cast() [with T = wasm::Const]: Assertion `int(_id) == int(T::SpecificId)' failed.

Looks related to the extra bitcast function and/or the call to emscripten_asm_const_int@FUNCTION.

**Comment by sbc100** [comment]
[emcc-llvm-backend-output.s.old.txt](https://github.com/WebAssembly/binaryen/files/1516472/emcc-llvm-backend-output.s.old.txt)
[emcc-llvm-backend-output.s.new.txt](https://github.com/WebAssembly/binaryen/files/1516473/emcc-llvm-backend-output.s.new.txt)

**Comment by sunfishcode** [comment]
See also the discussion in https://bugs.llvm.org/show_bug.cgi?id=35385. I'll plan to revert the patch.

**Comment by sunfishcode** [comment]
The patch is now reverted (in r319452).

**Comment by AlgorithMan-de** [comment]
Running self-compiled emscripten from current HEAD against self-compiled LLVM from current HEAD still produces this issue on my rather large project. I wasn't able to construct a small example that produces the error yet.

**Comment by AlgorithMan-de** [comment]
Okay, I have got it running by doing `./emsdk install latest; ./emsdk activate latest` and **_not_** pointing to my self-compiled LLVM in `~/.emscripten` (I thought `./emsdk activate latest` would have overwritten that configuration, but apparently hadn't)

**Comment by jakirkham** [comment]
Guess this should be closed as won't fix given `s2wasm` was dropped. ( https://github.com/WebAssembly/binaryen/pull/1607 )

**Comment by kripken** [comment]
Yes, thanks @jakirkham
