### ISSUE TITLE
Source maps and the C-API

### ISSUE THREAD

**Issue by dcodeIO** [WebAssembly/binaryen#1315]
I noticed that there is some source map support but no way to provide the information necessary in the C-API yet. Hence, what if we'd do something like:

1. Call `BinaryenAddFile(const char* name): BinaryenFileRef` for each source file being compiled, returning a reference to the file (avoids having to copy file name strings every time in JS)
2. Call `BinaryenSetLoc(BinaryenFileRef file, BinaryenIndex lineStart, BinaryenIndex columnStart, BinaryenIndex lineEnd, BinaryenIndex columnEnd): void`, taking the file reference from above plus line and column information of the next function / global / import / export / expression being compiled
3. Call the respective C-API method as usual that then honors the location info previously set
4. Generate a source map from this information when creating the module (maybe `BinaryenModulePrintSourceMap`).

Would something like this be possible as of today?

**Comment by kripken** [comment]
1: Yes, something like `BinaryenModuleAddDebugInfoFilename` (with a better name) could return `BinaryenFileRef` could be the index in `Module::debugInfoFileNames`.

2 and 3: I think what you want here is something like `BinaryenFunctionAddDebugInfoLocation(Expression*, file#, line#, col#)` (again, need better name) which adds to `Function::debugLocations`. So you'd create the expression first normally, then call this to add the debug info metadata onto that expression.

4: The names section and/or source map are user sections in the wasm itself, so we could have a variant of `BinaryenModuleWrite`, `BinaryenModuleWriteWithSourceMap` which calls `setSourceMap`. There are some details with the URL there that I don't fully understand, though, but we can ask the author of the code if necessary (yurydelendik).

**Comment by dcodeIO** [comment]
On 2: I see, but we'd need additional functions for functions, imports, exports, globals etc. as well, if I'm not mistaken.

On 4 / `WriteWithSourceMap`: Hmm, personally I'd not want to include the entire source map in the WASM, just an URL to the external file containing the source map. In JS you can do both (inline or external, with external being the default for production builds). Then, if I ever had a need to debug something, I'd use the source map (browser dev tools do this automatically) and otherwise save the bandwidth. @yurydelendik ?

**Comment by kripken** [comment]
On 2: debug info can only be added to expressions (function code), so far (and not imports, exports, and other global entities).

**Comment by dcodeIO** [comment]
Implemented in https://github.com/WebAssembly/binaryen/pull/1392
