### ISSUE TITLE
Exporting an imported function does not validate

### ISSUE THREAD

**Issue by dcodeIO** [WebAssembly/binaryen#1325]
It might well be that this is by design, but putting it here in case it is not.

```js
var mod = new binaryen.Module();

var funcType = mod.addFunctionType("v", binaryen.none, []);
var func = mod.addImport("test", "env", "test", funcType);
mod.addExport("test", "test");

console.log(mod.emitText());
if (!mod.validate())
  console.log("-> does not validate");
```

```s
(module
 (type $v (func))
 (import "env" "test" (func $test))
 (memory $0 0)
 (export "test" (func $test))
)

[wasm-validator error in module] unexpected false: module function exports must be found, on
$test
-> does not validate
```

Feel free to close if this is a WebAssembly restriction. If it is, though, I'd wonder why, as one could simply export an otherwise identical wrapper calling the import.

**Comment by binji** [comment]
This is allowed by WebAssembly, see [this set of tests](https://github.com/WebAssembly/spec/blob/master/test/core/imports.wast#L44) for example. This seems to be a binaryen restriction.

**Comment by kripken** [comment]
This was disallowed earlier in the wasm spec process, right? I think we just left it that way here. Anyhow, worth fixing.

**Comment by kripken** [comment]
Or maybe I'm thinking about allowing/disallowing imported functions in tables.

**Comment by kripken** [comment]
Possible fix in #1326

**Comment by binji** [comment]
> This was disallowed earlier in the wasm spec process, right?

Maybe...? Hard to remember what's changed over time. :-)

**Comment by dcodeIO** [comment]
Closing as this has landed.
