### ISSUE TITLE
Minor local initialization optimization

### ISSUE THREAD

**Issue by dcodeIO** [WebAssembly/binaryen#1343]
The following

```s
 (func $assembly/pson/readVarint32 (; 15 ;) (type $i) (result i32)
  (local $0 i32)
  (local $1 i32)
  (block
   (set_local $0
    (i32.const 0)
   )
  )
  (block
   (set_local $1
    (i32.const 0)
   )
  )
  ...
```

currently optimizes to

```s
 (func $assembly/pson/readVarint32 (; 15 ;) (type $i) (result i32)
  (local $0 i32)
  (local $1 i32)
  (set_local $0
   (i32.const 0)
  )
  (set_local $1
   (i32.const 0)
  )
  ...
```

Not sure if my assumption here is correct, but if it is, could the initial `set_local`s be optimized away because locals are 0-ed anyway?

**Comment by kripken** [comment]
Yeah, thanks for reminding me, I was meaning to get around to this. I think it might be pretty common actually, as many loops start naturally at 0.

The tricky issue is that using the zero-init value means the lifetime extends all the way to the beginning of the function, which might be bad in some cases, so this should probably be done after coalescing. #1339 adds some liveness infrastructure that could help here.
