### ISSUE TITLE
Document Binaryen.parseText API

### ISSUE THREAD

**Issue by mbebenita** [WebAssembly/binaryen#1349]
`Binaryen.parseText` is missing from
https://github.com/WebAssembly/binaryen/blob/master/docs/binaryen.js.Markdown

**Comment by kripken** [comment]
Thanks!

There are probably more APIs not fully documented there, it would be good to do a pass over the whole thing if someone has time.

**Comment by dcodeIO** [comment]
There's also [this one](https://github.com/AssemblyScript/binaryen.js/blob/master/README.md) that I am maintaining. It has parseText but is probably not fully up to date either.

**Comment by dcodeIO** [comment]
The [other documentation](https://github.com/AssemblyScript/binaryen.js/blob/master/README.md) should be up to date now.
