### ISSUE TITLE
if to br_table?

### ISSUE THREAD

**Issue by dcodeIO** [WebAssembly/binaryen#1355]
Optimizing the following:

```s
(module
 (type $i (func (param i32) (result i32)))
 (memory $0 0)
 (export "test" (func $test))
 (func $test (; 0 ;) (type $i) (param $0 i32) (result i32)
  (if (result i32)
   (i32.eqz
    (get_local $0)
   )
   (i32.const 0)
   (get_local $0)
  )
 )
)
```

Yields:

```s
(module
 (type $i (func (param i32) (result i32)))
 (memory $0 0)
 (export "test" (func $test))
 (func $test (; 0 ;) (type $i) (param $0 i32) (result i32)
  (if (result i32)
   (get_local $0)
   (get_local $0)
   (i32.const 0)
  )
 )
)
```

Which got me thinking: When we already know that the condition is either 0 or 1 anyway (eqz, eq, ne, lt, le, gt, ge), would a br_table on 0 or 1 make the code any faster because branching (in some cases)? Please excuse if this is a not-so-smart question. I might be entirely mistaken here because I don't know the full picture, especially when it comes to generated machine code.

**Comment by kripken** [comment]
Good question. Actually the mandreel compiler used to emit switches in JS instead of ifs because that was faster on v8, a very long time ago. I suspect though that in wasm this doesn't end up useful enough, and does increase code size. Curious what @sunfishcode thinks.

**Comment by dcodeIO** [comment]
Maybe, in this specific example, the `if` could also be replaced by a `select` because both arms are free of side effects and not deeply nested. I think I read somewhere that Firefox compiles it branchless?

**Comment by kripken** [comment]
@dcodeIO "Maybe, in this specific example, the if could also be replaced by a select"

Oh right, actually that should already be happening. When I compile your input wast with `-O` or `-Os` I get
```
 (func $test (; 0 ;) (type $i) (param $0 i32) (result i32)
  (select
   (get_local $0)
   (i32.const 0)
   (get_local $0)
  )
 )
```
But not in `-O2` or `-O3`. In this case it does seem like select is always preferable, so maybe we should do that. Right now the code just doesn't do this if we aren't optimizing for size.

Btw, what are you compiling with?

@binji 

Very interesting! If I read that right (my x86 is rusty) the native compiler outputs are consistently good? While the v8 ones seem to keep the branches? Is it odd that happens even when the input is a select?

**Comment by dcodeIO** [comment]
> Btw, what are you compiling with?

binaryen.js's default optimizations (is that `-Oz`?). Reminds me that I always wanted to add the ability to specify optimization levels to the C-API :)

**Comment by kripken** [comment]
The default should be `-Os`, in which case you should have gotten a select. Can you make a testcase showing the wrong output, I can debug that?

**Comment by binji** [comment]
@kripken I'm not even close to an x86 expert, but my understanding is that cmov is not always a clear winner vs branch+mov. In this case cmov is probably a better choice, but in a larger function it increases register pressure and has longer dependency chains.

**Comment by dcodeIO** [comment]
This is the test case I used: https://github.com/AssemblyScript/assemblyscript/blob/d89703cdad5ed5cb44189b2ca0f69e9cfc16829f/tests/binaryen/optimize-if-eqz.js

My binaryen.js version is a couple of commits behind master atm, though (40.0.0-nightly.20171229).

**Comment by sunfishcode** [comment]
While it will ultimately depend on the engine, the basic expectation is that if/br_if are conditional branches, br_table is a jump table, and select is a conditional move. This is what FIrefox generates on x86; you can see the code in the WebAssembly Explorer [here](https://goo.gl/tuh5Ak). In such an engine, the short answers are: if/br_if are expected to be faster than a two-way br_table, and select is expected to be faster than if/br_if when the inputs are cheap and the condition is "random" (making branch prediction ineffective).

**Comment by kripken** [comment]
@dcodeIO: thanks, I think I see the problem in that testcase. we run the passes but don't set the opt level. we can fix that in your PR (next on my list to read) if it's not fixed already.

@sunfishcode @binji I see, thanks.

**Comment by dcodeIO** [comment]
Thanks for the clarification!
