### ISSUE TITLE
struct std::hash’ in different namespace

### ISSUE THREAD

**Issue by winsvega** [WebAssembly/binaryen#1362]
```
src/binaryen/src/literal.h:158: error: specialization of ‘template<class _Tp> struct std::hash’ in different namespace [-fpermissive] template<> struct hash<wasm::Literal> {
```

could not compile binaryen with this error.

**Comment by kripken** [comment]
What compiler is that with?

**Comment by winsvega** [comment]
GNU Make 4.1
Built for x86_64-pc-linux-gnu
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609

**Comment by kripken** [comment]
Very strange, I am literally on the same version,
```
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
```
and latest master works ok.

Any chance the source was modified, or another compiler was found by cmake? And what revision is this of binaryen?

**Comment by winsvega** [comment]
looks like the issue was the include headers order that we had in our project.

**Comment by kripken** [comment]
What was the order? Maybe there is something we can improve here. (Or was it the order of includes with other projects?)

**Comment by winsvega** [comment]
after the headers were moved to another file it works
```
+#include "wast2wasm.h"
 +
 +#include <libdevcore/CommonData.h>
 +
 +#include <boost/test/unit_test.hpp>
 +
 +// Disable MSVC warning "unary minus operator applied to unsigned type".
 +#pragma warning(push)
 +#pragma warning(disable: 4146)
 +#include <wasm-binary.h>
 +#include <wasm-s-parser.h>
 +#include <wasm-validator.h>
 +#pragma warning(pop)
```

binaryen is a part of Hera repo which used with wasm. 
I guess the issue might  have been that in our project we already have defenition for hash 
and it produced such conflict.

**Comment by kripken** [comment]
I see, yeah, sounds like that's the explanation then. Ok, closing.

**Comment by davnav** [comment]
Could you please advise how do you resolved this issue ? I am getting the below error when I try to make:**cmake . && make**


errror:

In file included from /home/naveen/rustprojects/wasmexample/wasm-trace/tests/binaryen/src/literal.h:26:0,
                 from /home/naveen/rustprojects/wasmexample/wasm-trace/tests/binaryen/src/wasm/literal.cpp:17:
/home/naveen/rustprojects/wasmexample/wasm-trace/tests/binaryen/src/wasm-type.h:133:23: error: specialization of ‘template<class _Tp> struct std::hash’ in different namespace [-fpermissive]
 template<> class std::hash<wasm::Signature> {
                       ^
In file included from /usr/include/c++/5/bits/basic_string.h:5471:0,
                 from /usr/include/c++/5/string:52,
                 from /usr/include/c++/5/stdexcept:39,
                 from /usr/include/c++/5/array:38,
                 from /home/naveen/rustprojects/wasmexample/wasm-trace/tests/binaryen/src/literal.h:20,
                 from /home/naveen/rustprojects/wasmexample/wasm-trace/tests/binaryen/src/wasm/literal.cpp:17:
/usr/include/c++/5/bits/functional_hash.h:58:12: error:   from definition of ‘template<class _Tp> struct std::hash’ [-fpermissive]
     struct hash;
            ^
cc1plus: error: unrecognized command line option ‘-Wno-unknown-warning-option’ [-Werror]
cc1plus: error: unrecognized command line option ‘-Wno-implicit-int-float-conversion’ [-Werror]
cc1plus: all warnings being treated as errors
src/wasm/CMakeFiles/wasm.dir/build.make:62: recipe for target 'src/wasm/CMakeFiles/wasm.dir/literal.cpp.o' failed
make[2]: *** [src/wasm/CMakeFiles/wasm.dir/literal.cpp.o] Error 1
CMakeFiles/Makefile2:888: recipe for target 'src/wasm/CMakeFiles/wasm.dir/all' failed
make[1]: *** [src/wasm/CMakeFiles/wasm.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by winsvega** [comment]
Check this pr
 https://github.com/ethereum/aleth/pull/4754/files

**Comment by ygina** [comment]
@davnav To compile binaryen as a toolchain, check the output of `cmake .`:

```
-- The C compiler identification is GNU 5.5.0
-- The CXX compiler identification is GNU 5.5.0
```

Even though 5.5.0 supports C++11, upgrading the links for `gcc` and `g++` to 9.2.1 with `sudo update-alternatives` fixed it for me. 7.4.0 also worked.
