### ISSUE TITLE
Minor precompute optimization

### ISSUE THREAD

**Issue by dcodeIO** [WebAssembly/binaryen#1364]
When I compile

```ts
function fls<T>(word: T): i32 {
  return (<i32>sizeof<T>() << 3) - <i32>clz(word) - 1;
}
```

to

```s
 (func $assembly/tlsf/fls<usize> (; 8 ;) (type $ii) (param $0 i32) (result i32)
  (return
   (i32.sub
    (i32.sub
     (i32.shl
      (i32.const 4)
      (i32.const 3)
     )
     (i32.clz
      (get_local $0)
     )
    )
    (i32.const 1)
   )
  )
 )
```

it optimizes to

```s
 (func $assembly/tlsf/fls<usize> (; 7 ;) (type $ii) (param $0 i32) (result i32)
  (i32.add
   (i32.sub
    (i32.const 0)
    (i32.clz
     (get_local $0)
    )
   )
   (i32.const 31)
  )
 )
```

Now, when I switch the order a bit, the following

```ts
function fls<T>(word: T): i32 {
  return (<i32>sizeof<T>() << 3) - 1 - <i32>clz(word);
}
```

compiles to

```s
 (func $assembly/tlsf/fls<usize> (; 8 ;) (type $ii) (param $0 i32) (result i32)
  (return
   (i32.sub
    (i32.sub
     (i32.shl
      (i32.const 4)
      (i32.const 3)
     )
     (i32.const 1)
    )
    (i32.clz
     (get_local $0)
    )
   )
  )
 )
```

and optimizes to

```s
 (func $assembly/tlsf/fls<usize> (; 7 ;) (type $ii) (param $0 i32) (result i32)
  (i32.sub
   (i32.const 31)
   (i32.clz
    (get_local $0)
   )
  )
 )
```

which seems preferable in the first case as well because of one less operation.

**Comment by kripken** [comment]
Thanks! Yeah, this is good to do. Done in #1365.

This happens on hello world code too (see diff in that PR), it might not be that rare actually, given that `0-x` is how we negate ints...

**Comment by dcodeIO** [comment]
Maybe somewhat similar:

```s
 (func $assembly/tlsf/Control#sl_bitmap_set (; 0 ;) (type $iiiv) (param $0 i32) (param $1 i32) (param $2 i32)
  (i32.store
   (i32.add
    (i32.add
     (get_local $0)
     (i32.const 20)
    )
    (i32.mul
     (get_local $1)
     (i32.const 4)
    )
   )
   (get_local $2)
  )
 )
```

or `($0 + 20) + ($1 * 4)`. Seems to me `20` could become the store offset? Is that actually desirable?

**Comment by kripken** [comment]
The offset semantics are tricky, actually. Integers wrap, but offsets don't (if the point + 20 overflows as a 32-bit int, it throws instead of loading from the wrapped value). Under limited circumstances you can optimize such things, but you need to know more about the pointer $1 here.

**Comment by dcodeIO** [comment]
Thanks, makes sense.

**Comment by dcodeIO** [comment]
Another thing that might have a simple explanation:

```s
 (func $assembly/ugc/Control#get:set1 (; 0 ;) (type $0) (param $0 i32) (result i32)
  (get_local $0)
 )
```

is not being inlined in `wasm-opt -O2 --inlining` but is in `wasm-opt -O3 --inlining`, is that correct?

**Comment by kripken** [comment]
The current inlining heuristics are pretty conservative. In -O2 and below we only inline functions with a single use, that guarantees that when we inline them we can remove the original, so it should never be bad for code size. In -O3 we consider inlining functions with multiple uses as well.

Yeah, it seems like a tiny getter like that could be inlined with no code size risk, even with multiple uses. Maybe anything with just a single get_local or a const is safe. I can look into that (unless you want to).

**Comment by dcodeIO** [comment]
So, if the size of the function body equals that of a call (2 bytes if the immediate function index is less than 128, otherwise more, but this might change after optimizations and linking so cannot be relied upon), it can be inlined everywhere even if exported for a performance-win. If it is not exported, function declaration and its body can also be removed for an additional 3 + 2 bytes size-win, with the possibility of eliminating its function type as well (unlikely because it's such a simple one, but theoretically possible). Is that the kind of thinking that applies here?

**Comment by kripken** [comment]
Yeah, exactly, those are the issues here.

Another important detail is that we create a block and some new locals when we inline - inline without optimizing to see what that looks like. When we inline+optimize, we can often but not always get rid of those. For example, it depends if there are multiple params with incoming values with side effects, in that case we may need a new local and the block,
```
 (call $inline-able
   (call $x)
   (call $y)
 )
..
(func $inline-able (param $x i32) (param $y i32) (result i32)
  (i32.sub
    (get_local $y)
    (get_local $x)
  )
)
```
In this case we can't just replace the call with
```
  (i32.sub
    (call $y)
    (call $x)
  )
```
because those calls may have side effects and can't be reordered. So we must use a block + local.

But a "getter" type example, as you said, is safe. If it has just one param or less, and its body is small enough.

**Comment by dcodeIO** [comment]
Thanks!
