### ISSUE TITLE
mismatch between logging code and actual code in BinaryenModuleDispose

### ISSUE THREAD

**Issue by froydnj** [WebAssembly/binaryen#1369]
The [logging in `BinaryenModuleDispose`](https://github.com/WebAssembly/binaryen/blob/master/src/binaryen-c.cpp#L173) indicates that `imports` and `exports` should be cleared, but the code doesn't actually clear those variables.

It's not clear that the `.clear()`'ing of things is really useful in the first place, since the `Module` is being deleted.

**Comment by dcodeIO** [comment]
These variables are tracing specific (not used by the module, but by tracing) and created when `BinaryenSetAPITracing(1)` has been called. Hence, when `tracing` evaluates to true, the variables are guaranteed to be set. I'm not exactly sure how arena allocation handles this, but their contents point to no longer used memory (if not even free'd), so clearing them when disposing a module is a sane thing to do.

**Comment by froydnj** [comment]
Indeed, I mistakenly read those as member variables, not globals!  Clearing them would indeed be the reasonable thing to do in that case.

**Comment by kripken** [comment]
Yes, looks like imports and exports should also be cleared there. We probably just forgot to do that when we added them.
