### ISSUE TITLE
asm2wasm - What's the use of ' import "env" ' in the compile result

### ISSUE THREAD

**Issue by maoyuyang** [WebAssembly/binaryen#1388]
here is the asm code
```
function add () {
  "use asm";
  
  function add(x, y) {
    x = x | 0;
    y = y | 0;
    return x + y | 0;
  }
  
  function square(x, y) {
    x = x | 0;
    y = y | 0;
    return x + y | 0
  }
  
  return { 
    add: add,
    square: square
  };
}
```

here  is the wat code
```
(module
 (import "env" "memory" (memory $0 256 256))
 (import "env" "table" (table 0 0 anyfunc))
 (import "env" "memoryBase" (global $memoryBase i32))
 (import "env" "tableBase" (global $tableBase i32))
 (export "add" (func $add))
 (export "square" (func $square))
 (func $add (; 0 ;) (param $x i32) (param $y i32) (result i32)
  (return
   (i32.add
    (get_local $x)
    (get_local $y)
   )
  )
 )
 (func $square (; 1 ;) (param $x i32) (param $y i32) (result i32)
  (return
   (i32.add
    (get_local $x)
    (get_local $y)
   )
  )
 )
)
```
What's the use of the first four import code ? what does the 'memoryBase' and  'tableBase' mean ? 

I think the results should be as follows,  but why not ?
```
(module
 (export "add" (func $add))
 (export "square" (func $square))
 (func $add (; 0 ;) (param $x i32) (param $y i32) (result i32)
  (return
   (i32.add
    (get_local $x)
    (get_local $y)
   )
  )
 )
 (func $square (; 1 ;) (param $x i32) (param $y i32) (result i32)
  (return
   (i32.add
    (get_local $x)
    (get_local $y)
   )
  )
 )
)
```

any help ? thanks

**Comment by kripken** [comment]
Without optimizations, some default imports may be left in, which are not needed. When I compile your asm.js with optimizations I get this:
```
$ bin/asm2wasm a.asm.js -Os
(module
 (export "add" (func $add))
 (export "square" (func $add))
 (func $add (; 0 ;) (param $0 i32) (param $1 i32) (result i32)
  (i32.add
   (get_local $0)
   (get_local $1)
  )
 )
)
```
(Notice that it detected the two functions are identical so it merged them, and it optimized out the return.) So basically just run asm2wasm with `-Os` (or another optimization level) to get a small minimal output, without anything unnecessary.

As to what those imports are, by default we import a memory and a table, and also an offset of where we can use space in them. That is useful for dynamic linking, where multiple modules might use the same memory, each with a different range. But for a case like this, with just pure computation, the memory and table and the offsets are not needed and the optimizer can remove them.

**Comment by maoyuyang** [comment]
oh, I write wrong, the square func shound be x * y，sorry，but thank your for your answer

**Comment by maoyuyang** [comment]
oh, I wrote the square function wrong. It should not be the same as the add func. sorry. but thank you for your answer

**Comment by maoyuyang** [comment]
I try to use `-0s` but it say `Unknown option '-0s'`. Do you know the possible reason? ?  I only install the binaryen
