### ISSUE TITLE
Alignment testing

### ISSUE THREAD

**Issue by kripken** [WebAssembly/binaryen#141]
The torture tests on the waterfall broke on new LLVM output, where it aligns functions and globals. We only fixed loads and stores, so that remained to be done in c57934eb52a0a415bb362f4e6f09065a40515e3f and 30b67c29dfd9a075b526043dfbf8556c918c6e5a

Perhaps we should add a test for this directly in `test/llvm_autogenerated`? cc @sunfishcode

**Comment by sunfishcode** [comment]
Sorry, I forgot to notify binaryen when updating LLVM. https://github.com/WebAssembly/binaryen/pull/142 is a PR with newly generated tests. They contain uses of the new .p2align syntax.

**Comment by kripken** [comment]
Great, looks like we can close this.
