### ISSUE TITLE
Divergences from binary format spec

### ISSUE THREAD

**Issue by kripken** [WebAssembly/binaryen#145]
Just documenting this here: I increased the size of blocks and functions in the binary format for now, since I ran into the spec size limits when trying to build larger codebases (BananaBread).

This means we can't interoperate with other binary format producers/consumers. If that's a concern, maybe we should put it behind an option.

**Comment by JSStats** [comment]
The block size becomes a leb128 and the function body size become uint32 (fixed width to be easy to patch). Seems fine to me. I would not worry about interoperability at this stage. If it were me I'd just submit the patch to v8 and sexp-wasm. Would you like me to help by doing this?

I was just wondering about the local variable sizes, why they are uint16 not leb128. Might it be in part because 2^16 is a good limit for implementations anyway, or are these to be revised too?

**Comment by titzer** [comment]
Maybe we should just make all sizes into LEB128?

**Comment by titzer** [comment]
BTW you can achieve arbitrarily big size blocks by nesting them in a tree
structure.

**Comment by JSStats** [comment]
@titzer Some producers patch the function body size, so it helps them if it is a fixed width, however it does not seem a big burden to write it to memory first and then to a file when the body size is known.

* Number of locals, currently uint16, would work easily as LEB128.

* Function signature index, and length, currently uint8, also would work easily as LEB128.

* Function flags, memory access flags, currently uint8. Moving to LEB128 might allow for extension?

* Memory size, currently uint8, patches pending to use LEB128 in units of pages.

* An i32.const.leb128 ? and a signed version?

* An i64.const.leb??? and a signed version. Is an i32.const and i8.const accepted to functions expecting an i64?

**Comment by JSStats** [comment]
Sorry, the function bodies are expected to be moved OOL, so it would be a burden to pre-compute their size. It would be necessary to compute all the function body sizes before emitting the functions section if they were all OOL. So a good reason to keep if a fixed width.

**Comment by kripken** [comment]
I agree basically all sizes could be LEB128.

Except for function sizes - as @JSStats says they may be moved OOL, but even if not, when writing we need to go back and set the size afterwards, and with LEB we don't know how much space to reserve. Not a big deal - the writer could do an extra copy - but the overhead of just using an int32 seems low.

**Comment by kripken** [comment]
I'm also adding the module and base for imports (i.e. `name = module.base`; name was already present).

**Comment by kripken** [comment]
Also adding the option to export a function by a different name than itself. If exported, we read a second string after the first.

**Comment by kripken** [comment]
Power of 2 memory does not allow memory size 0, which some spec tests need. Making it be power of 2 offset by 1, and "0" means actual 0.

**Comment by JSStats** [comment]
@kripken The issue of the export and import names has already been raised and these seem to be clearly the export and import names in the v8 encode. Binaryen needs to stop using the v8 encoding function name as an internal label name.

There seems little point hacking the power-of-two memory size when there are patches pending to move to a size in units of pages. Why don't you just land these patches to resolve the problem.

**Comment by kripken** [comment]
Well, it was useful to hack things to get full spec test coverage quickly. When there is consensus on the page size approach, we can change to that.

**Comment by kripken** [comment]
Meanwhile I now have the full spec test suite passing through the binary format - that is, each spec test passes after being converted to binary and back - so I don't think I'll need to do any more divergence.

**Comment by JSStats** [comment]
Great. Did you change all those u8's to leb128 too?

**Comment by kripken** [comment]
Just where I saw a problem. Not sure if that was all of them. We should definitely make sure to look at this eventually.

**Comment by kripken** [comment]
Also added a `start` section for the new wasm start property.

**Comment by jfbastien** [comment]
V8 has support for start: https://codereview.chromium.org/1692173002/
Maybe it's just missing from the binary format spec. @titzer ?

**Comment by titzer** [comment]
Yes, I just added it on Friday. I'd like to update the binary format PR
#537 if we can resolve some of the discussion there.
