### ISSUE TITLE
Windows installation/update fails for version 1.37.35

### ISSUE THREAD

**Issue by z--z---z-----** [WebAssembly/binaryen#1454]
The following error happens during the **emsdk install latest** step:

"
Installing tool 'emscripten-1.37.35'..
Error downloading URL 'https://github.com/kripken/emscripten/archive/1.37.35.zip': <urlopen error [Errno 1] _ssl.c:504: error:1407742E:SSL routines:SS
L23_GET_SERVER_HELLO:tlsv1 alert protocol version>
Installation failed!
"

There is a workaround, and it works:

https://groups.google.com/forum/#!topic/emscripten-discuss/4BTW7rdyXdw

But forces everyone trying to update the compiler to look for the solution, it would be nice to have the bundle with the appropriate python version.

**Comment by kripken** [comment]
Sorry about this, it is being discussed in #6275. Hopefully we can fix it soon.

**Comment by z--z---z-----** [comment]
Thanks. I am closing this issue then as there is another issue where this is being taking care of.
