### ISSUE TITLE
asm2wasm crashing with min and max functions

### ISSUE THREAD

**Issue by sboys3** [WebAssembly/binaryen#1455]
When I attempt to compile this code it causes asm2wasm to crash. It only crashes when I use the min or max functions. I can use other functions such as abs without any problems.

	function init(stdlib, foreign, heap){
		"use asm";
		var min=stdlib.Math.min;
		var max=stdlib.Math.max;
		var imul=stdlib.Math.imul;
		var abs=stdlib.Math.abs;
		function clamp(a){
			a=a|0;
			var b=0;
			b=max(min(a|0,255),0);
			//b=abs(a|0);
			return b|0;
		}
		
		return {clamp:clamp};
	}

**Comment by kripken** [comment]
The error handling in asm2wasm is not very good, sorry about that. The issue here is that min/max are float operations in both asm.js and wasm, so doing them on an integer is an error. I opened #1456 with better reporting.

**Comment by kripken** [comment]
The error should be clear now with that merged. Thanks for filing!
