### ISSUE TITLE
complete npm example

### ISSUE THREAD

**Issue by pannous** [WebAssembly/binaryen#1490]
At https://www.npmjs.com/package/binaryen
newcomers might appreciate if the last three dots 
"..." will be completed:
const compiled=new WebAssembly.Module(wasmData)
const instance = new WebAssembly.Instance(compiled, {})
console.log(instance.exports.add(41,1))

**Comment by kripken** [comment]
Good idea, cc @dcodeIO

**Comment by dcodeIO** [comment]
Should be in the README now, thanks! :)

**Comment by pannous** [comment]
beautiful
