### ISSUE TITLE
Large br_table in asm2wasm libc

### ISSUE THREAD

**Issue by jgravelle-google** [WebAssembly/binaryen#1501]
In asm2wasm's libc, in the function `frexp`, we generate a `br_table` with 2048 cases, even though it only has three branch targets, which adds 2KB to the module size.

A small standalone reproduction (stripped-down version of frexp) is:
```c
__attribute__((noinline))
int foo(int x, int *e) {
  int ee = x & 0x7ff;
  if (!ee) {
    return foo(x*0x1p64, e);
  } else if (ee == 0x7ff) {
    return x;
  }

  *e = ee - 0x3fe;
  return x;
}

int main(int argc, char** argv) {
  int x = 10;
  x += foo(argc, &x);
  return x;
}
```

**Comment by jgravelle-google** [comment]
I agree that we should fix it in a Binaryen pass, which is why I filed this here as opposed to Emscripten :)

And I think that saying "wasm backend is smaller than asm2wasm because asm2wasm does something fairly degenerate" is an unsatisfying place to wind up.

**Comment by AndrewScheidecker** [comment]
I was browsing the issues and noticed that this is a dup of #1098.

**Comment by kripken** [comment]
Thanks @AndrewScheidecker . We can close both after #1502.
