### ISSUE TITLE
"parse exception: duplicate function name" seems unnecessary

### ISSUE THREAD

**Issue by fitzgen** [WebAssembly/binaryen#1503]
```
$ wasm-opt ./wasm_game_of_life_bg.wasm > /dev/null 
[parse exception: duplicate function name: _ZN55_$LT$alloc..heap..Heap$u20$as$u20$core..heap..Alloc$GT$3oom17hd04c1481d29d6dd3E]Fatal: error in parsing input
```

The name section is for debugging purposes only, and it seems odd that a duplicate name results in a hard error where I can't run `wasm-opt` anymore.

FWIW, this wasm was generated by rustc and wasm-bindgen

**Comment by fitzgen** [comment]
Test case: [wasm_game_of_life_bg.zip](https://github.com/WebAssembly/binaryen/files/1895601/wasm_game_of_life_bg.zip)

**Comment by fitzgen** [comment]
I just rebuilt and this is fixed on the latest master. Sorry for the noise!

**Comment by kripken** [comment]
What revision of binaryen is that? That error message appears to have been removed based on git, with a fix, and running current master I can't reproduce the failure on that input.

**Comment by kripken** [comment]
Ah heh we had a race condition :)
