### ISSUE TITLE
flake8 errors are hard to notice

### ISSUE THREAD

**Issue by kripken** [WebAssembly/binaryen#1559]
For example https://api.travis-ci.org/v3/job/381223420/log.txt

The log ends with
```
The command "./check.py --test-waterfall" exited with 0.[0m

Done. Your build exited with 1.
```
which seems very confusing. You need to search for the string "exited with" to find the flake8 error, that is, it hits an error in that stage, keeps going, and marks the entire build as failed after that.

**Comment by kripken** [comment]
I hit this again now. At least I remembered how to figure it out ;)

cc @sbc100, I think you set up the current flake8 stuff?

**Comment by sbc100** [comment]
Sadly this is just how travis works.. each of the "scripts" runes independently, and if any one of them fails then the whole thing is considered to have failed, but it doesn't stop at the first failure.

There are probably ways around this.  I'll give it a go.
