### ISSUE TITLE
What's BinaryenHost ?

### ISSUE THREAD

**Issue by xqyww123** [WebAssembly/binaryen#1564]
I'm writting a binding for Crystal, but cannot find any document about `BinaryenHost`.
It'a trivial question but there are only 5 pages about `BinaryenHost` in Google.
Thanks.

**Comment by kripken** [comment]
It's an expression representing a wasm "host" op, that is, one of the special operations that connect to the host environment. `HostOp` in `wasm.h` has a list of the possible operations, which are `page_size, current_memory, grow_memory, has_feature`. (`grow_memory` is probably the only one that really matters at this point.)

Glad to hear about Crystal bindings, btw :)

**Comment by xqyww123** [comment]
@kripken, thank you, but could you please tell me more about parameter `name`, or an example of `grow_memory` calling. Really thanks.

**Comment by kripken** [comment]
Looks like `nameOperand` is used for `hasfeature` (I found that in `Print.cpp`).

For examples of `grow_memory` etc, you can search in the wasm spec test suite under `test/` in https://github.com/WebAssembly/spec The rest of the spec repo should have details on what the host operations mean, but in my experience reading the tests is usually easier.

**Comment by xqyww123** [comment]
So, could I regard `name` as just a comment for developing?

**Comment by kripken** [comment]
It depends. As I said, `has_feature` uses it. If that is necessary, then `name` is. But I'm not sure if it is.

**Comment by xqyww123** [comment]
OK I understand you, `nameOperand` is the name of feature to test by `has_feature`.
Thanks.
