### ISSUE TITLE
Math simplification and constant folding

### ISSUE THREAD

**Issue by MaxGraey** [WebAssembly/binaryen#1593]
It seems constant fold propagation with combination of math simplification not always work as properly (-O3 opt flag enabled).

Minimal example case:

```ts
export function test(value: u64): u64 {
  var mod1: u64 = -1;
  var mod2: u64 = -1;

  var rlo = value << 1;
  var rhi = rlo & ~mod2; // <<< problem part. Should always fold to 0

  rhi |= rhi << 1;
  rhi |= (value >> 63) & mod1;
  return rlo + rhi;
}
```
Produce:
```wat
(func $main/test (export "test") (type $t0) (param $p0 i64) (result i64)
    (local $l0 i64) (local $l1 i64)
    get_local $p0
    i64.const 1
    i64.shl
    tee_local $l1
    i64.const 0
    i64.and
    tee_local $l0
    get_local $l0
    i64.const 1
    i64.shl
    i64.or
    get_local $p0
    i64.const 63
    i64.shr_u
    i64.or
    set_local $l0
    get_local $l1
    get_local $l0
    i64.add)
```
But expected:
```wat
(func $main/test (export "test") (type $t0) (param $p0 i64) (result i64)
    get_local $p0
    i64.const 1
    i64.shl
    get_local $p0
    i64.const 63
    i64.shr_u
    i64.add)
```

### [Full example](https://webassembly.studio/?f=pazst4cesyl)

**Comment by MaxGraey** [comment]
That happened because binaryen can't recognize unsigned value and always operate with signed integer types, right?

**Comment by kripken** [comment]
When I compile that link with `-O0`, then run binaryen `wasm-opt -O3` on that, I get
```
 (func $foo3 (; 0 ;) (type $3) (param $0 i64) (result i64)
  (local $1 i64)
  (i64.add
   (tee_local $1
    (i64.shl
     (get_local $0)
     (i64.const 1)
    )
   )
   (i64.const 0)
  )
 )
```
which looks almost optimal to me (the `tee` can be removed, which another `-O3` does, which we may want to fix).

Is it possible you're using an older binaryen.js, before recent optimization improvements?

**Comment by kripken** [comment]
(I think `foo3` is the right function to look at in that link - I don't see a `test` there?)

**Comment by MaxGraey** [comment]
Ahh, sorry. I link to older complicated version (updated "full example" link). But that almost the same

**Comment by MaxGraey** [comment]
The binaryen already run with "-O3" optimization, see gulpfile.js flags

**Comment by kripken** [comment]
Thanks, now I see `test` and also I see the problem.

That type is code requires flattening for the optimizer to work optimally. When I run `--flatten -O3` I get
```
(module
 (type $0 (func (param i64) (result i64)))
 (memory $0 1)
 (export "test" (func $main/test))
 (export "expected" (func $main/test))
 (export "memory" (memory $0))
 (func $main/test (; 0 ;) (type $0) (param $0 i64) (result i64)
  (i64.add
   (i64.shl
    (get_local $0)
    (i64.const 1)
   )
   (i64.shr_u
    (get_local $0)
    (i64.const 63)
   )
  )
 )
)
```
which looks optimal, it propagated everything and then merged `test` and `expected`.

In general, running `flatten` adds significant overhead, but it can definitely be worth it as you can see here. I've also improve `flatten` quite a bit recently and it should be ready for general use now. So perhaps we should add an `-O4` which does `--flatten -O3`, what do you think?

**Comment by MaxGraey** [comment]
Yah, I like idea about `-O4` or `-Ofast` (which apply all perf passes)

**Comment by MaxGraey** [comment]
By the way if manually replace this line:
```ts
var rhi = rlo & ~mod2;
```
to this:
```ts
var rhi = rlo & ~-1;
```
All works as expected

**Comment by dcodeIO** [comment]
@kripken Does `--flatten` have to be run before, after or between other optimizations?

**Comment by kripken** [comment]
@dcodeIO before. I really should write a blogpost about the whole optimizer design, that would explain why. meanwhile though, I'll can have `-O4` ready for use soon (maybe today), including local-cse (that fixes https://github.com/WebAssembly/binaryen/issues/1521#issuecomment-385485525 ).

**Comment by kripken** [comment]
`-O4` landed, which fully optimizes this, closing.
