### ISSUE TITLE
Non-trapping float to int conversion

### ISSUE THREAD

**Issue by MaxGraey** [WebAssembly/binaryen#1597]
According to [this](https://github.com/WebAssembly/design/issues/1143) feature moved to Stage 4 and standardize for now.

I tried to start integrate this into binaryen but find it difficulty. [This spec](https://github.com/WebAssembly/nontrapping-float-to-int-conversions/blob/master/proposals/nontrapping-float-to-int-conversion/Overview.md#encoding) propose new prefix code, so currently we can have 2 bytes opcode like `0xfc 0x01` and I'm not sure about how legit just add extended opcode values (`0xfc01`) in the [following file](https://github.com/WebAssembly/binaryen/blob/master/src/wasm-binary.h#L515)?
It seems also it required make some changes to binary parser and serializer.

So my question is how complicate this task and maybe my skills will not be enough for now?

**Comment by binji** [comment]
I don't know much about binaryen, but the [atomic prefix](https://github.com/WebAssembly/binaryen/blob/master/src/wasm-binary.h#L547) will work the same way as the `0xfc` prefix, so you can probably use that as a guideline.

**Comment by MaxGraey** [comment]
Thanks @binji seems it a good start point
