### ISSUE TITLE
Type check aborting on an unreachable expressions.

### ISSUE THREAD

**Issue by JSStats** [WebAssembly/binaryen#160]
The following validates in ml-proto and sexp-wasm, but fails in wasm-as:
```
(module
 (func $f1 (result i32)
  (i32.xor (unreachable) (i32.const 10))))
```
src/wasm.h:827: void wasm::Binary::finalize(): Assertion `left->type == right->type' failed.

The type system can view the result of unreachable code as the empty set of types. The test is then that the actual type must be a subset of the expected type. Here the expected type is i32, and the actual type is the empty set. An empty set is a subtype of every other set, so this test would pass. Practically, when checking the type, if the actual type is the result of unreachable then the test passes.

Note that the unreachable type needs to propagate bottom up through the parameterised operators as they do not otherwise have a type, but wasm type checking appears to demand that they do not propagate any further. For example, `(i32.xor (f64.add (unreachable) ...) (i32.const 10))` would not validate. Top-down type checking would need to pass the expected type through the parameterised operators.

Note that `br` and `return` also have the empty set as their result types. The following also fails in wasm-as for the same reason:

```
(module
 (func $f1 (result i32)
   (block $l1 (i32.xor (br $l1 (i32.const 1)) (i32.const 10)))))
```

```
(module
 (func $f1 (result i32)
   (i32.xor (return (i32.const 1)) (i32.const 10))))
```

**Comment by sunfishcode** [comment]
This would be a great candidate for the spec repo's testsuite too.

**Comment by kripken** [comment]
Also fixed, and again I didn't add a test since looks like this will be tested in the spec tests anyhow.
