### ISSUE TITLE
Type check error for loop.

### ISSUE THREAD

**Issue by JSStats** [WebAssembly/binaryen#161]
The following example is failing in wasm-as but works in ml-proto and sexp-wasm:

```
(module
 (func $f1 (result i32)
  (i32.add (loop $l0 $l1 (i32.const 1))
           (i32.const 1))))
```
src/wasm.h:860: void wasm::Binary::finalize(): Assertion `0 && "left->type == right->type"' failed.

**Comment by sunfishcode** [comment]
It would be great to get testcases like this added to the spec repo's testsuite. wasm-as is tested against that, and many other things.

**Comment by kripken** [comment]
Fixed. I didn't add a test since looks like this will be tested in the spec tests anyhow.
