### ISSUE TITLE
BINARYEN_ASYNC_COMPILATION disabled due to user options.

### ISSUE THREAD

**Issue by rrhitman** [WebAssembly/binaryen#1619]
Hello, 
I am new to emscripten. I have a module which is used as shared library and a main module which uses dlopen to open the shared library. However I use the following command to build the shared library.

`emcc -O1 -s BINARYEN_ASYNC_COMPILATION=1 -s SIDE_MODULE=1 testLib.cpp -o testLib.bc`

I following warning:

> WARNING:root:BINARYEN_ASYNC_COMPILATION disabled due to user options. This will reduce performance and compatibility (some browsers limit synchronous compilation), see https://github.com/kripken/emscripten/wiki/WebAssembly#codegen-effects

I am using emscripten 1.38.8. What am I doing wrong here ?

**Comment by kripken** [comment]
I replied about the warning in the other issue you filed, https://github.com/kripken/emscripten/issues/6837 In the future, please don't open duplicate issues even in separate repos - unless there's no response for a long time in one ;)

About the second question here: dlopen loads a file from the filesystem, so the shared library should just be a normal file packaged there. Docs for that are here: http://kripken.github.io/emscripten-site/docs/porting/files/packaging_files.html

**Comment by rrhitman** [comment]
Sorry for the duplicate issues. Will close this down. Thank you for the link.
