### ISSUE TITLE
Precomputing simple function bodies

### ISSUE THREAD

**Issue by dcodeIO** [WebAssembly/binaryen#1624]
While doing the changes in https://github.com/WebAssembly/binaryen/pull/1622 I figured that, maybe, some function calls can be precomputed as well (i.e. calls to functions with a side-effect free body that can again be precomputed by PrecomputingExpressionRunner).

For example:

```ts
function isNaN<T>(value: T): bool { return value != value; }
function isFinite<T>(value: T): bool { return value - value == 0; }
```

Do you think that's something worth exploring?

**Comment by kripken** [comment]
Yeah, we should make sure stuff like that is well-optimized. I think the main mechanism is inlining - small functions like that should inlined, after which precompute etc. are run, which should give the effect you want? If so then the main thing here would be to improve our inlining rules.

**Comment by kripken** [comment]
Actually, maybe there is more than just improving the existing inlining rules. Maybe something like the inliner making its decisions using precompute, maybe even running it on potential locations to see if it's worth it...

**Comment by MaxGraey** [comment]
It will be great if binaryen will allow evaluate automatically or manually during compile time some pure functions for example which has all input arguments are constants and doesn't call any other non-pure functions in its body but can call himself (recursive). Something similar as `constexpr` in C++ 11. wdyt?

**Comment by kripken** [comment]
@MaxGraey Aside from the recursion, I think this could be handled by inlining (possibly with improvements)? The recursion sounds like a harder problem. I'm not sure offhand if that makes more sense in a general-purpose optimizer like binaryen or in the language's compiler. One argument for putting it in the language is that it may have a concept of `constexpr`, which binaryen and wasm don't (so in binaryen we'd need to try to find out which functions can be recursed into like this).

**Comment by MaxGraey** [comment]
Yeah, determine pure function case can be hard job for binaryen and it should do on host compiler side. Some compiler like C++ can handle this via `constexpr` but some like AssemblyScript or Go doesn't. So this could be provided by binaryen as api method but called manually per function instead implement this as some optimization pass.

**Comment by kripken** [comment]
I'm not sure about LLVM, but I don't think there is a constant/pure attribute for functions, http://llvm.org/docs/LangRef.html#function-attributes

I think it would make sense to start with the non-recursive case, see that we handle that well on examples, improving the inliner as necessary.

**Comment by MaxGraey** [comment]
Yah, but it seems `speculatable` LLVM flag for functions is pretty close to `pure` function. About constant expressions they are [described here](http://llvm.org/docs/LangRef.html#constant-expressions) but it seems they need only for simple constant folding.

**Comment by dcodeIO** [comment]
Btw. my impression was that this would also fit well into precompute because function arguments are already known to be constant and the Flow, well, just flows (stopping early) and does not have to care about introducing temp vars or blocks. Not sure if this is of any significance, though, haven't actually looked at the inliner.

**Comment by kripken** [comment]
@dcodeIO I see what you mean. However, structurally, the precompute pass is function-parallel, which means we run on each function separately, without looking at others. In particular function-parallel passes are safe to run on a function before we've even defined the functions it calls.

But you're right that this could fit there - we may want to add a new pass like "precompute-calls". However, I'd prefer to first try to see if we can achieve what we want using inlining first, until we get some testcases that inlining can't handle.

**Comment by dcodeIO** [comment]
While looking through my old issues here I figured that this one is actually related to https://github.com/WebAssembly/binaryen/pull/1898, heh. Similarly, it's not necessary for our use case anymore, hence closing.
