### ISSUE TITLE
Accepting -+nan

### ISSUE THREAD

**Issue by JSStats** [WebAssembly/binaryen#163]
Probably should not be accepting '-+nan' as valid float literal.

**Comment by jfbastien** [comment]
Which tool? Do you have a repro? s2wasm should handle `-nan` correctly, I didn't bother with `+nan` but I guess it doesn't hurt.

**Comment by binji** [comment]
looks like `parsing.h` allows "-+nan":
```
    bool negative = str[0] == '-';
    const char *positive = negative ? str + 1 : str;
    if (positive[0] == '+') positive++;
    if (positive[0] == 'n' && positive[1] == 'a' && positive[2] == 'n') {
  ...
```

**Comment by kripken** [comment]
Yeah, I guess we do accept this. Is it disallowed by the spec, though?

**Comment by binji** [comment]
Yep. https://github.com/WebAssembly/spec/blob/master/ml-proto/host/lexer.mll#L100

**Comment by kripken** [comment]
Thanks. Ok, let's fix this.

But first, `parsing.h` is also used by `s2wasm`. @sunfishcode, is `-+nan` a valid value in the `.s` format?

**Comment by jfbastien** [comment]
It's **allowed** by the spec, or am I reading this wrong?

**Comment by JSStats** [comment]
@jfbastien '-+nan' fails to parse in the ml-proto.

**Comment by sunfishcode** [comment]
`-+nan` is not valid in the .s syntax -- both GAS and llvm-mc reject it.

**Comment by jfbastien** [comment]
Ah I misunderstood: you weren't asking about `-` *or* `+`, you were asking about *both* `-+` right?

**Comment by kripken** [comment]
Fixed.
