### ISSUE TITLE
Source Map not generated correctly for return

### ISSUE THREAD

**Issue by aseemgarg89** [WebAssembly/binaryen#1640]
Source Maps seem to be pointing at wrong location for return statement.
Step to reproduce:
compile the following code (saved as hello.c) using: emcc hello.c -g4 --source-map-base "http://localhost:8080/" -s BINARYEN=1 -o hello.html
reading the hello.wasm.map file using sourcemap2json.js shows return statement mapped to location 1225 but that doesn't seem to be correct (using wasm-objdump, it seems to be at 1221).

code:
#include <stdio.h>
int main(int argc, char ** argv) {
  printf("Hello, world!\n");
  printf("second hello\n");
  return 0;
}

**Comment by kripken** [comment]
The `.wast` at least looks correct, with
```
  ;;@ a.cpp:5:0
  (return
   (i32.const 0)
  )
```
(5 is indeed the line with the return). So something might be going wrong in the later offset computation.

cc @yurydelendik

**Comment by yurydelendik** [comment]
Can you provide version for emscripten and binaryen? #1628 can be in play here

**Comment by yurydelendik** [comment]
I just check a dump (via https://wasdk.github.io/wasmcodeexplorer/) of built with incoming emscripten:

<img width="1211" alt="screen shot 2018-08-21 at 2 30 23 pm" src="https://user-images.githubusercontent.com/1523410/44424458-cbcc5c00-a54e-11e8-926a-6f40b58e3cae.png">

1219 == 0x4C3  The `return 0;` points to the right location. WFM

**Comment by aseemgarg89** [comment]
I am using emscripten version 1.38.8

For me the source map for the given file decodes to 
[{"source":"hello.c","generatedLine":1,"generatedColumn":1205,"originalLine":3,"originalColumn":0,"name":null},{"source":"hello.c","generatedLine":1,"generatedColumn":1213,"originalLine":4,"originalColumn":0,"name":null},{"source":"hello.c","generatedLine":1,"generatedColumn":1225,"originalLine":5,"originalColumn":0,"name":null}]

the objdump (also verified in the wasmcodeexplorer linked above) shows the return at 0x4c5 == 1221.
The other 2 seem to be correct (1-based) at 0x4b4 == 1204 and 0x4bc == 1212.

PS: I am building this on a macbook.

screenshot of relevant part of objdump
<img width="464" alt="screen shot 2018-09-04 at 2 00 17 pm" src="https://user-images.githubusercontent.com/13683642/45057718-3dc29c00-b04b-11e8-8553-22de39f68e1a.png">

**Comment by aseemgarg89** [comment]
Attaching my generated files for reference.

[hello.tar.gz](https://github.com/WebAssembly/binaryen/files/2350257/hello.tar.gz)

**Comment by yurydelendik** [comment]
> I am using emscripten version 1.38.8

v1.38.8: 07/06/2018 predates fix for https://github.com/WebAssembly/binaryen/pull/1628 (7/25/2018)

Closing as fixed. Please check your files with newer version to reopen the issue.
