### ISSUE TITLE
binaryen.js bot failing on asm.js output

### ISSUE THREAD

**Issue by dcodeIO** [WebAssembly/binaryen#1669]
The binaryen.js bot [started failing](https://travis-ci.org/AssemblyScript/binaryen.js/jobs/423958081#L5401) 5 days ago with `Fatal: non-function imports aren't supported yet` while emitting asm.js, possibly related to recent changes in wasm2asm/wasm2js. Doesn't affect the build directly, just [this test](https://github.com/AssemblyScript/binaryen.js/blob/master/tests/index.js#L119-L125). Any ideas? :)

**Comment by kripken** [comment]
Looks like that error comes from f109f3cae1cd81db22ba490a4da17a7a4c495047 , #1642 , cc @alexcrichton

My guess is that that's a new assert added there, and indeed wasm2js doesn't support non-function imports (that is, globals) yet. We don't have a test for a module with globals, but looks like the binaryen.js bot does. What does the module it is trying to translate look like?

**Comment by dcodeIO** [comment]
> My guess is that that's a new assert added there

That'd make sense, yeah.

The test module looks like:

```wat
(module
 (type $i (func (result i32)))
 (import "env" "provided" (func $imported (result i32)))
 (import "env" "memory" (memory $0 0))
 (export "main" (func $main))
 (export "memory" (memory $0))
 (func $main (; 1 ;) (type $i) (result i32)
  (return
   (i32.const 0)
  )
 )
)
```

Likely the memory import then.

**Comment by kripken** [comment]
Oh ok, makes sense now. I see the same error in the native build too.

I was confused because I thought we did have tests with imports, but I guess that was for wasm2asm, before wasm2js. So for now, need to disable that test on your bot.

(Also, we should rename the binaryen.js API to be `emitJS`.)

**Comment by alexcrichton** [comment]
Ah sorry about that! Would it be possible to ignore the test for `wasm2js` mode? From a feature perspective I'm not sure how practical it'd be to support imported memories for `wasm2js` because the only way it'd work is to pass in a duck-typed object that looked like `WebAssembly.Memory` (because that can't be assumed to exist)

**Comment by dcodeIO** [comment]
Thanks! Made it so that the bot removes the memory import again before testing the asm.js output, which works.
