### ISSUE TITLE
Missing option to declare memory as shared in BinaryenAddMemoryImport and BinaryenSetMemory

### ISSUE THREAD

**Issue by nidin** [WebAssembly/binaryen#1679]
# Introduction
I am working on worker based threads support for AssemblyScript. AS is using **BinaryenAddMemoryImport** to memory import and **BinaryenSetMemory** to set the initial module memory. These functions have no arguments to declare memory as shared. 

# Solution 
Add a new argument `bool shared`
and define `wasm->memory.shared = true` if argument shared is true.

PS: Please advice if an alternative solution already exist.

**Comment by kripken** [comment]
Makes sense. Another option is to add a single function to set the shared flag, but I think what you suggested is better and more consistent with the current API.

**Comment by nidin** [comment]
@kripen I can submit a PR for this. Is there any restrictions that shared memory need to be declared with max pages ?

**Comment by kripken** [comment]
Thanks, a PR sounds great!

I believe that's right about shared memory, the [docs say](https://github.com/WebAssembly/threads/blob/master/proposals/threads/Overview.md#resizing) it needs to define a max size.

**Comment by dcodeIO** [comment]
Should also add the new parameter to the JS wrapper [here](https://github.com/WebAssembly/binaryen/blob/master/src/js/binaryen.js-post.js#L1079).

**Comment by nidin** [comment]
👍🏻 I will update it.
