### ISSUE TITLE
Strange NaN memory behavior

### ISSUE THREAD

**Issue by kripken** [WebAssembly/binaryen#1680]
This was noticed in https://github.com/WebAssembly/binaryen/pull/1641#issuecomment-421157814 where that PR broke `binaryen2.test_float_builtins`. The new pass from that PR happens to let the binaryen optimizer see this:
```
   (f64.div
    (f64.const 0)
    (f64.const 0)
   )
```
which it optimizes to
```
   (f64.const nan:0x8000000000000)
```
That seems right, and the spec interpreter agrees on it. However, when we store it to memory and load it, the high bits are different. I see this in both v8 and sm, so it doesn't look like a VM issue. Is this expected behavior?

Here's a full testcase:
```
(module
 (memory $0 1 1)
 (export "memory" (memory $0))
 (func "func1"
  (f64.store
   (i32.const 0)
   (f64.div
    (f64.const 0)
    (f64.const 0)
   )
  )
 )
 (func "func2"
  (f64.store
   (i32.const 0)
   (f64.const nan:0x8000000000000)
  )
 )
 (func "func3"
  (f64.store
   (i32.const 0)
   (f64.const -nan:0x8000000000000)
  )
 )
)
```
Create a binary from that, and then run this JS, passing the filename of that binary as an argument,
```
if (typeof console === 'undefined') {
  console = { log: print };
}
var binary;
if (typeof process === 'object' && typeof require === 'function' /* node.js detection */) {
  var args = process.argv.slice(2);
  binary = require('fs').readFileSync(args[0]);
  if (!binary.buffer) binary = new Uint8Array(binary);
} else {
  var args;
  if (typeof scriptArgs != 'undefined') {
    args = scriptArgs;
  } else if (typeof arguments != 'undefined') {
    args = arguments;
  }
  if (typeof readbuffer === 'function') {
    binary = new Uint8Array(readbuffer(args[0]));
  } else {
    binary = read(args[0], 'binary');
  }
}
// main
var instance = new WebAssembly.Instance(new WebAssembly.Module(binary), {});
var buffer = instance.exports.memory.buffer;
var heapu8 = new Uint8Array(buffer);
function check(name, description) {
  console.log('storing: ' + description);
  instance.exports[name]();
  console.log('     high byte: ' + heapu8[7]);
}
check('func1', '0 / 0');
check('func2', 'nan');
check('func3', '-nan');
```
The output is
```
storing: 0 / 0
     high byte: 255
storing: nan
     high byte: 127
storing: -nan
     high byte: 255
```
That is, storing `0 / 0` results in the same high bits as when storing a *negative* NaN...?

cc @sbc100 @sunfishcode

**Comment by sunfishcode** [comment]
Yes, the sign bit of a NaN generated by an arithmetic instruction like 0/0 is nondeterministic in wasm.

**Comment by kripken** [comment]
Thanks @sunfishcode! For some reason I remembered nondeterminism was possible in simd but forgot about this. So I guess we need to update that test to not depend on nondeterminism in wasm, I'll do that.

**Comment by sbc100** [comment]
Thanks for tracking that down!
