### ISSUE TITLE
C-API support for growing tables

### ISSUE THREAD

**Issue by dcodeIO** [WebAssembly/binaryen#1683]
The C-API currently provides the following API to set a module's function table

```c
// Function table. One per module
void BinaryenSetFunctionTable(BinaryenModuleRef module, const char** funcNames, BinaryenIndex numFuncNames);
```

that doesn't allow us to set the maximum table size like `BinaryenSetMemory` does for memory.

I haven't yet looked into the internals, but I'd propose to add a third parameter for the maximum size so `WebAssembly.Table#grow` can be used with a module assembled by Binaryen. When `0` is provided, `numFuncNames` would be used as the maximum. Currently, any table set by Binaryen has a fixed size and can't grow. Wdyt?

**Comment by kripken** [comment]
Sounds good.
