### ISSUE TITLE
Windows and OSX binary releases

### ISSUE THREAD

**Issue by ashleygwilliams** [WebAssembly/binaryen#1695]
Hi! I work on [`wasm-pack`](https://github.com/rustwasm/wasm-pack), an integrated build tool for rust->wasm projects and we are currently looking to integrate `wasm-opt` into the tool. Based on the current status of the APIs here, I think we'd like to download a binary of the tool and run it in a child process. I see that you have a bunch of release binaries on GitHub, but notably don't have ones for MacOS or Windows, which are 2 of `wasm-pack`s most heavily used OSes. Would you be willing to produce those as well? Let me know if you have any questions or if there's any way I can help!

cc @fitzgen

**Comment by kripken** [comment]
Good idea!

We probably need help with this, though - I don't think any of the active developers here know how to do that - even the current linux builds were added by someone else (and I'm not sure how they work...).

**Comment by ashleygwilliams** [comment]
@kripken i am very happy to open a PR- i should be able to do it all just fine- the only thing i'd need help with would be understanding your current release versioning system (i see semver-seeming and "version_#" things and don't know how they relate) as well as a github key (though i may be able to reuse whatever the current setup is using)! i can get a WIP PR by tomorrow morning. maybe we can hop on a quick call to discuss the versioning thing? (or just a reply here would also work)

**Comment by kripken** [comment]
About the versioning, yeah, there are two - the `version_#` one is the relevant one, that's the main version. The other number is the corresponding emscripten version.

I'm not sure how the github key stuff works... it's all very mysterious to me ;)

Happy to do a call too if that can help.

**Comment by ashleygwilliams** [comment]
i'll get a PR started and we can go from there!

**Comment by alexcrichton** [comment]
I've posted the Windows half to https://github.com/WebAssembly/binaryen/pull/1700

**Comment by jakirkham** [comment]
FWIW we make [Conda]( https://conda.io/en/latest/ ) binaries in [conda-forge]( https://conda-forge.org/ ). Here's the [feedstock]( https://github.com/conda-forge/binaryen-feedstock ).
