### ISSUE TITLE
asm2wasm --mem-max (4GB) causes validation failure

### ISSUE THREAD

**Issue by jgravelle-google** [WebAssembly/binaryen#1699]
`asm2wasm --mem-max 4294967296` results in `[wasm-validator error in module] unexpected true: memory max >= initial` every time, because we `atoi` the argument, which wraps the value to 0.

**Comment by kripken** [comment]
Probably we should show an error there, yeah. But I don't think this can work, as browsers don't support over 2GB anyhow?

**Comment by dschuff** [comment]
I wouldn't artificially limit it to less than 4G. Browsers can ([and will](https://bugs.chromium.org/p/v8/issues/detail?id=7881)) fix limitations transparently so we shouldn't have to update the tools later to accommodate that.

**Comment by kripken** [comment]
Sounds good, I opened https://github.com/WebAssembly/binaryen/pull/1702 to fix this here.

**Comment by kripken** [comment]
Fixed by #1702
