### ISSUE TITLE
asm2wasm not folding away some redundant type coercions

### ISSUE THREAD

**Issue by JSStats** [WebAssembly/binaryen#17]
Spotted at lot of `(i32.shr_u <exp> 0)` operations. Most are probably a remnant of asm.js style and should be removed?

For example: `(i32.gt_u (i32.shr_u (get_local $i3) (i32.const 0)) (i32.shr_u (get_local $i1) (i32.const 0))))`

**Comment by kripken** [comment]
Yes, we should remove those. What source code led to them?

**Comment by JSStats** [comment]
Emscripten generated asm.js for the zlib benchmark. This example looks like asm.js `if (i3 >>> 0 > i1 >>> 0) ...`  Any asm.js unsigned operators might has similar issues.

**Comment by kripken** [comment]
I see, thanks, looks like for calls and returns we look through the coercions, but for comparisons specifically we don't. Looking into that now.

**Comment by kripken** [comment]
Ok, the issue wasn't comparisons, but rather that we had the look-through logic for `|0` but not `>>>0`. Fixed on master. Thanks again for filing!

**Comment by kripken** [comment]
Forgot to add the issue # in the commit, it was this: 2654fe23914c87afb2dd7340709db2cea5e2b047
