### ISSUE TITLE
[Proposal] Optimization Pass. Accelerating float division when the divisor is const

### ISSUE THREAD

**Issue by MaxGraey** [WebAssembly/binaryen#1712]
Currently in most languages this optimization is missing due imprecise issue which appear when do it in naive way like replace `x / 10.0` to `x * (1.0 / 10.0)` which actually `x * 0.1`. In float point space this not equal `x / 10.0 != x * 0.1`. But we could do this without rounding error and this described in current article:
 http://perso.ens-lyon.fr/nicolas.brisebarre/Publi/fpdivision.pdf

Compilers like GCC can do only imprecise naive optimization when `--ffast-math` flag is set.
I reproduced this algorithm with benchmark on AssemblyScript:
https://webassembly.studio/?f=1vgprmreu32

Results (Chrome 71.0.3578.20 beta):
![precomputez](https://user-images.githubusercontent.com/1301959/47618449-da4d6b80-dadb-11e8-95b0-dae3193ab2f6.png)

### Algorithm (Full precise):
1. Precompute `z` (this should be done in compile time):
```ts
function precompute(y: f64): f64 {
  let z1 = 1.0 / y;
  let e  = 1.0 - y * z1;
  let z2 = z1 + z1 * e;
  let e1 = e  * e;
  let z3 = z2 + z2 * e1;
  let e2 = e1 * e1;
  let z  = z3 + z3 * e2;
  return z;
}
```
where `y` is constant divider.
2. And finally actual optimized version of division by float point constant look like:
```ts
// use 1 mul and 2 mad/fma ops
function divconst(x: f64, y: f64, z: f64): f64 {
  let q1 = x * z;
  let r  = x  - y * q1;
  let q  = q1 + r * z;
  return q;
}
```
3. Replace `x / constY` to `divconst(x, constY, precompute(constY))`

### Also possible faster version but with some valid range limitations (only 98.7% fully precise results for double but could be used for single float points):
1. precompute z as described above and additionally compute `zl = 1.0 / y - z`
2. Procedure:
```ts
// use 1 mul and 1 mad/fma op
function divconst(x: f32, z: f32, zl: f64): f32 {
  return (x * z + (x * zl)) as f32;
}
```

cc @kripken @sunfishcode @jgravelle-google

**Comment by kripken** [comment]
iiuc, the article's algorithm 2 is what you are referring to? And it depends on fused multiply-add, which [may be added to wasm eventually ("fma")](https://webassembly.org/docs/future-features/)?

**Comment by MaxGraey** [comment]
I mean `FMA` as `mul+add` (may be better called this MAD) instruction set which on most modern hardware execute at the same time. However some CPUs support special `fma` (fused multiply add) which execute at the same time + avoid rounding error which appear if we execute `mul` and `add` sequentially. Anyway this algorithm should works without `fma`.

**Comment by sunfishcode** [comment]
The paper is very specific about using *fused* multiply-accumulate, including in algorithm 5, so it's not clear that the "Full precise" algorithm above is correct.

For the less precise version, that is something that Binaryen might want to have available, under control of something like a "fast-math" flag, because Binaryen is a much better place to do fast-math kinds of things than wasm engines.
