### ISSUE TITLE
Create a pass to erase non-numeric names.

### ISSUE THREAD

**Issue by mbebenita** [WebAssembly/binaryen#172]
The current implementation of `wasmTextToBinary()` in SpiderMonkey doesn't support non-numeric names. We should have a way to generate compatible `.wast` files so we can do testing. 

My current approach is to:
1. Make name serialization not print `$` in front of numeric names.
2. Write a Binaryen pass that updates all references to symbols to use numeric names.
3. Erase names on functions, labels, etc.
4. Make the AST serialization skip printing empty names:

```
  printMinorOpening(o, "local ");
  if (local.name != "") {
    o << local.name << ' ';
  }
  o << printWasmType(local.type) << ")\n";
```

Is this a reasonable approach? I can foresee problems when I erase names, because Binaryen may get confused about multiple symbols with the same empty `""` name. Another option would be to rename symbols, but just not print them, driven by some global switch toggled by a command line argument to the Binaryen shell.

**Comment by kripken** [comment]
Will this output parse ok in the spec interpreter? If yes, then it should already be re-parsable back into binaryen.

The AST printing can't avoid printing empty names, because e.g. a break needs to refer by name to somewhere. Unless you mean it would have a number there?

Overall it sounds fine to

1. Have a pass that makes all names numeric (`strip-names`?).
2. Make the printing emit as concise as possible output that is still spec-compliant when names are numeric.

**Comment by mbebenita** [comment]
> Unless you mean it would have a number there?

So, if it's a number, it just prints the number without the `$` prefix. Sometimes however, in the case of `function` it wouldn't print anything because the function name is now implicit, and thus empty.

I think Binaryen may have trouble parsing some AST nodes that don't have names, (imports for instance) so I'd have to fix those cases.

**Comment by kripken** [comment]
Ok. I hope you don't, though - we parse everything in the spec tests, and it has examples of those things. But yeah, might be something missing.

**Comment by mbebenita** [comment]
K, thanks, I'll look deeper, I just wanted to make sure I'm not way off track.

**Comment by jfbastien** [comment]
Can this be optional and off by default? It sounds like fixing SM is the better solution :-)

**Comment by mbebenita** [comment]
Yes, it would be optional and off by default. Since Binaryen can consume numeric names, I think it makes sense to also generate them (optionally). And yes, we should also fix SM to handle non-numeric names.

**Comment by jfbastien** [comment]
sgtm

**Comment by kripken** [comment]
Any updates here?

I had another thought meanwhile. Maybe not relevant if you're already close to done. But perhaps we should move printing out to a pass, which seems cleaner anyhow. Then we can have a print pass, and a printStripped pass. Or maybe stripping would be an option in a single print pass. That way, printing is entirely encapsulated on the side, and this would require no AST changes.

**Comment by mbebenita** [comment]
Yes, it would be nice to move printing to its own pass. I have a patch that
removes names in the AST, but binaryen can't interpret the ast correctly
afterwards. It's only good for printing really. I'll push what I have so
far.

I'm also writing a patch for SpiderMonkey to handle names, which should
help with testing since we would be able to run the spec test suite as is.
