### ISSUE TITLE
expected 'type' in call_indirect

### ISSUE THREAD

**Issue by singpolyma-shopify** [WebAssembly/binaryen#1724]
Here is a snippet that will produce this error from `wasm-as`:

```
(module
	(table $lambda 1 anyfunc)
	(elem (i32.const 0) $__lambda0)
	(func $all? (param $cbor i32) (param $array i32) (param $lambda i32) (result i32)
		(call_indirect (param i32) (param i32) (result i32) (get_local $cbor) (get_local $array) (get_local $lambda))
	)
)
```

Obviously this is not complete code, but my complete code contains this exact `call_indirect` and is accepted by `wat2wasm` from `wabt` without issue...

**Comment by binji** [comment]
My guess is that the binaryen parser doesn't support that syntax. The original syntax for `call_indirect` was:

```wasm
(call_indirect (type $sig) ...)
```

But we added support for inline signatures later. You can use the `wat-desugar` tool in wabt to convert it to a form that binaryen should accept:

```sh
wat-desugar old_file.wat --fold -o new_file.wat
```

**Comment by kripken** [comment]
Thanks @singpolyma-shopify and @binji, turns out that is in fact the issue. Added support for the new notation in #1725
