### ISSUE TITLE
Appveyor should be configured to cancel PR builds on a new push to the PR branch

### ISSUE THREAD

**Issue by tlively** [WebAssembly/binaryen#1758]
This thread suggests that this should be possible: https://help.appveyor.com/discussions/problems/586-cancel-queued-builds-for-old-commits-of-the-same-branch. I'm not sure who has permissions to configure this, but I'm pretty sure I don't.

**Comment by kripken** [comment]
Looks like I don't either - @dschuff probably can though?

Talking with @tlively I think we want to select "rolling builds" and "only for pull requests" there.

**Comment by kripken** [comment]
Huh, we changed it for the fork I do have access to, and it seemed to have worked... so looks like this is fine.
