### ISSUE TITLE
Are browser extensions feasible with WASM in C++

### ISSUE THREAD

**Issue by antoan** [WebAssembly/binaryen#1762]
I do not have a web development background but have a rough idea on how to go about using the Emacsen SDK to compile my code to asm.js  from C++, which I am familiar with and would like to stick to as much as possible.

I am aiming to be able to do things like access browser tabs, group/reorder them and communicate some of their state to external program like Emacs. 

I am unsure if it  is possible for WASM code to access the chromium browser api like this (eg to access tabs)?

**Comment by kripken** [comment]
That is not possible. Wasm programs can only access JS, which means you can only access the normal Web APIs. You can't do anything you can't do with the browser that JS can't do (except faster).

**Comment by antoan** [comment]
Pardon my ignorance, aren't  chrome.* APIs based on javascript? 
https://developer.chrome.com/extensions/tabs

I was hoping to call this from WASM using a tool like Embind.

**Comment by kripken** [comment]
Chrome APIs are available to Chrome extensions, but not to normal web pages. So you can't use them in normal web development, which is what I understood from your first post here, but maybe I was mistaken?

In any case, the rule is that if you can do something from JS, you can do it from wasm that calls JS (and yes, embind is one mechanism to do that).

**Comment by antoan** [comment]
Thank you very much.
