### ISSUE TITLE
MSVC error C2338 std::aligned_storage static_assert

### ISSUE THREAD

**Issue by Markyparky56** [WebAssembly/binaryen#1763]
Compiling binaryen under MSVC 15.9.2 emits the error (added some newlines since it's all one giant string)

```
c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\type_traits(1271): 
error C2338: You've instantiated std::aligned_storage<Len, Align> with an extended alignment (in other 
words, Align > alignof(max_align_t)). Before VS 2017 15.8, the member type would non-conformingly 
have an alignment of only alignof(max_align_t). VS 2017 15.8 was fixed to handle this correctly, but the fix 
inherently changes layout and breaks binary compatibility (*only* for uses of aligned_storage with 
extended alignments). Please define either (1) _ENABLE_EXTENDED_ALIGNED_STORAGE to acknowledge 
that you understand this message and that you actually want a type with an extended alignment, or (2) 
_DISABLE_EXTENDED_ALIGNED_STORAGE to silence this message and get the old non-conformant 
behavior.
```

In reference to the file mixed_arena.h, line 66

``` c++
  typedef std::aligned_storage<CHUNK_SIZE, MAX_ALIGN>::type Chunk;
```

Adding the line
```cmake
  ADD_COMPILE_FLAG("/D_ENABLE_EXTENDED_ALIGNED_STORAGE")
```

To CMakeLists.txt appears to be all that is required to fix it this. I ran check.py which seemed happy with the output.

**Comment by tlively** [comment]
@kripken Do we care about supporting the older compilers? If so, we should probably do something other than just silence the warning.

**Comment by Markyparky56** [comment]
MSVC 15.9 is the latest version, [released last week](https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes). The year is not synced with the version number.

**Comment by tlively** [comment]
@Markyparky56 But if we want to support VS 2017 15.8 or earlier, it sounds like we should decrease `MAX_ALIGN` so we actually get an error when it would be otherwise miscompiled.

**Comment by hackcasual** [comment]
/D_DISABLE_EXTENDED_ALIGNED_STORAGE will revert to old behavior

**Comment by Markyparky56** [comment]
Since [a fix appears to have been merged](https://github.com/WebAssembly/binaryen/pull/1823) I'll close this issue.
