### ISSUE TITLE
wasm2js miscompiles select instruction with i64 operands

### ISSUE THREAD

**Issue by ngg** [WebAssembly/binaryen#1767]
It seems that when `select` instructions with i64 operands are compiled to js only the low bits are actually set according to the condition.

The following code
```wast
(module
 (type $0 (func (result i64)))
 (func $0 (; 0 ;) (type $0) (result i64)
  (return
   (select
    (i64.const -1)
    (i64.const 0)
    (i32.const 1)
   )   
  )    
 )     
)
```

compiles to
```js
 var i64toi32_i32$HIGH_BITS = 0;
 function $0() {
  var i64toi32_i32$1 = 0, i64toi32_i32$0 = 0, wasm2js_i32$0 = 0, wasm2js_i32$1 = 0, wasm2js_i32$2 = 0;
  i64toi32_i32$1 = 0;
  i64toi32_i32$0 = i64toi32_i32$1;
  i64toi32_i32$1 = (wasm2js_i32$0 = 4294967295, wasm2js_i32$1 = 0, wasm2js_i32$2 = 1, wasm2js_i32$2 ? wasm2js_i32$0 : wasm2js_i32$1);
  i64toi32_i32$HIGH_BITS = i64toi32_i32$0;
  return i64toi32_i32$1 | 0;
 }
```
which gives the correct answer (-1) in the lower bits but the high bits are incorrectly set to 0.

**Comment by kripken** [comment]
cc @alexcrichton

**Comment by ngg** [comment]
So it seems like the bug is in the `i64-to-i32-lowering` pass, where `select` and `if` are handled the same way and `TempVar highBits` is always set in the false branch which becomes the high bit output of the full instruction. This works ok for `if` because only one of the branches actually execute, but in case of `select`, both branches execute so the high bits will always come from the false branch.
