### ISSUE TITLE
Sort the local variable order with the most frequently referenced first.

### ISSUE THREAD

**Issue by ghost** [WebAssembly/binaryen#18]
To give a canonical ordering for experimenting with the encoding efficiency it might help to sort each functions local variables with the most frequently referenced first. This way an encoding optimizing for small local variable indexes might do best, such as the polyfill-prototype-1. I assume similar encoding optimizations will be used in the MVP too because it appears quite effective.

**Comment by kripken** [comment]
We can do this in a binaryen pass, then it wouldn't be tied to asm2wasm (but asm2wasm could run it in its optimizations phase).

**Comment by tlively** [comment]
This is done by the ReorderLocals pass.
