### ISSUE TITLE
Stores in wasm-intrinsics.wast?

### ISSUE THREAD

**Issue by kripken** [WebAssembly/binaryen#1811]
https://github.com/WebAssembly/binaryen/blob/master/src/passes/wasm-intrinsics.wast#L573 - we have stores and loads of absolute address 1024. That looks risky, as user data could be there?

Are those used to implement reinterpret casts?

cc @alexcrichton

**Comment by alexcrichton** [comment]
Hm I'm not sure! IIRC these came straight out of LLVM, so it may some stack manipulation or something like that. May be a good point to regenerate them

**Comment by kripken** [comment]
Would regenerating them fix this - is it a bug? I think it might be expected, that is, maybe it's writing to some global memory location. So we'd need to modify the source code too?

Alternatively, we can maybe just patch those to point to address 0, which is safer and already done in other places in the wasm2js path.

**Comment by alexcrichton** [comment]
It seems like it's likely a bug! I sort of forget at this point :(

**Comment by brion** [comment]
It looks like these have been refactored to use of `wasm2js_scratch_store_i64` in `_ZN17compiler_builtins3int4udiv10divmod_u6417h6026910b5ed08e40E` used to implement `i64.div_u` -- however I see no corresponding loads.

If these don't do anything anymore, can they be removed?

**Comment by brion** [comment]
Oh nevermind I found the loads -- it's used to store the remainder, so gets used when called via the helper for `i64.rem_u`.

In that case I think we can close this out, as it's been refactored to use the preferred method of saving this data. :)
