### ISSUE TITLE
Tests that live in test/dot_s were deleted.  We should verify that the lld tests have enough metadata coverage.

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/binaryen#1813]
s2wasm tests were deleted in #1607.

I just noticed that there is at least one place there where had coverate of the metadata output that we currently like.  That is the "emJsFuncs" key in the json output.

**Comment by jgravelle-google** [comment]
In general I feel we should audit the deleted tests for features we still care about that we no longer have coverage for, which is mostly going to be metadata, but any of the emscripten-glue parts of s2wasm may not have a corresponding wasm-emscripten-finalize test.
