### ISSUE TITLE
--remove-unused-brs produces invalid wasm

### ISSUE THREAD

**Issue by tlively** [WebAssembly/binaryen#1833]
Running `wasm-opt foo.wast --remove-unused-brs` with the following contents of foo.wast leads to a validation error on the output.

```
(module
 (func $foo (result i32)
  (loop
   (return
    (i32.const 0)
   )
   (block $A
    (if
     (i32.const 0)
     (return
      (i32.const 0)
     )
     (br $A)
    )
   )
  )
 )
)
```

**Comment by binji** [comment]
This module is already invalid; it should have an `i32` return value.

**Comment by tlively** [comment]
I believe this might be one of the special cases of Binaryen's type system where its treatment of unreachable code is different from WebAssembly's since Binaryen wants to be able to reason locally about types, but if that is not the case, then there is a bug in the Binaryen validator since this module passes validation.

**Comment by kripken** [comment]
Yeah, this is a case where binaryen's unreachable type allows things that wasm does not. The loop here has unreachable type.

Fix in #1835 - we were flowing out a value through the block that does not actually flow. Thanks!

**Comment by binji** [comment]
I see -- I didn't realize the binaryen validator was more permissive than WebAssembly. Doesn't that mean that binaryen can produce invalid wasm files?

**Comment by kripken** [comment]
What should happen is that Binaryen IR has an unreachable type, but when we emit a wasm binary we make sure to produce something that is valid, removing the unreachable type where it appears. It's a potential source for bugs though, yeah - I wonder if we shouldn't reconsider this.
