### ISSUE TITLE
`wasm-opt -O <file>` should throw an error

### ISSUE THREAD

**Issue by surma** [WebAssembly/binaryen#1907]
When I run `wasm-opt -O3 myfile.wasm`, I get no error and no output, but myfile.wasm stays the same. This lead me to believe that these files had already been properly optimized.

Then @kripken told me that I had to specify an output file like this: `wasm-opt -O3 -o myfile2.wasm myfile.wasm`.

I think my first command should error.

**Comment by kripken** [comment]
Ah, I saw this after I opened https://github.com/WebAssembly/binaryen/pull/1908

Options seem to be

 * Emit a warning (what that PR does).
 * Emit an error.
 * Do what llvm-opt does, which is always output (to stdout).
 * Not change anything.

**Comment by surma** [comment]
Personally, I'd expect wasm-opt to overwrite the input file. That being said, all but the last option work for me, so I fully support your PR :)
