### ISSUE TITLE
assert should be used for validating assumptions, not error handling

### ISSUE THREAD

**Issue by binji** [WebAssembly/binaryen#191]
This is pervasive in binaryen. Some examples:
in `SExpressionParser::parseInnerList`:

```
      input = strstr(input, ";)");
      assert(input);
```

in `SExpressionParser::parse`:

```
      skipWhitespace();
      assert(input[0] == ')');
```

in `wasm::parseConst`:

```
      const char * modifier = positive[3] == ':' ? positive + 4 : nullptr;
      assert(modifier ? positive[4] == '0' && positive[5] == 'x' : 1);
...
  assert(ret->value.type == type);
```

There are many more of these, but it's often difficult to tell which asserts are failed assumptions.

Because assert() calls abort(), these look like crashes. So, for example, you can't easily use a fuzzer, because input errors look like crashes:

```
$ ../../../wasm-as id\:000000\,sig\:06\,src\:000000\,op\:flip1\,pos\:0 
wasm-as: .../binaryen/src/wasm-s-parser.h:68: List &wasm::Element::list(): Assertion `isList_' failed.
Aborted
```

This hides real crashes:

```
$ cat id\:000002\,sig\:11\,src\:000000\,op\:flip1\,pos\:0
)module
  (func (result i32) (return (i32.const 42))))
$ ../../../wasm-as id\:000002\,sig\:11\,src\:000000\,op\:flip1\,pos\:0 
Segmentation fault
```

**Comment by kripken** [comment]
Good point. Sorry about this.

My main problem in fixing it is that I'm not sure how much error handling we want here, nor what is an error we want to handle vs. not. So the line here is fuzzy in my head, not just in the code ;)

**Comment by binji** [comment]
Well, even if the input error isn't handled, having something like this would be better:
```
void fatal(const char* msg) {
  fprintf(stderr, "error: %s\n", msg);
  exit(1);
}
```

So it would be possible to distinguish an error and a crash.

Assertions are designed to be disabled (just define `NDEBUG`) so the program should have the same behavior with and without them enabled. That might be an easy way to determine which ones should be errors instead.

**Comment by jfbastien** [comment]
My rule would be: fuzzer-generate inputs should never be able to hit `assert`.

**Comment by kripken** [comment]
I guess I don't feel strongly about either of your comments. I'm not sure why a particular rule here is better than another (e.g., why shouldn't fuzzer testcases be able to hit assert?). So I'm happy to go with whatever you all agree to.

**Comment by jfbastien** [comment]
In most projects asserts are meant as a sanity check which can be disabled without the program being invalid. That means that user inputs should never be able to trigger asserts. This makes it easier to understand what the code does: when I add a new feature and hit an assert I know I messed up and broke how the program is intended to work.
