### ISSUE TITLE
Some notes about addisonal simple optimizations for f32/f64

### ISSUE THREAD

**Issue by MaxGraey** [WebAssembly/binaryen#1911]
1. Replace `a *= -1` to `a = -a`

Actual:
```wat
get_local $p0
f64.const -0x1p+0 (;=-1;)
f64.mul
```
Expected:
```wat
get_local $p0
f64.neg
```

2. `x * (1 / x)` => `x / x` or `x * (1 / y)` => `x / y`

Actual:
```wat
get_local $p0
f64.const 0x1p+0 (;=1;)
get_local $p0
f64.div
f64.mul
```
Expected:
```wat
get_local $p0
get_local $p0
f64.div
```

3. `-x / 1000`

Actual:
```wat
get_local $p0
f64.neg
f64.const 0x1.f4p+9 (;=1000;)
f64.div
```

Expected:
```wat
get_local $p0
f64.const -0x1.f4p+9 (;=-1000;)
f64.div
```

**Comment by binji** [comment]
There are explicit tests in the spec repo that disallow these transformations, see https://github.com/WebAssembly/spec/blob/master/test/core/float_exprs.wast.

**Comment by MaxGraey** [comment]
@binji 
I see:
https://github.com/WebAssembly/spec/blob/master/test/core/float_exprs.wast#L163

Hmm, may I ask why this all legalized for LLVM but not for wasm by spec?

**Comment by MaxGraey** [comment]
Also LLVM based compilers as Rust and emscripten produce:
```
get_local $p0
f64.neg
```
for `x * -1` without `-ffast-math`
Should they also disable this?

**Comment by kripken** [comment]
> `1 / (x / x) => NaN`

Hmm, why? E.g. if `x == 1`, then `1 / (1 / 1) => 1`?

**Comment by MaxGraey** [comment]
@kripken Good catch, looks like I meant another expression. Remove that

**Comment by binji** [comment]
> Hmm, may I ask why this all legalized for LLVM but not for wasm?
> 
> `nan * -1` produce `nan` but `-nan` => `-nan`. That's main reason?

Sorry, was on vacation. The difference is that the nan bitpattern changes. `fxx.neg` will only flip the sign bit, but `fxx.mul` (and other operators) will produce an arithmetic nan, which is a quiet nan with an indeterminate sign bit. LLVM can optimize this because AIUI the C language doesn't say anything about
nan bitpatterns.

**Comment by MaxGraey** [comment]
@binji I understand this. But I wondering is it necessary skip this optimizations for LLVM-backed compilers when they targeting to Wasm as well?

**Comment by binji** [comment]
No, the user of LLVM is operating with a different set of assumptions. If they care about nan bitpatterns, they know that they can't use LLVM for this (at least by default).

**Comment by MaxGraey** [comment]
Wow. This is unexpected!

**Comment by dcodeIO** [comment]
Would it be viable to make it an optional pass that a user must run explicitly? For instance, we have [a discussion](https://github.com/AssemblyScript/assemblyscript/issues/465) over at AssemblyScript to eventually add a compiler flag that emits deterministic code exclusively, but it seems that unless this flag is set, doing such optimizations would be fine.

**Comment by kripken** [comment]
Yes, I think an optional pass could do optimizations like these that are unsafe in general, but valid for some compiler.

Another option is to add a pass option, like "don't care about nan bits" - then existing passes can check that and behave accordingly. Sort of like the existing --ignore-implicit-traps.

**Comment by MaxGraey** [comment]
Other possible optimization for floats found on n-body bench:
```c++
function div(x: f64): f64 {
    return -x / 1000.0;
}
```
currently produce:
```wat
(func $div (export "div") (type $t0) (param $p0 f64) (result f64)
    get_local $p0
    f64.neg
    f64.const 0x1.f4p+9 (;=1000;)
    f64.div)
```
but optimal:
```wat
(func $div (export "div") (type $t0) (param $p0 f64) (result f64)
    get_local $p0
    f64.const -0x1.f4p+9 (;=-1000;)
    f64.div)
```
