### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Warchant** [WebAssembly/binaryen#1921]
https://github.com/WebAssembly/binaryen/blob/master/src/passes/LegalizeJSInterface.cpp#L197

```C++
    auto* func = new Function;
    ...
    if (!module->getFunctionOrNull(func->name)) {
      // 1. internally it allocates unique_ptr for this pointer, so if this is executed, it is fine
      module->addFunction(func);  
    } // 2. however, if ELSE is executed, then it is a memory leak. 
```

Same with `legal` variable

**Comment by kripken** [comment]
Thanks, yes, we should use `std::unique_ptr` for stuff like this. Perhaps you'd like to submit a PR?

**Comment by Warchant** [comment]
@kripken yes, I will definitely fix that.
