### ISSUE TITLE
Optimize call_indirect with constant index to direct call

### ISSUE THREAD

**Issue by dcodeIO** [WebAssembly/binaryen#1973]
A simple optimization to avoid `call_indirect`s seems to be to evaluate whether the function index is constant, and if that's the case, convert it to a direct call instead. For example, the following could eliminate `callee` if it did that, in turn eliminating the call, and maybe eliminating the function table if that's safe:

```wat
(module
 (type $v (func))
 (table $0 1 1 funcref)
 (elem (i32.const 0) $callee)
 (export "main" (func $caller))
 (func $callee (; 0 ;) (; has Stack IR ;) (type $v)
  (nop)
 )
 (func $caller (; 1 ;) (; has Stack IR ;) (type $v)
  (call_indirect (type $v)
   (i32.const 0)
  )
 )
)
```

Of course the signature might mismatch, which would result in a runtime error with a `call_indirect` but a validation error with a `call`, so the optimization should not be performed if that's the case to retain error semantics I guess. Also, if the table could be modified somehow, like if imported or exported, this can't be done I assume?

Binaryen.js test case for completeness:

```js
var binaryen = require("binaryen");

var mod = new binaryen.Module();

var ftype = mod.addFunctionType("v", binaryen.none, []);

mod.addFunction("callee", ftype, [], mod.block(null, [
]));
mod.setFunctionTable(1, 1, [ "callee" ]);

mod.addFunction("caller", ftype, [], mod.block(null, [
  mod.call_indirect(mod.i32.const(0), [], "v"),
]));
mod.addFunctionExport("caller", "main");

binaryen.setOptimizeLevel(4);
binaryen.setShrinkLevel(0);
binaryen.setDebugInfo(false);
mod.optimize();
if (!mod.validate())
  console.log("-> does not validate");
console.log(mod.emitText());
```

**Comment by dcodeIO** [comment]
The [exact use case](https://github.com/AssemblyScript/assemblyscript/pull/535#issuecomment-478243556) that lead me here is more complicated, though, and I am not sure if it can actually be optimized. Essentially, there is a `call_indirect` first that is always performed with a function index that never changes, so this also involves argument reduction where a function is always (indirectly, hmm) called with the same constant argument. For example:

```wat
(module
 (type $v (func))
 (type $vi (func (param i32)))
 (table $0 2 2 funcref)
 (elem (i32.const 0) $callee-1 $callee-2)
 (export "main" (func $caller))
 (func $callee-2 (; 0 ;) (; has Stack IR ;) (type $v)
  (nop)
 )
 (func $callee-1 (; 1 ;) (; has Stack IR ;) (type $vi) (param $0 i32)
  (call_indirect (type $v)
   (local.get $0) ;; so this index is actually always the same
  )
 )
 (func $caller (; 2 ;) (; has Stack IR ;) (type $vi) (param $0 i32)
  (call_indirect (type $vi)
   (i32.const 1) ;; callee-1 is always called with the same constant index
   (local.get $0)
  )
 )
)
```

Here, `caller` performs the first call_indirect, which cannot be optmized due to a dynamic index, with a constant argument, so `callee-1` is always called with the same argument (here: 0), which ideally would optimize to a direct call. This looks like it might be impossible to optimize because the argument to `callee-1` isn't known statically, but thought I mention it just in case :)

**Comment by kripken** [comment]
Ah, in AssemblyScript is the table neither imported nor exported? Then yeah, we should definitely do this, I opened #1974 Please test if you can, and let me know if you find any issues or if I've missed something in the testing.

(In emscripten we need to access the table from the outside, so this can't be done in general.)

Note that the optimizer can handle even your last testcase, since inlining/dae can eventually result in a constant index there. However, it depends on the order of the passes and if they were run enough times - but when running with `--converge` it should definitely work, please file an issue if not.

**Comment by dcodeIO** [comment]
> in AssemblyScript is the table neither imported nor exported?

Hmm, good point actually. The compiler expects that GC-related functions and the `null` placeholder at index 0 won't be modified, but the table is actually exported by default to deal with function pointers. Of course, I'd say, didn't think that through yet apparently. Which leads me to: Would it maybe make sense to have an option for that pass, similar to the safe memory flag for propagating constant load offsets, that sets a table index up to that it's safe (or rather, required to be safe by the generator) to perform directize even though the table is exported?

**Comment by kripken** [comment]
Possibly we can consider an option, but like with that other one, we should be sure there isn't a better solution first, as these add complexity.

 * Why does AS export the table - you say "for function pointers", but why specifically?
 * If the compiler knows GC functions are fixed in the table and will never move, why are they not generated as direct calls in the first place?
 * How big is the win from doing this, in code size and speed? (can test with that PR)

**Comment by dcodeIO** [comment]
> Why does AS export the table - you say "for function pointers", but why specifically?

A user can return a function from a module export, look up the function in the table, do something with it, and specify it as an argument to an export again. For example:

```ts
function doSomething(): void {
  ...
}
export function someExport(): () => void {
  return doSomething;
}
export function someOtherExport(fn: () => void): void {
  fn();
}
```

> If the compiler knows GC functions are fixed in the table and will never move, why are they not generated as direct calls in the first place?

It would actually be possible to make most of this direct calls, yeah. One reason for not doing this right away was that the garbage collector in AssemblyScript is pluggable, so the compiler provides the necessary functionality to implement a GC instead of integrating it. One such compiler-generated thing is that each class has an implicit traversal function to traverse its reference-typed fields, of the form

```ts
MyClass.__iterate(fn: (ref: usize) => void) {
  ...
}
```

which is general enough to implement a tracing GC that provides `fn`. Currently, the GC obtains the respective traversal function from a managed header that each object has, which contains its class id which itself equals the function index of the traversal function, calling it indirectly. Example: GC wants to mark, calls a builtin `iterateRoots` function to obtain all root references, and from there on indirectly calls all the iterate functions to traverse all reachable references, marking them before sweeping.

The obvious alternative there is to bake this into the module, calling the mark implementation statically (e.g. a global `__ref_mark` function instead of a dynamic `fn`) and replacing use of the function table with a compiler-generated function containing a big switch that hosts all the traversal code, by class id.

> How big is the win from doing this, in code size and speed?

I'd assume that most indirect calls a GC emits can be optimized this way. For a class that has lets say 5 reference-typed fields, that'd be 10 indirect calls (calling `fn` to mark and calling `__iterate` to traverse for each). From a code size perspective there'd be somewhat less compiler-generated code, like the big switch, but that's minor.

**BUT** I must admit though that I'm not so sure about my plans anymore after this conversation and I'll go and think about this more. Suggesting to forget about the option for now until I figured this out :)

**Comment by kripken** [comment]
Interesting, thanks. Curious to see what you end up with.

I'd recommend trying to avoid exporting the table entirely, to maximize optimization opportunities - perhaps there could be another way to find table indexes?
