### ISSUE TITLE
We need a proper build system

### ISSUE THREAD

**Issue by kripken** [WebAssembly/binaryen#2]
CMake?

**Comment by waywardmonkeys** [comment]
I've got a start on this in cmake ... I'll submit a pull request shortly. It isn't complete, but it is a start.

**Comment by svenstaro** [comment]
CMake is fine. @waywardmonkeys your changes don't seem to be public yet. Can you push them? I would like to take a look as I'm also interested in working on this.

**Comment by kripken** [comment]
After @waywardmonkeys first pull and some tweaks, cmake mostly works. The main missing piece is it doesn't invoke emcc to build wasm.js yet.

**Comment by mbebenita** [comment]
`build.sh` is not in sync with CMake and fails in several ways. Even after making sure that I compile the same source files as CMake, `check.py` fails because the `support` library is not built.

Question is, should we fix `build.sh` or just drop it all together?

**Comment by kripken** [comment]
Yeah, it's getting worse. I just pushed a commit to move build.sh to use cmake for everything that it can, which is everything but wasm.js. Hopefully we can figure out the wasm.js bit (tricky part is calling emcc, and not the system compiler), and remove build.sh entirely.

**Comment by kripken** [comment]
This is mostly done, but we still have `build-js.sh` for building the JS parts. Would be nice if that could be done in cmake as well, but it means invoking out to call a different compiler (emcc) so maybe not. If not, we can close this.

**Comment by dschuff** [comment]
If `build-js.sh` stays as simple as it is, then unlikely to be worth the effort of trying to have multiple toolchains in a single build system configuration. This is especially true since we don't really need to have support for random users running it on a variety of OSes. I'd say we can call this issue fixed since we have CMake and of course update it as needed.

**Comment by binji** [comment]
With sexpr-wasm, I have a neat trick where I have a top-level Makefile drive the CMake build underneath. That way you can have different toolchain configurations easily accessible. Currently I support a full matrix of {gcc, gcc-i686, clang, emscripten, gcc w/ AFL fuzz} * {debug, release} * {msan, lsan, asan, ubsan}.
