### ISSUE TITLE
wasm-opt --rereloop crashes

### ISSUE THREAD

**Issue by hpohl** [WebAssembly/binaryen#2007]
Using it on [this file](https://s3.eu-central-1.amazonaws.com/trail-public/tmp/orig.wasm):
```
$ wasm-opt orig.wasm -o opt.wasm --rereloop
wasm-opt: ../src/ir/ExpressionAnalyzer.cpp:428: void wasm::ExpressionAnalyzer::hash(wasm::Expression*)::Hasher::visitScopeName(wasm::Name): Assertion `internalNames.find(curr) != internalNames.end()' failed.
```

**Comment by kripken** [comment]
This is because need to run `--flatten` before that pass, as it requires flat IR. Sadly we don't have a nice error message for this yet - I'll look into that.

**Comment by hpohl** [comment]
Roger, I guess it's the same case with `--optimize-added-constants` which needs `-lmu`. The assertion failure was just a bit more helpful this time.
