### ISSUE TITLE
asm2wasm: disable mutable globals

### ISSUE THREAD

**Issue by mnater** [WebAssembly/binaryen#2011]
Hi

Since asm.js requires globals to be mutable asm2wasm converts all imported globals to mutable globals (https://github.com/WebAssembly/binaryen/blob/master/src/asm2wasm.h#L922).

This is not necessary if the imported globals isn't reassigned a new value. I don't reassign values to imported globals (and if so I'd copy the value to a local variable). Is there a way to disable this assignment upon compiling from asm2wasm or when optimizing code?

**Comment by kripken** [comment]
Thanks, we should add a pass that optimizes stuff like that. If no one else is interested I can write it.

**Comment by kripken** [comment]
https://github.com/WebAssembly/binaryen/pull/2066 implements this. Please test to see if it does what you expect @mnater

**Comment by mnater** [comment]
Hi kripken

Great. https://github.com/WebAssembly/binaryen/pull/2066 does exactly what I was looking for.
Thanks for this awesome work.

**Comment by kripken** [comment]
Great, thanks @mnater, I'll try to land it later today then.
