### ISSUE TITLE
Installed Binaryen-c.h refers to missing compiler-support.h

### ISSUE THREAD

**Issue by turbolent** [WebAssembly/binaryen#2054]
The [CMake file installs the binaryen-c.h header](https://github.com/WebAssembly/binaryen/blob/09945884f7461135286357d14f993f9b5c5a329b/CMakeLists.txt#L178), and that file [imports `compiler-support.h`](https://github.com/WebAssembly/binaryen/blob/c3ed0f176b36a502ef2e1fd915550a808b8d8f0b/src/binaryen-c.h#L50) which is not installed. 

Shouldn't the CMakefile also install `compiler-support.h`? If that's the case I'll open a PR.

**Comment by kripken** [comment]
Hmm, it might be better to remove that dependency, so we are only a single standalone header. It's only for `WASM_DEPRECATED`, so perhaps we can just include that directly there?

**Comment by turbolent** [comment]
I'll see if that's possible 👍

**Comment by irmen** [comment]
Ran into this as well, also the arch linux community and AUR packages are missing this file so after their installation, you can't include the header file without this error.
