### ISSUE TITLE
[Proposal] Move directize pass before inlining-optimizing 

### ISSUE THREAD

**Issue by MaxGraey** [WebAssembly/binaryen#2074]
According to my experiments will be great if [directize pass](https://github.com/WebAssembly/binaryen/blob/master/src/passes/pass.cpp#L394) will be before [inlining-optimizing](https://github.com/WebAssembly/binaryen/blob/master/src/passes/pass.cpp#L386) because directized function could be pretty simple and definitely make sense inline it. For example:
```ts
function sort<T>(arr: T[], cmp: (a: T, b: T) => i32): void {
   ...
   if (cmp(arr[i], arr[j]) < 0) {
     ...
   }
}

sort(arr, (a, b) => a - b);
```
after `directize`, `dae-optimizing` and `inlining-optimizing` passes becomes:
```ts
function sort<T>(arr: T[]): void {
   ...
   if ((arr[i] - arr[j]) < 0) {
      ...
   }
}
```
Or even better: `arr[i] < arr[j]`
But currently this not happening with `-O4`. It require additional `inlining-optimizing` pass.

**Comment by MaxGraey** [comment]
Also found one more logical optimization for `optimize-instructions`:
current input with `-O4`:
```wat
get_local $p0
get_local $p1
i32.sub
i32.const 0
i32.lt_s
```
optimal:
```wat
get_local $p0
get_local $p1
i32.lt_s
```

**Comment by kripken** [comment]
Thanks @MaxGraey. In general, I'm not sure what the right order is - might be other code on which that change makes it worse. Instead, see the `--converge` option, it keeps running all the passes until binary size doens't decrease. When you want the best code size, that's highly recommended.

Probably best to open a new issue with that optimization suggestion, so it's not forgotten.

**Comment by MaxGraey** [comment]
Sure, I add this to this issue #1764
