### ISSUE TITLE
Write the s-expression format into a file? (Extension of BinaryenModuleWrite to write s-expressions)

### ISSUE THREAD

**Issue by bollu** [WebAssembly/binaryen#2103]
In the C API, I found `void BinaryenModulePrint(BinaryenModuleRef module);`, which prints the s-expression format to `stdout`, and `size_t BinaryenModuleWrite(BinaryenModuleRef module, char* output, size_t outputSize);` which prints the module _in binary_ (assembled) into the buffer.

What I want is a function that _prints the s-expression format into a buffer_.

Could such a function be added to the API? I'd be implement it and send a PR, but I want to understand if there's some reason this doesn't already exist. 

Thanks!

**Comment by kripken** [comment]
Sounds reasonable to add that, yeah, PR would be welcome (so far we've just used the text format for debugging purposes, and stdout was enough, so we didn't spend much time on a nicer API for it).

**Comment by bollu** [comment]
@kripken may I please have some help with the PR? I have some questions regarding the API and color handling on PR #2106, and help would be greatly appreciated!
