### ISSUE TITLE
Add CMake option to disable tool building

### ISSUE THREAD

**Issue by AlexAltea** [WebAssembly/binaryen#2140]
I'm building Binaryen with Emscripten since I need to generate WebAssembly modules on the fly. To do so, I call `emcmake cmake -DBUILD_STATIC_LIB=ON .` on Binaryen's root directory.

However, I get this error with *wasm-reduce*:

```bash
Scanning dependencies of target wasm-reduce
[ 83%] Building CXX object CMakeFiles/wasm-reduce.dir/src/tools/wasm-reduce.cpp.o
[ 84%] Linking CXX executable bin/wasm-reduce.js
error: undefined symbol: popen
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
Error: Aborting compilation due to previous errors
shared:ERROR: '/home/alex/tools/emsdk/node/8.9.1_64bit/bin/node /home/alex/tools/emsdk/emscripten/1.38.31/src/compiler.js /tmp/tmpfyNH1G.txt /home/alex/tools/emsdk/emscripten/1.38.31/src/library_pthread_stub.js' failed (1)
CMakeFiles/wasm-reduce.dir/build.make:104: recipe for target 'bin/wasm-reduce.js' failed
make[2]: *** [bin/wasm-reduce.js] Error 1
CMakeFiles/Makefile2:115: recipe for target 'CMakeFiles/wasm-reduce.dir/all' failed
make[1]: *** [CMakeFiles/wasm-reduce.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

For my current use-case, all that matters is having Binaryen available as a library, and not any of the tools, wouldn't it make sense to add something like this to the *CMakeLists.txt* file?

```cmake
OPTION(BUILD_TOOLS "Build additional Binaryen tools" ON)
```

...and then, conditionally enable the compilation of these tools based on that flag?
Just a suggestion, I'd be happy to listen to alternative approaches. :-)

**Comment by kripken** [comment]
Binaryen has the `build-js.sh` script which we use to build binaryen.js (easier to do it directly, without cmake) - is that what you are trying to do?

**Comment by AlexAltea** [comment]
I'm not using `build-js.sh` because I'm not using Binaryen directly from Javascript, but instead I'm using it from another C++ project.

Hence, I need to compile Binaryen separately (`emcmake cmake -DBUILD_STATIC_LIB=ON . && make`) and link `libbinaryen.a` against my project. This fails due to the aforementioned issue and I have to manually remove all tools from the *CMakeLists.txt* file for the build to succeed.

**Comment by kripken** [comment]
I see, interesting.

Can you just use a selective `make` command? Like `make wasm-opt` (or whichever tools you want)? Then it won't build stuff you don't want.

**Comment by AlexAltea** [comment]
Oh, I hadn't thought about that, thanks for the suggestion!
Simply doing `make binaryen` does what I want.
