### ISSUE TITLE
StackIR conversion can lead to unnecessary unreachables

### ISSUE THREAD

**Issue by dcodeIO** [WebAssembly/binaryen#2169]
While functionally irrelevant (doesn't affect execution or optimized code), given the following exemplary input

```wast
(module
 (type $ii (func (param i32) (result i32)))
 (export "0" (func $0))
 (func $0 (; 0 ;) (type $ii) (param $0 i32) (result i32)
  (loop $continue
   (if
    (local.get $0)
    (return
     (i32.const 1)
    )
    (return
     (i32.const 2)
    )
   )
  )
 )
)
```

and converting it to StackIR yields

```wat
(module
 (type $ii (func (param i32) (result i32)))
 (export "0" (func $0))
 (func $0 (; 0 ;) (type $ii) (param $0 i32) (result i32)
  loop $continue
   local.get $0
   if
    i32.const 1
    return
   else
    i32.const 2
    return
   end
   unreachable
   unreachable
  end
  unreachable
 )
)
```

Note the `unreachable`s. Got hit by this while I was trying to reduce unnecessary instructions in unoptimized test output for clarity (AssemblyScript uses unoptimized StackIR for its tests, which perhaps isn't the smartest decision), but ended up being more confused than before because I thought the compiler would be doing something strange :)

**Comment by dcodeIO** [comment]
The reason for my confusion was that the more I tried to do the right thing by inserting the necessary unreachables myself, it became worse:

```wast
(module
 (type $ii (func (param i32) (result i32)))
 (export "0" (func $0))
 (func $0 (; 0 ;) (type $ii) (param $0 i32) (result i32)
  (loop $continue
   (if
    (local.get $0)
    (return
     (i32.const 1)
    )
    (return
     (i32.const 2)
    )
   )
   (unreachable)
  )
  (unreachable)
 )
)
```

```wat
(module
 (type $ii (func (param i32) (result i32)))
 (export "0" (func $0))
 (func $0 (; 0 ;) (type $ii) (param $0 i32) (result i32)
  loop $continue
   local.get $0
   if
    i32.const 1
    return
   else
    i32.const 2
    return
   end
   unreachable
   unreachable
   unreachable
  end
  unreachable
  unreachable
 )
)
```

Fwiw, binaryen.js test case I used is

```js
var mod = new binaryen.Module();
var funcType = mod.addFunctionType("ii", binaryen.i32, [ binaryen.i32 ]);
mod.addFunction("0", funcType, [],
  mod.block(null, [
    mod.loop("continue",
      mod.block(null, [
        mod.if(
          mod.local.get(0, binaryen.i32),
          mod.return(mod.i32.const(1)),
          mod.return(mod.i32.const(2))
        ),
        mod.unreachable()
      ])
    ),
    mod.unreachable()
  ], binaryen.i32)
)
console.log(mod.emitText());
console.log(mod.emitStackIR());
```

**Comment by kripken** [comment]
The `optimize-stack-ir` pass should remove those. What output do you get with that?

**Comment by dcodeIO** [comment]
Oh, yes, that removes all the duplicates. I wasn't using it because it also does other things, possibly suppressing mistakes the compiler made in code generation that then wouldn't show up in the test fixtures, like DCE/removing blocks. Hmm.... looks like it really shouldn't use StackIR for tests.

**Comment by kripken** [comment]
Yeah, if you want to see the Binaryen IR you generated, then changes in the conversion from IR to stack IR can be confusing. But it may also be useful to see that the stack IR looks good too, maybe after optimization.
