### ISSUE TITLE
[emscripten-finalize] longjmp rewriter fails to update GOT

### ISSUE THREAD

**Issue by Keno** [WebAssembly/binaryen#2180]
The `fixInvokeFunctionNames` pass in emscripten-finalize rewrites the function and import for `emscripten_longjmp_jmpbuf` to `emscripten_longjmp`, but doesn't do anything to any potential GOT entries that may be present in the module. This causes a fatal error later in the same utility:
```
Fatal: GOT.func entry with no import/export: $emscripten_longjmp_jmpbuf
```

**Comment by kripken** [comment]
@sbc100 do you have time to look at this? if not I can, but I could use some direction (testcase would be good)

**Comment by sbc100** [comment]
Ah yes, it should re-write them both.  I'll take a look.   Do you know why we haven't seen this is test code?  What are we missing that we need to add that will tickle this?

**Comment by Keno** [comment]
Presumably this should just trigger on any code compiled with `-fPIC` that also uses `longjmp`.

**Comment by sbc100** [comment]
Or `-fPIC` and exceptions?  I'm surprised we don't have any that in out test suite.  I'll be sure to add some if that is needed all thats needed.

**Comment by jeromelaban** [comment]
@sbc100 @kripken Here's a repro (extracted [from this test](https://github.com/emscripten-core/emscripten/blob/5187ea263120ff57424a184c1bc73259e24dc9a9/tests/core/test_longjmp3.c)) with emscripten `1.38.48-upstream`:
```cpp
#include <setjmp.h>
#include <stdio.h>

typedef struct {
  jmp_buf* jmp;
} jmp_state;

void setjmp_func(jmp_state* s, int level) {
  jmp_buf* prev_jmp = s->jmp;
  jmp_buf c_jmp;

  if (level == 2) {
    longjmp(*(s->jmp), 1);
  }

  if (setjmp(c_jmp) == 0) {
    setjmp_func(s, level + 1);
  }
}

int main() { return 0; }
```
Note the code in itself does not make sense, I removed everything I could up to the breaking point.

It's built with:
```
emcc \
   test.cpp \
   -o test.wasm \
   -s SIDE_MODULE=1
```

I cannot build Skia (canvaskit) as a side module as result of this issue, hope this will help!
