### ISSUE TITLE
Wasm.js and Html Dom example

### ISSUE THREAD

**Issue by nickbetteridge** [WebAssembly/binaryen#219]
Hi
I'm very interested in getting involved with this but I'm not too sure if it's too early to ask about whether it's possible to manipulate the html dom with s expressions via wasm.js yet?
Cheers,
Nick

**Comment by kripken** [comment]
wasm.js only runs pure wasm in an interpreter. And wasm itself doesn't have DOM integration. However, a compiler can allow calling into JS which can them manipulate the DOM (e.g. emscripten does so using `EM_ASM` blocks).

**Comment by nickbetteridge** [comment]
Thanks for the pointer to EM_ASM - I'll read through it. So I guess the route to manipulating the dom is building something around import/export?

**Comment by kripken** [comment]
Yes, for now you need to call out of wasm to do DOM stuff, which can be done by calling an import. That's how emscripten does EM_ASM.

**Comment by nickbetteridge** [comment]
OK. Thanks.
