### ISSUE TITLE
asm2wasm instruction separator

### ISSUE THREAD

**Issue by Cellule** [WebAssembly/binaryen#220]
Right now the following fails to parse because the line `i3 = (i3+1) |0` is missing a `;`.

``` js
    function f5() {
     var i3 = 0;
     i3 = (i3+1) |0
     return i3|0;
    }
```

Is this by design or should we make the parser follow the same rules as javascript for instruction separator?

**Comment by kripken** [comment]
If it's easy to support that, I think we should. However, the parser was written to support emscripten output, which is easier and faster to parse than general asm.js, and the parser does depend on that. I'm not sure how easy it would be to generalize things.

**Comment by Cellule** [comment]
I don't know how easy it would be to support that.
I understand the point is to parse emscripten output. 
I was just hoping I could use this tool to convert existing asmjs test case to wasm. 
Most of them have been written by hand so I guess it is unlikely they will parse with a script parser.

**Comment by kripken** [comment]
Might be the simplest thing is to manually add a `;` there, and there might be a few other minor things you need to fix up.

But in general, there is a problem here - asm2wasm assumes emscripten input for other reasons. In particular, wasm does not have globals, but asm.js does, so asm2wasm maps them into memory. But it needs help to know where is a safe place in memory to do so. For that reason, asm2wasm works ok when run in integration with emscripten, but would not work on older emscripten outputs, nor on non-emscripten files. Unless they happen to not have globals.

**Comment by jfbastien** [comment]
Loosening the parser rules would be fine IMO, but not as far as implementing automatic semicolon insertion. Unless @BrendanEich implements it as penance ;-)
