### ISSUE TITLE
"exception index 3 out of bounds" error

### ISSUE THREAD

**Issue by kripken** [WebAssembly/binaryen#2204]
The error happens in v8 (a related error in wabt too) when run on the binary form of events.wast in this repo's test suite (`bin/wasm-as -all test/events.wast -o a.wasm`).

**Comment by aheejin** [comment]
I saw this error this afternoon, but this error does not occur anymore. Maybe #2202 possibly solved this..? Wabt runs fine, and I don't know how to run d8 without a js file.

**Comment by kripken** [comment]
Yes, it looks fixed thanks to #2202!
