### ISSUE TITLE
[Proposal] Optimize jump tables / switch-case

### ISSUE THREAD

**Issue by MaxGraey** [WebAssembly/binaryen#2222]
It will be great if Binaryen use LUT tables for simple numeric remapping in switch /case like in this example:
```ts
export function switch_case(x: i32): i32 {
  switch (x) {
    case 0: return 0;
    case 1: return 1;
    case 2: return 2;

    case 3: return 3;
    case 4: return 3;
    case 5: return 3;

    default: return -1;
  }
}
```
Produce this output (165 bytes):
```wat
(func $switch_case (export "switch_case") (type $t0) (param $p0 i32) (result i32)
    block $B0
      block $B1
        block $B2
          block $B3
            block $B4
              block $B5
                get_local $p0
                if $I6
                  get_local $p0
                  i32.const 1
                  i32.eq
                  br_if $B5
                  block $B7
                    get_local $p0
                    i32.const 2
                    i32.sub
                    br_table $B4 $B3 $B2 $B1 $B7
                  end
                  br $B0
                end
                i32.const 0
                return
              end
              i32.const 1
              return
            end
            i32.const 2
            return
          end
          i32.const 3
          return
        end
        i32.const 3
        return
      end
      i32.const 3
      return
    end
    i32.const -1)
```

But LLVM used lookup table for this case (154 bytes):
```c
int switch_case(int x) {
  switch (x) {
    case 0: return 0;
    case 1: return 1;
    case 2: return 2;
    case 3: return 3;
    case 4: return 3;
    case 5: return 3;
    default: return -1;
  }
}
```
Output:
```wat
(func $switch_case (export "switch_case") (type $t1) (param $p0 i32) (result i32)
    block $B0
      get_local $p0
      i32.const 5
      i32.gt_u
      br_if $B0
      get_local $p0
      i32.const 2
      i32.shl
      i32.const 1024
      i32.add
      i32.load
      return
    end
    i32.const -1)
 (data (i32.const 1024) "\00\00\00\00\01\00\00\00\02\00\00\00\03\00\00\00\03\00\00\00\03\00\00\00"))
```
which looks pretty optimal and more compact. WDYT?

**Comment by kripken** [comment]
That may be more optimal, yeah, but Binaryen can't do it without understanding how memory space is reserved. It needs to ask for free space, and the actual language runtime being compiled would need to provide it. There isn't a mechanism for that atm. So in the short term doing this before Binaryen (where the compiler manages memory allocations) is necessary.

In theory in the future with multiple memories we could create a new memory just for such a table, and then it would not have any possible interferences with other allocations.

Another option is to design an interface to do "static allocations" in binaryen, if the runtime being optimized supports it. We could define and ABI for that. That might also help us optimize stack operations better. That's non-trivial though.

**Comment by MaxGraey** [comment]
Ahh, didn't see your response. Thanks for exploration! So this kind of optimization better produce on higher level representation.
