### ISSUE TITLE
On funcref replacing anyref in text format

### ISSUE THREAD

**Issue by dcodeIO** [WebAssembly/binaryen#2248]
It recently [came to my attention](https://github.com/AssemblyScript/assemblyscript/issues/723#issuecomment-513717567) that Binaryen now emits `funcref` instead of `anyref` (`anyfunc`?) as the table type, which does not seem to be understood universally yet. My first guess is that Binaryen is simply ahead in specification terms, solely affecting text format, but opening this issue in case the breakage isn't intended. Is it?

(might well be that it has been this way for a long time already, and it's only an issue for the specific interpreter in question)

**Comment by binji** [comment]
`anyfunc` -> `funcref` is one of the many text changes that occurred during the path from wasm MVP -> v1, [described here](https://github.com/WebAssembly/spec/issues/884#issuecomment-426433329).

**Comment by dcodeIO** [comment]
Thanks for clarifying, binji. This is obviously a non-issue.
