### ISSUE TITLE
Segmentation fault in wasm-opt

### ISSUE THREAD

**Issue by TrevorSundberg** [WebAssembly/binaryen#2343]
I produced [this wasm file](https://drive.google.com/open?id=1mKQPPwwNzFuPbgoPwb7-64QnKtRegAes) from compiling a large game engine project with Emscripten. When running `wasm-opt` with `-O4` or `-Oz` it will result in a `Segmentation fault (core dumped)`. There is no output otherwise. I checked memory with htop and my machine was only using 9 of 32 gigs (and basically none of the swap), so it's not an out of memory issue.

I am running Ubuntu 18.04 and downloaded the binaryen-version_89-x86_64-linux/binaryen-version_89.

Note that using default optimizations does work.

**Comment by kripken** [comment]
Running on latest master or on `version_89`, I don't see a crash on either `-O4` or `-Oz`. (`-O4` does take 14 gigs though...)

If you still see a crash, then getting a stack trace using gdb or valgrind might help.

**Comment by TrevorSundberg** [comment]
Thanks for the reply. I ran gdb but didn't have symbols so the stack was useless. I'll build from source so I can get symbols and try again. Closing this bug for now until I have some more details for you.

**Comment by canadaduane** [comment]
I'm seeing the same issue with `version_90` on the following file (unzipped):

```
wasm-opt -Oz -o public/ayanara.wasm target/wasm32-unknown-unknown/release/ayanara.wasm
Segmentation fault: 11
```

[ayanara.wasm.gz](https://github.com/WebAssembly/binaryen/files/4077780/ayanara.wasm.gz)

**Comment by canadaduane** [comment]
Oddly, even if I do not specify optimization, it still results in a segfault:

```
$ wasm-opt -o test.wasm public/ayanara.wasm
warning: no passes specified, not doing any work
Segmentation fault: 11
```

**Comment by kripken** [comment]
Thanks for the testcase @canadaduane ! Fix in https://github.com/WebAssembly/binaryen/pull/2607 . I'm not sure why that DWARF is invalid, but at least now we won't crash on it (if you can get a small testcase that shows the same issue, that might be worth investigating in more detail).
