### ISSUE TITLE
Should we switch from travis + appveyor to circleci?

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/binaryen#2356]

**Comment by kripken** [comment]
Is there a specific benefit we are hoping for - current CI here seems reasonable?

**Comment by sbc100** [comment]
Having the config split between two different CI providers seems needlessly complex.

Also circleci has been a lot more responsive when that travis when using it with emsdk and emscripten-core.

Also, there are concens about the future/direction of travisci: https://medium.com/@dirk.avery/r-i-p-travis-ci-347753c73775

I don't see this is as urgent of course.

**Comment by dcodeIO** [comment]
There is also GitHub Actions (Beta) now that supports Linux, Mac OS and Windows. We switched to that over at AssemblyScript recently, in case you are interested in an [example](https://github.com/AssemblyScript/assemblyscript/blob/master/.github/workflows/ci.yml) how that [looks](https://github.com/AssemblyScript/assemblyscript/actions). The biggest difference to Travis etc. is that one doesn't have as much control over the VM and it instead relies on pluggable actions that work the same on all platforms. Thought I mention in case you'd like to consolidate even more :)

**Comment by sbc100** [comment]
Yes, it does seem like github actions is probably the future.   I'm not a fan of github/ms becoming the center of world for all of the things, but I'm also not going to die on that hill.
