### ISSUE TITLE
JS build issues

### ISSUE THREAD

**Issue by dcodeIO** [WebAssembly/binaryen#2359]
The binaryen.js bot is [currently failing](https://travis-ci.org/AssemblyScript/binaryen.js/jobs/590073082#L5597) with

```
In file included from binaryen/src/shell-interface.h:28:
binaryen/src/wasm-interpreter.h:1783:28: error: 'auto' not allowed in lambda parameter
      auto fillLanes = [&](auto lanes, size_t laneBytes) {
```

Wondering if this has something to do with the bot still [using fastcomp](https://travis-ci.org/AssemblyScript/binaryen.js/jobs/590073082#L488), or if it's something else?

**Comment by MaxGraey** [comment]
It also use [Clang 5.0.0](https://travis-ci.org/AssemblyScript/binaryen.js/jobs/590073082#L462)

**Comment by dcodeIO** [comment]
Yeah, it uses Clang 5 to compile Emscripten (which works), but the error is from Emscripten compiling Binaryen.

**Comment by kripken** [comment]
I suspect this is related to the recent upgrade in Binaryen to use c++14 (and temporary c++17, which we reverted), cc @tlively

**Comment by sbc100** [comment]
Looks like you are building in ubuntu/trusty image which is really old now.  There are two more recent ubuntu LTS images: xenial and bionic.  Is there some way you can switch to one of those?

**Comment by dcodeIO** [comment]
Yeah, plan is to update the bot to use the Emscripten docker image eventually, though I *think* that the issue here is not necessarily related to the OS. The build script compiles and then uses Emscripten incoming, which then emits this error when trying to compile Binaryen.

**Comment by tlively** [comment]
`auto` in lambda parameters is the feature from C++14 that prompted us to upgrade from C++11. It looks like the bot is [still using C++11](https://travis-ci.org/AssemblyScript/binaryen.js/jobs/590073082#L5586). Perhaps you need to update here: https://github.com/AssemblyScript/binaryen.js/blob/master/scripts/build.js#L46.

**Comment by dcodeIO** [comment]
Thanks, that's probably it. Decided to switch to the Emscripten docker image meanwhile, which builds fine again using `build-js.sh`. Speaking of which, I guess [this line](https://github.com/WebAssembly/binaryen/blob/master/build-js.sh#L40) in build-js.sh needs to be downgraded to C++14 as well?

**Comment by tlively** [comment]
Yep! Handled in https://github.com/WebAssembly/binaryen/pull/2360.

**Comment by dcodeIO** [comment]
Perfect! :)
