### ISSUE TITLE
Arrays out of bounds

### ISSUE THREAD

**Issue by fpcfjf** [WebAssembly/binaryen#2373]
Hi,
Mixed_arean.h，Line：352：
Similar to:
 T& operator[](std::ptrdiff_t off) const { return (*parent)[index + off]; }

Arrays that are out of bounds are not checked and may cause a crash.Other operator overloading also has this possibility

**Comment by tlively** [comment]
Are you observing an actual crash? In general we want to be defensive, but we do fuzz a lot and we don't want to introduce overhead for potential issues that haven't been problematic in practice.

**Comment by fpcfjf** [comment]
I am testing the actual situation, if there is any problem, I will promptly feedback it.

**Comment by tlively** [comment]
I'll close this issue for now. Please open new issues for any bugs you find!
