### ISSUE TITLE
v8x16.shuffle op code wrong?

### ISSUE THREAD

**Issue by postspectacular** [WebAssembly/binaryen#2401]
Working on a SIMD lib (using AssemblyScript), I have run into an illegal opcode issue in `wasm2wat` (with `--enable-all`), which complains about `v8x16.shuffle` being encoded as `0xfd 0x03 ...`.

I've verified that this is seemingly the SIMD opcode used also in [wasm-binary.h](https://github.com/WebAssembly/binaryen/blob/master/src/wasm-binary.h#L718), however the [SIMD design spec](https://github.com/WebAssembly/simd/blob/master/proposals/simd/BinarySIMD.md) document states `0xfd 0xc1` for this operation. So who is right here? :)

Even stranger is that the current shuffle op code actually works in v8 (haven't tested others yet) and produces correct results...

**Comment by tlively** [comment]
Although wabt is up to date with the current spec proposal, v8 and the tools all use an older opcode for shuffles. If you need to inspect binaries that include shuffles (or the newest SIMD opcodes) I recommend using binaryen’s wasm-dis instead for now.

**Comment by postspectacular** [comment]
Thanks, @tlively - that makes sense. FWIW meanwhile I've also tried `wasm-dis` and `wasm-objdump`, but the latter bails (silently) on that instruction too (no further output beyond that instruction). This was a bit surprising, since I believed all these WABT tools share the same constants, but obviously not the case....
