### ISSUE TITLE
warning C4800: 'uint32_t': forcing value to bool 'true' or 'false' (performance warning)

### ISSUE THREAD

**Issue by jakirkham** [WebAssembly/binaryen#2430]
Have been seeing the following warning for the past few releases (including `1.39.1`) when building on Windows. Here is the [attached build log]( https://github.com/WebAssembly/binaryen/files/3834232/windows_binaryen_azure_build_log.txt ) and a snippet of the warning seen below. This can also be seen in [this Azure build]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=92148&view=logs ).

```C++
d:\bld\binaryen_1573453236089\work\src\wasm-features.h(71): warning C4800: 'uint32_t': forcing value to bool 'true' or 'false' (performance warning)
d:\bld\binaryen_1573453236089\work\src\wasm-features.h(72): warning C4800: 'uint32_t': forcing value to bool 'true' or 'false' (performance warning)
d:\bld\binaryen_1573453236089\work\src\wasm-features.h(73): warning C4800: 'uint32_t': forcing value to bool 'true' or 'false' (performance warning)
d:\bld\binaryen_1573453236089\work\src\wasm-features.h(74): warning C4800: 'uint32_t': forcing value to bool 'true' or 'false' (performance warning)
d:\bld\binaryen_1573453236089\work\src\wasm-features.h(75): warning C4800: 'uint32_t': forcing value to bool 'true' or 'false' (performance warning)
d:\bld\binaryen_1573453236089\work\src\wasm-features.h(76): warning C4800: 'uint32_t': forcing value to bool 'true' or 'false' (performance warning)
d:\bld\binaryen_1573453236089\work\src\wasm-features.h(77): warning C4800: 'uint32_t': forcing value to bool 'true' or 'false' (performance warning)
d:\bld\binaryen_1573453236089\work\src\wasm-features.h(78): warning C4800: 'uint32_t': forcing value to bool 'true' or 'false' (performance warning)
d:\bld\binaryen_1573453236089\work\src\wasm-features.h(79): warning C4800: 'uint32_t': forcing value to bool 'true' or 'false' (performance warning)
```

**Comment by kripken** [comment]
Thanks @jakirkham! I opened #2431 now to add casts to bool. Does it fix that warning?

**Comment by jakirkham** [comment]
Thanks @kripken! Tried out your patch in PR ( https://github.com/conda-forge/binaryen-feedstock/pull/34 ). Unfortunately it seems [the warning still occurs]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=93538&view=logs&jobId=2cc45e14-23e3-52d7-b33a-8c2744410b97 ). Here's [the new log]( https://github.com/WebAssembly/binaryen/files/3843818/windows_binaryen_azure_build_log_2.txt ).

**Comment by tlively** [comment]
Gross https://stackoverflow.com/questions/20919650/warning-c4800-int-forcing-value-to-bool-true-or-false-performance-warn/20919738

**Comment by aheejin** [comment]
Maybe we should use `!!`...

**Comment by jakirkham** [comment]
Yeah some code generators use ` != 0` to solve this issue on Windows as well.

**Comment by kripken** [comment]
@jakirkham Ok, hopefully #2449 fixed it properly now..?
