### ISSUE TITLE
Rename wasm-opt executable

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/binaryen#2443]
I believe this name came from llvm where I also find it confusing.    Open to suggestions for alternatives:

1. `binaryen`
2. `binaryen-run`
3. `wasm-binaryen-run`
4. `wasm-pass-runner`

I'm leaning towards KISS and just going with `binaryen`.   We could keep wasm-opt around for a tool that just run optimization passes and takes flags like `-O1` and -O2`.

**Comment by kripken** [comment]
Some more options:

5) `wasm-byn-run`
6) `wasm-byn`

**Comment by tlively** [comment]
Strong +1 for renaming from a technical perspective. Weak +1 taking ecosystem turn into account. I like `binaryen` as a name.

**Comment by sbc100** [comment]
I don't see why we need the `wasm-` prefix since this tool would be pretty specific and mostly for internal use (unlike `wasm-opt` which is more generally useful).

**Comment by kripken** [comment]
It feels more consistent to have a prefix for all the tools, I think? But I don't have strong feelings about any of this.

**Comment by sbc100** [comment]
Hmm, I think I disagree.   I actually see this new tool as more of an binaryen-developer-only thing.   Maybe it wouldn't be installed via `make install` .. kind of like the `opt` tool in llvm.  That is not generally part of llvm, it doesn't get installed as /usr/bin/opt, and it doesn't have the `llvm-` prefix like the other tools.     

I still like `binaryen`.. its describes exactly what it is.

**Comment by kripken** [comment]
Maybe I don't understand the proposal here. Specifically the connection between wasm-opt (which you say might be kept around) and a new tool. Are you saying the new tool would be binaryen-developer-only? What would users use, the old wasm-opt? (And why can't both use the same tool?)

Meanwhile I see that binaryen on npm has `binaryen-opt, -dis, -as` tools. cc @dcodeIO 

Maybe one way to go is to say that `npm install binaryen` gets you tools for users, like that `binaryen-opt`, while binaryen developers themselves would typically use a binary build of wasm-opt etc.

However, if want to recommend that users use the npm version, I think we need to make that build fast - build to wasm, and use multithreading.

**Comment by dcodeIO** [comment]
I also like `binaryen` as a name. Perhaps we can make a single executable for everything, like `binaryen --as` would do what `wasm-as` does and so on?

**Comment by sbc100** [comment]
Yeah I think we could continue to ship wasm-opt.. whose sole job is optimizing wasm binaries (it would take arg like -O1 and -O2 and it would always take and input and output binary).  Where as `binaryen` or `binaryen-pass-runner` would be a more like swiss army knife that wasm-opt is today capable of running all kinds of passes?    Maybe its unnecessary change?

**Comment by dcodeIO** [comment]
Other nice side effects of a single binary would be that all we need is one static 4mb binary instead of multiple of about the same size, keeping the package small, and since it matches the package name one can simply `npx binaryen [options...]` without even `npm install`ing anything (I believe).

**Comment by sbc100** [comment]
I'm not proposing that we remove all the other executable.   If space is an issue when we we can ship the binayen shared library rather than static linking.. like how clang and all the llvm tools can link against libLLVM.so.

**Comment by tlively** [comment]
There seems to be disagreement over whether the target audience for a generic pass runner should be normal application develops targeting wasm or only toolchain authors. I think it would be really cool if normal developers started running custom passes over their modules as a debugging aid, but perhaps that's not realistic. Is code instrumentation too low-level to be useful for debugging applications?

If we do ship a generic pass runner for consumption by end users, I agree with @sbc100 that it would be good to ship a wrapper utility called `wasm-opt` that takes only very simple arguments and runs preconfigured sequences of passes explicitly to optimize modules.

**Comment by kripken** [comment]
Hmm, but doesn't the current wasm-opt already do just that, except it also supports more arguments? But if people just pass in the simple arguments, that works.

I guess I don't see the benefit of doing the work to split out another tool?

I do agree there have been some confusions on wasm-opt, like expecting it to optimize by default even without flags, which we've added a warning for. Do poeple think that's not enough?

**Comment by sbc100** [comment]
Yes, perhaps its not a big enough deal but I find it strange to see wasm-opt used in emcripten for running passes that don't relate to optimization at all.

I think I'm going to close this for now as probably not worth it..
