### ISSUE TITLE
Optimizing functions with `anyref` locals runs into assertion

### ISSUE THREAD

**Issue by dcodeIO** [WebAssembly/binaryen#2444]
I'm currently trying to track down a Binaryen assertion happening with the following module:

```wat
(module
  (import "ref" "null" (global $ref_null anyref))
  (import "ref" "is_null" (func $ref_is_null (param anyref) (result i32)))
  (func $test
    (local $0 anyref)
    (local.set $0
      (global.get $ref_null)
    )
    (drop
      (call $ref_is_null
        (local.get $0)
      )
    )
    ;; remove this to make it work:
    (drop
      (call $ref_is_null
        (local.get $0)
      )
    )
  )
  (export $test $test)
)
```

which yields

```
abort(Assertion failed: false, at: ./src/literal.h,87,makeFromInt32)
```

when I attempt to optimize it with optimizeLevel > 1. The problem goes away if I remove the second

```wat
    (drop
      (call $ref_is_null
        (local.get $0)
      )
    )
```

from the function or make `$0` a function parameter, so I guess that there is an optimization trying to move/copy local values around that causes this as soon as there are two `local.get`s of the same anyref local or something along those lines. This isn't overly important, just ran into this while trying to polyfill `ref.null` etc. so we can have shiny things. Perhaps there's an easy fix?

**Comment by aheejin** [comment]
I'm working on reference types support now, and this will be fixed by that patch soon. Thank you for reporting.
