### ISSUE TITLE
Binaryen as a subproject: linking to `libbinaryen.a` gives undefined reference

### ISSUE THREAD

**Issue by ImmanuelHaffner** [WebAssembly/binaryen#2450]
Hi all,

I want to include Binaryen as a subproject so I can use it as a backend to generate WebAssembly code. My project uses CMake and I decided to add this repo as a CMake ExternalProject like below:

```cmake
ExternalProject_Add(
    Binaryen
    PREFIX third-party
    SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/third-party/binaryen"
    CMAKE_ARGS -DBUILD_STATIC_LIB=ON -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    INSTALL_COMMAND ":"
    )
```

I set `BUILD_STATIC_LIB` to `ON` such that the CMake configuration of Binaryen builds the statically linked library `libbinaryen.a`.  This works and I get said library file. However, when I try linking it to my backend library, I get "undefined reference" linker errors. To link `libbinaryen.a` to my backend, I use
```cmake
target_link_libraries(backend binaryen)
```
Am I missing something here?

I have tried several ways to make `libbinaryen.a` available in my project:

1)
```cmake
link_directories("${PROJECT_BINARY_DIR}/third-party/src/Binaryen-build/lib/")
```

2)
```cmake
add_library(binaryen STATIC IMPORTED)
set_target_properties(binaryen PROPERTIES IMPORTED_LOCATION "${PROJECT_BINARY_DIR}/third-party/src/Binaryen-build/lib/libbinaryen.a")
```

3)
```cmake
add_library(binaryen INTERFACE)
target_link_libraries(
    binaryen
    INTERFACE
    "${PROJECT_BINARY_DIR}/third-party/src/Binaryen-build/lib/libbinaryen.a"
    "${PROJECT_BINARY_DIR}/third-party/src/Binaryen-build/lib/libpasses.a"
    "${PROJECT_BINARY_DIR}/third-party/src/Binaryen-build/lib/libwasm.a"
    "${PROJECT_BINARY_DIR}/third-party/src/Binaryen-build/lib/libasmjs.a"
    "${PROJECT_BINARY_DIR}/third-party/src/Binaryen-build/lib/libemscripten-optimizer.a"
    "${PROJECT_BINARY_DIR}/third-party/src/Binaryen-build/lib/libir.a"
    "${PROJECT_BINARY_DIR}/third-party/src/Binaryen-build/lib/libcfg.a"
    "${PROJECT_BINARY_DIR}/third-party/src/Binaryen-build/lib/libsupport.a"
    )
```

Both 1) and 2) produce "undefined reference" linker errors, which means the `libbinaryen.a` is found bot does not contain the required symbols. Only with 3) I am able to successfully link binaryen to my backend library. But this is hack-ish, as it strongly relies on Binaryen's internal build structure.

How to properly build and link with `libbinaryen.a`?
FYI: I want to use the API of https://github.com/WebAssembly/binaryen/blob/master/src/binaryen-c.h

Thanks & regards,
Immanuel

**Comment by kripken** [comment]
What are the specific undefined reference errors? Or is it basically all of them, and libbinaryen itself is just not found?

I'm not that familiar with cmake, but here is how the test suite links with libbinaryen: https://github.com/WebAssembly/binaryen/blob/00bbde099c0d968ce4ab95eba56d767d534e4094/check.py#L525

**Comment by ImmanuelHaffner** [comment]
Basically, all references are undefined.

Here is an excerpt of my CMake build configured with option 2 from above. (Option 1 is the same.)
```plain
FAILED: bin/wasm 
: && /usr/bin/clang++  -std=c++17  -W -Wall -pedantic -DLEVEL1_DCACHE_LINESIZE=64 -DPAGESIZE=4096 -march=native -ggdb -Wno-variadic-macros -Wno-gnu-zero-variadic-macro-arguments -Wno-gnu-label-as-value -g -fsanitize=address  -rdynamic src/CMakeFiles/wasm.dir/wasm.cpp.o  -o bin/wasm  lib/libbackend.a third-party/src/Binaryen-build/lib/libbinaryen.a lib/libIR.a lib/libio.a lib/libstorage.a lib/libparse.a lib/liblex.a lib/libcatalog.a lib/libutil.a && :
/usr/bin/ld: third-party/src/Binaryen-build/lib/libbinaryen.a(binaryen-c.cpp.o): in function `wasm::flattenAppend(cashew::Ref, cashew::Ref)':
/home/immanuel/Documents/Work/PhD/db/third-party/binaryen/src/wasm2js.h:65: undefined reference to `cashew::Ref::operator[](unsigned int)'
... (hundreds of undefined references more)
```
where `wasm` is the executable to build, to which I want to link `libbinaryen.a`.
The Binaryen source tree is located at `./third-party/binaryen/`, build as CMake external project as explained above. This produces the statically linked library `libbinaryen.a`:
```bash
$ find . -iname 'libbinaryen.a'
./build_debug/third-party/src/Binaryen-build/lib/libbinaryen.a
```
However, as you can see, I get undefined reference errors.

If I manually link all the libraries that make up `libbinaryen.a` to my `wasm` executable, i.e. the libraries listet here: https://github.com/WebAssembly/binaryen/blob/00bbde099c0d968ce4ab95eba56d767d534e4094/CMakeLists.txt#L199
it just works.

**Comment by ImmanuelHaffner** [comment]
I think the `BUILD_STATIC_LIBS` is messed up. Instead of producing a single statically linked `.a` file, it just tells CMake that target `binaryen` requires targets `passes`, `wasm`, etc. to be linked in as well. This might work well within the project, but it does not provide a single file to link with for a third-party.

I figured that my 3rd approach is still not correct, as it does not capture build dependences between the external project and the root project. I had to tell CMake that the external project produces the files that are used to link the interface library `binaryen`. Here is my code:

```cmake
ExternalProject_Add(
    Binaryen
    PREFIX third-party
    SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/third-party/binaryen"
    CMAKE_ARGS -DBUILD_STATIC_LIB=ON -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    BUILD_BYPRODUCTS
        "${PROJECT_BINARY_DIR}/third-party/src/Binaryen-build/lib/libbinaryen.a"
        "${PROJECT_BINARY_DIR}/third-party/src/Binaryen-build/lib/libpasses.a"
        "${PROJECT_BINARY_DIR}/third-party/src/Binaryen-build/lib/libwasm.a"
        "${PROJECT_BINARY_DIR}/third-party/src/Binaryen-build/lib/libasmjs.a"
        "${PROJECT_BINARY_DIR}/third-party/src/Binaryen-build/lib/libemscripten-optimizer.a"
        "${PROJECT_BINARY_DIR}/third-party/src/Binaryen-build/lib/libir.a"
        "${PROJECT_BINARY_DIR}/third-party/src/Binaryen-build/lib/libcfg.a"
        "${PROJECT_BINARY_DIR}/third-party/src/Binaryen-build/lib/libsupport.a"
    INSTALL_COMMAND ":"
    )
include_directories(third-party/binaryen/src)
add_library(binaryen INTERFACE)
target_link_libraries(
    binaryen
    INTERFACE
    "${PROJECT_BINARY_DIR}/third-party/src/Binaryen-build/lib/libbinaryen.a"
    "${PROJECT_BINARY_DIR}/third-party/src/Binaryen-build/lib/libpasses.a"
    "${PROJECT_BINARY_DIR}/third-party/src/Binaryen-build/lib/libwasm.a"
    "${PROJECT_BINARY_DIR}/third-party/src/Binaryen-build/lib/libasmjs.a"
    "${PROJECT_BINARY_DIR}/third-party/src/Binaryen-build/lib/libemscripten-optimizer.a"
    "${PROJECT_BINARY_DIR}/third-party/src/Binaryen-build/lib/libir.a"
    "${PROJECT_BINARY_DIR}/third-party/src/Binaryen-build/lib/libcfg.a"
    "${PROJECT_BINARY_DIR}/third-party/src/Binaryen-build/lib/libsupport.a"
    )
```

The redundance in this code makes me cringe, but I can't find a better way to make it work

**Comment by TerrorJack** [comment]
We encountered a similar problem last year when building Haskell bindings to `binaryen`; we ended up with a workaround: set `-DBUILD_STATIC_LIB=ON` when building `binaryen`, and collect all object files in all resulting `.a` archives, repack them into a new archive and run `ranlib` to generate the symbol index. The combined `.a` links fine as long as `libstdc++` is also linked against.

[Here](https://github.com/tweag/asterius/blob/master/binaryen/Setup.hs#L47) points to a Haskell build script of our static `binaryen` lib, hopefully it helps. It's a pity I do not know enough CMake to fix the `BUILD_STATIC_LIB` stuff upstream.

**Comment by ImmanuelHaffner** [comment]
@TerrorJack thanks for the reply. I just came across the same approach on stackoverflow as you describe here. It's a workaround, as you said.

I also read about object libraries in Cmake which you can use to build the desired shared or statically linked libraries. I will try to patch the Binaryen cmake files in that regard and file a PR if successful.

**Comment by kripken** [comment]
Sounds good, thanks @ImmanuelHaffner ! (And sorry I wasn't more help here, I don't know much about CMake...)

**Comment by ImmanuelHaffner** [comment]
In case someone is interested in how to include Binaryen as CMake `ExternalProject_add`, here is my code:

```cmake
ExternalProject_Add(
    Binaryen
    PREFIX third-party
    SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/third-party/binaryen"
    CMAKE_ARGS -DBUILD_STATIC_LIB=ON -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    BUILD_BYPRODUCTS "${PROJECT_BINARY_DIR}/third-party/src/Binaryen-build/lib/libbinaryen.a"
    BUILD_COMMAND ${CMAKE_BUILD_TOOL} binaryen
    INSTALL_COMMAND ":"
    )
include_directories(SYSTEM third-party/binaryen/src)
add_library(binaryen STATIC IMPORTED)
set_target_properties(binaryen PROPERTIES IMPORTED_LOCATION "${PROJECT_BINARY_DIR}/third-party/src/Binaryen-build/lib/libbinaryen.a")
```

**Comment by kripken** [comment]
@ImmanuelHaffner Nice! That might be useful to mention in the README, maybe you want to open a PR?

**Comment by ImmanuelHaffner** [comment]
@kripken Yeah, can do that. Anyways, I just stumbled upon a problem with thread libs. Currently, `libbinaryen` is built without thread libs. This means, if you link with `libbinaryen` and it requires threading support, you get linker errors. These can be fixed in two ways: *we* can link `${CMAKE_THREAD_LIBS_INIT}` to `libbinaryen`, or we can leave that task to the user to link `${CMAKE_THREAD_LIBS_INIT}` with his executable. Which one is the way to go?

**Comment by kripken** [comment]
@ImmanuelHaffner good question! Offhand, it seems like us linking that in is best.
