### ISSUE TITLE
parallel analysis passes should not rely on global state

### ISSUE THREAD

**Issue by tlively** [WebAssembly/binaryen#2467]
As encountered in #2466, parallel passes currently must use global state to record analysis results because there is no way to retrieve information from the pass instances on the various threads of the thread pool. Unfortunately, the use of global state for these passes means that they cannot be run on more than one module at a time, and makes the libbinaryen not thread-safe. This has been encountered by users trying to run tests in parallel: #1376.

In order to fix this, we need to add a mechanism for collecting results from parallel passes then audit the codebase and replace uses of global state. While we're at it, we should also add a mechanism to pass arguments to parallel passes.

Long term we should consider preventing these issues by rewriting in Rust ;)

**Comment by kripken** [comment]
I commented in that PR, I don't think we need global state for those things - we have passes that use the pattern of "parallel pass operations write to pass-local infos, then after we join we merge the infos". I'll add a helper for that to make it easier.

**Comment by tlively** [comment]
Oh good, I didn’t think it was possible to fetch and merge results like that. What is a pass that already does this?

**Comment by kripken** [comment]
The Asyncify and Inlining (see FunctionInfoScanner etc.) passes do related things, I believe.

Here's a quick (untested) wip patch to explain what I mean (meant to be applied after your PR lands).

**Comment by tlively** [comment]
Ah, I like this patch! The part I was missing was that `create` is a non-static member function, so it can farm out shared references to collections to the instances on other threads :+1: I'll close this issue and refactor my patch a bit since it's failing the tsan build anyway.
