### ISSUE TITLE
read_file is slow

### ISSUE THREAD

**Issue by mbebenita** [WebAssembly/binaryen#250]
On AngryBots, `read_file` is responsible for 17% (1 second) of the total execution time. If I read directly into a char \* buffer, then it drops to 10%, ... still quite a bit for a 200MB file.

**Comment by ramiro1234** [comment]
Is this still an issue and if so is it possible to get a little more background info?

**Comment by froydnj** [comment]
Repeating the question on whether this is still an issue.

**Comment by kripken** [comment]
Hmm, 200MB suggests this was measured on loading the text format version, not the binary. Load time doesn't matter that much for the text format.

It might be useful to profile the load speed of the binary format. If it's too slow, and there's nothing obvious to fix, we could parallelize the function parsing section as wasm is designed for that.

Overall, though, I haven't had the impression that our binary load times are bad, at least recently, so there might be nothing to fix here. Let's close this, if there are concrete issues measured, we can open new issues.
