### ISSUE TITLE
Fuzz error after #2466

### ISSUE THREAD

**Issue by aheejin** [WebAssembly/binaryen#2512]
Currently this command fails:
```
wasm-opt input.dat -ttf -all --disable-threads  --disable-exception-handling --disable-sign-ext --disable-tail-call
```
This was found by the fuzzer, and it happens after #2466. I haven't investigated the cause myself yet. 

I'll attach compressed `input.dat` (`dat` extension is not supported as attachment, so)
[input.dat.zip](https://github.com/WebAssembly/binaryen/files/3932748/input.dat.zip)

cc @tlively

**Comment by tlively** [comment]
Thanks, I can reproduce the issue. Looking into it now.
