### ISSUE TITLE
Introspection of Module contents in binaryen.js

### ISSUE THREAD

**Issue by brion** [WebAssembly/binaryen#2537]
I can load an existing .wasm file into binaryen.js and modify / re-emit it, but I can't find any way to get general info about the loaded module:
* list of imports
* list of exports
* list of types
* list of functions
* list of opcodes in a function
etc

There are some functions for getting info on some of the above if you have them, but I can't figure out how to obtain suitable references.

This would be useful to do introspection or custom optimizations/transformations when writing in JS instead of C++. (I'm sure they'll perform better in C++ but I can often prototype things a lot faster in JS!)

**Comment by brion** [comment]
Once I have the top-level info it seems to be possible to drill down to the opcodes in a function just fine using getFunctionInfo and getExpressionInfo.

**Comment by brion** [comment]
Alon pointed me to the test suite and I found `getNumFunctions` and `getFunctionByIndex` which and such which should get me what I need. I'll reopen more specific issues if I find anything else missing. :)

Looks like these were added a few months ago and aren't available in the default `npm install binaryen` but do show up if I install nightly build with `binaryen@nightly`.

**Comment by GulgDev** [comment]
Is there a way to get the list of module imports?
