### ISSUE TITLE
Ninja does not work for bianryen.js build

### ISSUE THREAD

**Issue by aheejin** [WebAssembly/binaryen#2546]
After #2503, `make` still seems to work but `ninja` fails with the following message:
```
$ ninja binaryenjs
ninja: error: build.ninja:478: multiple rules generate bin/binaryen.js [-w dupbuild=err]
```
Both `make` and `ninja` worked OK before #2503. My configuration command was
```
emconfigure cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug .
```

cc @dcodeIO

**Comment by dcodeIO** [comment]
Hmm, the relevant change is [here](https://github.com/WebAssembly/binaryen/pull/2503/files#diff-af3b638bc2a3e6c650974192a53c7291R415-R416), where I attempted to emit just `bin/binaryen.js` for both the `binaryen_js` and `binaryen_wasm` targets.

Is it possible that `ninja binaryenjs` (correct target name is `binaryen_js`) tries to build both targets at once?
