### ISSUE TITLE
wasm2js segfaults

### ISSUE THREAD

**Issue by db48x** [WebAssembly/binaryen#2559]
I'm using emscripten to build MAME (tag mame0217) for archive.org, and this step fails when it runs wasm2js (version "wasm2js 1.39.1-91-g05d785e6e"). The command that fails is `~/src/emsdk/upstream/bin/wasm2js --emscripten -O ~/src/mame/mameapple2p.wasm -g --mvp-features`. The input wasm file is at http://db48x.net/rr-recordings/mameapple2p.wasm.

Here is an RR recording of the crash: http://db48x.net/rr-recordings/wasm2js-0.tar.bz

**Comment by kripken** [comment]
Thanks @db48x ! Turns out this is an integer overflow bug, a big lua-related function has over 70,000 locals here. Fix in #2560
