### ISSUE TITLE
Don't require Git to build binaryen 

### ISSUE THREAD

**Issue by apoleon** [WebAssembly/binaryen#2563]
Since version 90 binaryen requires Git to be built from source. Linux/BSD distributions will usually just download the release tarball and won't build binaryen from Git directly. Please consider to remove or relax the requirement to build-depend on Git. For instance you could just change CMakelists.txt to

 set(BINARYEN_VERSION_INFO "90")

before you cut a release and create the release tarball.

**Comment by kripken** [comment]
Thanks @apoleon , looks like this changed in @sbc's #2304 . Perhaps that could check if git isn't present, and show "no version info" in that case?

**Comment by kripken** [comment]
Oops, wrong ping, sorry @sbc! I meant to ping @sbc100

**Comment by apoleon** [comment]
Either no version info or you need to set the version when you cut a new release. Could be a script that parses CHANGELOG.md, perhaps?
