### ISSUE TITLE
Version error detection breaking CI

### ISSUE THREAD

**Issue by kripken** [WebAssembly/binaryen#2617]
e.g. https://travis-ci.org/WebAssembly/binaryen/jobs/641013614?utm_medium=notification&utm_source=github_status

```
fatal: No names found, cannot describe anything.
CMake Error at CMakeLists.txt:25 (message):
  Error running git describe to determine version
```
(example PR: https://github.com/WebAssembly/binaryen/pull/2616)

cc @sbc100

**Comment by sbc100** [comment]
Fixing..
