### ISSUE TITLE
tools should be less verbose when errors occur

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/binaryen#2634]
Currently tools like wasm-opt have a tendency to dump the entire program to stdout when they fail.

See: https://github.com/emscripten-core/emscripten/issues/10331

For normal users this is almost never what they want or useful.  Perhaps we should different modes?  Perhaps only print a summary/snippet by default?

**Comment by Ghabry** [comment]
Still not highly useful but I would prefer an output like "wasm-validate" from wabt.
```
```
module.wasm:00627b2: error: type mismatch in call, expected [i32, i32, i32, i32, i32, i32, f64, i32, i32] but got [i32, i32, f64, i32, i32, i32, i32, i32, i32]
module.wasm:00627b5: error: type mismatch in block, expected [] but got [i32]
module.wasm:0062d8c: error: type mismatch in call, expected [i32, i32, i32, i32, i32, i32, f64, i32, i32] but got [i32, i32, f64, i32, i32, i32, i32, i32, i32]
module.wasm:0062da5: error: type mismatch in block, expected [] but got [i32]
```
(and if this is somehow possible also print the function names for the addresses)
