### ISSUE TITLE
clang-tidy.diff no longer shows diff

### ISSUE THREAD

**Issue by kripken** [WebAssembly/binaryen#2653]
See e.g.

https://travis-ci.org/WebAssembly/binaryen/jobs/647592174?utm_medium=notification&utm_source=github_status

It shows
```
$ ./clang-tidy-diff.sh
The command "./clang-tidy-diff.sh" exited with 1.
```
There is no printed diff to apply.

cc @sbc100 - maybe the recent travis config refactor?

**Comment by sbc100** [comment]
Hmm.. I guess it could be related to https://github.com/WebAssembly/binaryen/pull/2641.  Let me see..

**Comment by sbc100** [comment]
I don't see how it could have changed anything.  Strange that there is no output at all.
