### ISSUE TITLE
wasm-opt have no version information when built from release tarball

### ISSUE THREAD

**Issue by Luthaf** [WebAssembly/binaryen#2664]
Building binaryen from a release tarball (such as https://github.com/WebAssembly/binaryen/archive/version_90.tar.gz) creates a wasm-opt binary without version information, which then crashes emcc with `shared:ERROR: error parsing binaryen version (wasm-opt (unable to determine version)). Please check your binaryen installation`.

Steps to reproduce:
```
wget https://github.com/WebAssembly/binaryen/archive/version_90.tar.gz
tar xf https://github.com/WebAssembly/binaryen/archive/version_90.tar.gz
cd binaryen-version_90
cmake .
make 
./bin/wasm-opt --version
# output 'wasm-opt (unable to determine version)'
```

---

I discovered this while trying to use the version binaryen built by homebrew

**Comment by kripken** [comment]
cc @sbc100 who changed this.

**Comment by sbc100** [comment]
I believe this is already fixed in #2632, we just need to do a new release.

**Comment by sbc100** [comment]
Looks like I even already have a PR up for that..

**Comment by Luthaf** [comment]
Thanks a lot!

**Comment by Luthaf** [comment]
The release seems to be missing a tag: https://github.com/WebAssembly/binaryen/releases

**Comment by sbc100** [comment]
Sorry, tagged.

**Comment by Luthaf** [comment]
Thanks again! https://github.com/Homebrew/homebrew-core/pull/50661
