### ISSUE TITLE
Trivial patch to fix build issue due to ::fileno() on OpenBSD

### ISSUE THREAD

**Issue by osen** [WebAssembly/binaryen#2666]
Hello,

I noticed a build issue on OpenBSD 6.6 (libc++) and have attached a very simple patch.

`
/home/kpedersen/embuild/work/binaryen/third_party/llvm-project/raw_ostream.cpp:526:12: error: expected unqualified-id
  return ::fileno(stdout);
           ^
/usr/include/stdio.h:406:19: note: expanded from macro 'fileno'
#define fileno(p)       (!__isthreaded ? __sfileno(p) : (fileno)(p))
`

From the looks of it, fileno is defined as a MACRO which causes issues with the :: qualifier.

[raw_ostream_cpp.diff.txt](https://github.com/WebAssembly/binaryen/files/4255578/raw_ostream_cpp.diff.txt)

**Comment by kripken** [comment]
Thanks @osen! Would you like to submit a PR with that? (if not I can apply it, but you wouldn't get credit)

**Comment by osen** [comment]
Pull request submitted!

Looking forward to the credit and glory for my 2 character patch XD

That said, I have never done a pull request on GitHub before so I am using this as a learning experience. Hopefully it all goes smoothly.

**Comment by kripken** [comment]
I think it went great :grinning: , thanks again!

Closing this issue as fixed by #2669
