### ISSUE TITLE
Module#addFunctionType doesn't exist in JS API

### ISSUE THREAD

**Issue by RReverser** [WebAssembly/binaryen#2677]
As the title says, `Module#addFunctionType` is documented at https://github.com/WebAssembly/binaryen/wiki/binaryen.js-API but doesn't actually exist in the binaryen.js from npm (package version: 91.0.0), making it impossible to construct functions.

**Comment by RReverser** [comment]
Hmm checking example on https://github.com/AssemblyScript/binaryen.js, it appears that the documentation is simply incorrect and should remove `addFunctionType` and instead add top-level `createType`?

**Comment by tlively** [comment]
Yes, `FunctionType` no longer exists. `createType` should be used to create the tuple types for the params and results and those types should be specified when the `Function` is created. I did not know about this Wiki Page before. Would there be a way to automatically update it based on documentation in the code? My guess is not, but we should definitely add a comment telling people to update the wiki when they change the API.

**Comment by RReverser** [comment]
> I did not know about this Wiki Page before.

Heh, that's one of the first hits for binaryen.js when searching for docs.

> Would there be a way to automatically update it based on documentation in the code?

These should be - Github wikis are just repos, so they can be pushed to either manually or by any tools that can work with Git. https://help.github.com/en/github/building-a-strong-community/adding-or-editing-wiki-pages#adding-or-editing-wiki-pages-locally

**Comment by tlively** [comment]
Neat, I guess we could check in a script to generate the wiki page and have the CI check that it is up to date, much as we currently do with the script that generates instruction parsing code.
