### ISSUE TITLE
wasmJS is not defined in V8 native module

### ISSUE THREAD

**Issue by antelle** [WebAssembly/binaryen#270]
Hello!
I've compiled an app with binaryen and sexpr-wasm-prototype, it successfully loads in browser and starts executing ok in V8.
But when more memory is allocated, we get to [`mergeMemory(newBuffer)`](https://github.com/WebAssembly/binaryen/blob/6f1cf66e71f3db6af5c2c8087e001fe0c77b0fc4/src/js/wasm.js-post.js#L96) and fail with error that wasmJS is not defined. Looks like it's defined [below](https://github.com/WebAssembly/binaryen/blob/6f1cf66e71f3db6af5c2c8087e001fe0c77b0fc4/src/js/wasm.js-post.js#L203), only when using a polyfill.

**Comment by kripken** [comment]
By more memory do you mean memory growth? I think that's not currently a tested path.

**Comment by antelle** [comment]
Yes, I mean growth. Thanks for status! I thought it was supported already.

**Comment by kripken** [comment]
Oh, it should be supported ;) I'll look into it now, actually. I just wasn't expecting anyone to try this yet, I wasn't aware browsers had support yet. Even before browsers get there, we should get interpreter support working.

**Comment by kripken** [comment]
Ok, should be fixed now.
