### ISSUE TITLE
shared:ERROR: asm2wasm failed (-1073740791)

### ISSUE THREAD

**Issue by woxinchangdanzou** [WebAssembly/binaryen#2725]
shared:ERROR: 'D:/TechnologyStudy/emsdk/fastcomp\bin\asm2wasm GsealApp.temp.asm.js --total-memory=16777216 --trap-mode=allow --mem-max=2097152000 --wasm-only --enable-threads -g -o GsealApp.wast -S --mvp-features --enable-threads' failed (-1073740791)

Environment:
emcc 1.38.41 fastcomp

**Comment by kripken** [comment]
We need more information here, as that's a generic failure. But the most likely possibility is it runs out of memory. To check that, you can look at memory usage while it runs.

If that's not it, you can try to run it in valgrind to check for memory issues.

If you can provide a testcase that shows the problem that we can reproduce, that would be good too.

**Comment by woxinchangdanzou** [comment]
ok,I'll focus on memory issues

**Comment by woxinchangdanzou** [comment]
After testing, I think it's really a memory problem. When I connect to the debug library, I always encounter problems. When I link to the release library, it's always ok
