### ISSUE TITLE
Suspect logic in src\support\safe_integer.cpp(40)

### ISSUE THREAD

**Issue by juj** [WebAssembly/binaryen#277]
Reading the logic at https://github.com/WebAssembly/binaryen/blob/master/src/support/safe_integer.cpp#L37, the code first asserts that `x` is an integer in range `[0, uint32_max]`, but then proceeds to dynamically check if `x` is smaller than `uint32_max`. The ternary condition for this dynamic check never fails(?), so it would be equivalent to just have `return (uint32_t)x;`. Was the intent here to abort if `x` is not a integer in range, or is the intent to dynamically allow `x` to be an integer outside range, and clamp?

**Comment by juj** [comment]
Likewise the logic in function `wasm::toSInteger32` and the others in that file are suspicious: the assert()s first ensure that the conditions exist for `x` to be in range, but then it still dynamically checks that it is so.

**Comment by kripken** [comment]
The asserts are bogus, yeah. Fixing in #282. These just cast and clamp.

**Comment by jfbastien** [comment]
Opened #284 to address some other issues.
