### ISSUE TITLE
Fuzz failure on --flatten with "all used types should be allowed"

### ISSUE THREAD

**Issue by kripken** [WebAssembly/binaryen#2770]
cc @tlively - looks like it's multivalue related?

```
bin/wasm-opt --all-features --disable-exception-handling a.wasm --flatten
```
[a.wasm.gz](https://github.com/WebAssembly/binaryen/files/4489041/a.wasm.gz)

**Comment by kripken** [comment]
Side note, I think the reducer hits a bad case when trying to work on this, since with multivalue loading and storing the wasm can increase the size. So it thinks it's doing poorly, and skips to working on a factor of 1, which is the slowest speed.

**Comment by kripken** [comment]
Due to both of these issues perhaps we should disable multivalue in the fuzzer for now?

**Comment by kripken** [comment]
Took a while but here's a reduced testcase:

[reduced.wasm.gz](https://github.com/WebAssembly/binaryen/files/4489193/reduced.wasm.gz)

**Comment by kripken** [comment]
Hmm, even with `--disable-multivalue` these testcases fail with that error. It's like flatten causes it to use multivalue things?

**Comment by tlively** [comment]
Investigating now.

**Comment by tlively** [comment]
I'm not seeing any failures when you remove the `--disable-exception-handling` flag. There is a function that has an exnref local in this module. I don't think this has anything to do with multivalue after all. I am concerned if the fuzzer produced an exnref local when it shouldn't have, though.

**Comment by kripken** [comment]
Ah yes, maybe this is exceptions then. Alternative flags to see this:
```
wasm-opt --enable-reference-types --enable-multivalue --enable-simd --flatten reduced.wasm
```
and adding
```
--enable-exception-handling
```
fixes it.

cc @aheejin
