### ISSUE TITLE
Deprecated strdup warning

### ISSUE THREAD

**Issue by juj** [WebAssembly/binaryen#279]
Visual Studio likes to raise the following build warning on each instance of `strdup`:

```
c:\code\binaryen\src\s2wasm.h(390): warning C4996: 'strdup': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _strdup. See online help for details.
c:\code\binaryen\src\wasm2asm.h(146): warning C4996: 'strdup': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _strdup. See online help for details.
c:\code\binaryen\src\wasm-js.cpp(396): warning C4996: 'strdup': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _strdup. See online help for details.
```

and points to https://msdn.microsoft.com/en-us/library/ms235454.aspx. Is `_strdup` readily available on Linuxes/OS X/other compilers we care that we should just use that?

**Comment by jfbastien** [comment]
It would be nicer to use something which owns the memory instead.

**Comment by froydnj** [comment]
The warnings have gone away in #1386, so I guess this issue can be closed?  Trying to express memory ownership more clearly with types would be good, but that should be a separate issue.
