### ISSUE TITLE
Comments about memory leaks

### ISSUE THREAD

**Issue by juj** [WebAssembly/binaryen#280]
Noticed that there are the following leftover comments in the code about memory leaks:

```
c:\code\binaryen\src\emscripten-optimizer\istring.h:
   75:         char *copy = (char*)malloc(strlen(s)+1); // XXX leaked

  151:     char *curr = new char[size+1]; // leaked!

c:\code\binaryen\src\s2wasm.h:
 1111:     auto raw = new std::vector<char>(); // leaked intentionally, no new allocation in Memory

c:\code\binaryen\src\wasm-js.cpp:
  396:   return (int)strdup(stack.c_str()); // XXX leak

c:\code\binaryen\src\wasm2asm.h:
  146:       char *mod = strdup(str); // XXX leak
```

The one in s2wasm.h clearly documents an one-off allocation. Any chance that any of the others could potentially be running leaks?

**Comment by jfbastien** [comment]
asan's leak detection is [turned off](https://github.com/WebAssembly/binaryen/blob/master/.travis.yml#L43) in `.travis.yml` because of these. Would be nice to fix.

**Comment by kripken** [comment]
Is there a way to tell asan to allow some leaks? E.g. the leaks in istring.h are intentional, they need to live until the end of the process lifetime. Using a "proper" method of allocation that frees them on shutdown is nice, but adds unnecessary overhead.

**Comment by jfbastien** [comment]
IMO in that case the best approach is to allocate istrings with their own bump allocator. That's much nicer than using the same allocator as other objects, and you can free it when the global context object is freed.

**Comment by kripken** [comment]
Working on this in #403.

**Comment by tlively** [comment]
This is resolved. We run full ASan in CI now.
