### ISSUE TITLE
wasm-reduce unintentionally adds a feature

### ISSUE THREAD

**Issue by kripken** [WebAssembly/binaryen#2813]
This annoying thing happens:

* The reducer finds a bug. It uses no features while doing so on that testcase, plain MVP.
* `wasm-reduce` adds `-all` to all its commands. It does that so that it can succeed to load all wasm files.
* When it writes out the wasm after doing `-all`, it writes out the DataCount section, because `bulk-memory` has been enabled, and we always emit that section when that feature is enabled.
* When we try to run wasm2c on that testcase it now fails, as wasm2c only supports MVP features.

IOW, `wasm-reduce` uses `-all` to work around feature errors, but enabling features - even when just reading and writing the wasm - has a side effect of turning the output wasm into actually using features :cry: 

@tlively I hope you'll have a good idea here...

**Comment by kripken** [comment]
Ah reading the code I see this promising comment:
```cpp
        // TODO(tlively): -all should be replaced with an option to use the
        // existing feature set, once implemented.
```
So maybe this is expected and we have a plan?

**Comment by tlively** [comment]
Hmm, we have an option `--detect-features` that uses the target features section, but in general that section may not be present in the input. The simplest thing to do might be to add feature flags to `wasm-reduce`? I guess we could also add a pass or flag that detects used features and shrinks the enabled feature set to be minimal, but I've so far resisted doing that in favor of being more explicit and declarative.
