### ISSUE TITLE
What does --detect-features do?

### ISSUE THREAD

**Issue by kripken** [WebAssembly/binaryen#2831]
I realize I don't understand that flag. We started to use it in wasm-reduce recently, in order to just use the necessary features and not do `-all` (as enabling them all enables bulk memory, and then writing it out adds a new section, which is confusing). But the docs say

```
  --detect-features                             Use features from the target 
                                                features section, or MVP 
                                                (default) 
```

Maybe I'm misreading that, but it surprises me? (don't we always read that section, if it's present? and doesn't the option detect the features from the wasm?)

Because of that confusion, I'm not sure if I found a bug or not. The following fails:

```
wasm-opt --detect-features original.wasm
```

with stuff like `[wasm-validator error in module] unexpected false: all used types should be allowed`. But it works with `-all`. Is that expected?

This problem explains why wasm-reduce fails on a lot of fuzzer testcases atm, complaining it can't read and write the wasm.

[original.wasm.gz](https://github.com/WebAssembly/binaryen/files/4589110/original.wasm.gz)

**Comment by tlively** [comment]
--detect-features only says to use whatever features are in the target features section. original.wasm does not have a target features section, so `--detect-features` is the same as `--mvp-features`. This is the default behavior of wasm-opt, and the flag only exists to override other feature flags on the same command line to restore the default behavior.

**Comment by tlively** [comment]
The fuzzer probably needs to manually emit the target features section using `--emit-target-features` so that `--detect-features` works as intended.

**Comment by kripken** [comment]
Then I don't understand. Why did we think that mass-changing `wasm-reduce`'s use of `wasm-opt -all` to `wasm-opt --detect-features` would help? (#2813 , #2815)

**Comment by kripken** [comment]
(I mean, I know why I thought it would help - I totally misunderstood the option! :rofl: But it seemed like you thought it would help? So I'm still missing something.)

**Comment by tlively** [comment]
I probably thought that the target features section would be emitted by default 😬 sorry for the confusion.

**Comment by kripken** [comment]
Thanks, IIUC then #2836 should fix this.

With that, I seem to be able to reduce easily when I find a bug.
