### ISSUE TITLE
Ambiguous versioning scheme

### ISSUE THREAD

**Issue by AMDmi3** [WebAssembly/binaryen#2872]
I see that there were two incompatible concurrent versioning schemes used before in binaryen, e.g. `version_72` vs. `1.38.29`. This is confusing for packagers and users, makes it harder to automatically report new releases and imposes security risk, as package versions (most packagers [stick to single-number scheme](https://repology.org/project/binaryen/versions)) cannot be matched against versions associated with CVEs - for instance, [known binaryen CVEs](https://repology.org/project/binaryen/cves) use X.Y.Z scheme, so packages of vulnerable binaryen versions cannot be reported.

I strongly advise to switch to a single scheme - probably `version_X`, since it's widely used for packaging and was the only scheme used in 2020, or in other words never use `X.Y.Z` versions. If you can confirm that, I can mail NVD to fix versions in CVEs so they can be matched to packages.

**Comment by kripken** [comment]
Yes, we've agreed to only use `version_X` (but have not removed the old `1.*` tags from the repo).

**Comment by AMDmi3** [comment]
Okay, then the issue is closed. I'll submit NVD update then.
