### ISSUE TITLE
Can't pass fuzz testing due to d8 and binaryen interpreter produce diff results

### ISSUE THREAD

**Issue by MaxGraey** [WebAssembly/binaryen#2915]
`./scripts/fuzz_opt.py 9806017957528267069`
`./scripts/fuzz_opt.py 12039960161667038382`
`./scripts/fuzz_opt.py 8142584983490264672`
and etc

Actually it seems fuzz testing completely broken. Could somebody confirm? May be It's some local issue on my side.

```
d8 --version
8.3.110.13
```

**Comment by MaxGraey** [comment]
```
!
-----------------------------------------
Exception:
  File "./scripts/fuzz_opt.py", line 799, in <module>
  File "./scripts/fuzz_opt.py", line 648, in test_one
  File "./scripts/fuzz_opt.py", line 427, in handle_pair
  File "./scripts/fuzz_opt.py", line 446, in run_vms
  File "./scripts/fuzz_opt.py", line 185, in compare_between_vms
  File "./scripts/fuzz_opt.py", line 154, in compare
-----------------------------------------
!
CompareVMs between VMs: binaryen interpreter and d8 (note: different number of lines between vms) comparison error, expected to have '[fuzz-exec] calling hashMemory
```

**Comment by kripken** [comment]
The full logging might have more info. I saw an error now locally myself that is fixed by https://github.com/WebAssembly/binaryen/pull/2916 - does that help you too? If not, what is your full log?

**Comment by MaxGraey** [comment]
Thanks! Can confirm #2916 solve this issue
