### ISSUE TITLE
wasm-opt crashing with "uncaught exception of type std::out_of_range: unordered_map::at: key not found"

### ISSUE THREAD

**Issue by akoeplinger** [WebAssembly/binaryen#2992]
Repro steps:

1. Download and unzip [wasm-opt-crash.zip](https://github.com/WebAssembly/binaryen/files/4984161/wasm-opt-crash.zip)
2. Setup emscripten sdk version 1.39.20
3. Run the following command:

```bash
emcc --profiling-funcs -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 -s BINARYEN=1 -s ALIASING_FUNCTION_POINTERS=0 -s NO_EXIT_RUNTIME=1 -s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall', 'FS_createPath', 'FS_createDataFile', 'cwrap', 'setValue', 'getValue', 'UTF8ToString', 'UTF8ArrayToString', 'addFunction']" -s "EXPORTED_FUNCTIONS=['_putchar']" --source-map-base http://example.com  -emit-llvm -s FORCE_FILESYSTEM=1 -s USE_ZLIB=1 -g -O2 -s ASSERTIONS=1 -DENABLE_NETCORE=1 -DDEBUG=1 --js-library library_mono.js --js-library binding_support.js --js-library dotnet_support.js libSystem.IO.Compression.Native.a libSystem.Native.a libicudata.a libicui18n.a libicuuc.a libmono-ee-interp.a libmono-icall-table.a libmono-ilgen.a libmonosgen-2.0.a corebindings.o driver.o pinvoke.o -o dotnet.js
```

It crashes with the following error:

```
libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: unordered_map::at: key not found
emcc: error: '/Users/alexander/dev/emsdk/upstream/bin/wasm-opt --post-emscripten --no-exit-runtime -O2 --low-memory-unused --strip-producers --pass-arg=stack-pointer@5883312 --pass-arg=emscripten-sbrk-ptr@640272 dotnet.wasm -o dotnet.wasm -g --mvp-features' failed (-6)
```

@sbc100 mentioned that this is most likely a binaryen issue.

**Comment by akoeplinger** [comment]
If I remove the `-g` option then the crash doesn't happen.

**Comment by kripken** [comment]
When I try to run that command I get
```
wasm-ld: error: Invalid record
wasm-ld: error: Invalid record
```
It looks like the problem is 2 out of the 3 `.o` files,
```bash
$ file *.o
corebindings.o: WebAssembly (wasm) binary module version 0x1 (MVP)
driver.o:       LLVM IR bitcode
pinvoke.o:      LLVM IR bitcode
$ llvm-dis driver.o 
llvm-dis: error: Invalid record
$ llvm-dis pinvoke.o 
llvm-dis: error: Invalid record
```
Are those valid? How were they generated? (I checked if they are old LLVM IR, like maybe from fastcomp, but it doesn't seem like it, fastcomp can't load them either.)

Removing those from the emcc command, it runs without an error (with `-g`). I'm not sure if that means the original problem was in those files, or whether the original problem is some corruption in those bitcode files.

**Comment by akoeplinger** [comment]
@kripken are you running on Linux? I'm on macOS 10.15.5 here.

These files were generated using emcc, with the targets defined here: https://github.com/dotnet/runtime/blob/1d05f27bf92586e8b7e0d312194b83de6a35ba67/src/mono/wasm/Makefile#L84-L91

It looks like `corebindings.o` doesn't use `$(EMCC_FLAGS)` for some reason, I'll ask about whether that's intentional.

I can still run `llvm-dis` against the other two .o files though but I need to use the tool from `emsdk/upstream/bin/llvm-dis`.

**Comment by kripken** [comment]
Interesting... yes, I am on linux. Testing some more, that's not the issue, but I had to update LLVM. It seems like a recent LLVM change (in the last few weeks) made our two versions incompatible. I can reproduce the problem now.

Separately, it might be worth finding out why some of those `.o` files are wasm object files, and others are LLVM IR. Using wasm object files consistently would make linking slightly faster (IR only makes sense if you are doing LTO).

**Comment by akoeplinger** [comment]
> Separately, it might be worth finding out why some of those .o files are wasm object files, and others are LLVM IR

That was just a missing makefile flag for that one .o that I fixed in https://github.com/dotnet/runtime/pull/40024

I don't think we particularly care about linking speed but I'll ask whether there's a reason why we compile to LLVM IR.

**Comment by kripken** [comment]
Oh, I see, so you do want LTO then? Makes sense.

Meanwhile I opened #2997 which should fix that bug. Thanks for the report!
