### ISSUE TITLE
Duplicated unary / binary expression ellimination

### ISSUE THREAD

**Issue by MaxGraey** [WebAssembly/binaryen#3014]
Many unary duplicated operations could be eliminated. Like:
~~`~(~x)` -> `x`~~
~~`-(-x)` -> `x`~~
`abs(abs(x))` -> `abs(x)`
`ceil(ceil(x))` -> `ceil(x)`
`floor(floor(x))` -> `floor(x)`
`trunc(trunc(x))` -> `trunc(x)`
`nearest(nearest(x))` -> `nearest(x)`
etc

and some binary:
`y - (y - x)` -> `x` _int only_
`(x ^ y) ^ y` -> `x`
`(x | y) | y` -> `x | y`
`(x & y) & y` -> `x & y`
etc

~~I think it should be something general like `ZeroRemover` and call it like `Deduplicator` or `DupRemover` which walk recursively. Thoughts?~~

**Comment by kripken** [comment]
I think this should be part of OptimizeInstructions, as it's the type of peephole optimization done there, and after doing it more optimizations may show up.

We should however refactor that pass to have more small functions probably, so it's more modular. The code that does this family of patterns might be such a function.

**Comment by MaxGraey** [comment]
I guess such cases like `(x | y) | y | y .... | y` better handle via `PostWalker` and better create mist walker like ZeroRemover, right?

Regarding splitting OptimizeInstructions. By what criterion is it better to divide? It might be worth doing separation by kind of expressions: `OptimizeBinaryInstructions`, `OptimizeUnaryInstructions`, ``OptimizeSelectInstruction` and etc?

**Comment by kripken** [comment]
OptimizeInstructions is run in a loop, so it should be able to handle things like `(x | y) | y | y | y ..`.

I don't have specific ideas for the splitting. It could be by Binary/Unary/Select, that's a good starting point.

**Comment by MaxGraey** [comment]
I see, thanks
