### ISSUE TITLE
A pass to store mutable state in linear memory?

### ISSUE THREAD

**Issue by johnnesky** [WebAssembly/binaryen#3080]
Hi! I'm exploring the potential for using Wasm for complex games/simulations. I'm currently trying to record the state of the program by copying a Wasm instance's linear memory, and later "rewinding" to that state by overwriting the current memory with the recorded state. Being able to do this would be useful for various things, like undo, recording sessions to replay later, [online multiplayer rollback netcode](https://en.wikipedia.org/wiki/GGPO), or even just literally rewinding like in the popular game [Braid](https://en.wikipedia.org/wiki/Braid_%28video_game%29). 

However, I discovered that only some of the program state is stored in linear memory. In my experiments, I'm able to rewind, say, the values of elements inside a global array, but not the value of a global i32, because the global array actually just points to a region of linear memory, but the global i32 does not reference linear memory at all and is inaccessible to JavaScript unless I export it. This leads to an inconsistently rewound state. 

I asked about this in the AssemblyScript discord server, and @dcodeIO helpfully pointed out that basic global variables and local variables that are captured by closures are not stored in linear memory, but he suggested a couple workarounds. First, I could simply make a custom global singleton object to store all my global variables, which might work if I'm careful, but would require that I only use code that is aware of this constraint. (Maybe instead I could try to export all my global variables to make them accessible to JavaScript for recording, but again only if the code is designed for that.)

Second, he suggested I could use a Binaryen pass like asyncify to move hidden state into linear memory, which intrigued me. Upon further investigation, I don't think asyncify does what I want, but it's a similar idea, and I'm wondering if there is another pass available that does what I want, or perhaps I could make one. 

I admit I know little about how Wasm works at the moment, but in principle, I don't yet see any reason why an optional pass couldn't move basic mutable global variables into linear memory, perhaps by turning all existing global variables into pointers? Does such a pass exist? If I were to try to make such a pass, would it be accepted? Are there any existing passes that would serve as a good example of how I could write such a thing?

(It would be even better if such a pass could also store local variables captured by closure functions in linear memory! That sounds more difficult, but I think it would go a long way toward being able to successfully record all mutable state in linear memory for arbitrary programs, allowing me to easily rewind simulation state. I don't think I need to record the current call stack for my use-cases, but if I did it sounds like asyncify would allow me to record that too. Is there any other hidden state I need to worry about?)

Worst case scenario, I know I can just write Wasm code to explicitly encode and serialize all relevant state, and I may end up doing that anyway for persistent storage that needs to be parseable by new versions of the Wasm simulation, but that's a lot more complex and less efficient than just copying memory as one big blob for live rewinding, so I was hoping there was a simple solution. Thanks for any advice you can give!

**Comment by kripken** [comment]
You can move globals into linear memory, but only if you know a proper place to do so. If you somehow know that memory region 0-10,000 for example is reserved for this purpose (and nothing else will use it) then writing such a pass would be easy. So the pass would need to take the range as a parameter (or receive the range at runtime).

(Future wasm may make this easier with multi-memory - you can add a new memory just for this.)

Separately, as @dcodeIO said you may need asyncify if you want to save local state that is currently on the stack. But if nothing is on the stack when you do this operation, then all you need to care about are globals.

**Comment by binji** [comment]
You probably don't want to copy all of linear memory anyway, since a lot of it is not relevant to your game's state (it may be known by your application to be constant data, for example). Instead, you probably want to find which regions of memory can possibly change and only save that. Wasm doesn't have a concept for this, but C/C++ does so you may be able to use linking section boundaries to help with this. If you know how many globals your Wasm module has, then you could allocate space for this in linear memory and copy only the wasm globals in, as a pre-pass.

**Comment by johnnesky** [comment]
Regarding constant data, I figured I would put only mutable globals in linear memory, and I'd keep any other constant data outside the Wasm simulation entirely, like graphics and audio assets can be handled by JavaScript instead. But you're right that some constant data might end up in Wasm linear memory, like if there's a non-destructible environment to navigate it could be considered immutable data. I guess it depends on the kind of game. I wonder if projects like [this emulator enhanced with rollback netcode](https://slippi.gg/netplay) make any effort to distinguish constant and non-constant data...

Also that's a good point about needing to have space set aside to store the globals in linear memory. I assume the size number of global variables can be determined from analyzing the Wasm code, and that much space can be allocated at the beginning, but I'd have to make sure that the rest of the program doesn't overwrite that region somehow...
