### ISSUE TITLE
Enchance isSymmetric

### ISSUE THREAD

**Issue by MaxGraey** [WebAssembly/binaryen#3126]
Currently `isSymmetric` is allow currently only integer binary operations:
```cpp
inline bool isSymmetric(Binary* binary) {
  switch (binary->op) {
    case AddInt32:
    case MulInt32:
    case AndInt32:
    case OrInt32:
    case XorInt32:
    case EqInt32:
    case NeInt32:

    case AddInt64:
    case MulInt64:
    case AndInt64:
    case OrInt64:
    case XorInt64:
    case EqInt64:
    case NeInt64:
      return true;

    default:
      return false;
  }
}
```
which affect to `canonicalize` operation as well. I guess we could add  some float operations:
`EqFloat(32|64)`, `NeFloat(32|64)`, `AddFloat(32|64)` and `MulFloat(32|64)`. However last two should have some more careful testing and exclude situation when lhs and rhs are NaNs with different bit set (like qNaN and sNaN).

WDYT?

**Comment by tlively** [comment]
Seems reasonable for EqFloat and NeFloat, at least. For anyone else, there is more discussion on the PR.
