### ISSUE TITLE
Branches

### ISSUE THREAD

**Issue by kripken** [WebAssembly/binaryen#313]
The design and spec repos are moving to have a branch for each binary version on the way to 1.0, next is 0xb. Perhaps we should do the same here?

On the other hand, we have a lot more code moving around, so much higher risk of merge issues. My initial thought is that we'd target the next binary version (now, 0xb) on our master. After 0xb ships, we'd tag or branch that, so people could use it with browsers supporting that version.

**Comment by jfbastien** [comment]
Tags sound simpler IMO.

**Comment by kripken** [comment]
Yes, although if we want to backport to 0xb while working on 0xc, a branch would be nice. But maybe we can start with a tag and see.

Sounds like no concerns with master tracking the next binary format?

**Comment by jfbastien** [comment]
Depends how you recommend consumers work. If we want to get it for the waterfall then it'll break :-)

**Comment by tlively** [comment]
Binary format is now stable.
