### ISSUE TITLE
Fuzzer found bug realate to non-canonical NaNs

### ISSUE THREAD

**Issue by MaxGraey** [WebAssembly/binaryen#3138]
Seed `11654949811299783419`. wasm-reduce don't help due to `original.wasm` and reduced file contains invalid param type `0000016: error: expected valid param type (got -0x5)`

**Comment by MaxGraey** [comment]
Foud a problem. This:
```wat
[f32] (f32.sub
 [f32] (f32.const -nan:0x1e2d70)
 [f32] (f32.const 0)
)
```
can't be reduced to:
```wat
[f32] (f32.const -nan:0x1e2d70)
```

**Comment by dcodeIO** [comment]
Fwiw, `expected valid param type (got -0x5)` looks like `v128`, i.e. SIMD not enabled.
