### ISSUE TITLE
Missing feature validations?

### ISSUE THREAD

**Issue by dcodeIO** [WebAssembly/binaryen#3147]
The validator currently checks that all used types, unary and binary ops are valid, but seems not very strict when it comes to other instructions. For instance

* `ref.null` is checked indirectly via its return type, but not when dropped
* `ref.is_null` is checked via its argument that must be a reference type
* `try` does not have a feature check
* `throw` is checked via usage of events
* `rethrow` is checked via its exnref argument
* There might be more

So I wanted to look into this, but figured that some of this might be intentional in order to avoid unnecessary checks? Personally I'd prefer an explicit "x requires y to be enabled" error on the instruction over an implied generic "all used types should be allowed" error for clarity, but I've also noticed that there have been concerns about validation overhead so I figured I better ask.

To give an example, this is a perfectly cromulent MVP module currently:

```wat
(module
 (type $none_=>_none (func))
 (export "a" (func $a))
 (func $a
  (drop
   (ref.null extern)
  )
  (try
   (do
    (nop)
   )
   (catch
    (nop)
   )
  )
 )
)
```

**Comment by tlively** [comment]
This seems like an oversight to me.
