### ISSUE TITLE
Support for Multi-Dimensional Tuples

### ISSUE THREAD

**Issue by drew-y** [WebAssembly/binaryen#3183]
Playing around with Binaryen I was a little surprised to learn that you cannot have a tuple inside of another tuple.

For example:
```javascript
const tupleType = binaryen.createType([
  binaryen.i32,
  binaryen.createType([binaryen.i32, binaryen.i32]),
  binaryen.i32
]);

mod.addFunction("make-tuple", binaryen.none, tupleType, [], mod.block("", [
  mod.return(mod.tuple.make([
    mod.i32.const(1),
    mod.tuple.make([mod.i32.const(2), mod.i32.const(22)]),
    mod.i32.const(3)
  ]))
]));
```

Running the above generates `Error: abort(Assertion failed: t.isSingle()`.

The simple workaround for a language implementer is to represent the multi-dimensional tuple as a flat in Binaryen land. 

Is it was feasible or worthwhile for Binaryen to support them directly?

**Comment by tlively** [comment]
Tuples in Binaryen are essentially a hack that allows Binaryen IR's tree structure to represent multivalue blocks and functions. Their use is intentionally limited to contexts where they are necessary to meet that goal to keep Binaryen as simple as possible. As you've noticed, tuples cannot be elements of other tuples, but they also cannot be passed as function arguments, for example.

**Comment by drew-y** [comment]
Makes sense to me. Thanks for the info!
