### ISSUE TITLE
pop()s in test/passes/instrument-locals_all-features.wast are not written correctly to binary

### ISSUE THREAD

**Issue by kripken** [WebAssembly/binaryen#3213]
STR:

```
wasm-opt test/passes/instrument-locals_all-features.wast -o a.wasm
wasm-opt a.wasm
```

error:
```
[parse exception: attempted pop from empty stack / beyond block start boundary at 161 (at 0:161)]
```

**Comment by tlively** [comment]
Well, the pops are correctly [not] written to the binary, but the wast deliberately is not valid.

**Comment by kripken** [comment]
In what way is it not valid?

**Comment by tlively** [comment]
```
    (local.set $F (pop funcref))
    (local.set $X (pop externref))
    (local.set $E (pop exnref))
```

This is not valid. Pops are only allowed as the very first instructions in `catch` blocks or in Poppy IR, and if this were Poppy IR, it would be still be invalid because those pops don't correspond to any instructions that produce any values.

**Comment by kripken** [comment]
Oh, right, thanks...

I'll disable this in the fuzzer then.
