### ISSUE TITLE
Partially evaluation for xor expressions with consts

### ISSUE THREAD

**Issue by MaxGraey** [WebAssembly/binaryen#3224]
Currently this works properly:
`((x | 1) | 3) | 5` -> `x | 7`
`((x & 5) & 3) & 1` -> `x & 1`

But folding xor constants as:
`((x ^ -2) ^ -1) ^ -5` -> `x ^ -5`
It seems **doesn't work** for now!

@kripken could you point me which part of the code to look at, so that I could fix it?

**Comment by kripken** [comment]
@MaxGraey I think it is

https://github.com/WebAssembly/binaryen/blob/8943fcc31d12545043043c06c037cf6dfee14722/src/passes/OptimizeInstructions.cpp#L514-L524

**Comment by MaxGraey** [comment]
Oh, thanks!

**Comment by MaxGraey** [comment]
@kripken btw for integer multiplication and division we could do the same:
```cpp
((x * 2) * 3) * 4  ->  x * 24
((x / 2) / 3) / 4  ->  x / 24
```
Is it better create another PR or do it in #3236 ?
