### ISSUE TITLE
wasm-opt adds names that are not present in the input 

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/binaryen#3226]
As of #3162 it seems that emscripten output files include a names for tables/memories/globals that are not present in the input:

```
$ ./emcc -g ~/test/hello.c -o out.wasm
$ wasm-objdump -x out.wasm
 - table[0] <0>
 - memory[0] <0>
 - global[0] <global$0>
 - global[1] <global$1>
```

@dcodeIO please take a look.  We've had users of emscripten who have been stung by this unexpected change.

**Comment by sbc100** [comment]
I looks like this problem actually predates #3162.. wasm-opt will also have made up names for functions if they are not found in the input.

I think the problem is that binaryen doesn't distinguish between something that a user-defined name, and something that was given and internal name simply because binaryen needs to assign a name to everything.

**Comment by kripken** [comment]
Why is this a problem? (a few more bytes in the names section doesn't seem bad, as it isn't present in release builds anyhow..?)

**Comment by sbc100** [comment]
The name section is supposed to be for user-visible names, not these internal names that we make up for binaryen-specific reasons.      I won't expect tools like binaryen and wabt to add names to my binaries that were not present in the input.

I'd rather turn the question around: what useful purpose does adding these number-based named serve?   For functions it just gives them the names `0`.. `1` .. `2`.  This is not helpful, and a little misleading because it might suggest to the user that the `1` is the name of the function in the source language which is clearly isn't.

**Comment by sbc100** [comment]
Isn't the fact that binaryen assigns numeric names to things as it reads them in is an implementation detail that wasm-opt should not persist in the output file?

**Comment by kripken** [comment]
I agree. Sorry if I wasn't clear before. Yes, it would be better to avoid this. I was just trying to say, it seems like a very minor aesthetic issue? When you said

> We've had users of emscripten who have been stung by this unexpected change.

That sounds like something more serious to me, but maybe I'm misreading it.

**Comment by sbc100** [comment]
> I agree. Sorry if I wasn't clear before. Yes, it would be better to avoid this. I was just trying to say, it seems like a very minor aesthetic issue? When you said
> 
> > We've had users of emscripten who have been stung by this unexpected change.
> 
> That sounds like something more serious to me, but maybe I'm misreading it.

This part is because most wasm parsers out there don't yet handle the names for memories/tables/globals there were recently added.  Clearly it would be good to fix those parsers too (they should be ignoring those failures anyway).   But also good to make this fix to binaryen.

**Comment by kripken** [comment]
I see, so by always emitting new names, we uncovered those bugs earlier than expected. Sgtm to fix.
