### ISSUE TITLE
Handle zeros in passive segments for TLS data

### ISSUE THREAD

**Issue by kripken** [WebAssembly/binaryen#3245]
Brought up by @tlively : if we optimize out some zeros from a passive
memory segment that is used as TLS, we would prevent it from zeroing
out memory that was already used, when it is applied later, if there was
something in that memory space already.

It doesn't seem like there is something we can do for that, so maybe
we need to avoid optimizing zeros from TLS? Can we tell if a segment
is only for TLS?

**Comment by tlively** [comment]
Actually, I was reminded when I actually looked at the code again the other day that we split memory.init instructions into sequences of memory.init and memory.fill instructions, so the zeroes aren't skipped after all. Sorry for the false alarm!

**Comment by kripken** [comment]
Oh great, let's close this then!
