### ISSUE TITLE
BinaryenModuleRead overrides existing function names in the name section

### ISSUE THREAD

**Issue by TerrorJack** [WebAssembly/binaryen#3259]
Currently `BinaryenModuleRead` always assign auto-created function names to the functions, even if the name section is present in the input wasm binary. So when the input binary is serialized again, that info is lost.

For a bit of more context on why this impacts binaryen user experience: we use `wasi-sdk` to create a wasm module which exports libc routines we need, deserializes it and adds compiled Haskell code on top of it, then runs the passes and emits final wasm module. When we need to debug the final module, the libc function names in the JS stack traces are uninformative integers instead of proper names.

It would be nice if binaryen HQ plans to fix this. If not we'll try to extend the C API to correct the internal function names after deserializing, but that sounds a bit too hacky :)

Seems relevant: #3247

**Comment by kripken** [comment]
If the name section is present then we should never replace the name, that would be a bug. If the name section is present, however, and you do not pass `-g`, then it will ignore it. If it's not that, do you have a testcase?

**Comment by TerrorJack** [comment]
Ah, after some more investigation, it turns out that the `-O3` flag of `clang` would drop the name section somehow, even if no `--strip-*` flag is passed. So not a problem of binaryen after all, I'll close this and thanks for answering :)

Here's a "repro" that shows binaryen's behavior is good. Might worth adding to the test suite anyway if it helps:

```c
#include <stdio.h>
#include <binaryen-c.h>

int main() {
  BinaryenSetDebugInfo(1);

  BinaryenModuleRef m0 = BinaryenModuleCreate();
  BinaryenAddFunction(m0, "foo", BinaryenTypeNone(), BinaryenTypeNone(), NULL,
                      0, BinaryenNop(m0));
  BinaryenModuleAllocateAndWriteResult r0 =
      BinaryenModuleAllocateAndWrite(m0, NULL);

  BinaryenModuleRef m1 = BinaryenModuleRead(r0.binary, r0.binaryBytes);
  BinaryenFunctionRef foo = BinaryenGetFunctionByIndex(m1, 0);
  const char *foo_name = BinaryenFunctionGetName(foo);

  printf("foo name: %s\n", foo_name);

  return 0;
}
```
