### ISSUE TITLE
Eqref fuzz bug?

### ISSUE THREAD

**Issue by kripken** [WebAssembly/binaryen#3266]
```wat
(module
 (export "func_145" (func $0))
 (func $0 (param $0 eqref) (param $1 i31ref) (result anyref)
  (local $2 i32)
  (local $3 anyref)
  (local $4 eqref)
  (local.set $4
   (local.get $0)
  )
  (local.set $0
   (local.get $1)
  )
  (local.set $2
   (ref.eq
    (local.get $4)
    (local.get $0)
   )
  )
  (if
   (local.get $2)
   (unreachable)
  )
  (local.get $3)
 )
)
```

turns into

```wat
(module
 (export "func_145" (func $0))
 (func $0 (param $0 eqref) (param $1 i31ref) (result anyref)
  (local $2 i32)
  (local $3 anyref)
  (local $4 eqref)
  (nop)
  (local.set $0
   (local.get $1)
  )
  (nop)
  (if
   (ref.eq
    (local.get $0)
    (local.get $0)
   )
   (unreachable)
  )
  (local.get $3)
 )
)
```

by `--simplify-locals-notee`. `--fuzz-exec` finds a different result in them. The first returns `anyref(null)` and the second hits that `unreachable`.

What seems to happen is that in the first case we do `ref.eq` on an `eqref` and on an `i31ref`. Both are null, and we get that they are not equal. Is that correct?

In the second case, we end up comparing the `i31ref` to itself, and find they are equal.

(edit: fuzz seed `11824809954583288331` on `initialfuzz` branch)

**Comment by dcodeIO** [comment]
Looks like in the first case the function essentially checks `$0 == (eqref)$1` (likely null == 0, note that `i31ref` is not nullable) turning out `false`, while in the second case it checks `(eqref)$1 == (eqref)$1` turning out `true`. Looks like a bug to me.
