### ISSUE TITLE
This asm.js code crashes asm2wasm preprocessor

### ISSUE THREAD

**Issue by griffin2000** [WebAssembly/binaryen#327]
The attached asm.js code will hit this assert in Asm2WasmPreProcessor:
`assert(strstr(growthFuncStart + 1, "function ") == 0); // should be only this one function in this area, so no confusion for us
`

[Blob.zip](https://github.com/WebAssembly/binaryen/files/209745/Blob.zip)

**Comment by kripken** [comment]
How was that code generated?

**Comment by griffin2000** [comment]
From emcc:
emcc DCEL.cpp MS.cpp Blob.cpp -o html/Blob.js -O3 -s EXPORTED_FUNCTIONS="['_Blobify']" -s TOTAL_MEMORY=200000000

Tried various variations such as removing optimization, etc. Same result.
 
[CCode.zip](https://github.com/WebAssembly/binaryen/files/210638/CCode.zip)

**Comment by kripken** [comment]
Ok, asm2wasm is meant to be run just on asm.js. Those files contain normal JS too.

Even if you manually strip it out, it might not be compatible with asm2wasm's expections, you should run with `--separate-asm` to get a proper `.asm.js` file.

Or, just build with `-s BINARYEN=1` and it will [run asm2wasm for you](https://github.com/kripken/emscripten/wiki/WebAssembly).

I tried to verify that works on those files, but looks like a file is missing,

````
./Vectors.h:3:10: fatal error: 'Compatibilty.h' file not found
#include "Compatibilty.h"
         ^
1 error generated.
````

**Comment by griffin2000** [comment]
When I add --separate-asm it complains that I need to compile to HTML. If I compile to HTML, then the .js file that result doesn't seem to have the functions exported correctly.  When I try and run _Blobify from my Javascript app it says:

```
Uncaught TypeError: Module.asm is not a function
  (anonymous function)	
Uncaught TypeError: _Blobify is not a function
  init	
  (anonymous function)	
```

**Comment by griffin2000** [comment]
Do I need a particular Emscripten build for BINARYEN=1 to work?

**Comment by griffin2000** [comment]
My bad, missed a file.  Trying again...
[CCodeAgain.zip](https://github.com/WebAssembly/binaryen/files/210851/CCodeAgain.zip)

**Comment by kripken** [comment]
In html, things can be more async. You might be running code before it's loaded. If so, building with `-s ASSERTIONS=1` should give an error. See this [faq entry](http://kripken.github.io/emscripten-site/docs/getting_started/FAQ.html#how-can-i-tell-when-the-page-is-fully-loaded-and-it-is-safe-to-call-compiled-functions).

To use BINARYEN, best to get latest incoming, as things are moving fast.
