### ISSUE TITLE
[fuzzer] contain a lot of [LoggingExternalInterface ignoring an unknown import env . setTempRet0 records

### ISSUE THREAD

**Issue by MaxGraey** [WebAssembly/binaryen#3277]
Approximately every third fuzz iterations contain this logging messages for `./scripts/fuzz_opt.py`:
```
[LoggingExternalInterface ignoring an unknown import env . setTempRet0
[LoggingExternalInterface ignoring an unknown import env . setTempRet0
[LoggingExternalInterface ignoring an unknown import env . setTempRet0
.... 10-20 times...
[LoggingExternalInterface ignoring an unknown import env . setTempRet0
[LoggingExternalInterface ignoring an unknown import env . setTempRet0
warning: no passes specified, not doing any work
warning: no output file specified, not emitting output
```

Is it expected?

**Comment by kripken** [comment]
Yes, this is expected currently, I added it recently. The fuzzer used to silently ignore unknown import calls. But it is annoying, so I'm not sure that was a good decision.

But if that function is the most annoying one, then https://github.com/WebAssembly/binaryen/pull/3279 that I just opened might be good enough?

**Comment by MaxGraey** [comment]
Yes, I guess it will resolve current verbosity. Thanks!
