### ISSUE TITLE
Pops are not valid in Os_print-stack-ir_all-features.wast

### ISSUE THREAD

**Issue by aheejin** [WebAssembly/binaryen#3283]
Currently a `pop` can only come after a `catch`, and its argument should be `exnref`. [Os_print-stack-ir_all-features.wast](https://github.com/WebAssembly/binaryen/blob/master/test/passes/Os_print-stack-ir_all-features.wast) contains tests for pops for various types, so there's no way to make this file a valid wasm file for now. This makes the test not usable as initial content for the fuzzer, and it is in general good to make all our tests valid.

Once the [new EH spec](https://github.com/WebAssembly/exception-handling/pull/137) is implemented, `catch` should be able to pop other types values than `exnref`, then we will be able to make this test valid as well. This is a tracking issue for this problem.

**Comment by tlively** [comment]
It would also be fine to just delete that part of the test. It comes from back when I first implemented Push and Pop with the idea that they could be used anywhere.

**Comment by aheejin** [comment]
OK I'll remove the pops from the file then.

**Comment by aheejin** [comment]
Closed by #3282.
