### ISSUE TITLE
Use zero based local symbol naming

### ISSUE THREAD

**Issue by JSStats** [WebAssembly/binaryen#33]
The asm2wasm output labels the locals with symbols using the pattern `$i<n>` starting with `$i1`. The wast spec allows these to be named by index, starting at zero. If the naming also started at `$i0` then the index would match, and this might be handy when comparing it to the encoded files.

**Comment by kripken** [comment]
The local names should be the same as in asm.js. There, `i1` etc. are int32s, while `d1` etc. are doubles, etc.

I agree it might be nice to be zero-based for comparison to the encoded files, but the comparison to the original asm.js would suffer if we rename locals in asm2wasm. Instead, we could write a pass to do that renaming, although it would actually be equivalent to converting to binary and back, so I don't think it's necessary.
