### ISSUE TITLE
wasm-as generates invalid binaries on Windows

### ISSUE THREAD

**Issue by griffin2000** [WebAssembly/binaryen#331]
When compiled on WIndows (VS2013) wasm-as generates bad data (resulting invalid WASM version number). Looks to be a filemode line ending error (its adding 0x0D linefeed character at the end of each string). Example attached (Basic.wasm has a 0x0d in its version buffer, causing an error).
[Basic.zip](https://github.com/WebAssembly/binaryen/files/211539/Basic.zip)

**Comment by binji** [comment]
The wasm binary format likely will move from being pre-order to post-order, and wasm-as generates a binary format that matches this future change. (Though it sounds like you may be seeing a different issue.)

If you want to generate a binary format that matches the format currently supported in browsers, you'll need to use [spidermonkify](https://github.com/WebAssembly/binaryen/blob/master/scripts/spidermonkify.py) or [sexpr-wasm-prototype](https://github.com/WebAssembly/sexpr-wasm-prototype).

Please remember that WebAssembly is being actively developed. Many things will change between now and the first release.

**Comment by jfbastien** [comment]
This may just be that the files aren't open in binary mode?

**Comment by kripken** [comment]
They should be in binary, [we pass that flag](https://github.com/WebAssembly/binaryen/blob/master/src/wasm-as.cpp#L60), but maybe there's a bug somewhere.

**Comment by bstavroulakis** [comment]
I had the same issue when I ran the example in Chrome. It was fixed when I ran it in Chrome Canary.
