### ISSUE TITLE
Additional canonalize rule. Unify x - C to x + (-C)

### ISSUE THREAD

**Issue by MaxGraey** [WebAssembly/binaryen#3320]
like: `x - C` -> `x + (-C)`

It will signifintally simplify and reduce amount of matches in #3316 for example. Btw LLVM also provide this

WDYT?

**Comment by kripken** [comment]
I agree the extra canonicalization is a good idea.

And I think this makes sense, since constants are encoded as signed LEBs, so this should not affect code size, unless I'm missing something.
