### ISSUE TITLE
Assertion failed: pass->isFunctionParallel()

### ISSUE THREAD

**Issue by CommanderTvis** [WebAssembly/binaryen#3333]
Cannot run default optimization passes on function with O3: 
```kotlin
        binaryen.setOptimizeLevel(3)
        optimizeFunction("executable")
```

```
Error: abort(Assertion failed: pass->isFunctionParallel(), at: /home/runner/work/binaryen.js/binaryen.js/binaryen/src/passes/pass.cpp,787,runPassOnFunction). Build with -s ASSERTIONS=1 for more info.
Error: abort(Assertion failed: pass->isFunctionParallel(), at: /home/runner/work/binaryen.js/binaryen.js/binaryen/src/passes/pass.cpp,787,runPassOnFunction). Build with -s ASSERTIONS=1 for more info.
	at <global>.q(/mnt/d/IdeaProjects/kmath/build/js/node_modules/binaryen/index.js:54)
	at <global>.h(/mnt/d/IdeaProjects/kmath/build/js/node_modules/binaryen/index.js:103)
	at <global>.BQ(/mnt/d/IdeaProjects/kmath/build/js/node_modules/binaryen/index.js:13)
	at <global>.BMb(/mnt/d/IdeaProjects/kmath/build/js/node_modules/binaryen/index.js:13)
	at <global>.Oc(/mnt/d/IdeaProjects/kmath/build/js/node_modules/binaryen/index.js:177)
	at Object._BinaryenFunctionOptimize(/mnt/d/IdeaProjects/kmath/build/js/node_modules/binaryen/index.js:13)
	at Object.d.optimizeFunction(/mnt/d/IdeaProjects/kmath/build/js/node_modules/binaryen/index.js:265)
	at <global>.compileMstToWasmF64(kotlin/kmath-kmath-ast-test.js:16454)
	at Test_0.c(kotlin/kmath-kmath-ast-test.js:17338)
	at _no_name_provided__77.invoke(kotlin/kmath-kmath-ast-test.js:17383)
	at Context.<anonymous>(kotlin/kmath-kmath-ast-test.js:17376)
	at <global>.processImmediate(internal/timers.js:456)
```

**Comment by tlively** [comment]
Hmm, that's not great. Working on a fix now.

**Comment by tlively** [comment]
Actually, this turns out to be trickier than I thought. `BinayenFunctionOptimize` eventually ends up calling `PassRunner::runPassOnFunction`, which asserts that the pass is parallel. This is actually a correct assertion because it then calls `Pass::runOnFunction`, which is only implemented for parallel passes. So `BinaryenFunctionOptimize` seems fundamentally broken because some optimization passes are not able to run on individual functions. I recommend that we remove it from the C and JS APIs entirely. @kripken, what do you think?

@CommanderTvis, would you be able to use `optimize` rather than `optimizeFunction`?

**Comment by CommanderTvis** [comment]
I'm not able, since my module consists of set of precompiled functions which need no optimization and a function that need optimization  Optimizing the whole module takes 2 seconds.

**Comment by CommanderTvis** [comment]
Can you fix the passes set that are enabled for that feature and remove non-parallel?

**Comment by aheejin** [comment]
Not sure about the correctness of that code, and I think @kripken will know more. If there is an unstated assumption that all default optimization passes have to be function-parallel, I think that has to be commented somewhere.

But actually there seem to be only three passes that are not function-parallel: `I64ToI32Lowering`, `TrapMode`, and `RemoveNonJSOpts`, and none of these are included in the default optimization passes for any level. What is the command line and the test case to reproduce this problem?

**Comment by CommanderTvis** [comment]
In this repository, https://github.com/mipt-npm/kmath/tree/feature/binaryen. Command is `./gradlew :kmath-ast:jsTest`, and the stacktrace can be checked in the test report.
![image](https://user-images.githubusercontent.com/38042667/98822898-f83c5d80-2463-11eb-8e21-6ff4ba7cf2c2.png).

**Comment by kripken** [comment]
If I am not missing something, I think #3339 fixes this. Indeed we ran the wrong passes, so this apparently never worked..?
