### ISSUE TITLE
Fuzzer issue

### ISSUE THREAD

**Issue by MaxGraey** [WebAssembly/binaryen#3362]
Fuzzer found issue (`seed 15763270784619598781`) in master. Unfortunately reduced file can't parsed:
```
Error: readWasm failed:
0000012: error: expected valid result type (got -0x13)
```

[w.wasm.zip](https://github.com/WebAssembly/binaryen/files/5541115/w.wasm.zip)

**Comment by kripken** [comment]
Thanks @maxgraey, reducing this it looks like a bug in optimize-instructions shifts, so maybe something from your recent work?

STR: `wasm-opt a.wat --fuzz-exec --optimize-instructions`

```wat
(module
 (import "fuzzing-support" "log-i32" (func $fimport$0 (param i32)))
 (export "func_42" (func $1))
 (func $0 (param $0 i32)
  (call $fimport$0
   (i32.shr_s
    (i32.shl
     (i32.shr_s
      (i32.shl
       (local.get $0)
       (i32.const 24)
      )
      (i32.const 24)
     )
     (i32.const -66)
    )
    (i32.const 24)
   )
  )
 )
 (func $1
  (call $0
   (i32.const 65419)
  )
 )
)
```
(the `readWasm` error may be because the testcase needs more features enabled. but i reduced it further in this wat, and now it doesn't need any)

**Comment by MaxGraey** [comment]
Thanks! Will investigate this

**Comment by MaxGraey** [comment]
@kripken After comment all places which relate to Shl / ShrS (include getMaxBits parts) I found rule which fold:

```wat
   (i32.shr_s
    (i32.shl
     (i32.shr_s
      (i32.shl
       (local.get $0)
       (i32.const 24)
      )
      (i32.const 24)
     )
     (i32.const 30) ;; originally (i32.const -66)
    )
    (i32.const 24)
   )
```
into:
```wat
   (i32.shl
    (i32.shr_s
     (i32.shl
      (local.get $0)
      (i32.const 24)
     )
     (i32.const 24)
    )
    (i32.const 6)
   )
```
If comment this rule: https://github.com/WebAssembly/binaryen/blob/master/src/passes/OptimizeInstructions.cpp#L492
issue is gone and  (i32.shr_s (i32.shl ...) 30) 24) doen't fold anymore as expected.
