### ISSUE TITLE
wasm-dis does not support SIMD128?

### ISSUE THREAD

**Issue by juj** [WebAssembly/binaryen#3371]
When I try to wasm-dis a .wasm file built with `-msimd128` in Emscripten, I get

```
>wasm-dis t_shapes.wasm
[parse exception: Illegal lane index (at 0:176)]
Fatal: error in parsing wasm binary
```
Is that currently expected? `wasm-dis --help` at least does not give a hint if I should include some kind of `--enable-simd` flag or similar.

Attached t_shapes.wasm.

[t_shapes.zip](https://github.com/WebAssembly/binaryen/files/5545469/t_shapes.zip)

**Comment by kripken** [comment]
What version of binaryen is that? Running `wasm-dis t_shapes.wasm` it works for me on current trunk.

My guess is maybe your version is before some recent SIMD spec changes?

**Comment by juj** [comment]
Thanks, my Binaryen was from the 5th of November. It looks like updating to latest fixed the issue!
