### ISSUE TITLE
Another fuzz issue

### ISSUE THREAD

**Issue by MaxGraey** [WebAssembly/binaryen#3379]
`seed 15910146314477889821`

reduced wasm file: 
[w.wasm.zip](https://github.com/WebAssembly/binaryen/files/5554546/w.wasm.zip)

**Comment by MaxGraey** [comment]
Btw it will be great if `reduce.sh` automatically create `w.wat` text file at the end of reduction process

**Comment by kripken** [comment]
On which commit does this happen? I just landed a fuzzer fix on master, that might be related.

Trying that hash on latest master, it doesn't fail. Looking at the wasm, I think that might be the issue.

About the reducer, I agree that might be convenient, but also risky - if the reduced output is not tiny, it could fill the console, maybe enough to remove the user's history.

**Comment by kripken** [comment]
Oh, if you mean to just create the file but not print it, then that seems ok, but it would need to handle the case where `wasm-dis` fails on the testcase (if the bug is in `wasm-dis`).

**Comment by MaxGraey** [comment]
> Oh, if you mean to just create the file but not print it, then that seems ok

yes. Only create a file)

**Comment by MaxGraey** [comment]
Alright, it seems latest commit fix this issue
