### ISSUE TITLE
s2wasm doesn't handle conditional branches correctly

### ISSUE THREAD

**Issue by griffin2000** [WebAssembly/binaryen#338]
The code for parsing conditional branches in s2wasm.h appears to be incorrect. It expects the label then the condition:

```
curr->name = getBranchLabel(getInt());
if (hasCondition) {
  skipComma();
  curr->condition = getInput();
}

```

But that's not how they appear in the .s file that LLC spits out (as of ToT April 2016):
`	br_if   	$pop12, 0       # 0: up to label240`

Parsing code should be this:

```
if (hasCondition) {
  curr->condition = getInput();
  skipComma();
}
curr->name = getBranchLabel(getInt());
```

Code attached, I'll submit PR when I've tidied up the Windows fix discussed in #325 
[s2wasm.zip](https://github.com/WebAssembly/binaryen/files/214093/s2wasm.zip)

**Comment by kripken** [comment]
Thanks, looking forward to the PR.

**Comment by griffin2000** [comment]
Actually I was using older version of LLVM. My bad.
