### ISSUE TITLE
BinaryEn and sexpr-wasm don't agree on format of select node

### ISSUE THREAD

**Issue by griffin2000** [WebAssembly/binaryen#339]
The WAST generated by S2WASM doesn't match sexpr-wasm. Specifically the sexpr expects a select node consisting of the true case, the false case, then conditional. S2WASM generates the cond node, then true, the false node:

I fixed this in the Bison generated C code (as I don't have Bison 3.0 installed). Like this (line 2434 in src\prebuilt\wasm-bison-parser.c):

```

      (yyval.expr)->select.cond = (yyvsp[-2].expr);
      (yyval.expr)->select.true_ = (yyvsp[-1].expr);
      (yyval.expr)->select.false_ = (yyvsp[0].expr);

```

Don't know enough about system to say whether this is issue with S2WASM or sexpr-wasm. But this fix worked for me.

**Comment by kripken** [comment]
Is the problem with printing, or with processing of .s input? A testcase would help. Looking at the binaryen printing and s2wasm code, both seem ok (condition at the end).

**Comment by kripken** [comment]
cc @binji

**Comment by binji** [comment]
The condition should be last, see the spec test [here](https://github.com/WebAssembly/spec/blob/master/ml-proto/test/select.wast). sexpr-wasm runs and passes these tests, so I'm pretty sure it works.

**Comment by griffin2000** [comment]
Test case attached.  See line 13431:
```
            (select
              (i32.eq
                (get_local $$2)
                (i32.load offset=8
                  (get_local $$0)
                )
              )
              (get_local $$5)
              (get_local $$2)
            )

```
[WastTestCase.zip](https://github.com/WebAssembly/binaryen/files/214126/WastTestCase.zip)

**Comment by griffin2000** [comment]
This was generated from the attached .S file with S2WASM:
[TestSFIle.zip](https://github.com/WebAssembly/binaryen/files/214134/TestSFIle.zip)

**Comment by kripken** [comment]
Are you using an old version of s2wasm perhaps? Current s2wasm fails to parse that `.s` file.

If you're using an older s2wasm, before the spec update on the order of select operands, it would explain the error. Like sexpr-wasm that @binji noted, binaryen passes the spec tests, so it has to be correct on this, unless some weird corner case is somehow being hit.

**Comment by griffin2000** [comment]
That's probably issue #338, I am using ToT from a day or two ago with that fix.
--
Sent from myMail app for Android Monday, 11 April 2016, 06:06PM -07:00 from Alon Zakai < notifications@github.com> :

**Comment by froydnj** [comment]
Looks like the original report came from mismatched pieces of the toolchain, so this PR should be closed?

**Comment by kripken** [comment]
Yeah, this should be well-covered with tests throughout the toolchain space now.
