### ISSUE TITLE
Using stack from WASM generated by BinaryEn+sexpr-wasm causes error  in Chrome Canary

### ISSUE THREAD

**Issue by griffin2000** [WebAssembly/binaryen#340]
I am generating WASM using BinaryEn+sexpr-wasm everything works fine except when I try and access the stack. Then I get this error:
Uncaught memory access out of bounds

Test case attached. When Basic.wasm is called it crashes the first time it tries to access the stack. Any ideas what the issue could be?  Is there some setup step I am missing in Javascript? Or a CLang flag I need to use?

[StackCrash.zip](https://github.com/WebAssembly/binaryen/files/214137/StackCrash.zip)

**Comment by kripken** [comment]
Binaryen by itself doesn't set up the stack by default. When using emcc, emcc notes where the stack is stored (first allocated global location, that emcc tells s2wasm), and will write the stack location there, and then things work.

There is also a `--allocate-stack` flag that emcc doesn't use, and might help here, not sure.

**Comment by griffin2000** [comment]
@kripken  --allocate-stack 1000000 did the trick, thanks
