### ISSUE TITLE
Pass idea: Managed shadow stack with "stackify"

### ISSUE THREAD

**Issue by dcodeIO** [WebAssembly/binaryen#3406]
**Use case:**

Incremental tracing GC wants to know what's currently live on the execution stack in the middle of a program, so it can mark reachable objects before sweeping.

**Problem:**

WebAssembly's execution stack is not randomly accessible.

**Typical solution:**

Maintain a shadow stack (here: of managed pointers only).

**Introducing stackify:**

* Generator emits a write barrier when assigning to a "managed" local: `$local = __stackify(value)`. Other locals remain unmodified and do not go to the shadow stack.
* Pass evaluates `__stackify` patterns, maintains a map of stackified local indexes to stack slots.
* Iff it finds at least one pattern, amends the function
  * Prepare the stack frame when entering the function, for example `$sp = __stackifyprepare(NUM_SLOTS)`.
    Effect: Zero the new stack frame so the GC does not ever see invalid pointers, and update a global `__stackifyptr`.
  * Restore the previous stack frame when exiting the function, for example `__stackifyrestore($sp)`.
    Effect: Update the global `__stackifyptr` to the previous.
  * Amend `__stackify` patterns to also do a store to the local's respective stack slot address.

**Usage:**

When GC marks roots it can now also mark what's currently on the managed shadow stack, for example all pointers in between `__stackifyptr` and `__stackifybase`.

Somewhat similar to asyncify in nature. Might this be a fine Binaryen feature?

**Comment by kripken** [comment]
We actually have two experimental ways to do that:

1. Asyncify, as you mentioned, can do this: call out to JS, pause execution (which then writes the locals), read them, then resume later. This is implemented in emscripten by [emscripten_scan_registers](https://emscripten.org/docs/api_reference/emscripten.h.html#c.emscripten_scan_registers) and it would be easy to do it outside of emscripten too.
2. We had a [SpillPointers](https://github.com/WebAssembly/binaryen/pull/1339) pass that was removed for lack of interest and maintenance. It did something more specific, without asyncify: it would spill i32s (which can be pointers) around calls. This would be much more efficient than using asyncify, potentially. If this pass is useful I'd support restoring it.

**Comment by dcodeIO** [comment]
Interesting, thanks. Thinking about these two mechanisms, it seems these work best with a conservative GC due to touching all the locals, while AS's GC is precise and as such works best with known pointers so it can look at only what's necessary in less code. Doesn't need logic to detect what's a valid pointer for example, needs less stores to the shadow stack, maintains a smaller stack size and can omit instrumentation in functions not using managed locals. I also see advantages in dynamically maintaining the stack instead of emitting static unwind code at each location, because I expect the GC to do a few steps at each allocation for example. Allocations are sprinkled all over a program typically, and unwind code at all these places would probably make binaries significantly larger. Wdyt?

**Comment by dcodeIO** [comment]
Looking at SpillPointers, it seems that adding a "precise" mode to it would do about what I need, i.e. annotating which locals are of interest (and which are not) via `$local = __spill(value)` during codegen or so. Then supports both conservative and precise GC essentially.

**Comment by dcodeIO** [comment]
Alright, thanks! Keeping it on the AS-side for now, and if there ever is a need for it it also shouldn't be too hard to make a Binaryen pass of it :) Just lmk.

**Comment by dcodeIO** [comment]
Here's the [mechanism I ultimately came up with btw](https://github.com/AssemblyScript/assemblyscript/blob/89a2b8cca206b0bb62744ca084bb14332168e57c/src/passes/shadowstack.ts). Turned out to be not as bad as I initially expected, though we ended up not using it yet. Pinning it here in case it's useful (maybe to polyfill Wasm GC one day), or someone sees a trivial flaw in it that I'd be very interested to know about :)
