### ISSUE TITLE
Release 98 lacks Linux build

### ISSUE THREAD

**Issue by kripken** [WebAssembly/binaryen#3459]
The others are there, but oddly linux is not,

https://github.com/WebAssembly/binaryen/releases/tag/version_98

@sbc100 did we change something there?

Nothing looks obviously wrong in the scripts, and I'm not sure where I would look for a log with an error on it for a failed build...

**Comment by sbc100** [comment]
The failed build shows up here: https://github.com/WebAssembly/binaryen/actions/runs/304698147

**Comment by sbc100** [comment]
"Error: The operation was canceled."

**Comment by sbc100** [comment]
Sadly I don't see any way to "retry" the github action.   Maybe lets just try tagging 99 now?

**Comment by sbditto85** [comment]
when I try to build based off of the tag "version_98" in my linux container I get a compiler error. Not sure if that is just my setup though.

**Comment by sbc100** [comment]
Can you share the error you get?  I imagine its unrelated as our CI is green for that revision.

**Comment by kripken** [comment]
Yes, let's try tagging now to see if it works. I can do it, unless there's a reason not to atm? (roller is green, so I'm not aware of any issues)

**Comment by sbc100** [comment]
Sounds good!  Please go ahead.

**Comment by kripken** [comment]
https://github.com/WebAssembly/binaryen/releases/tag/version_99 , let's see how it goes...

**Comment by kripken** [comment]
The linux build failed again. https://github.com/WebAssembly/binaryen/pull/3475 *may* fix it. That is definitely a fix for a problem that would have that symptom. But the testcase that fails should not hit it, and does not locally, so I am not sure. But let's see after it lands.

(Is there an easy way to run the release action in a test mode for debugging?)

**Comment by sbc100** [comment]
> (Is there an easy way to run the release action in a test mode for debugging?)

Not that I know of... if you figure out a why I would be very interested to know about it.  Kind of annoying that you can re-run actions or trigger them manually :(   (I mean you can probably do those things but I have no idea how to).

**Comment by TriplEight** [comment]
I can't see the Linux bin in 99 either.

**Comment by sbc100** [comment]
Indeed it looks like the alpine builder is failing during testing for some reason: https://github.com/WebAssembly/binaryen/runs/1669944081?check_suite_focus=true

I guess we should add alpine to the normal CI avoid the difference here.

**Comment by TriplEight** [comment]
right, or release with ubuntu

**Comment by sbc100** [comment]
The release I believe was specifically designed to build with alpine to avoid all dependencies (including libc.so).   This is possible on alpine linux which uses musl but not on ubuntu which uses glibc (IIRC there are issues with building truly static binaries against modern glibc).

**Comment by kripken** [comment]
I verified release 100 has a proper Linux build thanks to @sbc100 's work - thanks!
