### ISSUE TITLE
error in validating output

### ISSUE THREAD

**Issue by VivianoRiccardo** [WebAssembly/binaryen#3463]
at the begininng of the error it says: unresolved symbol: "a random function"

`Fatal: error in validating output
ERROR:root:'/emsdk/binaryen/master_64bit_binaryen/bin/asm2wasm index.temp.asm.js --total-memory=16777216 --trap-mode=allow -O2 --mem-max=4294967296 --wasm-only --enable-threads -o index.wasm' failed`

**Comment by sbc100** [comment]
asm2wasm is no longer part of binaryen and no longer used by emscripten.   It was part of the old fastcomp toolchain which was removed in the 2.0.0 release and deprecated long before that.   Are you using a particularly old version of emscripten perhaps?   Can you try updating?

**Comment by VivianoRiccardo** [comment]
ah ok thx for the response i will update then, the fact is that i have an old version on my pc, but i ran the version on a docker image that was supposed to be updated according to the newset version, the error is shown for the version 1.38.8 (in the docker), but it doesn't show up for 1.38.48 (on my pc)
