### ISSUE TITLE
wasm-opt segfault

### ISSUE THREAD

**Issue by panstromek** [WebAssembly/binaryen#3513]
`wasm-opt`, version 90 segfaults when running it any of the wasm files in this archive: 
[wasm-opt-report.zip](https://github.com/WebAssembly/binaryen/files/5861791/wasm-opt-report.zip)

Note: All of these files are the same program, they just went through different versions or different settings of wasm-opt. I also added the problematic `wasm-opt` binary. I got this one from `wasm_pack` installation.

Steps to reproduce:
`wasm-opt opted.wasm -O2 -o output.wasm`

I tried the latest version of binaryen on Ubuntu, which is 91 and I couldn't reproduce the issue anymore, so if you think the underlying issue is fixed, feel free to close this. I just wanted to report this just in case it's something serious still hidden in the code.

**Comment by aheejin** [comment]
Have you tried the latest version? The latest version does not seem to have the problem.

**Comment by aheejin** [comment]
Oh sorry, I missed the part that you already tried the latest version and found out the problem did not exist. :)

**Comment by aheejin** [comment]
Oh sorry, I missed the part that you already tried the latest version and found out the problem did not exist. :)
