### ISSUE TITLE
HEX number conversion is wrong asm2wasm

### ISSUE THREAD

**Issue by drom** [WebAssembly/binaryen#352]
```js
function asmFunc(global, env, buffer) {
  'use asm';
  function test () {
    var res = 0;
    res = (127 + 0x7F) | 0;
    return res;
  }
}
```
```
asm2wasm test.js > test.wast
```
```lisp
(module
  (memory 256 256)
  (export "memory" memory)
  (func $test (result i32)
    (return
      (i32.add
        (i32.const 127)
        (i32.const 122)   <= ???
      )
    )
  )
)
```

Looks like:
`0x7F` -> 122
`0x7f` -> 127

**Comment by drom** [comment]
In general HEX number parser is looks broken.
`0xa 0xb 0xc 0xd 0xe 0xf` -> `10 11 12 13 14 15`
`0xA 0xB 0xC 0xD 0xE 0xF` -> `5 6 7 8 9 10`

**Comment by yurydelendik** [comment]
typo at https://github.com/WebAssembly/binaryen/blob/master/src/emscripten-optimizer/parser.h#L240

**Comment by drom** [comment]
`A <-> F` typo has some Russian charisma ;)

**Comment by drom** [comment]
@kripken I can't see this fix upstream. What should I do to get it?

**Comment by kripken** [comment]
Just pulling latest master should be enough.

**Comment by drom** [comment]
```
> git remote -v
origin  git@github.com:drom/binaryen.git (fetch)
origin  git@github.com:drom/binaryen.git (push)
upstream        https://github.com/WebAssembly/binaryen.git (fetch)
upstream        https://github.com/WebAssembly/binaryen.git (push)
> git fetch upstream
```
I still see old code.

**Comment by kripken** [comment]
Maybe you forgot to pull into your clone? Or the local copy? `fetch` isn't enough, it just gets the data into the local `upstream/master` branch. You also need to do `pull` or `merge` or something like that, into your own branches.
