### ISSUE TITLE
Two concurrent assertion failures during `BinaryenModuleOptimize()`

### ISSUE THREAD

**Issue by ImmanuelHaffner** [WebAssembly/binaryen#3532]
I try to optimize some generated Wasm code like so:

```cpp
BinaryenSetOptimizeLevel(1); // the optimization level doesn't matter; crashes on O0 and O2, too
BinaryenModuleOptimize(the_module);
```

When I run this I get two failed assertions in two threads.

The first failed assertion is ``Assertion `!resultUsed || curr->type != Type::none'`` in `Vacuum::optimize()`, where `resultUsed` is `true` and `curr` is a `nop`.  So I guess its `type` is `none`.

The second failed assertion is ``Assertion `values.size() == 1'``  in `Flow::getSingleValue()`, where `values` is a `wasm::SmallVector<wasm::Literal, 1>` with `usedFixed=0` and its `flexible` `std::vector` is empty.

These two assertions fail concurrently in separate threads.  I don't know whether they are somehow related... I tried to `dump()` the block that contains `curr` in `Vacuum::visitBlock(), but that crashes the debug session
```plain
binaryen/src/wasm-traversal.h:89: ReturnType wasm::OverriddenVisitor<wasm::PrintSExpression, void>::visit(wasm::Expression *) [SubType = wasm::PrintSExpression, ReturnType = void]: Assertion `curr' failed.
```

The error does not occur if I don't invoke `BinaryenModuleOptimize()`.  How can I debug the cause of these problems?  I am on `version_99` btw.

**Comment by kripken** [comment]
The first thing I would try is to run `BinaryenModuleValidate` to check if the IR is valid.

If it is valid, then I would save it as a binary, and then debugging can be done using the reducer and other tools, and you can paste it here.

**Comment by ImmanuelHaffner** [comment]
Oh, I didn't include it in the snippet.  The immediate lines before running optimization are
```cpp
    if (not BinaryenModuleValidate(the_module) 
        throw std::logic_error("invalid module");
```

**Comment by kripken** [comment]
The reducer is a little like c-reduce, yes, but on wasm. See https://github.com/WebAssembly/binaryen/wiki/Fuzzing#reducing and  https://kripken.github.io/blog/binaryen/2019/06/11/fuzz-reduce-productivity.html

If the module is valid, then it's either an optimizer bug, or the validator is missing something. To save the module, you can either print it as text (`BinaryenModulePrint`) or as binary (`BinaryenModuleWrite`), then investigate using the tools.

If it's an internal bug, then the text or binary printing may also hit a bug, but hopefully one of them will work... if not, then at least getting a stack trace from `BinaryenModulePrint` may be useful.

**Comment by ImmanuelHaffner** [comment]
I will try my best to produce a minimal example with the advice you have given. Thanks.

**Comment by ImmanuelHaffner** [comment]
I have tried to produce a minimal example, but using the `wasm-opt` executable on the printed module doesn't reproduce the error. Optimization succeeds.  So I can't use `wasm-reduce` to minimize the example.

Here is what I have done in particular:
1. Run my application to produce a Binaryen `wasm::Module`.
2. Print the module with `BinaryenModuleAllocateAndWriteText()`:
  ```cpp
  auto result = BinaryenModuleAllocateAndWriteText(the_module);
  std::cout << result;
  free(result);
  ```
3. Write the printed module to a file `bad.wat`.
4. Run `wasm-opt` on `bad.wat` with `-O0` (expected to work):
  ```plain
  $ bin/wasm-opt path/to/bad.wat -O0 -S -o o0.wat
  ```
  The command succeeds.
5. Run `wasm-opt` on `bad.wat` with `-O1` (expected to fail):
  ```plain
  $ bin/wasm-opt path/to/bad.wat -O1 -S -o o1.wat
  ```
  The command *succeeds unexpectedly*.

I cannot produce a minimal example because `wasm-opt` succeeds on the textual module `bad.wat` while `BinaryenModuleOptimize(the_module)` crashes with a failed assertion.

What to do?

**Comment by kripken** [comment]
Try to run your application with `BINARYEN_PASS_DEBUG=1` in the environment. That adds a lot more runtime assertions, and it runs the passes one by one. (That will also show clearly in which pass it fails.)

`BINARYEN_PASS_DEBUG=3` will also emit intermediate files after each pass, which can help as well.

**Comment by ImmanuelHaffner** [comment]
I ran *my* application (so not `wasm-opt`) with `BINARYEN_PASS_DEBUG=1`.  This is what I get:

```plain
[wasm-validator error in function run] expression seen more than once in the tree in run on 0x62d00003c400
, on 
[i32] (local.get $1)
[wasm-validator error in function run] expression seen more than once in the tree in run on 0x62d00003c480
, on 
[i32] (local.get $4)
[wasm-validator error in function run] expression seen more than once in the tree in run on 0x62d00003c450
, on 
[i32] (local.get $3)
[wasm-validator error in function run] expression seen more than once in the tree in run on 0x62d00003c450
, on 
[i32] (local.get $3)
[wasm-validator error in function run] expression seen more than once in the tree in run on 0x62d00003c440
, on 
[i32] (global.get $R_num_rows)
[wasm-validator error in function run] expression seen more than once in the tree in run on 0x62d00003c460
, on 
[i32] (i32.lt_u
 [i32] (local.get $3)
 [i32] (global.get $R_num_rows)
)
[wasm-validator error in function run] expression seen more than once in the tree in run on 0x62d00003c400
, on 
[i32] (local.get $1)
[wasm-validator error in function run] expression seen more than once in the tree in run on 0x62d00003c40c
, on 
[i32] (local.get $2)
[wasm-validator error in function run] expression seen more than once in the tree in run on 0x62d00003c400
, on 
[i32] (local.get $1)
```

It seems I misunterstand something about Binaryen... I cannot reuse the exact *same* expression but must create an *equal* copy to place it somewhere else in the code?

**Comment by ImmanuelHaffner** [comment]
Turns out there is a [`BinaryenExpressionCopy()`](https://github.com/WebAssembly/binaryen/blob/3da8b08ecd57f5662bebc69ea73bf59e1928341e/src/binaryen-c.h#L861) to create *deep* copies of an expression.  I was on `version_91` that did not have this yet, so i upgraded to `version_99`. Patching my code to *create copies rather than reusing an expression* seems to do the trick.  First test cases are passing w/o problems ;)

**Comment by kripken** [comment]
Good, I'm glad that option helped figure it out!

Yes, Binaryen's IR does not allow the same node to be referred to more than once. The IR is a simple tree, not a DAG. That makes various operations simpler and more efficient.

**Comment by ImmanuelHaffner** [comment]
OK got it. I will rewrite my code gen and see whether that fixes everything. Still I am wondering, shouldn't the validation of the module catch multiple uses of the same expression? I mean, if the module is valid, I expect optimization to run with our errors...

**Comment by kripken** [comment]
It is pretty expensive to check for multiple uses, which is why it is gated on that env var, which enables the heavy things. But maybe we should optimize it or enable it regardless...

**Comment by ImmanuelHaffner** [comment]
I haven't looked into Binaryen's internals.  A simple solution that comes to my mind is having each expression point to its user (if any).  Then, when using the expression again, a debug build could check whether the expression is already in use and abort or throw.  A respective flag/field to track whether an expression is in use can be present only in the debug build to save space in the release build.  This design would avoid multiple uses by construction and is fairly simple to check.  Even further, a user of Binaryen would be pointed precisely to the point where the expression is used again, rather than seeing the error only at the very end, when validation runs.  (I am currently in this situation, where I have an invalid module and have to figure out the places where I create multiple uses of the same expression. Quite tedious.)

**Comment by kripken** [comment]
@ImmanuelHaffner 

Interesting idea. It's a little tricky since we don't have hooks for every time an expression is transplanted, though.

However, the validation code that found the problem here could be improved to print out which node it was, and which parent, by building a map with the parent information as in your idea. A PR would be great if you or someone else is interested to add that.

**Comment by ImmanuelHaffner** [comment]
I am currently under time pressure as I am working towards a publication and the deadline is soon.  Once I get the paper submitted, I think I can get some free time to give this a look.

BTW -- and maybe off-topic -- I only looked at the C API so far, as I find it very self explanatory.  Is there like a *stable* C++ API?  For me, that would be kinda interesting, as I care a lot about code generation performance and the C++ API could help if functions/methods are defined in the header (so the compiler can inline and optimize further).  Besides, maybe the C++ API would be the right place to start tinkering with catching multiple uses of an expression. What do you think?

**Comment by kripken** [comment]
I think that the C++ API is not stable, sort of like LLVM's C++ API isn't. We sometimes do large refactorings to make things better, and stable APIs would make that difficult.

The C API is intentionally more stable.
