### ISSUE TITLE
wasm-opt fails when `-o` is omitted, instead of writing to stdout as fallback

### ISSUE THREAD

**Issue by cmichi** [WebAssembly/binaryen#3579]
The `wasm-opt` cli arg `-o` is specified as `Output file (stdout if not specified)"`.

The output to `stdout` does not work though, if `-o` is omitted `wasm-opt` just fails with `warning: no output file specified, not emitting output` (https://github.com/WebAssembly/binaryen/blob/2488b523216600b4de2fe1e33ad695b337f8b9f8/src/tools/wasm-opt.cpp#L374).

**Comment by pipcet** [comment]
Worse, I think, is that it fails only after the optimization has run, which can take a long time.

**Comment by martianboy** [comment]
@cmichi The way it works right now, it requires a `-o` to emit an output, or specify a pass like `--print` that prints directly to stdout. In your case, I believe you'd need to specify STDOUT explicitly with `-o -`.

**Comment by cmichi** [comment]
@martianboy Thanks! It works with `-o -`.
