### ISSUE TITLE
Optimized file size regression for `wasm-opt`

### ISSUE THREAD

**Issue by cmichi** [WebAssembly/binaryen#3587]
I run into a regression when executing ` bin/wasm-opt /tmp/flipper.wasm -O3 -o /tmp/flipper-optimized.wasm`:

Up until the commit https://github.com/WebAssembly/binaryen/commit/ab68c1b2ffd034f8c30d2a4820c5c708491679cb this resulted in a file size of ~2.5k. From https://github.com/WebAssembly/binaryen/commit/cdc2d2c006bc0406c93509ed0d7a2dfbb6f51ea5 on it results in the optimized file size being ~18.9k (the original file size is ~19.1k). This persists up until the current binaryen `HEAD`.

This is the file for which I notice the regression: [flipper.wasm](http://share.creal.de/flipper.wasm).

I've experimented a bit with other optimization flags in `HEAD`, but can't seem to bring it down anymore.

I'm a bit skeptical if I am overlooking something here, since it seems this would have been noticed earlier (the commits for which I observe this behavior are from the beginning of November). Did cli behavior maybe change for the optimization args or anything like that?

**Comment by martianboy** [comment]
@cmichi Since the memory in your module is imported, wasm-opt needs to be told that the memory is initialized to zeros, otherwise it won't run the memory-packing prepass. Using `--zero-filled-memory` results in a ~2.7k file.

     bin/wasm-opt /tmp/flipper.wasm --memory-packing --zero-filled-memory -o /tmp/flipper-optimized.wasm

**Comment by cmichi** [comment]
@martianboy Great, thanks!
