### ISSUE TITLE
Indirect function calls that occur as a top-level expression cause a crash

### ISSUE THREAD

**Issue by AndrewScheidecker** [WebAssembly/binaryen#36]
The problem occurs [here](https://github.com/WebAssembly/binaryen/blob/master/src/asm2wasm.h#L1210):
`ret->fullType = getFunctionType(astStackHelper.getParent(), ret->operands);`

`astStackHelper.getParent()` is null for a top-level expression, which causes `getFunctionType` to crash.

Instead of calling `astStackHelper.getParent()`, shouldn't it try to determine the return type of the functions in the specified function table?

**Comment by kripken** [comment]
Fixed, thanks for filing.

The lack of a parent implies a void return type, since asm.js forces a coercion if there is a return type (even if discarded).
