### ISSUE TITLE
asm2wasm clang error: argument unused [...] '-pthread'

### ISSUE THREAD

**Issue by data-ux** [WebAssembly/binaryen#360]
On 4dfeb1c, when trying to `make`, I get the following error on OS X 10.11.4:

```
[ 41%] Linking CXX executable bin/asm2wasm
clang: error: argument unused during compilation: '-pthread'
make[2]: *** [bin/asm2wasm] Error 1
make[1]: *** [CMakeFiles/asm2wasm.dir/all] Error 2
make: *** [all] Error 2
```

Previous commit, f2905f9 builds ok.

**Comment by kripken** [comment]
Hmm, `-pthread` is a necessary flag on gcc and clang on linux at least. Maybe not on OS X? Does it need a different flag for a multithreaded program?

**Comment by adam852** [comment]
Try to rem pthread section in CMakeLists.txt. It works for on my OS X 10.11.4

ELSE()
  ADD_COMPILE_FLAG("-std=c++11")
  ADD_COMPILE_FLAG("-msse2")
  ADD_COMPILE_FLAG("-mfpmath=sse")
  ADD_COMPILE_FLAG("-Wall")
  ADD_COMPILE_FLAG("-Werror")
  ADD_COMPILE_FLAG("-Wextra")
  ADD_COMPILE_FLAG("-Wno-unused-parameter")
  ADD_COMPILE_FLAG("-fno-omit-frame-pointer")
  #ADD_LINK_FLAG("-pthread")

**Comment by data-ux** [comment]
Yes removing that line works for me too. [According to this](http://stackoverflow.com/questions/17841140/os-x-clang-pthread), clang needs the -pthread flag when compiling, but not when linking. Maybe the linking would work on Linux, too, without the flag?

**Comment by kripken** [comment]
Thanks, looks like that's correct, it works for me locally on linux. Added a commit to the thread-fixes PR #353.

**Comment by kripken** [comment]
Should be fixed by that PR.

**Comment by yurydelendik** [comment]
Still an issue for me at 5494c531db301

**Comment by yurydelendik** [comment]
Probably this one is related http://public.kitware.com/Bug/view.php?id=12652 : "We have always had to pass compilation flags to the compiler front-end when using it for linking. It matters at least for C++ because some compilers actually do real compilation at link time to do template instantiation (pre-linker)..."

**Comment by yurydelendik** [comment]
Can we use `ADD_COMPILE_FLAG("-Qunused-arguments")` ?

**Comment by kripken** [comment]
Would that make it ignore unused arguments? Seems risky, we might miss other things later.

Unless we have no other solution for this issue here, but it should be resolved now that on master we add the flag at compile and not link time?

**Comment by adam852** [comment]
CMAKE_CXX_LINK_EXECUTABLE is a variable which contain linking cmd.
Default value is:
<CMAKE_CXX_COMPILER>  <FLAGS> <CMAKE_CXX_LINK_FLAGS> <LINK_FLAGS> <OBJECTS>  -o <TARGET> <LINK_LIBRARIES>

My proposition for separating flags for compiling and linking is something like this:
  SET(CMAKE_CXX_LINK_EXECUTABLE "<CMAKE_CXX_COMPILER> <LINK_FLAGS> <OBJECTS>  -o <TARGET> <LINK_LIBRARIES>")
  ADD_COMPILE_FLAG("-std=c++11")
  ADD_COMPILE_FLAG("-msse2")
  ADD_COMPILE_FLAG("-mfpmath=sse")
  ADD_COMPILE_FLAG("-Wall")
  ADD_COMPILE_FLAG("-Werror")
  ADD_COMPILE_FLAG("-Wextra")
  ADD_COMPILE_FLAG("-Wno-unused-parameter")
  ADD_COMPILE_FLAG("-fno-omit-frame-pointer")
  ADD_COMPILE_FLAG("-pthread")

**Comment by data-ux** [comment]
Error persists with 31dd39a

**Comment by adam852** [comment]
"Do not use -pthread on Darwin
It's not needed because Darwin has POSIX Threads in libc"

 IF(NOT ${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
    ADD_COMPILE_FLAG("-pthread")
  ENDIF()

**Comment by kripken** [comment]
Interesting, thanks @adam852. Maybe it would be safer to do the opposite, add the flag only on linux? I don't know cmake that much, but probably there's a way to do that?

**Comment by jfbastien** [comment]
Look at what LLVM does to handle Windows and pthread-in-libc:
https://github.com/llvm-mirror/llvm/blob/master/cmake/config-ix.cmake#L93

**Comment by adam852** [comment]
I think, add the flag for all without OSX. I did two tests without the "pthread" flag on OSX (you can see effects below). 



bash-3.2$ cmake .
-- The CXX compiler identification is AppleClang 7.3.0.7030029
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- No build type selected, default to Release
-- Building with -std=c++11
-- Building with -msse2
-- Building with -mfpmath=sse
-- Building with -Wall
-- Building with -Werror
-- Building with -Wextra
-- Building with -Wno-unused-parameter
-- Building with -fno-omit-frame-pointer
-- Building with -O2
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/adam/test_binaryan/binaryen
bash-3.2$ make
Scanning dependencies of target support
[  1%] Building CXX object CMakeFiles/support.dir/src/support/bits.cpp.o
[  3%] Building CXX object CMakeFiles/support.dir/src/support/colors.cpp.o
[  5%] Building CXX object CMakeFiles/support.dir/src/support/command-line.cpp.o
[  7%] Building CXX object CMakeFiles/support.dir/src/support/file.cpp.o
[  9%] Building CXX object CMakeFiles/support.dir/src/support/safe_integer.cpp.o
[ 11%] Building CXX object CMakeFiles/support.dir/src/support/threads.cpp.o
[ 13%] Linking CXX static library lib/libsupport.a
[ 13%] Built target support
Scanning dependencies of target wasm-as
[ 15%] Building CXX object CMakeFiles/wasm-as.dir/src/wasm-as.cpp.o
[ 16%] Linking CXX executable bin/wasm-as
[ 16%] Built target wasm-as
Scanning dependencies of target binaryen-shell
[ 18%] Building CXX object CMakeFiles/binaryen-shell.dir/src/binaryen-shell.cpp.o
[ 20%] Building CXX object CMakeFiles/binaryen-shell.dir/src/pass.cpp.o
[ 22%] Building CXX object CMakeFiles/binaryen-shell.dir/src/passes/LowerIfElse.cpp.o
[ 24%] Building CXX object CMakeFiles/binaryen-shell.dir/src/passes/MergeBlocks.cpp.o
[ 26%] Building CXX object CMakeFiles/binaryen-shell.dir/src/passes/NameManager.cpp.o
[ 28%] Building CXX object CMakeFiles/binaryen-shell.dir/src/passes/OptimizeInstructions.cpp.o
[ 30%] Building CXX object CMakeFiles/binaryen-shell.dir/src/passes/PostEmscripten.cpp.o
[ 32%] Building CXX object CMakeFiles/binaryen-shell.dir/src/passes/Print.cpp.o
[ 33%] Building CXX object CMakeFiles/binaryen-shell.dir/src/passes/RemoveImports.cpp.o
[ 35%] Building CXX object CMakeFiles/binaryen-shell.dir/src/passes/RemoveUnusedBrs.cpp.o
[ 37%] Building CXX object CMakeFiles/binaryen-shell.dir/src/passes/RemoveUnusedNames.cpp.o
[ 39%] Building CXX object CMakeFiles/binaryen-shell.dir/src/passes/SimplifyLocals.cpp.o
[ 41%] Building CXX object CMakeFiles/binaryen-shell.dir/src/passes/ReorderLocals.cpp.o
[ 43%] Building CXX object CMakeFiles/binaryen-shell.dir/src/passes/Vacuum.cpp.o
[ 45%] Building CXX object CMakeFiles/binaryen-shell.dir/src/passes/Metrics.cpp.o
[ 47%] Linking CXX executable bin/binaryen-shell
[ 47%] Built target binaryen-shell
Scanning dependencies of target wasm-dis
[ 49%] Building CXX object CMakeFiles/wasm-dis.dir/src/pass.cpp.o
[ 50%] Building CXX object CMakeFiles/wasm-dis.dir/src/passes/Print.cpp.o
[ 52%] Building CXX object CMakeFiles/wasm-dis.dir/src/wasm-dis.cpp.o
[ 54%] Linking CXX executable bin/wasm-dis
[ 54%] Built target wasm-dis
Scanning dependencies of target s2wasm
[ 56%] Building CXX object CMakeFiles/s2wasm.dir/src/pass.cpp.o
[ 58%] Building CXX object CMakeFiles/s2wasm.dir/src/passes/Print.cpp.o
[ 60%] Building CXX object CMakeFiles/s2wasm.dir/src/s2wasm-main.cpp.o
[ 62%] Linking CXX executable bin/s2wasm
[ 62%] Built target s2wasm
Scanning dependencies of target wasm2asm
[ 64%] Building CXX object CMakeFiles/wasm2asm.dir/src/wasm2asm-main.cpp.o
[ 66%] Building CXX object CMakeFiles/wasm2asm.dir/src/emscripten-optimizer/parser.cpp.o
[ 67%] Building CXX object CMakeFiles/wasm2asm.dir/src/emscripten-optimizer/simple_ast.cpp.o
[ 69%] Building CXX object CMakeFiles/wasm2asm.dir/src/emscripten-optimizer/optimizer-shared.cpp.o
[ 71%] Linking CXX executable bin/wasm2asm
[ 71%] Built target wasm2asm
Scanning dependencies of target asm2wasm
[ 73%] Building CXX object CMakeFiles/asm2wasm.dir/src/asm2wasm-main.cpp.o
[ 75%] Building CXX object CMakeFiles/asm2wasm.dir/src/pass.cpp.o
[ 77%] Building CXX object CMakeFiles/asm2wasm.dir/src/passes/MergeBlocks.cpp.o
[ 79%] Building CXX object CMakeFiles/asm2wasm.dir/src/passes/OptimizeInstructions.cpp.o
[ 81%] Building CXX object CMakeFiles/asm2wasm.dir/src/passes/PostEmscripten.cpp.o
[ 83%] Building CXX object CMakeFiles/asm2wasm.dir/src/passes/Print.cpp.o
[ 84%] Building CXX object CMakeFiles/asm2wasm.dir/src/passes/RemoveUnusedBrs.cpp.o
[ 86%] Building CXX object CMakeFiles/asm2wasm.dir/src/passes/RemoveUnusedNames.cpp.o
[ 88%] Building CXX object CMakeFiles/asm2wasm.dir/src/passes/SimplifyLocals.cpp.o
[ 90%] Building CXX object CMakeFiles/asm2wasm.dir/src/passes/ReorderLocals.cpp.o
[ 92%] Building CXX object CMakeFiles/asm2wasm.dir/src/passes/Vacuum.cpp.o
[ 94%] Building CXX object CMakeFiles/asm2wasm.dir/src/emscripten-optimizer/parser.cpp.o
[ 96%] Building CXX object CMakeFiles/asm2wasm.dir/src/emscripten-optimizer/simple_ast.cpp.o
[ 98%] Building CXX object CMakeFiles/asm2wasm.dir/src/emscripten-optimizer/optimizer-shared.cpp.o
[100%] Linking CXX executable bin/asm2wasm
[100%] Built target asm2wasm
bash-3.2$ make clean
bash-3.2$ rm -R CMakeFiles
bash-3.2$ rm CMakeCache.txt
bash-3.2$ CXX=g++-mp-4.9 cmake .
-- The CXX compiler identification is GNU 4.9.3
-- Checking whether CXX compiler has -isysroot
-- Checking whether CXX compiler has -isysroot - yes
-- Checking whether CXX compiler supports OSX deployment target flag
-- Checking whether CXX compiler supports OSX deployment target flag - yes
-- Check for working CXX compiler: /opt/local/bin/g++-mp-4.9
-- Check for working CXX compiler: /opt/local/bin/g++-mp-4.9 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- No build type selected, default to Release
-- Building with -std=c++11
-- Building with -msse2
-- Building with -mfpmath=sse
-- Building with -Wall
-- Building with -Werror
-- Building with -Wextra
-- Building with -Wno-unused-parameter
-- Building with -fno-omit-frame-pointer
-- Building with -O2
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/adam/test_binaryan/binaryen
bash-3.2$ make 
Scanning dependencies of target support
[  1%] Building CXX object CMakeFiles/support.dir/src/support/bits.cpp.o
[  3%] Building CXX object CMakeFiles/support.dir/src/support/colors.cpp.o
[  5%] Building CXX object CMakeFiles/support.dir/src/support/command-line.cpp.o
[  7%] Building CXX object CMakeFiles/support.dir/src/support/file.cpp.o
[  9%] Building CXX object CMakeFiles/support.dir/src/support/safe_integer.cpp.o
[ 11%] Building CXX object CMakeFiles/support.dir/src/support/threads.cpp.o
[ 13%] Linking CXX static library lib/libsupport.a
[ 13%] Built target support
Scanning dependencies of target wasm-as
[ 15%] Building CXX object CMakeFiles/wasm-as.dir/src/wasm-as.cpp.o
[ 16%] Linking CXX executable bin/wasm-as
[ 16%] Built target wasm-as
Scanning dependencies of target binaryen-shell
[ 18%] Building CXX object CMakeFiles/binaryen-shell.dir/src/binaryen-shell.cpp.o
[ 20%] Building CXX object CMakeFiles/binaryen-shell.dir/src/pass.cpp.o
[ 22%] Building CXX object CMakeFiles/binaryen-shell.dir/src/passes/LowerIfElse.cpp.o
[ 24%] Building CXX object CMakeFiles/binaryen-shell.dir/src/passes/MergeBlocks.cpp.o
[ 26%] Building CXX object CMakeFiles/binaryen-shell.dir/src/passes/NameManager.cpp.o
[ 28%] Building CXX object CMakeFiles/binaryen-shell.dir/src/passes/OptimizeInstructions.cpp.o
[ 30%] Building CXX object CMakeFiles/binaryen-shell.dir/src/passes/PostEmscripten.cpp.o
[ 32%] Building CXX object CMakeFiles/binaryen-shell.dir/src/passes/Print.cpp.o
[ 33%] Building CXX object CMakeFiles/binaryen-shell.dir/src/passes/RemoveImports.cpp.o
[ 35%] Building CXX object CMakeFiles/binaryen-shell.dir/src/passes/RemoveUnusedBrs.cpp.o
[ 37%] Building CXX object CMakeFiles/binaryen-shell.dir/src/passes/RemoveUnusedNames.cpp.o
[ 39%] Building CXX object CMakeFiles/binaryen-shell.dir/src/passes/SimplifyLocals.cpp.o
[ 41%] Building CXX object CMakeFiles/binaryen-shell.dir/src/passes/ReorderLocals.cpp.o
[ 43%] Building CXX object CMakeFiles/binaryen-shell.dir/src/passes/Vacuum.cpp.o
[ 45%] Building CXX object CMakeFiles/binaryen-shell.dir/src/passes/Metrics.cpp.o
[ 47%] Linking CXX executable bin/binaryen-shell
[ 47%] Built target binaryen-shell
Scanning dependencies of target wasm-dis
[ 49%] Building CXX object CMakeFiles/wasm-dis.dir/src/pass.cpp.o
[ 50%] Building CXX object CMakeFiles/wasm-dis.dir/src/passes/Print.cpp.o
[ 52%] Building CXX object CMakeFiles/wasm-dis.dir/src/wasm-dis.cpp.o
[ 54%] Linking CXX executable bin/wasm-dis
[ 54%] Built target wasm-dis
Scanning dependencies of target s2wasm
[ 56%] Building CXX object CMakeFiles/s2wasm.dir/src/pass.cpp.o
[ 58%] Building CXX object CMakeFiles/s2wasm.dir/src/passes/Print.cpp.o
[ 60%] Building CXX object CMakeFiles/s2wasm.dir/src/s2wasm-main.cpp.o
[ 62%] Linking CXX executable bin/s2wasm
[ 62%] Built target s2wasm
Scanning dependencies of target wasm2asm
[ 64%] Building CXX object CMakeFiles/wasm2asm.dir/src/wasm2asm-main.cpp.o
[ 66%] Building CXX object CMakeFiles/wasm2asm.dir/src/emscripten-optimizer/parser.cpp.o
[ 67%] Building CXX object CMakeFiles/wasm2asm.dir/src/emscripten-optimizer/simple_ast.cpp.o
[ 69%] Building CXX object CMakeFiles/wasm2asm.dir/src/emscripten-optimizer/optimizer-shared.cpp.o
[ 71%] Linking CXX executable bin/wasm2asm
[ 71%] Built target wasm2asm
Scanning dependencies of target asm2wasm
[ 73%] Building CXX object CMakeFiles/asm2wasm.dir/src/asm2wasm-main.cpp.o
[ 75%] Building CXX object CMakeFiles/asm2wasm.dir/src/pass.cpp.o
[ 77%] Building CXX object CMakeFiles/asm2wasm.dir/src/passes/MergeBlocks.cpp.o
[ 79%] Building CXX object CMakeFiles/asm2wasm.dir/src/passes/OptimizeInstructions.cpp.o
[ 81%] Building CXX object CMakeFiles/asm2wasm.dir/src/passes/PostEmscripten.cpp.o
[ 83%] Building CXX object CMakeFiles/asm2wasm.dir/src/passes/Print.cpp.o
[ 84%] Building CXX object CMakeFiles/asm2wasm.dir/src/passes/RemoveUnusedBrs.cpp.o
[ 86%] Building CXX object CMakeFiles/asm2wasm.dir/src/passes/RemoveUnusedNames.cpp.o
[ 88%] Building CXX object CMakeFiles/asm2wasm.dir/src/passes/SimplifyLocals.cpp.o
[ 90%] Building CXX object CMakeFiles/asm2wasm.dir/src/passes/ReorderLocals.cpp.o
[ 92%] Building CXX object CMakeFiles/asm2wasm.dir/src/passes/Vacuum.cpp.o
[ 94%] Building CXX object CMakeFiles/asm2wasm.dir/src/emscripten-optimizer/parser.cpp.o
[ 96%] Building CXX object CMakeFiles/asm2wasm.dir/src/emscripten-optimizer/simple_ast.cpp.o
[ 98%] Building CXX object CMakeFiles/asm2wasm.dir/src/emscripten-optimizer/optimizer-shared.cpp.o
[100%] Linking CXX executable bin/asm2wasm
[100%] Built target asm2wasm
bash-3.2$

**Comment by kripken** [comment]
@adam852: ok, thanks, that sounds good. Do you want to open a PR with that?

@jfbastien: it does sound good to do what llvm does, but seems like we'd need to import a lot of cmake from there, which makes me worry...

**Comment by jfbastien** [comment]
> @jfbastien: it does sound good to do what llvm does, but seems like we'd need to import a lot of cmake from there, which makes me worry...

Probably, but we know it works right on multiple platforms, so we won't need to keep fixing cmake :-)

**Comment by adam852** [comment]
Ok, I found a better way for setting "-pthread" flag. I've made PR.

**Comment by floooh** [comment]
Btw, I also stumbled over this on OSX after updating to the latest Xcode 7.3 beta command line tools (it worked with older clangs). I fixed it like this (still prints the warning, but doesn't stop the build):

```cmake
  IF("${CMAKE_CXX_COMPILER_ID}" MATCHES "Clang")
    ADD_COMPILE_FLAG("-Wno-error=unused-command-line-argument")
  ENDIF()
```

**Comment by floooh** [comment]
PS: but I think @adam852's PR is the cleaner solution...
