### ISSUE TITLE
API function name `BinaryenI31GetIsSigned` is not consistent

### ISSUE THREAD

**Issue by pmatos** [WebAssembly/binaryen#3613]
The API function name `BinaryenI31GetIsSigned` is not consistent and should probably be instead `BinaryenI31GetGetIsSigned`.

https://github.com/WebAssembly/binaryen/blob/d1d631d5f354ef3470c15003118d1c750b557fe2/src/binaryen-c.h#L1901

At this point I am not sure what can be done since it's part of the API header and I am not sure of the policies to change this. Either 

1. it's left as it is, 
2. we deprecate this function and add the correct name for it, 
3. or we just change it. 

The first option is not great due to consistency of the API naming. The last will break those relying on the new name. I will propose a PR for alternative 2. However, if the maintainers prefer another alternative altogether, feel free to close the PR.

**Comment by tlively** [comment]
I think our convention is to skip the `Get` when there is already and `Is`. For example, `BinaryenCallIsReturn` and `BinaryenLocalSetIsTee` work that way.

In general, though, we're somewhat cavalier about changing the C API (when there are benefits, not gratuitously) and generally just note changes in the change log. No one has complained too much about that so far. We would certainly like to present a stable API, but usually our competing desire to not have any tech debt in the API wins out.
