### ISSUE TITLE
test/try-delegate.wasm does not roundtrip through text

### ISSUE THREAD

**Issue by kripken** [WebAssembly/binaryen#3629]
```
$ bin/wasm-dis test/./try-delegate.wasm -o a.wat
$ bin/wasm-as a.wat
[parse exception: invalid catch block (at 15:3)]
```
The reducer reduces the issue to
```wat
(module
 (type $none_=>_none (func))
 (event $event$0 (attr 0) (param))
 (func $0
  (try $label$3
   (do
    (nop)
   )
   (catch $event$0
   )
  )
 )
)
```
The `catch` does not have 3 elements, and has no pop. Is that valid?

cc @aheejin

**Comment by aheejin** [comment]
Yes it is OK not to have no pop when the event type is none, as in the example:
```wasm
 (type $none_=>_none (func))
 (event $event$0 (attr 0) (param))
```
The code that assumed catch body's size should be at least 3 is a bug. Will fix it. Thanks for reporting!
