### ISSUE TITLE
Error - binaryen is outdated 

### ISSUE THREAD

**Issue by PolkaLink** [WebAssembly/binaryen#3651]
Hi, 

I've checked the version of my binaryen and its 91. I want to update it to a version >98 

I'm on Windows 10 but I'm using wsl Ubuntu

I dont know how to do this if I could get help please to update my binaryen  

Thank you

**Comment by tlively** [comment]
On the main GitHub page for the project there is a link on the right to the latest release. Here's the page for the lastest release at time of writing: https://github.com/WebAssembly/binaryen/releases/tag/version_100.

**Comment by PolkaLink** [comment]
This is how i fixed the binaryen issue (notice my npm file was missing)

$ sudo curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
$`sudo apt install nodejs`
$npm install -g binaryen --force

This gave me updated version of nodejs v12.16.3
and npm which was missing on ubuntu 6.14.4
and the Binaryen is now updated to Version 100

Then I ran

cargo install --force cargo-contract
cargo +nightly contract build
and all issues was fixed and the smart contract compiled
