### ISSUE TITLE
The compiler-rt problem

### ISSUE THREAD

**Issue by dschuff** [WebAssembly/binaryen#370]
Compiler-rt is a library containing functions, to which the compiler may emit calls during code generation. It includes a variety of functionality, but most notably functions for operations on types which the compiler can't generate directly (for example long doubles on wasm or 64-bit integers on asm.js). `memcpy` and friends are also in this category (calls to them can be emitted during codegen) but they are not actually in the compiler-rt library. Unlike an ordinary library (where dependencies on that library can be seen at bitcode link time), dependencies on compiler-rt functions do not appear until after final code generation.

In a traditional system, linking happens after all code generation is done, so compiler-rt can just be an ordinary native library included at the end of the link. Even when using LTO (in which case the user code is linked as bitcode) there is a native link step, which includes the native user code, native system libraries, and compiler-rt.

All of asm.js, PNaCl, and (currently) WebAssembly all use bitcode linking and so have the problem that the dependencies on compiler-rt are not visible at bitcode link time. PNaCl has a second (native) link step that happens on the client and includes some libraries provided by the browser as well as compiler-rt. 
That works well but it's not an option for asm.js or wasm, where we consider the "final" format to be JS or wasm, and need to ship everything to the client. For asm.js, emscripten effectively has a second native (i.e. JS) "link" step where it copies asm.js implementations of `__muldi3` and other int64 functions into the asm module when needed.

For WebAssembly in the long term, we want to have a model that looks more like the traditional one, in which linking can happen over the "native" (i.e. binary wasm) code after codegen. In that case compiler-rt can look just as it does for native platforms today. (We also do want to support LTO but there can still be a native link step as there is for LTO on native platforms). In the near term however, we are still using bitcode linking as implemented by emscripten. So we need to solve this problem. I see a couple of possibilities.

* The simplest thing would be to always link everything (where "everything" basically means the long double functions today) in. That's a bad idea because it would cause bloat (although it's not quite as bad an idea as it should be, because any use of `printf` today would cause them to be included anyway). But in any case it doesn't scale past just the long double functions.
* Do something like what emscripten does for asm.js and implement some kind of special custom second-stage link (which would be on the generated .s or .wast code). This would make emscripten's linking even more complex than it already is, and not fit with the goal of making wasm easy (or even possible) to use independently of emscripten and the web.
* Do a native link-like step in a binaryen tool such as s2wasm. s2wasm really has 2 jobs; parsing LLVM's .s format into wasm AST, and doing the relocation/layout portion of the linker's job. As part of the latter job it also can allocate the user stack (and the stack pointer) and `__dso_handle` (which is usually part of a toolchain runtime file such as `crtbeginT.o`). It would probably be straightforward to implement a (very!) simple "linking"-like step to pull already-generated implementations of compiler-rt functions (either in .s or .wast format) into the module.

I propose we do the latter. In fact I'm thinking of splitting the existing linking functionality (e.g. `fix()`) out of `S2wasmBuilder` and into its own class anyway. This would solve the problem, re-use code that we already have that is related, and do so in a way that is most like the solution we want in the long term,

**Comment by kripken** [comment]
Your proposal sounds good to me.

In previous discussion in #292, I ended up pinning the memcpy/memset/memmove methods. After your approach is implemented, we could remove that line in emcc.py.

> Even when using LTO (in which case the user code is linked as bitcode) there is a native link step, which includes the native user code, native system libraries, and compiler-rt.

Can't someone doing native development statically link in libc and other system libraries and LTO that? I mean, it can break, but this shows the problem is more general than us, I think? It's just that no one thinks to do it natively? Anyhow, just an academic point I guess.

**Comment by dschuff** [comment]
wrt libc in LTO, yes, someone could do that (if you take care to disable some libcall optimizations, as we do in PNaCl). And I actually seem to recall someone in LLVM recently improving LTO so that that could be more easily done. It's more or less orthogonal to the problem of calls materializing in the backend though.

**Comment by dschuff** [comment]
`__cxa_pure_virtual` is in this category too; the compiler puts its address in vtables, but there are no references to it from user code. However it comes from libcxxabi rather than compiler-rt, so its handling should be more like whatever exactly we decide to do for `memcpy` and friends.

**Comment by dschuff** [comment]
With https://github.com/kripken/emscripten/pull/4294 landed I'm going to go ahead and close this. There will be more changes to the linking functionality but the blocking problem and proposal is done.

**Comment by yurydelendik** [comment]
FWIW `__cxa_pure_virtual` how affects wasm-compiler-rt compilation (when WASM_BACKEND is used)
