### ISSUE TITLE
Support non-funcref tables

### ISSUE THREAD

**Issue by MrHate** [WebAssembly/binaryen#3712]
With the table number limit removal by #3517 and the incoming reference-type standardization, how about support non-funcref tables? I have recently encountered some Wasm tools generating externref tables unable to be handled by binaryen.

**Comment by martianboy** [comment]
I've been working on adding types to tables and element segments. Right now I'm just waiting for #3666 to be merged before I submit the new PR. :)

**Comment by MrHate** [comment]
> I've been working on adding types to tables and element segments. Right now I'm just waiting for #3666 to be merged before I submit the new PR. :)

That shall be very helpful, thanks very much!
