### ISSUE TITLE
Compiling binaryen to Wasm (no JS)

### ISSUE THREAD

**Issue by syrusakbary** [WebAssembly/binaryen#3722]
There are some projects depending on binaryen that are researching on using it from a full Wasm context (no JS).
One of example of this is the AssemblyScript project, which right now depends on binaryen to create the `.wasm` output files. They are currently using binaryen compiled to Wasm+JS using [Binaryen / Emscripten bindings](https://github.com/AssemblyScript/binaryen.js#readme).

However, binaryen right now uses C++ exceptions, which makes it impossible to fully use it from a Wasm context (no JS), since C++ exceptions are not natively supported in Wasm (yet).

Would it be possible to avoid depending on C++ exceptions for the time being? I'm thinking on two ways to do it:
* Conditional compilation (C++ exceptions would be used by default, but can be disabled via a flag)
* Change the codebase to return a tuple (result, error) rather than relying on C++ exceptions

Let me know if any of this paths could make sense!

**Comment by MaxGraey** [comment]
Yeah, we already discussed about this here: https://github.com/WebAssembly/binaryen/issues/2917

**Comment by kripken** [comment]
Yes, let's close this in favor of the original issue, and continue discussion there.
