### ISSUE TITLE
emscripten ci cache does not have webgl libs

### ISSUE THREAD

**Issue by sps-gold** [WebAssembly/binaryen#3742]
If we add tests on emscripten ci with flags like:
    self.emcc_args += ['-sUSE_WEBGL2']
    self.emcc_args += ['-sUSE_GLFW=3']
    self.emcc_args += ['-sFULL_ES3=1']

ci fails the test with exception like:
FROZEN_CACHE is set, but cache file is missing: sysroot/lib/wasm32-emscripten/lto-pic/libgl-webgl2-full_es3.a

test case: 
https://github.com/emscripten-core/emscripten/pull/13696

**Comment by kripken** [comment]
I think this may have been filed in the wrong repo? Should be emscripten.

I think this is working as intended, however. There are a lot of possible combinations of the GL libraries, and emscripten does not ship with them all by default. cc @sbc100

**Comment by sps-gold** [comment]
mistakenly logged under binaryen, moved to emscripten https://github.com/emscripten-core/emscripten/issues/13795
closing here
