### ISSUE TITLE
wasm-split: assertion failed "Function already has multiple table slots"

### ISSUE THREAD

**Issue by caiiiycuk** [WebAssembly/binaryen#3824]
Hi, I am trying to use `wasm-split` on big wasm file generated by Unity. Every time it crashes with assertion:

```
wasm-split: src/ir/module-splitting.cpp:155: void wasm::ModuleSplitting::{anonymous}::TableSlotManager::addSlot(wasm::Name, wasm::ModuleSplitting::{anonymous}::TableSlotManager::Slot): Assertion `it.second && "Function already has multiple table slots"' failed.
Signal: SIGABRT (signal SIGABRT)
```

This happens on function called `b0` (function name is not minified), slots:
```
b0, global 'gimport$0', index 0, tableName 'timport$0'
b0, global 'gimport$0', index 5, tableName 'timport$0'
b0, global 'gimport$0', index 6, tableName 'timport$0'
b0, global 'gimport$0', index 7, tableName 'timport$0'
```

If I comment out this assert, `wasm-splits` ends with exit code 0. However I am not tested the results yet.
So what actually this assertion stands for?

**Comment by caiiiycuk** [comment]
Here is a test case:
[test.zip](https://github.com/WebAssembly/binaryen/files/6341364/test.zip)

Archive contains:
- main.wasm.orig
- keepnames - functions that should be kept in main module

I slightly modified `wasm-split` to accept files instead of string, anyway seems problem is not related to keep-funcs argument.
I run it like this:
```
wasm-split \
--keep-funcs @/tmp/keepnames \
--enable-mutable-globals \
main.wasm.orig \
-o1main.wasm \
-o2 main.wasm.deferred \
-q
```

**Comment by caiiiycuk** [comment]
This is how I modified `parseNameList` to accept files(I can make PR if you think it's ok):
```
std::set<Name> parseNameList(const std::string& listOrFile) {
  std::string list;
  if (!listOrFile.empty() && listOrFile[0] == '@') {
    std::getline(std::ifstream(listOrFile.substr(1)), list, '\n');
  }

  std::set<Name> names;
  std::istringstream stream(list);
  for (std::string name; std::getline(stream, name, ',');) {
    names.insert(name);
  }
  return names;
}

```

**Comment by tlively** [comment]
Thanks for the report! This assertion was removed in #3825. Also, your improvement to accept functions from a file looks useful, please do make a PR for it :) It might be more readable to have the input files have one function name per line though, rather than have them contain a comma separated list. It would also be good to document this functionality in the option help text.

**Comment by caiiiycuk** [comment]
Ohh, sorry. I didn't receive messages, I will do the PR. Thanks
