### ISSUE TITLE
How to build on Windows?

### ISSUE THREAD

**Issue by qwertie** [WebAssembly/binaryen#384]
I'm having trouble with update.py (and btw, it should be documented that this requires Python 2.x and not Python 3.x). At first I had an error like

```
Downloading `D:\Dev\Wasm\binaryen\test\wasm-torture-s-5645.tbz2`
Traceback (most recent call last):
  File "update.py", line 74, in <module>
    override_build=args.override_build))
  File "update.py", line 52, in run
    updates += scripts.support.untar(downloaded, BASE_DIR)
  File "D:\Dev\Wasm\binaryen\scripts\support.py", line 76, in untar
    untared = _open_archive(tarfile, tmpdir)
  File "D:\Dev\Wasm\binaryen\scripts\support.py", line 28, in _open_archive
    subprocess.check_call(['tar', '-xvf', tarfile], cwd=tmp_dir, stdout=f)
  ...
  File "D:\Dev\etc\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

This turned out to just be because `tar` was not in my `PATH`, so I added it. Then the error changed to

```
Already have `D:\Dev\Wasm\binaryen\test\wasm-torture-s-5645.tbz2`
tar: Cannot connect to D: resolve failed
...
subprocess.CalledProcessError: Command '['tar', '-xvf', u'D:\\Dev\\Wasm\\binaryen\\test\\wasm-torture-s-5645.tbz2']' returned non-zero exit status 128
```

Hmmm... what the heck is that? It seems that the `:` in the path causes tar to open some kind of remote connection...

```
D:\Dev\Wasm\binaryen>tar -xvf D:\Dev\Wasm\binaryen\test\wasm-torture-s-5645.tbz2
tar: Cannot connect to D: resolve failed
```

But without the "D:" it still doesn't work...

```
D:\Dev\Wasm\binaryen>tar -xvf \Dev\Wasm\binaryen\test\wasm-torture-s-5645.tbz2

bzip2: Data integrity error when decompressing.
    Input file = (stdin), output file = (stdout)

It is possible that the compressed file(s) have become corrupted.
You can use the -tvv option to test integrity of such files.

You can use the `bzip2recover' program to attempt to recover
data from undamaged sections of corrupted files.

tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

So I looked at it in a hex editor and sure enough, every 0A (`\n`) is preceded by an 0D (`\r`). Sigh.

@griffin2000 you were trying to build on Windows... did your update.py work? If so ... what kind of Linux tools do you have installed? cygwin?

**Comment by jfbastien** [comment]
The python code that handles tar files may be opening the file without binary mode?

**Comment by kripken** [comment]
Do we still need `update.py`? I forgot it existed actually, I haven't run it in ages.

**Comment by jfbastien** [comment]
It semi-broke a while ago and I haven't gone back to fix it (it downloads, but doesn't untar in-place). Up to you, it makes the URL easy to get...

**Comment by kripken** [comment]
Ok, opened #385.
