### ISSUE TITLE
ReFinalize generates new types, not synchronized with the global store

### ISSUE THREAD

**Issue by kripken** [WebAssembly/binaryen#3843]
Testcase (reduced from 800K...):
```wat
(module
 (type $A (struct (field (ref null $C))))
 (type $B (struct (field (ref null $D))))
 (type $C (struct (field (mut (ref $A)))))
 (type $D (struct (field (mut (ref $A))) (field (mut (ref $A)))))

 (func $foo (param $a (ref null $A)) (result (ref null $A))
  ;; the select should have type $A
  (select (result (ref null $A))
   ;; one arm has type $A
   (local.get $a)
   ;; one arm has type $B (a subtype of $A)
   (ref.null $B)
   (i32.const 0)
  )
 )
)
```
STR: `wasm-opt w.wat -all --print --precompute  --print --roundtrip`

The first print is
```wat
(module
 (type $A (struct (field (ref null $C))))
 (type $ref?|$A|_=>_ref?|$A| (func (param (ref null $A)) (result (ref null $A))))
 (type $B (struct (field (ref null $D))))
 (type $C (struct (field (mut (ref $A)))))
 (type $D (struct (field (mut (ref $A))) (field (mut (ref $A)))))
 (func $foo (param $a (ref null $A)) (result (ref null $A))
  (select (result (ref null $A))
   (local.get $a)
   (ref.null $B)
   (i32.const 0)
  )
 )
)
```
Note that the select has the right type. The we precompute and print again, and now get this:
```wat
(module
 (type $A (struct (field (ref null $C))))
 (type $ref?|$A|_=>_ref?|$A| (func (param (ref null $A)) (result (ref null $A))))
 (type $B (struct (field (ref null $D))))
 (type $C (struct (field (mut (ref $A)))))
 (type $D (struct (field (mut (ref $A))) (field (mut (ref $A)))))
 (func $foo (param $a (ref null $A)) (result (ref null $A))
  (select (result (ref null ${ref?|$C|}))
   (local.get $a)
   (ref.null $B)
   (i32.const 0)
  )
 )
)
```
Note how the type went from `$A` to `${ref?|$C|}` - a new type (as can be seen from its lack of a name), structurally identical to `$A`, but different.

Precompute is not to blame here: nothing is precomputed. But Precompute runs ReFinalize which recomputes LUBs.

Finally, the roundtrip fails on
```
Missing type: (struct (field (ref null (struct (field (mut (ref (struct (field ...3)))))))))
wasm-opt: src/wasm/wasm-binary.cpp:529: uint32_t wasm::WasmBinaryWriter::getTypeIndex(wasm::HeapType) const: Assertion `0' failed.
Aborted
```
That happens in writing out the select, so it looks like the type confusion from before leads to us not having that new type in our list, and we don't know how to write it out.

cc @tlively

**Comment by tlively** [comment]
Thanks for the reproducer and the explanation! I will investigate this.

**Comment by tlively** [comment]
It looks like the issue is that the ShapeCanonicalizer only operates on the newly built HeapTypes in the TypeBuilder and does not create partitions for canonical HeapTypes that are not reachable from the temporary HeapTypes. That means that temporary HeapTypes that refer to equirecursively equivalent canonical HeapTypes are not properly minimized. Will fix.
