### ISSUE TITLE
wasm-opt crashing when invoked by emcc at higher optimization levels

### ISSUE THREAD

**Issue by kg** [WebAssembly/binaryen#3856]
When building our binary at ```-O2``` or ```-Os``` after a certain source commit (that only touched C), we get a crash in wasm-opt:
```
  source /home/kate/Projects/dotnet-runtime-wasm/src/mono/wasm/emsdk/emsdk_env.sh 2>/dev/null && emcc --profiling-funcs -s ALLOW_MEMORY_GROWTH=1 -s NO_EXIT_RUNTIME=1 -s FORCE_FILESYSTEM=1 -s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall', 'FS_createPath', 'FS_createDataFile', 'cwrap', 'setValue', 'getValue', 'UTF8ToString', 'UTF8ArrayToString', 'addFunction']" -s "EXPORTED_FUNCTIONS=['_putchar']" --source-map-base http://example.com  -emit-llvm -DENABLE_METADATA_UPDATE=1 -g -Os -s ASSERTIONS=1 -DDEBUG=1 --js-library runtime/library_mono.js --js-library runtime/binding_support.js --js-library runtime/dotnet_support.js --js-library /home/kate/Projects/dotnet-runtime-wasm/src/libraries/Native/Unix/System.Native/pal_random.js /home/kate/Projects/dotnet-runtime-wasm/artifacts/obj//mono/Browser.wasm.Debug/wasm/driver.o /home/kate/Projects/dotnet-runtime-wasm/artifacts/obj//mono/Browser.wasm.Debug/wasm/pinvoke.o /home/kate/Projects/dotnet-runtime-wasm/artifacts/obj//mono/Browser.wasm.Debug/wasm/corebindings.o /home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/mono/Browser.wasm.Debug//libmono-ee-interp.a /home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/mono/Browser.wasm.Debug//libmonosgen-2.0.a /home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/mono/Browser.wasm.Debug//libmono-ilgen.a /home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/mono/Browser.wasm.Debug//libmono-icall-table.a /home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/mono/Browser.wasm.Debug//libmono-profiler-aot.a /home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/native/net6.0-Browser-Debug-wasm//libSystem.Native.a /home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/native/net6.0-Browser-Debug-wasm//libSystem.IO.Compression.Native.a /home/kate/.nuget/packages/microsoft.netcore.runtime.icu.transport/6.0.0-preview.5.21226.1/runtimes/browser-wasm/native/lib//libicuuc.a /home/kate/.nuget/packages/microsoft.netcore.runtime.icu.transport/6.0.0-preview.5.21226.1/runtimes/browser-wasm/native/lib//libicui18n.a -o /home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/native/net6.0-Browser-Debug-wasm//dotnet.js
 
  terminate called after throwing an instance of 'std::out_of_range'
    what():  _Map_base::at

  emcc: error: '/home/kate/Projects/dotnet-runtime-wasm/src/mono/wasm/emsdk/upstream/bin/wasm-opt --post-emscripten --no-exit-runtime -Os --low-memory-unused --zero-filled-memory --strip-producers /home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/native/net6.0-Browser-Debug-wasm//dotnet.wasm -o /home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/native/net6.0-Browser-Debug-wasm//dotnet.wasm -g --mvp-features --enable-mutable-globals' failed (-6)

  make: Leaving directory '/home/kate/Projects/dotnet-runtime-wasm/src/mono/wasm'
```

Passing ```-O1``` to emcc makes it not crash, but it's not clear to me whether that causes it to just not invoke wasm-opt or not. I did verify that ```-O2``` is passed through to wasm-opt and still crashes just like -Os. Running emcc in verbose mode with ```-v``` shows that all the steps it runs preceding wasm-opt succeed.

Emcc seems engineered to overwrite its previous inputs with its outputs on every step and I can't figure out how to change that, so I don't have a hand-crafted set of inputs to use to reproduce the problem in wasm-opt. I'm going to try to manually construct an input binary to make this easy to repro and will try to attach it to this issue once I do.

In the interim, the painful repro steps are to clone https://github.com/dotnet/runtime, check out revision ```7ea91b742cc1646bd1611749a8179fba2fcdc3af```, provision all the necessary build dependencies, and then perform ```./build.sh --os Browser -c debug --subset mono+libs```. I should note that if you build it in our 'release' configuration, the wasm-opt crash doesn't happen, so this is specific to optimizing our debug binaries.

Not everyone on our team can reproduce this right now, but I'm also not the only person hitting it so something weird is going on here. My build environment is 64-bit Debian 10 (kernel 4.19.0-14), and we're using emsdk 2.0.12.

**Comment by kg** [comment]
[O0.zip](https://github.com/WebAssembly/binaryen/files/6419036/O0.zip)

Unpack this zip file and attempt to wasm-opt the contained .wasm file with this command line to reproduce the crash:
```emsdk/upstream/bin/wasm-opt --post-emscripten --no-exit-runtime -O2 --low-memory-unused --zero-filled-memory --strip-producers O0.wasm -o O2.wasm```

Can't guarantee this is the exact same way emcc invokes it, because emcc's verbose mode doesn't actually dump the arguments it passes to compiler.js so I have no way to manually reproduce the whole build process and give you a pristine pre-wasm-opt .wasm file.

```
kate@reeir-debian2:~/Projects/dotnet-runtime-wasm/src/mono/wasm$ "/home/kate/Projects/dotnet-runtime-wasm/src/mono/wasm/emsdk/upstream/bin/wasm-opt" --post-emscripten --no-exit-runtime -O2 --low-memory-unused --zero-filled-memory --strip-producers ~/O0.wasm -o ~/O2.wasm
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
Aborted
```

**Comment by vargaz** [comment]
The stack trace is:
```
   frame #9: 0x000000010021d458 libbinaryen.dylib`std::__1::__throw_out_of_range(char const*) + 56
    frame #10: 0x00000001004c643a libbinaryen.dylib`wasm::Debug::writeDWARFSections(wasm::Module&, wasm::BinaryLocations const&) + 8538
    frame #11: 0x000000010049dce6 libbinaryen.dylib`wasm::WasmBinaryWriter::write() + 390
    frame #12: 0x00000001004dd6fa libbinaryen.dylib`wasm::ModuleWriter::writeBinary(wasm::Module&, wasm::Output&) + 474
    frame #13: 0x00000001004dd93d libbinaryen.dylib`wasm::ModuleWriter::writeBinary(wasm::Module&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) + 173
    frame #14: 0x00000001004dda94 libbinaryen.dylib`wasm::ModuleWriter::write(wasm::Module&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) + 68
    frame #15: 0x0000000100007909 wasm-opt`main + 17129
    frame #16: 0x00007fff6aa6bcc9 libdyld.dylib`start + 1
```

**Comment by kg** [comment]
Looks like it's possibly #3697. Could have sworn I did an issue search first, but I overlooked that one somehow...

**Comment by kripken** [comment]
From the stack trace it does look like that other issue, yes. And running on that `O0.wasm` I don't see the crash. However from the timeline I'm not 100% sure, as that crash only started around March, but the version you are using (2.0.12) was released in January.

2.0.16 includes the fix for this. Please let me know if that doesn't resolve the crash.
