### ISSUE TITLE
Much slower compilation compare to v98

### ISSUE THREAD

**Issue by MaxGraey** [WebAssembly/binaryen#3857]
It was noticed [a long time ago](https://github.com/AssemblyScript/assemblyscript/pull/1700#issuecomment-784557145). Not sure it affect to native binaryen but binaryen.js since v99 definitely have slower optimization / compilation.

`assemblyscript.wasm` optimized compilation:
```
with binaryen.js v98:  4.13s
with binaryen.js v100: 7.22s
```
unoptimized builds (without any optimizations) also slower

**Comment by kripken** [comment]
I would recommend measuring this multiple times to make sure noise is not a factor (`perf stat -r 10` or such on linux is useful). If the regression is real, then the best thing is to bisect in order to find it.

**Comment by MaxGraey** [comment]
I figured out that [binaryen v99.0.0-nightly.20210122](https://github.com/AssemblyScript/binaryen.js/releases/tag/v99.0.0-nightly.20210122) is approx twice bigger than [binaryen v99.0.0-nightly.20210121](https://github.com/AssemblyScript/binaryen.js/releases/tag/v99.0.0-nightly.20210121) which published in previous day (in 21.01.2021). 
`v99.0.0-nightly.20210121 index.js`: 4,644,401 bytes (4.6 mb)
`v99.0.0-nightly.20210122 index.js`: 7,214,858 bytes (7.2 mb)

I don't benchmarked yet. But I guess that's may be main reason of slowdown factor.

**Comment by MaxGraey** [comment]
Btw changing from raw function pointer to `std::function` from wasm-traversal.h may theoretically cause to performance degradation: https://github.com/WebAssembly/binaryen/compare/85cfc36f0fccdf700045caa15218cef6cbc3e267...7a83bc744fff43349e6612263f11bce1fe8dbf34#diff-a03555ee930b0f0eb8d9888e8a6f936e986b79a0172931ac65f3aff5d64c34fcR253. But I'm not sure

**Comment by kripken** [comment]
Thanks @MaxGraey , that looks like the issue,

```diff
   // Tasks receive the this pointer and a pointer to the pointer to operate on
-  typedef void (*TaskFunc)(SubType*, Expression**);
+  using TaskFunc = std::function<void(SubType*, Expression**)>;
```
 Switching it back from a std::function to a raw function pointer reduces the `binaryen_wasm.js` build size by over 30%, and I assume also makes a big difference on speed.

I'm surprised it's so big, but it seems like storing a function pointer + a closure is much worse than just a function pointer.

@aheejin The change was made to support try-catch in CFGWalker, which uses lambdas. Perhaps that can store a stack on the side instead?

**Comment by MaxGraey** [comment]
> I'm surprised it's so big, but it seems like storing a function pointer + a closure is much worse than just a function pointer.

As I know std::function use allocation for internal context and also significant overhead when passing it by value so better use struct with overloaded call operator passed by reference or use raw pointer as before

**Comment by aheejin** [comment]
Hmm, I'm surprised that there's such a big difference. When I switched it to `std::function` I didn't compile a big application but I ran all wasm-opt tests and it showed no noticeable difference: https://github.com/WebAssembly/binaryen/pull/3494#discussion_r561018420
I didn't measure binaryen.js code size though. So the compilation speed degradation is only observed in binaryen.js? Can you check if you observe a similar thing in normal Binaryen too? (Degradation in binaryen.js alone can warrant reverting, but I just want to understand the issue better)

**Comment by kripken** [comment]
Checking now, yes, this does seem worse on a normal build too. Interesting because I think I did some measurements back then as well, and didn't see anything, like you. Testing now, I used the largest wasm I have (40MB of LLVM), as maybe this is in large part a matter of memory caches, and requires a huge program to see the difference? `-O1` on that goes from 42 seconds to 23 seconds with simple function pointers. Also `libbinaryen.so` is 15% smaller - I guess all the many templated things with traversals add up? Anyhow, it seems worth it to switch.

About the much larger effect on binaryen.js, it is possible this is worse due to C++ ABI issues with how `std::function` works in emscripten - I think I remember @dschuff looked into that, but maybe I'm wrong?

**Comment by MaxGraey** [comment]
I'm wondering is it make sense avoid std::function in [other places](https://github.com/WebAssembly/binaryen/search?q=std%3A%3Afunction) as well?

**Comment by aheejin** [comment]
> @aheejin The change was made to support try-catch in CFGWalker, which uses lambdas. Perhaps that can store a stack on the side instead?

What do you mean by "store a stack on the side"?

**Comment by kripken** [comment]
@aheejin 

I meant to store the data that the closure/lambda referred to, in a data structure on the side (and that data structure would only be used for Try-Catch, and so only add overhead there).
