### ISSUE TITLE
Sign extension operations may prevent optimize locals

### ISSUE THREAD

**Issue by MaxGraey** [WebAssembly/binaryen#3906]
We decided enable sign extensions by default but later we found out that these operations can block some passes.
Example of edge case:
```wat
local.tee $2
i32.extend8_s
local.get $2
i32.extend8_s
```
See full example [here](https://github.com/AssemblyScript/assemblyscript/pull/1869/files#diff-cf8b6507f501c7e1f9a7e95c332de6760045e888b2e2783e2e870bef5bda9b63R11)

**Comment by kripken** [comment]
Probably `ExtendS8Int32` etc. need to be handled in places like `Bits::getMaxBits`, `Properties::getSignExtValue`, etc. Most of that code has only been tuned for MVP wasm I think.

**Comment by MaxGraey** [comment]
After #3910 we have some improvements and some codegen regressions (or missing opportuneties) like transform:
```wat
i32.load8_s
local.get $1
i32.extend8_s
```
into
```wat
i32.load8_u
local.get $1
i32.const 255
i32.and
```
See [this update](https://github.com/AssemblyScript/assemblyscript/pull/1885/files#diff-3498b8e4e927e8f20db5751efa502487aeb9b0a35081bb1a6996ee9a39f8bea9)

Could someone point me in the direction of where to look to improve this situation?

My guesses:
1) https://github.com/WebAssembly/binaryen/blob/main/src/passes/OptimizeInstructions.cpp#L427
2) https://github.com/WebAssembly/binaryen/blob/main/src/passes/OptimizeInstructions.cpp#L520

**Comment by kripken** [comment]
I don't follow the example (you suggest turning something with 3 lines into 4, which would be larger in the binary size? and the first one, with 3 lines, never uses the result of the load). But in general, yes, this would go in OptimizeInstructions, and those two links looks relevant.

**Comment by MaxGraey** [comment]
> you suggest turning something with 3 lines into 4, which would be larger in the binary size?

Yes, I mean first example with `load8_s` and `extend8_s` more preferable in term of code size and will be great preserve this codegen

**Comment by kripken** [comment]
Yes, I agree finding places to use `extend8_s` etc. would be beneficial. Let me know if you get stuck trying to find where to add it in OptimizeInstructions
