### ISSUE TITLE
wasm-opt -O0 modifies the binary

### ISSUE THREAD

**Issue by vshymanskyy** [WebAssembly/binaryen#3914]
I'd like to apply only several specific transforms, but running `wasm-opt` without options or with `-O0` still applies some transformations. Is there any way to avoid it?

**Comment by vshymanskyy** [comment]
It mostly just replaces some code with `unreachable`, however it's not the same as `--dce`

**Comment by tlively** [comment]
No, binaryen currently does not have a way to avoid this. The light dce you're noticing is baked directly into the module writing code. Generally, parsing can also modify the code to work around the few structural differences between raw WebAssembly and Binaryen IR. We might eventually make it possible for Binaryen to roundtrip modules without modifications, but that is not a supported use case right now.

**Comment by vshymanskyy** [comment]
Thanks for explanation!
