### ISSUE TITLE
`drop` signature in the parser seems wrong 

### ISSUE THREAD

**Issue by alimpfard** [WebAssembly/binaryen#3948]
The spec mentions `drop` not having any arguments:
https://webassembly.github.io/spec/core/text/instructions.html#parametric-instructions

```
plaininstr ::= 'drop'     => drop
```

Yet the parser expects a "value" here:
https://github.com/WebAssembly/binaryen/blob/main/src/wasm/wasm-s-parser.cpp#L1303-L1308

As far as I can tell, `drop` doesn't take any arguments, and this makes a module from the spec tests to fail to parse (which is expected to parse cleanly):
https://github.com/WebAssembly/spec/blob/662232701afa7bef3c5b1e77362f2bab6173fca4/test/core/block.wast#L3-L351
Specifically, on the first `drop` here:
https://github.com/WebAssembly/spec/blob/master/test/core/block.wast#L24

**Comment by alimpfard** [comment]
I assume this is meant to be `(drop (expression))`, but that's neither in the text format nor the extended text format, if this is expected behaviour (seems to be so, opt passes treat it as such), could someone point me to the grammar this is expected to parse?

**Comment by tlively** [comment]
The folder form for instruction s-expressions is defined here: https://webassembly.github.io/spec/core/text/instructions.html#folded-instructions. Binaryen only supports folded expressions, including `drop`, rather than the full standard text format.

**Comment by alimpfard** [comment]
I see, thanks for clarifying that.
Out of curiousity, is there a tool available in binaryen that can correctly parse/assemble the text format?
(I'll close this issue as invalid)

**Comment by tlively** [comment]
No, although you might want to check out [wabt](https://github.com/webassembly/wabt) for that.
