### ISSUE TITLE
Error during fuzz_opt fuzzing

### ISSUE THREAD

**Issue by MaxGraey** [WebAssembly/binaryen#3967]
Fuzzer found this issue in master as well
seed `3077981557469174887` (`./scripts/fuzz_opt.py 3077981557469174887`)

```
[....binaryen/third_party/v8/d8', 
'--wasm-staging', 
'--experimental-wasm-eh', 
'--experimental-wasm-compilation-hints', 
'--experimental-wasm-gc', 
'--experimental-wasm-typed-funcref', 
'--experimental-wasm-memory64', 
'--liftoff', 
'--no-wasm-tier-up', 
'a.out.js']
```

Can't reduce it due to this warning:
```
|!! Make sure the above is what you expect! !!

|! execution time is dangerously close to the timeout - you should probably increase the timeout
```

Upd: I tried running wasm-reduce, but it took 9 hours to reduce the size from 32397 to only 27818. So I gave up

**Comment by kripken** [comment]
Can you paste the full output of running the script? I don't see the crash. It's possible it happens in d8, which may mean it depends on the version you have installed.

**Comment by kripken** [comment]
Oh wait, I see, it happens when fuzzing wasm2c, which I didn't have on...
