### ISSUE TITLE
Can't run clang-tidy-diff on MacOS

### ISSUE THREAD

**Issue by MaxGraey** [WebAssembly/binaryen#3985]
Unfortunately I can't run `./scripts/clang-tidy-diff.sh` due to error `readlink: illegal option -- f` on MacOS which caused in [this line](https://github.com/WebAssembly/binaryen/blob/main/scripts/clang-tidy-diff.sh#L20). Could we use some special fallback to something like [this](https://stackoverflow.com/a/1116890)?

**Comment by aheejin** [comment]
Yeah, it seems `readlink` in MacOS is different from that in Linux. It looks it was added in #2646.. @sbc100, what was the reason this was necessary?

**Comment by sbc100** [comment]
I think its because `/usr/bin/clang-tidy` can be symlink.   For example on my system:

```
$ ll /usr/bin/clang-tidy
lrwxrwxrwx 1 root root 29 May 12 09:30 /usr/bin/clang-tidy -> ../lib/llvm-11/bin/clang-tidy*
```

We want to find the location `clang-tidy-diff.py` relative `clang-tidy`  and we basically `../../lib/llvm-11/bin/clang-tidy`.   This doesn't work unless you resolve the symlinks first.

**Comment by aheejin** [comment]
Given that this is not meant to be used by normal users, I'm not sure the fully general solution is necessary.. @MaxGraey, does something like [this](https://stackoverflow.com/a/4031502) work for you?

**Comment by MaxGraey** [comment]
How about this?
```sh
function realpath() {
  python -c "import os,sys; print(os.path.realpath(sys.argv[1]))" "$CLANG_TIDY";
}

CLANG_DIR=$(dirname $(dirname $(realpath $CLANG_TIDY)))
```

**Comment by aheejin** [comment]
As long as it works, I'm OK with it. @MaxGraey, can you submit a PR with that then? (Maybe with a comment that why this is necessary, that `realpath -f` works for Linux but not mac, and this `realpath` function is meant to be equivalent to Linux's `realpath -f`.)

**Comment by MaxGraey** [comment]
Sure! Will do tomorrow. Thanks for help btw

**Comment by sbc100** [comment]
How about replacing `realpath` with `readlink -m` ?  Does that work on macOS?

**Comment by MaxGraey** [comment]
> How about replacing `realpath` with `readlink -m` ? Does that work on macOS?

unfortunately not
