### ISSUE TITLE
sanitize=undefined is ignored

### ISSUE THREAD

**Issue by kripken** [WebAssembly/binaryen#402]
The bot that runs this emits warnings in the log, e.g.

```
/home/travis/build/WebAssembly/binaryen/src/wasm-binary.h:97:32: runtime error: left shift of negative value -1
```

(see e.g. [this log](https://api.travis-ci.org/jobs/126003499/log.txt?deansi=true)). I happened to notice this by chance. It doesn't trigger an error, it's just logging, the process is not aborted like the other sanitizers do

Is that normal for ubsan? cc @jfbastien

**Comment by jfbastien** [comment]
Ugh the default is to recover and continue. I'm trying to fix now.
