### ISSUE TITLE
Magic division by constant for OptimizeForJS. Does it make sense?

### ISSUE THREAD

**Issue by MaxGraey** [WebAssembly/binaryen#4054]
I'm working on a new rule for OptimizeForJS that optimizes the division / modulo by constant for 64-bit types. Since for this particular case it is too expensive to call and execute a helper (polyfill) function for full division. According to my simple tests this gives up to 7x performance gain if the high part of dividend is not zero. The PR will come out pretty huge, so I'm wondering if it's worth it.

Rule will rewrite this `i64(x) / C` to something like this in simplified form `mulh64(x, mag.M) >> mag.S`

**Comment by tlively** [comment]
This sounds fairly straightforward, but I don't understand everything involved. What will make the PR large?

**Comment by MaxGraey** [comment]
See #4055. It's just half of PR

**Comment by MaxGraey** [comment]
So I expect it will be 1500-1700 LOCs including lit tests
