### ISSUE TITLE
Some opportunities for TrapsNeverHappen

### ISSUE THREAD

**Issue by askeksa-google** [WebAssembly/binaryen#4061]
I tried out the TrapsNeverHappen mode from https://github.com/WebAssembly/binaryen/pull/4059 on the Dart barista3 benchmark, and it successfully reduced the number of `(drop (ref.cast ...))`, `(drop (ref.as_non_null ...))` or `(drop (struct.get ...))` occurrences (as measured by searches in the `.wat` output) from more than 3000 to less than 150.

The remaining occurrences all seem to be cases where the inner expression has some side effect, but it should still be sound to reduce these to just a `drop` with the same contents.

Another situation sometimes seen is where the `ref.cast` or `ref.as_non_null` is unnecessary, in the sense that the code will still validate if the check is removed. These can also be removed in TrapsNeverHappen mode.

I found a function in the optimized module which (along with one it calls) illustrates some of these opportunities:
```wat
 (func $5602 (param $0 dataref) (result (ref null $type$5))
  (local $1 (ref null $type$574))
  (drop
   (ref.as_non_null
    (struct.get $type$574 0
     (local.tee $1
      (ref.cast
       (local.get $0)
       (rtt.canon $type$574)
      )
     )
    )
   )
  )
  (drop
   (call $5603
    (ref.as_non_null
     (local.get $1)
    )
   )
  )
  (ref.null $type$5)
 )
 (func $5603 (param $0 dataref) (result (ref null $type$5))
```
Remove the `ref.as_non_null`:
```wat
 (func $5602 (param $0 dataref) (result (ref null $type$5))
  (local $1 (ref null $type$574))
  (drop
   (struct.get $type$574 0
    (local.tee $1
     (ref.cast
      (local.get $0)
      (rtt.canon $type$574)
     )
    )
   )
  )
  (drop
   (call $5603
    (ref.as_non_null
     (local.get $1)
    )
   )
  )
  (ref.null $type$5)
 )
 (func $5603 (param $0 dataref) (result (ref null $type$5))
```
Remove the `struct.get`:
```wat
 (func $5602 (param $0 dataref) (result (ref null $type$5))
  (local $1 (ref null $type$574))
  (drop
   (local.tee $1
    (ref.cast
     (local.get $0)
     (rtt.canon $type$574)
    )
   )
  )
  (drop
   (call $5603
    (ref.as_non_null
     (local.get $1)
    )
   )
  )
  (ref.null $type$5)
 )
 (func $5603 (param $0 dataref) (result (ref null $type$5))
```
Transform dropped `local.tee` into `local.set`:
```wat
 (func $5602 (param $0 dataref) (result (ref null $type$5))
  (local $1 (ref null $type$574))
  (local.set $1
   (ref.cast
    (local.get $0)
    (rtt.canon $type$574)
   )
  )
  (drop
   (call $5603
    (ref.as_non_null
     (local.get $1)
    )
   )
  )
  (ref.null $type$5)
 )
 (func $5603 (param $0 dataref) (result (ref null $type$5))
```
Eliminate the local:
```wat
 (func $5602 (param $0 dataref) (result (ref null $type$5))
  (drop
   (call $5603
    (ref.as_non_null
     (ref.cast
      (local.get $0)
      (rtt.canon $type$574)
     )
    )
   )
  )
  (ref.null $type$5)
 )
 (func $5603 (param $0 dataref) (result (ref null $type$5))
```
The `ref.as_non_null` is now redundant, since its argument is non-nullable:
```wat
 (func $5602 (param $0 dataref) (result (ref null $type$5))
  (drop
   (call $5603
    (ref.cast
     (local.get $0)
     (rtt.canon $type$574)
    )
   )
  )
  (ref.null $type$5)
 )
 (func $5603 (param $0 dataref) (result (ref null $type$5))
```
The `ref.cast` is unnecessary, since the parameter to `$5603` has type `dataref` and the argument to the `ref.cast` is already `dataref`:
```wat
 (func $5602 (param $0 dataref) (result (ref null $type$5))
  (drop
   (call $5603
    (local.get $0)
   )
  )
  (ref.null $type$5)
 )
 (func $5603 (param $0 dataref) (result (ref null $type$5))
```

**Comment by kripken** [comment]
Ok, I think almost all of these things are now handled after recent improvements. However, there remains an open issue about calls (and the same thing with locals) that I'm not sure what to do about.

If a call "discards" additional type info, then in TNH mode we can skip a cast to make the type non-nullable or more specific, if the less specific type is good enough anyhow. But this actually goes in the opposite direction as our type-specialization pass for calls (and again, the same is for locals). That is, we have a pass that sees if all calls pass in a more specialized type, and if so, update the function type. That can potentially save casting in that function.

In this example, `$5603` receives a `dataref`, but maybe it could be specialized depending on other callers. Even if it can't right now, later optimization cycles might be able to in theory. So "de-specializing" the type we send may be harmful.

Overall the issue of specialization/despecialization for function params (and locals) seems difficult - there's no obvious way to make progress that avoids local minima. I lean towards leaving it for future investigation unless there is a better way to look at it that I am missing?

**Comment by tlively** [comment]
For optimizing a function (or block) body, you always want the parameters to be as specific as possible and the result to be as general as possible (i.e. the signature type should be generalized). For optimizing a function (or block) caller, you instead want the parameters to be as general as possible and the result to be as specific as possible (i.e. the signature type should be specialized).

We could do an analysis to figure out the upper bound on the function type based on all its users and the lower bound on the function type based on its contents, looking through casts in both directions. If the lower bound is a subtype of the upper bound, then all of the casts can be removed. Otherwise, we could decide to keep the casts in the callers or the casts in the function body and remove the others. (If calls and code size were cheap, we could even create a copy of the function with its casts removed and call it from only the call sites that would validate with the more general signature.)

I'm not sure what the delta is between what we currently do and what I just described.

**Comment by kripken** [comment]
@tlively Makes sense. Atm we don't look at the contents at call sites, we just look at the types there.

But the interactions here seem complex:

> For optimizing a function (or block) caller, you instead want the parameters to be as general as possible

If callsite params want to be as general as possible then that is in opposition by locals wanting to be as specific as possible, which is what the local type specialization pass does.

As long as everything went in the same direction - of specialization - things were simple...

**Comment by askeksa-google** [comment]
I looked at the output from most recent Binaryen and indeed those `drop` combinations are gone.

> In this example, `$5603` receives a `dataref`, but maybe it could be specialized depending on other callers. Even if it can't right now, later optimization cycles might be able to in theory. So "de-specializing" the type we send may be harmful.

Yes, in this case, if the parameter type could eventually be specialized, this would save a cast inside the function instead. Often (AFAICS) the function signature will be "locked" by being referred to either in a `ref.func` or a table. In those cases, removing the cast should be "safe" against the local minima.

A similar situation arises with locals. I see many (more than 2000) occurrences of `(local.set (ref.as_non_null ...))`, where the check can be removed when the local is nullable. As long as locals are always nullable, this should be a clear win. If locals can be non-nullable, I guess this depends on the interaction with local optimizations and CSE. WDYT? This optimization could be important in order to get a fair comparison between supporting non-nullable locals or not.

**Comment by kripken** [comment]
@askeksa-google 

> Often (AFAICS) the function signature will be "locked" by being referred to either in a ref.func or a table. In those cases, removing the cast should be "safe" against the local minima.

Interesting point. Makes sense, although not trivial to do as a `ref.func` might be optimized out later. So this would need to wait for late in the pipeline probably (which gets complicated if doing `--converge`).

> A similar situation arises with locals.

Good idea! Yeah, I think you're right. When non-nullable locals are not enabled, we should remove those in TNH mode, but not otherwise. I opened https://github.com/WebAssembly/binaryen/pull/4157

**Comment by askeksa-google** [comment]
Another optimization opportunity that I have encountered is double cast. In TNH mode, we can remove the weaker of the two casts. When the weaker cast is outermost, this might even trigger other optimizations, since the resulting type of the expression is now more precise.

**Comment by kripken** [comment]
I think these may have all been implemented. The last suggestion for example is here:

https://github.com/WebAssembly/binaryen/blob/f21774f3865e506b6dea912af8f8be16fd29dacb/src/passes/OptimizeInstructions.cpp#L1699-L1700

Let me know if you find anything not working as expected!
