### ISSUE TITLE
Fuzzing: Focus on recent initial contents

### ISSUE THREAD

**Issue by kripken** [WebAssembly/binaryen#4073]
The [fuzzer script](https://github.com/WebAssembly/binaryen/blob/52a90ac33416322c1be103fba6ab32764d3d1c9e/scripts/fuzz_opt.py#L174) will pick initial contents some of the time: an initial testcase to add fuzz on top of. This can be useful as often testcases are corner cases.

I had the idea that instead of randomly choosing a testcase with equal probability, we could give a higher chance for ones that are recently updated. That is, if the OS timestamp on the file is recent, increase the probability. This would have the effect of doing more fuzzing on changes that just landed, as the changes usually adjust tests.

**Comment by aheejin** [comment]
This sounds good, but I think it would be less confusing to make this possible to be turned on and off with an option, and make the option disabled by default.

**Comment by tlively** [comment]
I like the idea, but wouldn't this make it harder to share fuzz seeds usefully? The timestamps might be different on different people's machines.

**Comment by kripken** [comment]
@aheejin @tlively Good points - yeah, this is not as simple as I thought. I guess this should be opt-in.

**Comment by kripken** [comment]
Let's close this, as the points made show it is not a great idea.

Instead, in

https://github.com/WebAssembly/binaryen/pull/4111/files#diff-3c641dc74f54559f1df2b85afcac1c8e199a33edfbbf80a481167ad2e1b01f90R168-R175

something simpler is proposed: we can manually add new test files to
the list of important ones. Some time later we can then remove them.
This avoids the above issues I believe.
