### ISSUE TITLE
[fuzz-opt] Issue. Output must be deterministic

### ISSUE THREAD

**Issue by MaxGraey** [WebAssembly/binaryen#4099]
V8 version 9.5.50 (latest)

seed: `9887312019467156859`

reduced example:
```wat
(module
 (type $none_=>_eqref (func (result eqref)))
 (func $12 (result eqref)
  (unreachable)
 )
)
```

**Comment by MaxGraey** [comment]
Btw this issue does not always appear. You have to run it several times `./scripts/fuzz_opt.py 9887312019467156859`.

**Comment by MaxGraey** [comment]
It seems regress was appear in this PR: #4094

**Comment by MaxGraey** [comment]
Btw shouldn't `isNull` handle i31ref as well?
```diff
bool isNull() const {
  if (type.isNullable()) {
    if (type.isFunction()) {
      return func.isNull();
    }
    if (isData()) {
      return !gcData;
    }
    return true;
  }
+ if (type == Type::i31ref) {
+   return (i32 >> 31) != 0;
+ }
  return false;
}
```

**Comment by kripken** [comment]
I don't see this myself (I tried 30 times). But that doesn't mean it's not a real problem...

I'd suggest diffing the output. Sometimes that shows something obvious in what actually changed between the runs.

About I31s, I'm actually not sure. We don't have users of them atm I don't think, and I have not spent the time to fully understand them in the spec yet (I am still unclear on what value they add).

**Comment by MaxGraey** [comment]
I compared `b1.wat` with `b2.wat`. 
diff files:
```
2231,2233c2231
<                                  (local.set $21
<                                   (ref.null any)
<                                  )
---
>                                  (nop)

2236,2238c2234
<                                    (local.set $20
<                                     (ref.null any)
<                                    )
---
>                                    (nop)
```

files:
[b1_and_b2.zip](https://github.com/WebAssembly/binaryen/files/7035322/b1_and_b2.zip)

**Comment by MaxGraey** [comment]
b1 part (2221-2250):
```wat
(block $label$34 (result (ref $i32_=>_none))
  (local.set $22
    (ref.func $fimport$0)
  )
  (drop
    (block $label$35 (result i64)
      (local.set $16
        (i64.const 4294967281)
      )
      (drop
        (block $label$36 (result anyref)
          (local.set $21
            (ref.null any)
          )
          (drop
            (block $label$37 (result anyref)
              (local.set $20
                (ref.null any)
              )
              (local.set $7
                (i32.const 0)
              )
              (local.get $20)
            )
          )
          (local.get $21)
        )
      )
      (local.get $16)
    )
  )
```
b2 part (2221-2246):
```wat
(block $label$34 (result (ref $i32_=>_none))
  (local.set $22
    (ref.func $fimport$0)
  )
  (drop
    (block $label$35 (result i64)
      (local.set $16
        (i64.const 4294967281)
      )
      (drop
        (block $label$36 (result anyref)
          (nop)
          (drop
            (block $label$37 (result anyref)
              (nop)
              (local.set $7
                (i32.const 0)
              )
              (local.get $20)
            )
          )
          (local.get $21)
        )
      )
      (local.get $16)
    )
  )
```

**Comment by MaxGraey** [comment]
So it seems in first file we have non reduced
```wat
(local.set $21
  (ref.null any)
)
```
But on another file it will already reduced to `(nop)`

**Comment by kripken** [comment]
Manually reducing the work done on the wat files might help too. When you run `scripts/fuzz_opt.py SEED` it will run a lot of things - you can get the specific command that is nondeterministic, and see if some of the optimization passes it runs are unneeded. Ending up with a minimal command + diff between the wats should help here. (Without a minimal command, it's hard to know in which pass to even look.)

**Comment by MaxGraey** [comment]
Here passes which apply to `a.wasm`:
```py
['--remove-unused-nonfunction-module-elements', '--rse', '--precompute', '-fimfs=99999999', 
'--enable-threads', '--enable-mutable-globals', '--enable-tail-call', '--enable-reference-types', 
'--enable-multivalue', '--enable-gc', '--enable-memory64', '--enable-typed-function-references']
```

if remove `--rse` than the problem with nondeterminism disappears

**Comment by MaxGraey** [comment]
On RSE pass we have `std::unordered_map<Literals, Index> literalValues;`. which uses hashmap under the hood and sensitive for `operator==` in Literal which recently updated. 

So I see two solutions: somehow modify `Literal::operator==` to make it stricter again. Or switch to `std::map` instead `std::unordered_map`, but in this case we need to define "Literal::operator<" as well.

**Comment by kripken** [comment]
I think `literalValues` is not a problem, though because we never iterate on it. So the lack of order should not be noticeable.

Reading that pass, I don't see any iteration that looks dangerous... so I think we need to investigate more to find the problem, I can't see it.
