### ISSUE TITLE
Arm64 release?

### ISSUE THREAD

**Issue by maurolacy** [WebAssembly/binaryen#4135]
Hello,

Do you have plans to add a `arm64` release?

I've compiled it myself with good results (using the `alpine-linux` directives, from the CI setup), and I wonder why don't you add a `arm64-linux` release to the list of [releases](https://github.com/WebAssembly/binaryen/releases)?

It would be a good option for us, and probably others.

Thanks.

**Comment by kripken** [comment]
I'm not aware of anyone working on it atm, but a PR would definitely be welcome!

**Comment by maurolacy** [comment]
Will do.

**Comment by maurolacy** [comment]
After some research, [Github Actions currently supports Arm64 only for self-hosted runners](https://github.blog/changelog/2019-12-03-github-actions-self-hosted-runners-on-arm-architectures/).

There exist the possibility of using emulation through `qemu / buildx` and some plugins. See https://github.com/actions/virtual-environments/issues/2552 comments, and https://github.com/actions/virtual-environments/issues/2187#issuecomment-737339211.

But that is 5 to 10 times slower than a native runner, and native runners are probably around the corner.

So, closing / putting this on hold this until GA supports native arm64 builds.

**Comment by rathann** [comment]
FWIW, we at Fedora have been building binaryen on ARMv7 HFP and ARMv8 for quite some time now: https://src.fedoraproject.org/rpms/binaryen and we're running the test suite at the end of each build.

**Comment by kripken** [comment]
Thanks @rathann , that's good to know that things are correct!

**Comment by maurolacy** [comment]
We're also building it for ARMv8 using CircleCI, which currently supports native Arm machines. Adding the test suite at the end of the build is a good idea. Particularly considering that for the time being, it will not be built here as part of the release.

**Comment by maurolacy** [comment]
Closing this, until Arm native builders appear on GA.

**Comment by kripken** [comment]
This was implemented using QEMU for now in #6334
