### ISSUE TITLE
`wasm-opt` segfault

### ISSUE THREAD

**Issue by maurolacy** [WebAssembly/binaryen#4136]
Recent versions of `wasm-opt` segfault when optimizing some wasm code. Tested / reproduced with both 98 (dynamic) and 101 (static, latest) versions. 

To reproduce, you can try running `wasm-opt` on this [CosmWasm](https://github.com/CosmWasm) test artifact: [hackatom smart contract](https://github.com/CosmWasm/cosmwasm/blob/main/packages/vm/testdata/hackatom_0.16.wasm).

On the other hand, those contracts are being optimized without issues using `wasm-opt` v96.

Thanks,

**Comment by MaxGraey** [comment]
On MacOS and with latest 101 that wasm file works properly with `-O3` and `-O4`. Could you provide more information? Operating system, flags for wasm-opt, etc.

**Comment by maurolacy** [comment]
Sure:
```
/code/packages/vm # uname -a
Linux cd95941bc379 5.12.9-amd64 #5.12.9 SMP Fri Jun 4 22:13:11 CEST 2021 x86_64 Linux
/code/packages/vm # uname -a
Linux cd95941bc379 5.12.9-amd64 #5.12.9 SMP Fri Jun 4 22:13:11 CEST 2021 x86_64 Linux
/code/packages/vm # cat /etc/*elease
3.14.2
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.14.2
PRETTY_NAME="Alpine Linux v3.14"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
/code/packages/vm # /usr/bin/wasm-opt --version
wasm-opt version 98
/code/packages/vm # /usr/bin/wasm-opt -Os testdata/hackatom_0.16.wasm -o /dev/null
Segmentation fault
/code/packages/vm # /usr/bin/wasm-opt -O3 testdata/hackatom_0.16.wasm -o /dev/null
Segmentation fault
/code/packages/vm # /usr/bin/wasm-opt -O4 testdata/hackatom_0.16.wasm -o /dev/null
/code/packages/vm # 
```

**Comment by maurolacy** [comment]
This also happens on Mac M1 (Arm) machines, by the way.

**Comment by kripken** [comment]
I also am not having luck reproducing a crash locally. Can you perhaps build wasm-opt with ASan and see what that shows? Here is how our CI builds that mode:

https://github.com/WebAssembly/binaryen/blob/4e4c53c62c93e6dbb165ac3e941ef85c65ddb359/.github/workflows/ci.yml#L130-L148

**Comment by maurolacy** [comment]
How come? I'm using "stock" `wasm-opt` v98 bundled with `alpine` to reproduce.

I'll try your build instructions and report back.

**Comment by kripken** [comment]
If building is tricky, as we do have an alpine build in our CI already, another option might be to open a PR here and add your file to the test suite. Just placing it in `tests/passes/O3.wasm` would be enough, as the test runner will run `-O3` based on the name.

**Comment by maurolacy** [comment]
Closing in favour of #4143.
