### ISSUE TITLE
Visual Studio 2015 Build Error support/file.cpp

### ISSUE THREAD

**Issue by BSalita** [WebAssembly/binaryen#414]
Visual Studio 2015 reports a build error on line 42 of support/file.cpp It was fixed by changing `auto` to `int`. Other than this issue, binaryen builds successfully.

Original (syntax error):

`auto flags = std::ifstream::in;`

Error C2676: binary '|=': 'std::_Iosb<int>::_Openmode' does not define this operator or a conversion to a type acceptable to the predefined operator - binaryen\src\support\file.cpp	27	

Works:

`int flags = std::ifstream::in;`

**Comment by kripken** [comment]
I'm not sure that would work on other platforms, though. Might need to cast to int. Perhaps open a PR, and the bots will automatically test that?

**Comment by BSalita** [comment]
Shouldn't be a problem for several reasons. There's a similar line in the function just below it. `auto` resolves to `int`. Also `infile.open(filename, flags);` expects `flags` to be castable to `int`.

`          auto flags = std::ofstream::out | std::ofstream::trunc;`

I'll open a pull request.

**Comment by jfbastien** [comment]
Can you use `std::ios_base::openmode` instead of `int`, since that's the correct type?

**Comment by BSalita** [comment]
Yes, that works too. Be aware that VS reports  `std::ios_base::openmode` as an alias for `int`.

`typedef int std::ios_base::openmode;`

**Comment by jfbastien** [comment]
Right, but other compilers may define `openmode` as something else than `int`, so what works for MSVC isn't a clear fit for non-MSVC.

**Comment by BSalita** [comment]
I suppose the bitwise operations could yield non-ints. I suspect if that were true though, some of the usage would become syntax errors and there would be all sorts of compatibility havoc.

**Comment by BSalita** [comment]
I tested compatibility using several online sites.

[Compiles clang, gcc, or Visual Studio](http://rextester.com/l/cpp_online_compiler_visual)

**Comment by BSalita** [comment]
Fix is in PR #418

**Comment by jfbastien** [comment]
Thanks!
