### ISSUE TITLE
Add Shared Object and C API

### ISSUE THREAD

**Issue by MI3Guy** [WebAssembly/binaryen#417]
Adding support for building a shared object and a C api would allow other languages to use the library. This will be useful in the future for compiling other languages to WebAssembly and will enable other languages to run/call libraries written in WebAssembly.

**Comment by kripken** [comment]
I intend to work on a C API next week.

I'd also like to see a shared library, but I'm not sure how best to do that with cmake, hopefully someone else can help out there.

**Comment by tlively** [comment]
These exist now.
