### ISSUE TITLE
Add compiled binaries for version_102

### ISSUE THREAD

**Issue by junderw** [WebAssembly/binaryen#4341]
The release page has binaries for up to 101, but 102 only has the source tarballs.

If you could upload them I'd appreciate it.

Thanks.

**Comment by kripken** [comment]
cc @sbc100 - I think you know the build system here best?

**Comment by sbc100** [comment]
This a duplicate of #3651 I think.   Our github action that is supposed to add this binaries is no longer working sadly..

**Comment by sbc100** [comment]
Sorry duplicate of #4148
