### ISSUE TITLE
Fuzz issue

### ISSUE THREAD

**Issue by MaxGraey** [WebAssembly/binaryen#4343]
`seed 18024555986484678412`

I tried reduce this but unfortunately it takes too much time with very low reduction rate

**Comment by kripken** [comment]
Which binaryen commit did you see that error on? And what was the error? Providing that info would be good in bug reports about fuzz failures.

I don't see an error on current main, `03dca9aa1a5a266c53a474aeb3c10a3f0584b25b`.

**Comment by MaxGraey** [comment]
Ah, that's RSE issue which sometimes appear on my local fuzzer
