### ISSUE TITLE
tail calls

### ISSUE THREAD

**Issue by unicomp21** [WebAssembly/binaryen#4351]
Can binaryen support/simulate tail calls?

https://github.com/emscripten-core/emscripten/issues/10991#issuecomment-974638153

**Comment by unicomp21** [comment]
@kripken ^

**Comment by tlively** [comment]
Binaryen already has full support for the tail calls proposal. See https://github.com/WebAssembly/binaryen/blob/main/test/lit/tail-call.wast.
