### ISSUE TITLE
Could we use -O2 intead -Oz for binaryen wasm target?

### ISSUE THREAD

**Issue by MaxGraey** [WebAssembly/binaryen#4359]
Currently it uses -Oz. In binaryen.js (wasm) repo it produces approximately 3.8 Mb bundle. We decided to switch binaryen from asm.js  target to wasm target and were surprised to find that the performance increased only slightly (less than 15%). Perhaps the reason is that -Oz optimisation is being used

**Comment by MaxGraey** [comment]
We got a significant speedup by switching to `-O2`:
https://github.com/AssemblyScript/binaryen.js/pull/54#issuecomment-981113718

Size increased from `3.8` to `6` mb. which I guess basically acceptable given this significant speedup.

**Comment by kripken** [comment]
`-O2` sounds good to me given the very large speedup. Probably more inlining explains both the extra size and speed, and is the right tradeoff in most cases.
