### ISSUE TITLE
released package makes `binaryen-/` directory

### ISSUE THREAD

**Issue by ko1** [WebAssembly/binaryen#4398]
I download https://github.com/WebAssembly/binaryen/releases/download/version_103/binaryen-version_103-x86_64-linux.tar.gz and 
`tar xfvz binaryen-version_103-x86_64-linux.tar.gz` makes `binaryen-/` directory. 
Is it intentional or version is missed?

**Comment by sbc100** [comment]
I think that is due to a bug in the release builder that got fixed in #4366.

We should to another release which hopefully will not have this issue.   (Or we could manually download, unpack, repack, re-upload the archives for 1.0.3?)
