### ISSUE TITLE
Merge emscripten .mem into wasm

### ISSUE THREAD

**Issue by kripken** [WebAssembly/binaryen#44]
We currently apply the memory inside a wasm module into emscripten's memory, careful to merge them properly. This is used in the wasm-backend path in emscripten, where the LLVM wasm backend gives us a module, containing memory data. At runtime, emscripten creates memory, and then we instantiate the wasm, and combine the memories. However, when running asm2wasm, the LLVM asm.js backend gave us a .mem file separately, and we currently keep it separate.

We could merge it into the wasm module directly. A downside is that currently all our wasm is in .wast code, and so binary data is not efficiently encoded. This could be annoying for testing on large codebases. So perhaps it makes sense to wait on this until we have binary format support.

**Comment by AndrewScheidecker** [comment]
I don't know if there's any reason to do this other than to allow WAVM to more easily execute things compiled by Emscripten, but the size of static data makes up a small part of large program `.wast` files. The maximum increase in size for the memory data in the text format is 3x, but the maximum increase in size for the code is much higher: ~33x on my polyfill-prototype-1 to `.wast` translation of the UE4 HTML5 demo.
