### ISSUE TITLE
wasm-opt: Imported function params cause std::out_of_range when using --debuginfo

### ISSUE THREAD

**Issue by timkendrick** [WebAssembly/binaryen#4418]
I'm trying to use `wasm-opt` to optimize a hand-coded `.wat` file, but when I specify the `--debuginfo` wasm-opt CLI flag it causes an uncaught exception for WASM modules that contain imported functions that specify parameters in the type signature.

This only happens when an imported function signature specifies one or more input parameters. It seems to happen at all optimization levels (including unoptimized).

I've confirmed this behavior on `wasm-opt` v104 and v103 (I'm on macOS 10.15.7).

Minimal test case to reproduce:

```
echo '(module (func $foo (import "imports" "foo") (param i32)))' > ./foo.wat
wat2wasm --debug-names --output ./foo.wasm ./foo.wat
wasm-opt --debuginfo --output ./bar.wasm ./foo.wasm
```

Output: (error code 134)

```
warning: no passes specified, not doing any work
libc++abi.dylib: terminating with uncaught exception of type std::out_of_range
zsh: abort      wasm-opt --debuginfo --output ./bar.wasm ./foo.wasm
```

...note that this example works fine if you remove the `(param i32)` from the imported function signature.

**Comment by kripken** [comment]
Interesting, this looks like three separate issues: First, wasm2wat is emitting an empty "name" for parameter zero there (zero-length string). Please file a bug for that, unless I'm missing something and that is valid somehow... Second, we should have better error messages here, which I'll look into. Third, this only happens on param names of imported functions, which it looks like we don't support yet.

**Comment by timkendrick** [comment]
Thanks for taking the time to look into this!

 I've been looking into the WASM [binary encoding spec](https://webassembly.github.io/spec/core/binary/modules.html#binary-import), and I'm not sure I fully understand your explanation - when you say wat2wasm emits an empty "name" for parameter zero are you talking about the generated `functype` in the "Type Section" (I wasn't aware type params could have names)? Or are you talking about the debug name in the `.name` custom section?

As far as I understand it, the wasm binary emitted by wat2wasm for my example contains no "Function section" (/ `func` definitions). Instead it just contains an "Import section" that contains a single `import`, whose `importdesc` contains the type id `0x00 0x00` (which is the ID of the `functype` generated for the import). So given that there are no function definitions I'm not sure where it's trying to read the parameter names from?

If like you say `wasm-opt` doesn't support functions as `import` statements then I guess it makes sense that these would be misinterpreted, however the references to `ModuleUtils::iterImportedFunctions` do seem to imply that there is intended to be support for imported functions?

Apologies if I'm misunderstanding this, I'm pretty new to Web Assembly and don't have any experience with C++ so I could well be missing the point here.

**Comment by kripken** [comment]
> Or are you talking about the debug name in the .name custom section?

That's what I meant, sorry if I wasn't clear. Wabt is emitting a names section, and for that imported function it is emitting a subsection for local/param names. And the name for param 0 is "" (the empty string).

I think an empty name should be invalid, although I didn't read the spec. That is, the names section is used by debuggers and stuff like that - showing an empty string is not useful there, it's worse than showing the wasm index itself I'd say. Binaryen is careful about this when emitting the names section - it only emits names when they exist.

**Comment by timkendrick** [comment]
Thanks for your patience explaining this, apologies for misunderstanding what you were saying.

So it sounds like you're saying this is nothing to do with imported functions then, rather you're saying that you shouldn't be allowed empty strings as names of locals in the `.name` custom section?

That seems like a surprising restriction to me, seeing as a minimal example of a 1-arg function with no imports compiles fine in the latest release of `wasm-opt`, despite defining an empty local in the `.name` section:

```
echo '(module (func (param i32)))' > ./foo.wat     
wat2wasm --debug-names --output ./foo.wasm ./foo.wat
wasm-opt --debuginfo --output ./bar.wasm ./foo.wasm
warning: no passes specified, not doing any work
```

...you can see in the hex source that this still declares a single 'empty string' local (bytes 0x24 - 0x26), as confirmed by the [wat2wasm online tool](https://webassembly.github.io/wabt/demo/wat2wasm/) for the source`(module (func (param i32)))`:

```
; section "name"
0000019: 00                                        ; section code
000001a: 00                                        ; section size (guess)
000001b: 04                                        ; string length
000001c: 6e61 6d65                                name  ; custom section name
0000020: 02                                        ; local name type
0000021: 00                                        ; subsection size (guess)
0000022: 01                                        ; num functions
0000023: 00                                        ; function index
0000024: 01                                        ; num locals
0000025: 00                                        ; local index
0000026: 00                                        ; string length
0000021: 05                                        ; FIXUP subsection size
000001a: 0c                                        ; FIXUP section size
```

As you can probably imagine, your patched version will log a warning for this example:

```
echo '(module (func (param i32)))' > ./foo.wat     
wat2wasm --debug-names --output ./foo.wasm ./foo.wat
/binaryen-emptyparam/bin/wasm-opt --debuginfo --output ./bar.wasm ./foo.wasm
warning: empty local name at index 0 in function 0
warning: no passes specified, not doing any work
```

Like I say I'm not super-fussed about this seeing as I'm fine with it compiling with warnings, but I just thought I'd flag it in case it affects the design decision.

**Comment by kripken** [comment]
> So it sounds like you're saying this is nothing to do with imported functions then, rather you're saying that you shouldn't be allowed empty strings as names of locals in the .name custom section?

The crash is due to the custom section, yes. But it may also be related to imported functions - I suspect wabt only emits such an empty name for imports. At least I've never seen it emit an empty name for normal functions...

I agree a warning might be annoying, but I think it is a bug in wabt. I filed it now: https://github.com/WebAssembly/wabt/issues/1799 But we can also just not warn about it and skip such names. I'm ok either way.

**Comment by timkendrick** [comment]
Great, thanks for your help on this and for filing that issue @kripken!
