### ISSUE TITLE
Missing space in wasm-split basic test

### ISSUE THREAD

**Issue by ptrcnull** [WebAssembly/binaryen#4508]
When trying to run lit tests, `wasm-split/basic.wast` fails because of a missing space:
```
$ ":" "RUN: at line 34"
$ "binaryen-version_105/build/bin/wasm-split" "binaryen-version_105/test/lit/wasm-split/basic.wast" "--export-prefix=%" "-g" "-o1" "binaryen-version_105/build/test/wasm-split/Output/basic.wast.tmp.both.1.wasm" "-o2" "binaryen-version_105/build/test/wasm-split/Output/basic.wast.tmp.both.2.wasm" "--keep-funcs=foo,bar" "-v"
$ "filecheck" "binaryen-version_105/test/lit/wasm-split/basic.wast" "--check-prefix" "KEEP-BOTH"
# command stderr:
binaryen-version_105/test/lit/wasm-split/basic.wast:151:20: error: KEEP-BOTH-NEXT: expected string not found in input
;; KEEP-BOTH-NEXT: Splitting out functions:{{$}}
                   ^
<stdin>:3:1: note: scanning from here
Splitting out functions: 
^

Input file: <stdin>
Check file: binaryen-version_105/test/lit/wasm-split/basic.wast

-dump-input=help explains the following input dump.

Input was:
<<<<<<
          1: warning: not splitting any functions out to the secondary module
          2: Keeping functions: bar, foo
          3: Splitting out functions: 
next:151     X~~~~~~~~~~~~~~~~~~~~~~~~ error: no match found
>>>>>>

error: command failed with exit status: 1
```

In the tool's source code there's always a space after `Splitting out functions:`:
https://github.com/WebAssembly/binaryen/blob/7f24fce21a92f2aed4a11745d27d5181798ba6cd/src/tools/wasm-split/wasm-split.cpp#L258

**Comment by tlively** [comment]
What OS are you running on? It's weird that this doesn't fail on our linux dev boxes or on CI. Interestingly, if I try to fix the test to include the space locally, the test starts failing for me. It seems like this is a bug in the Python filecheck package. I'll investigate further.

**Comment by psycholance** [comment]
these tests are ran on alpine linux edge, and are actually ran with the llvm FileCheck renamed to filecheck and not the python version.. maybe that makes the difference?

**Comment by psycholance** [comment]
i will re-test this tomorrow with the actual correct filecheck, and hopefully this was just our downstream issue :)

**Comment by tlively** [comment]
Oh yes, that definitely makes a difference. The python `filecheck` package we use is a port of upstream `FileCheck` to Python and it's not an exact match. I'll file a bug or try to submit a fix to the Python package, but yeah, switching the the python package should fix this and avoid similar future breakage.

**Comment by tlively** [comment]
I opened https://github.com/mull-project/FileCheck.py/pull/188 to get this fixed in the Python package. If that gets merged, we should be able to fix this test locally to include the expected space. I'll leave this issue open until then.

**Comment by ptrcnull** [comment]
Thanks for pointing out that `filecheck` is supposed to be a Python module, I missed that while creating this issue :sweat_smile: 

When using the correct filecheck, all tests are passing correctly.

**Comment by ChristopherGS** [comment]
Looks like this issue can be closed now, right @tlively? Given this merged PR: https://github.com/WebAssembly/binaryen/pull/4537/files

**Comment by tlively** [comment]
Yes, thanks!
