### ISSUE TITLE
Bring pack spill-pointers

### ISSUE THREAD

**Issue by ChrisJefferson** [WebAssembly/binaryen#4566]
wasm-opt used to contain an option `--spill-pointers`, which would spill things to the C stack which could be pointers, to help with C systems that used stack scanning for GC.

This option was added in b5ee16f318019f89d8a897437fb906d470cfa8d9 , and removed in c61cb6f07a244067a7964d0d99c0fef0a068a3bf (when it was removed, it was non-functional).

I was using this option to build GAP ( www.github.com/gap-system/gap ). I was not keeping up to date (I was using enscripten 1.38, binaryen 1.37 for many years).

I'm not familiar enough with the internals of binaryen to know how easy this would be to bring back, but the commit message from @sbc100 mentioned bringing it back if anyone cared, so I wanted to mention I care! (that doesn't mean I'm expecting anyone to do the work to bring it back, but I thought I would register my interest).

**Comment by ChrisJefferson** [comment]
`src/gasman.c` is a conservative garbage collector. The function `GetStackFuncBags` walks along the stack, calling a function for every possible "pointerish" object, looking for objects we could collect.

If I understand the issue (the stack went in a "non-standard direction?", because gap (and gasman) were designed to support many very old machines , the function actually supports both stacks that go down, and stacks which go up, so this would have worked either way.

GAP itself is far too big for testing such a thing, but I'd be happy, inspired by GAP, to write some small test functions which test the principles of a conservative stack walker, writing some pointers to then stack and then going to look for them later.

**Comment by ChrisJefferson** [comment]
If you were looking for a build system which worked with emscripten, I have a private branch where I build GAP using emscripten, but at the moment it is a huge pile of hacks and dodgyness (partially as GAP isn't designed for cross-compiling, so I have to partially build a linux build, then do some hacks to build an emscripten version). I also needed to hack around problems building libgmp.

**Comment by sbc100** [comment]
Since this pass only ever worked with upward growing stacks I assume you never got it working with the llvm backend?  (only fastcomp, right?).

Re-landing this with the stack direction corrected seems doable.   Is it conservative enough to catch all possible pointer usages in locals?  Is som won't it be rather expensive to use?

**Comment by kripken** [comment]
This was done in #4570
