### ISSUE TITLE
Lit error on unrelated PR

### ISSUE THREAD

**Issue by kripken** [WebAssembly/binaryen#4575]
The clang test on https://github.com/WebAssembly/binaryen/pull/4574 is failing for an odd lit reason, and it doesn't seem to provide any details as to why:

https://github.com/WebAssembly/binaryen/runs/5820870416?check_suite_focus=true

That PR does not modify anything related to that test AFAICT.

The test is not required I see, so I guess we can land things without it meanwhile.

I see that test was added in #3426 cc @sbc100 @tlively

**Comment by tlively** [comment]
Not sure what's going on with this, but adding more verbose test output by merging https://github.com/WebAssembly/binaryen/pull/4577 might help us figure it out.
