### ISSUE TITLE
Unable to generate shared PIC wasm file with `dylink.0` section

### ISSUE THREAD

**Issue by ApsarasX** [WebAssembly/binaryen#4616]
### Discussed in https://github.com/WebAssembly/binaryen/discussions/4615

<div type='discussions-op-text'>

<sup>Originally posted by **ApsarasX** April 26, 2022</sup>
Clang and Emscripten both could generate shared/PIC wasm file using the following commands.

```bash
clang --target=wasm32-unknown-emscripten -nostdlib -Wl,--shared -fPIC demo.c  -o demo.wasm
```
```bash
emcc demo.c -Os -s WASM=1 -s SIDE_MODULE=1 -o demo.wasm
```

But now binaryen does not provide a way to generate shared PIC wasm
</div>

**Comment by kripken** [comment]
I don't think we need both an issue and a discussion for this? Let's close this and focus on the discussion.
