### ISSUE TITLE
wasm2asm crash on i64s

### ISSUE THREAD

**Issue by wanderer** [WebAssembly/binaryen#464]
The following will crash `wasm2asm`
```
(module
  (memory 256 256)
  (export "add" $add)
  (func $add (param $x i64) (param $y i64) (result i64)
    (i64.add
      (get_local $x)
      (get_local $y)
    )
  )
)
```

```
'./bin/wasm2asm    ./test/hell...' terminated by signal SIGABRT (Abort)
```

**Comment by kripken** [comment]
Yes, i64 support was never added to wasm2asm.

Meanwhile development on it has stopped, and it was recently removed from testing and then the build. If someone wants to pick it up, though, that's fine.

**Comment by wanderer** [comment]
ok @kripken  i'm not planing on picking this up, so ill close it.
