### ISSUE TITLE
Failed to grow table with wasm-opt and wasm-bindgen

### ISSUE THREAD

**Issue by allsey87** [WebAssembly/binaryen#4711]
When I enable reference types with `wasm-bindgen` and enable support for reference types with `wasm-opt` using `--enable-reference-types`, I am hitting the following error (without enabling these two flags everything works fine with `wasm-bindgen` maintaining its references to JS objects using its external stack). Am I missing an additional flag somewhere or is there perhaps something not supported here yet?

> Uncaught (in promise) RangeError: WebAssembly.Table.grow(): failed to grow table by 4

With a backtrace of:

    at i.wbg.__wbindgen_init_externref_table (index.js:1:11612)
    at 2b21204….wasm:0x23e15
    at c (index.js:1:12636)

**Comment by kripken** [comment]
I'm not familiar with "failed to grow table" errors. Is that a custom error from wasm-bindgen? If so, it might be a bug there. Or, if it's a wasm VM error, then first thing I'd check if this is a VM-specific bug (by trying it in multiple browsers).

If it's neither of those, providing the wasm files before and after `wasm-opt` could help figure this out.

(This should be supported, AFAIK.)

**Comment by MartinKavik** [comment]
> If it's neither of those, providing the wasm files before and after wasm-opt could help figure this out.

- Before: https://without-wasm-opt.netlify.app/  (see `Hello!` in dev console log)
- After: https://with-wasm-opt.netlify.app/  (see more detailed error in Chrome or less detailed one in Firefox)

It's Rust compiled to Wasm with `wasm-bindgen` and then optimized with `wasm-opt`. 
The Rust code:
```rust
use zoon::println;
fn main() {
    println!("Hello!");
}
```
but the same error appears even with the code `fn main() {}` or with any other complex example.
The deployed code is created by [MoonZoon](https://github.com/MoonZoon/MoonZoon), with the latest `wasm-bindgen` (`0.2.81`) and `wam-opt` (`109`).

The code has been compiled in the _profiling_ mode, i.e. optimized + debugbuild.

`wasm-bindgen` arguments:
```rust
    let mut args = vec![
        "--target",
        "web",
        "--no-typescript",
        "--reference-types",     // <---
        "--weak-refs",
        "--out-dir",
        "frontend/pkg",
    ];
    args.push(&wasm_path);
```

`wasm-opt` arguments:
```rust
    let mut args = vec![
        "frontend/pkg/frontend_bg.wasm",
        "--output",
        "frontend/pkg/frontend_bg.wasm",
        "--enable-reference-types",      // <---
    ];
    if build_mode.is_not_dev() {
        args.push("-Oz");
    }
    if let BuildMode::Profiling = build_mode {
        args.push("--debuginfo");
    }
```

Hope it helps! Please, let me know if I should provide some other info or anything else.
Thanks.

**Comment by allsey87** [comment]
Thanks for attaching that @MartinKavik! I have been meaning to upload a MRE for more than a week now...

**Comment by kripken** [comment]
Reading the wasm files I can't see anything obviously wrong. Can you provide a runnable testcase? Ideal would be a small bit of JS I can run in node that works with the first wasm, and fails with the second. Also, the `wasm-opt` command that was run to get the second wasm.

Btw, there is no `table.grow` in the wasm. I guess wasm-bindgen grows it from the outside? If so, you might be able to debug this on that side (add some `console.log` to see what size it tries to grow to).

**Comment by MartinKavik** [comment]
@allsey87 Could you create the example according to the @kripken's instructions written above? If not, I'll try to create one during following weeks.

> Also, the wasm-opt command that was run to get the second wasm.

I've written/copy-pasted the arguments in my previous comment - `wasm-opt xxx.wasm --output xxx.wasm --enable-reference-type -Oz --debuginfo`.

btw I've created an issue/question in the `wasm-bindgen` repo (https://github.com/rustwasm/wasm-bindgen/issues/2943), maybe some `wasm-bindgen` experts will be able to identify the problem quickly.

**Comment by allsey87** [comment]
The [attached MRE](https://github.com/WebAssembly/binaryen/files/8918359/mre.zip) reproduces the error inside node. The code attempts to create 64 `JsValue`s (numbers), which are to be stored in the external_ref table (if reference types are enabled):

```rust
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(js_namespace = console)]
    fn log(s: &str);
}

#[wasm_bindgen(start)]
pub fn main() {
    let mut js_values = vec![];
    for value in 0..=64 {
        js_values.push(JsValue::from(value));
    }
    log("done!");
}
```

However, since the external_ref table is only 32 slots by default, the generated bindings attempt to grow the table which fails in node with the following output:
```
/home/mallwright/Temporary/mre/growtable/growtable.js:42
    const offset = table.grow(4);
                         ^

RangeError: WebAssembly.Table.grow(): failed to grow table by 4
    at module.exports.__wbindgen_init_externref_table (/home/mallwright/Temporary/mre/growtable/growtable.js:42:26)
    at wasm://wasm/0002037a:wasm-function[115]:0x7640
    at Object.<anonymous> (/home/mallwright/Temporary/mre/growtable/growtable.js:61:6)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

Node.js v18.3.0
```
I left the generated growtable.js and growtable_bg.wasm in the archive directory (runnable using node). `build.sh` should regenerate everything if necessary. I am using the following versions of the following tools:

- wasm-opt version 108
- wasm-bindgen 0.2.81
- node: v18.3.0
- cargo 1.60.0 (d1fd9fe 2022-03-01)
- rustc 1.60.0 (7737e0b5c 2022-04-04)

**Comment by kripken** [comment]
Thanks for the testcase, but can you please provide both the working and the failing binary? (Otherwise I'd need to get and install all the build tools the testcase needs, when I just want to run `wasm-opt` to quickly debug this.) Looks like the archive has just the failing one:

```
$ node --experimental-wasm-reftypes  growtable.js 
growtable.js:42
    const offset = table.grow(4);
                         ^

RangeError: WebAssembly.Table.grow(): failed to grow table by 4
```
(note: recent node required, and that flag. I saw node 16 work but not 14 or earlier)

**Comment by allsey87** [comment]
- [wbg.zip: wasm-bindgen normal](https://github.com/WebAssembly/binaryen/files/8923223/wbg.zip)
- [wbg_opt.zip: wasm-bindgen normal + optimised](https://github.com/WebAssembly/binaryen/files/8923224/wbg_opt.zip)
- [wbgrefs.zip: wasm-bindgen reference-types](https://github.com/WebAssembly/binaryen/files/8923226/wbgrefs.zip)
- [wbgrefs_optrefs.zip: wasm-bindgen reference-types + optimised](https://github.com/WebAssembly/binaryen/files/8923227/wbgrefs_optrefs.zip)

**Comment by kripken** [comment]
Thanks! I can reproduce this locally. Reducing this down, the difference is that binaryen round-trips the export wrong,
```diff
  (export "main" (func $main))
- (export "__wbindgen_export_0" (table $1))
+ (export "__wbindgen_export_0" (table $0))
  (export "__wbindgen_start" (func $325))
```
Looking into a fix now.

About node, interesting, I guess they turned reftypes on by default...

**Comment by kripken** [comment]
Fix in https://github.com/WebAssembly/binaryen/pull/4736. I verified it fixes the testcase here, the file runs properly after `wasm-opt -Oz` (and shrinks to less than half the original size).
