### ISSUE TITLE
Floating issue with UNREACHABLE executed report

### ISSUE THREAD

**Issue by igoriakovlev** [WebAssembly/binaryen#4719]
Hi.

I am facing an unstable behaviour of self-built [main](https://github.com/WebAssembly/binaryen/commit/093bf06e1115e84c4300eca91197dc31336ee3e5) branch binaryen for MacOs x86-64.

Half of the runs on **same** wasm file I got successful result but on other runs its `UNREACHABLE executed at binaryen/src/wasm/wasm-type.cpp:598!` . Sometimes (rare case) it is just a dump wasm text on stdout. I printed out this kind and it seems it change its value every run. I could share my .wasm file if needed for future investigation.

Ran it with next line:
wasm-opt --enable-nontrapping-float-to-int --enable-typed-function-references --enable-gc --enable-reference-types --enable-exception-handling --hybrid -O3 --inline-functions-with-loops --traps-never-happen --fast-math ./x.wasm -o ./xx.wasm

Thank you.

**Comment by kripken** [comment]
Sounds like a possible bug. If you can provide the wasm file we can try to reproduce.

If you can't provide it, then you can investigate this on your side in a few ways:
* Run `wasm-reduce` to get a minimal testcase that you can share.
* Build with sanitizers (at least ASan and UBSan) and run with them to see if they catch anything.
* Make a debug build and run in a debugger to get a proper stack trace.

**Comment by igoriakovlev** [comment]
You can get it here
https://drive.google.com/file/d/1ihDxL_k_ltB15tpjp4mARYTDMn9KF8Mk/view?usp=sharing

**Comment by tlively** [comment]
This sounds like it is probably related to whatever is going on with this disabled test: https://github.com/WebAssembly/binaryen/blob/main/test/gtest/type-builder.cpp#L370-L394

This issue does not reproduce on Linux and I haven't investigated it deeply yet.

**Comment by kripken** [comment]
I can reproduce this on linux, but it is flaky. Reduced command:
```
$ bin/wasm-opt -all --hybrid --remove-unused-brs
unexpected kind
UNREACHABLE executed at src/wasm/wasm-type.cpp:598!
Aborted
```
This only happens with `--hybrid`.
