### ISSUE TITLE
can asm2wasm producing i64s?

### ISSUE THREAD

**Issue by wanderer** [WebAssembly/binaryen#475]
if i use an `int64_t` and then compile to asm.js then to wasm vai asm2wasm I would expect that to see it using i64 locals. But its not. Is it possible to do this?

**Comment by kripken** [comment]
Not fully, it would be a very hard problem to see i64s that were split into i32s and merge them back together.

However, asm2wasm does do a little optimization here, specifically it turns some of the runtime library code, for i64 division, to use i64 native operations. This saves code size and can make it faster.

But the only way to get full optimized i64 usage is to compile i64s directly, which the new wasm backend can do.

**Comment by wanderer** [comment]
thanks @kripken
