### ISSUE TITLE
wasm-opt produces "debug_loc error"

### ISSUE THREAD

**Issue by martindevans** [WebAssembly/binaryen#4788]
Attempting to optimise [this file](https://github.com/WebAssembly/binaryen/files/9079208/sqlite.zip):

> PS C:\Users\Martin\Downloads\binary\binaryen-version_109\bin> .\wasm-opt.exe .\sqlite.wasm --output sqlite-small.wasm -O1

Produces this error:

> debug_loc error

This error doesn't give me any hint what might be wrong. As far as I can tell this file is valid, for example running it through one of the other tools (`wasm2js`) produces a reasonable output with no errors.

Other details:
 - Windows 10
 - `.\wasm-opt.exe --version` -> `wasm-opt version 109 (version_109)`

**Comment by kripken** [comment]
This likely means it contains DWARF that wasm-opt doesn't know how to handle (`debug_loc` is a DWARF section). DWARF support is pretty limited atm.

If you don't need the DWARF, you can remove it with `--strip-dwarf` which should also avoid that error.

**Comment by martindevans** [comment]
That works, thanks very much :)
