### ISSUE TITLE
wasm-metadce dump question

### ISSUE THREAD

**Issue by michelledaviest** [WebAssembly/binaryen#4836]
Hello, 

When running wasm-metadce on a wasm binary and dumping the new reachability graph, I noticed the following node:
```
node: func$74$74
  is function 74
  reaches: importId$fimport$0$81
```
What does the last number in target `importId$fimport$0$81` denote? So far, I've been able to glean that this is an imported function, with the function id 0, but 81 doesn't match anything in the wat file of the binary.

Thanks!

**Comment by kripken** [comment]
I think the last number (81 there) is just a unique id. Each node in the graph gets a different number. It's not necessary, but it makes debugging easier.

**Comment by michelledaviest** [comment]
Makes sense, thank you!
