### ISSUE TITLE
Visual C++ Exposing Type Conflicts for Lengths

### ISSUE THREAD

**Issue by BSalita** [WebAssembly/binaryen#485]
I'm beginning to compile 64-bit using Visual Studio 2015. The compiler is exposing all sorts of conflicts for length types; size_t vs unsigned vs int vs uint32_t, maybe other too. Problem is different C++ implementations/options can make any of these types larger or smaller than others. To harmonize, there's probably several hundred edits required.

I'm not quite sure where to start or what's acceptable. Here's a few examples.
1. `int i = strlen()` // problem is strlen returns size_t
2. `Ref& operator[](unsigned x);` // conflict for code[n] where n is of type size_t
3. `typedef uint32_t Index;` // problem is assigning int/size_t

What's the best way to harmonize these lengths? If this was my code, I would be inclined to favor size_t processing for example 1.  Change unsigned to size_t for example 2.  Experiment with Index being size_t to avoid size change overhead, although ultimately uint32_t may prove efficient and practical.

**Comment by kripken** [comment]
`size_t` for 1 and 2 sounds good. For 3, we have Index and Address types that have a 32-bit size, so those should stay, and I guess assigning a `size_t` to them should be done carefully - why is that happening? - and if it's valid, through a cast, I guess? Maybe a cast function that checks for overflow?

Need input from @jfbastien and @dschuff here.

**Comment by dschuff** [comment]
`size_t` for 1 and 2 are ok with me too. Often variables like that end up getting fed back into e.g. array index operations which means they were getting implicitly promoted back to `size_t` anyway. And you often want size_t or an unsigned type for loop counters too.
IMO the general principles should be that types like `Address` and `Index` that are properties of the target (i.e. wasm, and could be wasm32 or wasm64) should not have types that depend on the host (i.e. the machine running the interpreter or compiler). E.g. they should not be `size_t` or `int`. When we convert we might want overflow checks anyway. In a lot of those cases we could have extra overloads or templates (e.g. `U32LEB(size_t)` which checks before encoding or casting down).

**Comment by jfbastien** [comment]
I'd do:

1. `auto`
2. `size_t`
3. Agree with @dschuff, it's a property of the target, we should have a specific type for it.

**Comment by BSalita** [comment]
I'm unsure where we are on this. Do I need to take some action to get a merge?

**Comment by kripken** [comment]
@BSalita: are you referring to a specific PR? If we forgot about one (sometimes things get lost, sorry), please comment in it in that PR (which will email us).

**Comment by dschuff** [comment]
I just found the gcc warning flags `-Wconversion` and `-Wsign-conversion` (https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html) which looks pretty similar to the MSVC warnings you are seeing. If we do want to keep these conversion warnings in MSVC (and assumung the actual set of things they warn about overlaps enough), we should enable these on gcc and clang too.

**Comment by tlively** [comment]
Our CI is pretty strict about this kind of thing these days.
