### ISSUE TITLE
GC opcode support in C-API

### ISSUE THREAD

**Issue by xujuntwt95329** [WebAssembly/binaryen#4866]
Hi, I found there are some opcodes in C-API related to GC proposal:

https://github.com/WebAssembly/binaryen/blob/3d3350d789d909445c8d8d03545c50bc0ae416ef/src/binaryen-c.h#L928-L944

But most of them are marked as `TODO`

My question is:
- Is there any timeline for supporting GC opcode? 
- Or is there any branch which provides early GC supports?

Thanks!

**Comment by kripken** [comment]
ping @dcodeIO, I think you may have been working on the C API for GC-related things?

**Comment by dcodeIO** [comment]
Was planning to look into adding more instructions once array and struct types can be made with just the C API. Requires #4803 I think.

**Comment by xujuntwt95329** [comment]
@kripken @dcodeIO Thanks a lot! It is exciting that the PR you mentioned has been merged.

BTW, does C++ API has fully support for all GC related opcode now?

**Comment by kripken** [comment]
Yes, Wasm GC support is 100% usable today in Binaryen except for the C API.

**Comment by xujuntwt95329** [comment]
@kripken Thanks a lot! Looking forward to the completion of C-API for GC.

I'll close this issue since its solved.

**Comment by dcodeIO** [comment]
See: https://github.com/WebAssembly/binaryen/pull/4998
