### ISSUE TITLE
Use Index in std::maps in wasm-binary.h?

### ISSUE THREAD

**Issue by BSalita** [WebAssembly/binaryen#489]
While working on harmonizing the type of lengths, I see that my changes are suggesting that all the `std::map` in wasm-binary.h may need different (improved) types. Am I correct that these maps actually contain indexes and therefore should use type of Index instead of uint32_t or size_t? If so, I propose the following declarations.
1. `std::map<Index, Index> mappedLocals;`
2. `std::map<WasmType, Index> numLocalsByType;`
3. `std::map<WasmType, Index> currLocalsByType;`
4. `std::map<Name, Index> mappedImports;`
5. `std::map<Name, Index> mappedFunctions;`
6. `std::map<Index, std::vector<Call*>> functionCalls;`
7. `std::map<Export*, Index> exportIndexes;`

**Comment by BSalita** [comment]
Looks like the signatures of some functions in wasm-binary.h should also change.

1. `Index getImportIndex(Name name)`

2. `Index getFunctionIndex(Name name)`

**Comment by kripken** [comment]
Yes, all those look like correct changes.
