### ISSUE TITLE
Unknown symbol: $__stack_pointer

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/binaryen#49]
It looks like 112 many of the torture tests [are now failing](https://build.chromium.org/p/client.wasm.llvm/builders/linux/builds/1259/steps/Link%20LLVM%20Torture%20with%20s2wasm/logs/stdio) with:

```
Unknown symbol: $__stack_pointer
```

There already were a few failures before about unknown symbols, but `__stack_pointer` wasn't one of them.

Did things regress, or did error detection improve? If the later then  could we just add that to the list of known failures until it's fixed?

The tests are:
20000412-2.c.s 20000801-1.c.s 20001228-1.c.s 20010116-1.c.s 20010518-2.c.s 20010915-1.c.s 20020406-1.c.s 20020413-1.c.s 20021120-3.c.s 20021219-1.c.s 20030218-1.c.s 20030221-1.c.s 20030222-1.c.s 20030313-1.c.s 20030916-1.c.s 20031012-1.c.s 20031201-1.c.s 20040218-1.c.s 20041019-1.c.s 20041124-1.c.s 20041126-1.c.s 20050121-1.c.s 20050203-1.c.s 20050502-1.c.s 20050502-2.c.s 20060420-1.c.s 20070201-1.c.s 20070212-1.c.s 20070517-1.c.s 20071029-1.c.s 20071030-1.c.s 20071202-1.c.s 20071219-1.c.s 20080502-1.c.s 20080604-1.c.s 20090207-1.c.s 20100708-1.c.s 20101013-1.c.s 20111208-1.c.s 20111212-1.c.s 20120105-1.c.s 20120808-1.c.s 20120919-1.c.s 20121108-1.c.s 20131127-1.c.s 20140425-1.c.s 920411-1.c.s 920501-9.c.s 921110-1.c.s 930513-1.c.s 930622-2.c.s 930930-2.c.s 941014-2.c.s 950710-1.c.s 960215-1.c.s 960327-1.c.s 960513-1.c.s 980605-1.c.s 990513-1.c.s 990531-1.c.s 991228-1.c.s alloca-1.c.s builtin-prefetch-2.c.s cbrt.c.s conversion.c.s fprintf-1.c.s gofast.c.s memcpy-1.c.s pr15262.c.s pr15296.c.s pr20527-1.c.s pr27073.c.s pr27285.c.s pr29006.c.s pr33142.c.s pr33992.c.s pr34176.c.s pr35472.c.s pr36339.c.s pr36343.c.s pr37573.c.s pr38212.c.s pr38236.c.s pr39120.c.s pr41239.c.s pr42614.c.s pr42691.c.s pr43236.c.s pr43835.c.s pr44202-1.c.s pr44852.c.s pr45070.c.s pr49218.c.s pr49279.c.s pr51466.c.s pr52760.c.s pr52979-1.c.s pr52979-2.c.s pr54471.c.s pr54985.c.s pr56799.c.s pr57124.c.s pr57131.c.s pr59229.c.s pr59358.c.s pr60960.c.s printf-1.c.s regstack-1.c.s string-opt-17.c.s string-opt-18.c.s string-opt-5.c.s

**Comment by kripken** [comment]
Error detection improved.

Should we just special-case `$__stack_pointer`? Or is that a temporary hack in the backend?

**Comment by kripken** [comment]
I pushed a temporary hack, we can remove it if we want.
