### ISSUE TITLE
Option to remove unused imports with wasm-opt

### ISSUE THREAD

**Issue by anuraaga** [WebAssembly/binaryen#4911]
wasm-opt will currently remove code that references an import without removing the import itself. This is presumably because it is not possible to know statically whether an import is referenced by call_indirect or not. It would be nice to have an option to remove them when it's known that imports are never used with call_indirect in a particular codebase.

**Comment by kripken** [comment]
If an import (or any other function, also) appears in the table it won't be removed, that's true - is that what you mean? If it is not in the table it will be optimized out (by RemoveUnusedModuleElements).

**Comment by anuraaga** [comment]
Thanks @kripken - I'm sorry if I don't understand the wasm vocabulary well, I have attached my wasm file which is produced by `make build` [here](https://github.com/anuraaga/coraza-wasm-filter/blob/main/Makefile#L6) (with tinygo)

`wasm-objdump` shows `Table` holding just one func ref to `time.UnixNano`. The function I am concerned about, `wasi_snapshot_preview1.fd_filestat_get` doesn't seem to be in table, but I haven't been able to get `wasm-opt` to remove, either with `-Os -c` or `-Os -c --remove-unused-module-elements` (my understanding is these two options are equivalent). Looking through the `wat` with `wasm2wat`, I can see the function is only referenced by the import and not any code.

Would you expect wasm-opt to have automatically removed the import in this case? You'll see in the above link my approach to "stub" the imports out (using `sed`, I couldn't find a direct tool for it) so the wasm loads in an environment that doesn't provide them.

[mainraw.wasm.zip](https://github.com/WebAssembly/binaryen/files/9366881/mainraw.wasm.zip)

**Comment by kripken** [comment]
>  The function I am concerned about, wasi_snapshot_preview1.fd_filestat_get doesn't seem to be in table, but I haven't been able to get wasm-opt to remove, either with -Os -c or -Os -c --remove-unused-module-elements (my understanding is these two options are equivalent). Looking through the wat with wasm2wat, I can see the function is only referenced by the import and not any code.

Hmm, it does look used to me? Here are the relevant lines from `wasm-dis`:

```wat
 (import "wasi_snapshot_preview1" "fd_filestat_get" (func $__imported_wasi_snapshot_preview1_fd_filestat_get (param i32 i32) (result i32)))

[..]

 (func $__wasi_fd_filestat_get (param $0 i32) (param $1 i32) (result i32)
  (i32.and
   (call $__imported_wasi_snapshot_preview1_fd_filestat_get
    (local.get $0)
    (local.get $1)
   )
   (i32.const 65535)
  )
 )
```
That `call` instruction uses the import, so it can't be removed.

Note that the import name is `wasi_snapshot_preview1.fd_filestat_get` but the internal name is `$__imported_wasi_snapshot_preview1_fd_filestat_get`, which is what the import is called in the module, and how it is referred to by that call.

**Comment by anuraaga** [comment]
So sorry for the confusion @kripken I should have attached the result of wasm-opt as well. In the result we see that the dead code referencing the function was removed (great!), but the import is still leftover. I run `wasm-opt -Os -c build/mainraw.wasm -o build/mainopt.wasm` so I think the `-c` should have it converge even if it's supposed to take multiple passes, but it doesn't seem to be the case.

[mainopt.wasm.zip](https://github.com/WebAssembly/binaryen/files/9378370/mainopt.wasm.zip)

**Comment by kripken** [comment]
I still see the import being used:
```wat
 (import "wasi_snapshot_preview1" "fd_filestat_get" (func $fimport$15 (param i32 i32) (result i32)))
 [..]
 (func $360 (param $0 i32) (param $1 i32)
 [..]
        (call $fimport$15
```
Looks like that function `$360` is fairly large - it might contain the contents of several inlined functions. But anyhow, that import is called from there, which is why it can't be optimized out.

**Comment by anuraaga** [comment]
Sorry @kripken I missed those! Thanks for checking and sorry for the noise
