### ISSUE TITLE
[Suggestion] Refactor signatures to placeholder type specifiers

### ISSUE THREAD

**Issue by MaxGraey** [WebAssembly/binaryen#4967]
Use `auto` as much as possible for signatures:
```c++
void empty();
auto some() -> int;
auto tuple() -> std::pair<int32_t, std::string>;
auto optional() -> std::optional<std::string>;
auto (*ptr)() -> int;
```
instead:
```c++
void empty();
int some();
std::pair<int32_t, std::string> tuple();
std::optional<std::string> optional();
int (*ptr)();
```

**Motivation**

Full auto return type deduction may be a danger, but with placeholders it makes this safer and more readable at the same time due to `auto` and `void` have the same width and thus align all the function / instance names in a row on the same line.

@kripken  @tlively WDYT?

**Comment by tlively** [comment]
Are you proposing that we make this change uniformly over the entire codebase? I might be fine with that as long as we have consistent rules about where it is used. I do see some benefit in using the `auto` style, although the benefit is small enough that I wouldn't want to work on this myself. It would also take a while to get used to after the change.

**Comment by MaxGraey** [comment]
> Are you proposing that we make this change uniformly over the entire codebase?

Yes. And perhaps add according rule for clang's format

>  I do see some benefit in using the auto style, although the benefit is small enough that I wouldn't want to work on this myself

I could do that. I hope the clang format has something that will automate this. Otherwise, I'll just write my own script in python or js

**Comment by tlively** [comment]
@kripken and @aheejin as well, WDYT?

**Comment by kripken** [comment]
Interesting...

`void/auto` being the same size is maybe nice, but this does add more typing (it's strictly more characters), and isn't idiomatic C++ today (is it?). So I'm not sure it's worth it.

I do think Carbon is something to consider eventually, and this does look more like it. But Carbon plans to have automatic migration tools IIUC.

**Comment by MaxGraey** [comment]
Yes, then maybe you shouldn't change anything yet. I'm closing this issue. Thanks for feedback!
