### ISSUE TITLE
Import memory caused to `Fatal: Module::addMemory: 0 already exists`

### ISSUE THREAD

**Issue by MaxGraey** [WebAssembly/binaryen#4988]
After https://github.com/WebAssembly/binaryen/pull/4811 we find out that `BinaryenSetMemory` + `BinaryenAddMemoryImport` produces fatal error:
```
Fatal: Module::addMemory: 0 already exists
```

**Comment by kripken** [comment]
Sounds reasonable. But we can make it backwards compatible too, that is, by gracefully handling the case where the memory already exists. I think that would be best.
