### ISSUE TITLE
Fuzzer found a bug

### ISSUE THREAD

**Issue by MaxGraey** [WebAssembly/binaryen#4997]
`seed 5854391141410264343`

V8 version `10.7.76` (latest)

```
[CompareVMs] running d8
.../bin/wasm-opt /.../binaryen/out/test/a.wasm --emit-js-wrapper=/.../binaryen/out/test/a.wasm.js 
--enable-mutable-globals 
--enable-bulk-memory 
--enable-exception-handling 
--enable-tail-call 
--enable-reference-types 
--enable-gc 
--enable-typed-function-references 
--enable-extended-const 
--enable-strings 
--enable-multi-memories 
--nominal

warning: no passes specified, not doing any work
warning: no output file specified, not emitting output

/.../.jsvu/v8 /.../binaryen/out/test/a.wasm.js 
--wasm-staging 
--experimental-wasm-eh 
--experimental-wasm-compilation-hints 
--experimental-wasm-gc 
--experimental-wasm-typed-funcref 
--experimental-wasm-memory64 
--experimental-wasm-extended-const 
-- /.../binaryen/out/test/a.wasm
```

Unfortunately reduction don't work

**Comment by kripken** [comment]
I can't seem to reproduce a problem on my machine. Can you attach the files (`a.wasm.js` and `a.wasm` from that directory)?

**Comment by MaxGraey** [comment]
I still think it's issue of VMs comparison. Even with `10.7.76` I still have fuzzer errors relate to diff executions of v8 and binaryen

**Comment by MaxGraey** [comment]
@kripken could you make a hint which version of `v8` currently compatible with binaryen's interpreter?

**Comment by tlively** [comment]
If you don't want to build from source, [JSVU](https://github.com/GoogleChromeLabs/jsvu) currently installs 10.7.91, which should work.

**Comment by MaxGraey** [comment]
> If you don't want to build from source, [JSVU](https://github.com/GoogleChromeLabs/jsvu) currently installs 10.7.91, which should work.

Thanks! I use JSVU btw. Will check

**Comment by MaxGraey** [comment]
Can confirm. `10.7.91` works. Thanks everyone!
