### ISSUE TITLE
UNREACHABLE when optimizing module with `extern` conversions

### ISSUE THREAD

**Issue by askeksa-google** [WebAssembly/binaryen#4999]
When optimizing [this module](https://github.com/WebAssembly/binaryen/files/9462694/m.wasm.gz) with `wasm-opt -all -O1 --hybrid m.wasm -o mo.wasm` (using da24ef6ed7055f64299fce22a051ba0e85284c23), I get the message:
```
unhandled BrOn
UNREACHABLE executed at ~/checkout/binaryen/src/ir/gc-type-utils.h:121!
Aborted
```
Unrelatedly, it looks like there's a copy-paste mistake in the error message here. It's the same for `BrOn`, `RefIs` and `RefAs`.

**Comment by kripken** [comment]
Thanks! Fix in https://github.com/WebAssembly/binaryen/pull/5000. I verified that the optimizer does not crash on that binary with that PR (also at other opt levels).
