### ISSUE TITLE
asm2wasm: f64.const 18446744073709551616 ?

### ISSUE THREAD

**Issue by JSStats** [WebAssembly/binaryen#50]
Seeing this asm.js `_frexp(d1 * 18446744073709551616.0, i2)` converted into `(f64.mul (get_local $d1) (f64.const 18446744073709551616))`.

The integer `18446744073709551616` is `0x10000000000000000` and is outside the range of a u64, and might this be unexpected?

Perhaps it should have been `(f64.const 1.844674407370955e19)` or `(f64.const 4895412794951729152)`?

**Comment by kripken** [comment]
Looks like it does get rounded as a double, to `18446744073709552000`, which could be written as `18446744073709552e3`, saving one character. So I guess that asm.js is not fully optimize. And I guess asm2wasm's handling of number conversions keeps the number exactly as it is, even though it should be rounded.

This seems technically correct, so not something urgent to fix, but I agree it would be nice to represent numbers concisely in .wast files.
