### ISSUE TITLE
Turn shl+shr of the same amount into a mask

### ISSUE THREAD

**Issue by kripken** [WebAssembly/binaryen#5012]
E.g.
```wat
(i32.shl
 (i32.shr_u
  (local.get $0)
  (i32.const 4)
 )
 (i32.const 4)
)
 =->
(i32.and
 (local.get $0)
 (i32.const -16) ;; 0xfffffff0
)
```
We optimize the reverse, `x << 16 >> 16` becomes a sign-extend, but not this.

Found by the superoptimizer https://github.com/WebAssembly/binaryen/pull/4994 (for comparison to other findings: rule `#28`, benefit `11044`).

**Comment by MaxGraey** [comment]
Already made PR for this: https://github.com/WebAssembly/binaryen/pull/4996

**Comment by kripken** [comment]
Thanks @MaxGraey ! Reading now.
