### ISSUE TITLE
Fuzz error with null types

### ISSUE THREAD

**Issue by kripken** [WebAssembly/binaryen#5180]
```wat
(module
 (type $type$2 (struct_subtype (field (mut (ref null $type$2))) data))
 (type $type$0 (func_subtype func))
 (type $type$1 (func_subtype (param (ref $type$2) (ref null $type$2)) func))
 (type $type$3 (func_subtype (param funcref i32) (result funcref) func))
 (elem declare func $0)
 (func $0 (type $type$0)
  (nop)
 )
 (func $1 (type $type$1) (param $0 (ref $type$2)) (param $1 (ref null $type$2))
  (drop
   (struct.get $type$2 0
    (local.get $1)
   )
  )
 )
 (func $2 (type $type$3) (param $0 funcref) (param $1 i32) (result funcref)
  (call $1
   (ref.as_non_null
    (ref.null none)
   )
   (ref.as_non_null
    (ref.null none)
   )
  )
  (ref.func $0)
 )
)
```

```wat
$ wasm-opt a.wat -all --nominal --signature-refining --print --gto

(module
 (type $type$0 (func_subtype func))
 (type $type$1 (func_subtype (param (ref none) (ref none)) func))
 (type $type$3 (func_subtype (param funcref i32) (result (ref $type$0)) func))
 (elem declare func $0)
 (func $0 (type $type$0)
  (nop)
 )
 (func $1 (type $type$1) (param $0 (ref none)) (param $1 (ref none))
  (drop
   (block ;; (replaces something unreachable we can't emit)
    (drop
     (local.get $1)
    )
    (unreachable)
   )
  )
 )
 (func $2 (type $type$3) (param $0 funcref) (param $1 i32) (result (ref $type$0))
  (call $1
   (ref.as_non_null
    (ref.null none)
   )
   (ref.as_non_null
    (ref.null none)
   )
  )
  (ref.func $0)
 )
)

src/ir/type-updating.cpp:140: wasm::HeapType wasm::GlobalTypeRewriter::update()::CodeUpdater::getNew(wasm::HeapType): Assertion `oldToNewTypes.count(type)' failed.
```

The problem appears to be that `struct.get` that is printed as unreachable. It is printed as unreachable, but it isn't actually unreachable. `BINARYEN_PRINT_FULL=1` shows this:

```wat
 (func $1 (type $type$1) (param $0 (ref none)) (param $1 (ref none))
  [none] (drop
   [(ref null $struct.0)] (block ;; (replaces something unreachable we can't emit)
    [none] (drop
     [(ref none)] (local.get $1)
    )
    [unreachable] (unreachable)
   )
  )
 )
```

That is, signature refining turned the `struct.get` input into a null type. So we print it as unreachable. But the type of the expression was not updated, and still refers to the type that used to be returned here. When we run GTO, that ends up being the only place that refers to that type, and so we hit that assertion on not knowing how to map it.

It does look like if the type is null then we do not update the expression's type:

https://github.com/WebAssembly/binaryen/blob/899ffddd109710d0e8794aa7f0ce36aa0410407f/src/wasm/wasm.cpp#L1036-L1042

Perhaps we should update it to unreachable @tlively ? Do you remember why we don't do that already?

**Comment by tlively** [comment]
We don't finalize the expression as unreachable because that would put the binary and text parsers into unreachable mode and cause them to accept invalid programs. Generally we try to follow the spec when parsing input. Besides that I don't think there would be any downside to typing this as unreachable.

We should fix this by calling `include` on this type annotation in module-utils.cpp. That will include the type in the set of used types, but won't increase its use count.
