### ISSUE TITLE
GCC unused-variable

### ISSUE THREAD

**Issue by phated** [WebAssembly/binaryen#5189]
Related to #5188, I've been using `-Wno-unused-variable` since Binaryen v103 because it also started failing on the OPAM CI. The logs have since been pruned so I don't have that error log, nor am I sure if these issues have been fixed since.

Is there a way we can test this in CI without needing to cut another release to OPAM?

**Comment by kripken** [comment]
I think the best thing would be to add a CI run with that version of gcc. And/or to replace our existing one, depending if that's newer or older.

**Comment by phated** [comment]
Dug into this some more and it seems to happen with gcc 7 due to the `_` used to mark unused variables. Since this version of GCC is so old, it probably doesn't need to be supported and I'll just keep that flag in my custom builder.
