### ISSUE TITLE
wast output uses `ref.cast_static` instead of `ref.cast`

### ISSUE THREAD

**Issue by osa1** [WebAssembly/binaryen#5190]
I couldn't find anything about `ref.cast_static` instruction in any of the GC documents so asked around, and I think it was renamed to `ref.cast`, but `wasm-opt -S` still prints `ref.cast_static`.

**Comment by kripken** [comment]
The spec is not fully stable yet, and there are differences between it and the prototype impl doc which is here:

https://docs.google.com/document/d/1DklC3qVuOdLHSXB5UXghM_syCh-4cMinQ50ICiXnK3Q/edit#heading=h.9dwoku9340md

I think binaryen right now is closer to that. But as the spec is finalized everything will come into alignment.

**Comment by osa1** [comment]
Ah, so it will be renamed again to `cast_static`? Thanks.

**Comment by kripken** [comment]
I'm actually not sure in which way it will be renamed. I'd prefer the shorter name personally.
