### ISSUE TITLE
Negative relocations

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/binaryen#52]
It looks like s2wasm fails on the following GCC torture tests because of negative relocations:
```
20060905-1.c.s # $s-384
pr58209.c.s $buf-4
```

**Comment by jfbastien** [comment]
I can take a look.

**Comment by kripken** [comment]
Ah, I wasn't aware relocations could be negative. Should be as easy as finding the one or two places that look for '+' and handling things there. I can do it if you prefer.

**Comment by kripken** [comment]
Actually this hits some minor parsing annoyance, let me do this.

**Comment by kripken** [comment]
Done, this should be fixed.
