### ISSUE TITLE
TypeError: binaryenCAPI._BinaryenStringConst is not a function

### ISSUE THREAD

**Issue by yviansu** [WebAssembly/binaryen#5230]
### Background
I noticed that `BinaryenStringConst` has been implemented in `binaryen-c.cpp`:
```cpp
BinaryenExpressionRef BinaryenStringConst(BinaryenModuleRef module,
                                          const char* name) {
  return static_cast<Expression*>(
    Builder(*(Module*)module).makeStringConst(name));
}
```
What's more, I saw that `'StringConst'` has been added to `binaryen-js-post.js`:
```javascript
// Expression ids
Module['ExpressionIds'] = {};
[ 
  ...
  'StringConst',
  ...
].forEach(name => {
  Module['ExpressionIds'][name] = Module[name + 'Id'] = Module['_Binaryen' + name + 'Id']();
});
```

### Question
In [binaryen.js](https://github.com/AssemblyScript/binaryen.js), the function can't be used yet, so I want to add it to my own `binaryen.d.ts` file and `binaryen.js` file, so that I can use this function.
```javascript
// binaryen.d.ts

module 'binaryen';

export type ExpressionRef = number;
export type ModuleRef = number;

export declare function _BinaryenStringConst(
    module: ModuleRef,
    name: string,
): ExpressionRef;


// binaryen.js

export const {
    _BinaryenStringConst,
} = binaryen;

export default binaryen;
```
However, when I invoke the function `_BinaryenStringConst`, the error `TypeError: binaryenCAPI._BinaryenStringConst is not a function`  occurs, I also have tested other function like `_BinaryenCallIndirect`, it works well. 

Why this error happens? What can I do to fix it?

I would really appreciate it if you could reply me.

**Comment by kripken** [comment]
I think that method needs to be added to `src/js/binaryen.js-post.js`, but no one has gotten around to it yet. A PR would be welcome. Looking at the git history of that file would show updates for other instructions, which that PR could be similar to.

**Comment by yviansu** [comment]
> I think that method needs to be added to `src/js/binaryen.js-post.js`, but no one has gotten around to it yet. A PR would be welcome. Looking at the git history of that file would show updates for other instructions, which that PR could be similar to.

Thanks for your reply!
I have seen the previous PR, and I still have two questions.

Q1:
Actually, I don't know how the method is added to `src/js/binaryen.js-post.js`.
For example, In this [PR](https://github.com/WebAssembly/binaryen/pull/4973/files), I think the method `BinaryenFeatureMultiMemories` has been added to `src/js/binaryen.js-post.js` because `MultiMemories` has been added in line 173, which means function `_BinaryenFeatureMultiMemories` has been added to Module.
```
173    Module['Features'][name] = Module['_BinaryenFeature' + name]();
```
However, when I add the function `_BinaryenFeatureMultiMemories` to my own `binaryen.d.ts` file and `binaryen.js` file, I can not use it. An error occurs `TypeError: binaryenCAPI._BinaryenFeatureMultiMemories is not a function`, just the same as `_BinaryenStringConst`.

Q2:
In the list of `Module['ExpressionIds']`, for each name, `Module['ExpressionIds'][name] = Module[name + 'Id'] = Module['_Binaryen' + name + 'Id']()` is applyed, so there will exist `Module['_BinaryenConstId']`, `Module['_BinaryenCallIndirectId']` etc, `_BinaryenConst` and `_BinaryenCallIndirect` will not exsit. 
In this case, when I add the function `_BinaryenConst` and `_BinaryenCallIndirect` in my own `binaryen.d.ts` file and `binaryen.js` file, why can I use these two functions and no error occur?

**Comment by kripken** [comment]
The full process is to add to `src/js/binaryen.js-post.js` and then rebuild `binaryen.js`. Then it should be available. If it isn't perhaps grepping in the file can help - you should see something corresponding to what you added in `src/js/binaryen.js-post.js` (if not, perhaps there is a mistake in the file you are looking at). Another thing you can try is to remove a function and see it is removed from the build output, to make sure the build is working properly.

**Comment by kripken** [comment]
`scripts/emcc-tests.sh` has the build instructions and tests used on CI, which can be helpful.

**Comment by yviansu** [comment]
Got it! 
Thanks for your help!
