### ISSUE TITLE
Is `wasm-as` supports `stringref` yet？

### ISSUE THREAD

**Issue by yviansu** [WebAssembly/binaryen#5233]
I have written the below wast code:
```
(module
    (memory 10 10)
    (type $stringref_=>_stringref (func (param stringref)(result stringref)))
    (func $stringTest (param $a stringref) (result stringref)
        (return
            (local.set $a
                (string.concat
                    (local.get $a)
                    (string.const "foo")
                )
            )
        )
    )
)
```
I have built the latest code, and `wasm-as` has been generated in `bin`, when I run command `./wasm-as stringref.wast --enable-strings -o stringref.wasm`, an error occurs:
```
[wasm-validator error in function stringTest] unexpected false: all used types should be allowed, on 
stringTest
[wasm-validator error in function stringTest] function result must match, if function has returns, on 
(return
 (local.set $0
  (string.concat
   (local.get $0)
   (string.const "foo")
  )
 )
)
Fatal: Error: input module is not valid.
```

It seems that `wasm-as` can not handle `stringref` even if I use `--enable-strings` flag.
What's more, the provided file `/test/lit/strings.wast` can't be handled too.

So, I guess maybe the `wasm-as` has not supported `stringref` yet?

**Comment by kripken** [comment]
`all used types should be allowed` means that you must allow those types manually. Try `wasm-as -all` which enables all features.

**Comment by kripken** [comment]
We should have better error messages here. What I think is happening is that `--enable-strings` is not enough as those types and instructions also need `--enable-reference-types`.

**Comment by yviansu** [comment]
Get it!
Thanks for your help!
