### ISSUE TITLE
wasm-as + wasm-dis does not round-trip loop precisely

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/binaryen#525]
This is the same as #522 but in reverse; with the fix in #523, if the original loop has a block, it is removed.

So on this input:

```
(module
  (memory 0)
  (type $0 (func (param f64) (result f64)))
  (export "foo" $foo)
  (func $foo (type $0) (param $var$0 f64) (result f64)
    (loop $label$0 $label$1
      (block $label$2
        (get_local $var$0)
        (get_local $var$0)
      )
    )
  )
)
```

wasm-as + wasm-dis emits this:

```
(module
  (memory 0)
  (type $0 (func (param f64) (result f64)))
  (export "foo" $foo)
  (func $foo (type $0) (param $var$0 f64) (result f64)
    (loop $label$0 $label$1
      (get_local $var$0)
      (get_local $var$0)
    )
  )
)
```

**Comment by kripken** [comment]
Yes, the code does optimize away some blocks - it goes further than just avoiding unnecessary ones.

Is this a problem, though? For the second time today, I feel I must say: bug, or... feature? :)

**Comment by sunfishcode** [comment]
Yes, I consider it a bug. If I'm debugging a wasm binary, I want to see exactly what's in the binary, even if it is suboptimal :-).

**Comment by kripken** [comment]
Fair enough, agreed.

**Comment by tlively** [comment]
Binaryen still doesn't round trip binaries with full fidelity, but that's now firmly established as WAI. There are other tools that are better for use cases that need round tripping.
