### ISSUE TITLE
Add a sign extension lowering pass

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/binaryen#5250]
The llvm default dfeature set was recently added in https://reviews.llvm.org/D125728.

I'm working on an emscripten change that will automatically disabled these new features if the user targets older browsers: https://github.com/emscripten-core/emscripten/pull/17690

We decided the simplest way to implement this "disabling" would be as a binaryen pass to lower away the new feature(s).

**Comment by sbc100** [comment]
@kripken maybe you fancy taking this on?

**Comment by kripken** [comment]
Sure, if no one else wants to, I can.
