### ISSUE TITLE
How to generate `array.new_data` opcode

### ISSUE THREAD

**Issue by yviansu** [WebAssembly/binaryen#5270]
`array.new` opcode has been implemented through `makeArrayNew`, and `array.new_data` opcode has been implemented through `makeArrayNewSeg`.

In `src/binaryen-c.app`, `makeArrayNew` is wrapped by `BinaryenArrayNew`, so we can invoke `BinaryenArrayNew` to generate `array.new`. However, I don't find the corresponding api related to `makeArrayNewSeg`, so I don't know how to generate `array.new_data` opcode.

In my opinion, it is reasonable to have `BinaryenArraySeg` in the `src/binaryen-c.app` file, am I right?

**Comment by kripken** [comment]
Yes, some of the newer methods do not have C API support yet. Looks like there is a TODO:

https://github.com/WebAssembly/binaryen/blob/590f63782b9ee6307a2bc0e21917001a66ba16ba/src/binaryen-c.h#L1075

**Comment by yviansu** [comment]
Got it, thanks~
