### ISSUE TITLE
Dead code elimination is too agressive on struct globals [Closed World]

### ISSUE THREAD

**Issue by chambart** [WebAssembly/binaryen#5292]
When using `wasm-opt` (with `--enable-gc --enable-reference-types`) on the following `.wast` with optimisation level `-01` and up, there seems to be some dead code elimination pass that consider the function `$f` unreachable.

I suppose that the criterion for reachability of a function code is: it is reachable if it is called by a reachable function, by start or part of a function table. But with the gc extension, functions can also be part of exported globals.
```WASM
(module
  (type $f
    (func (param (ref eq)) (result (ref eq))))
  (type $s
    (struct (field (ref $f))))

  (elem declare func $f)
  (func $f (param $x (ref eq)) (result (ref eq))
    (local.get $x))

  (global $glob (export "g") (ref $s) (struct.new $s (ref.func $f)))
)
```

The produced code with `-01` is
```WASM
(module
 (type $f (func (param (ref eq)) (result (ref eq))))
 (type $s (struct (field (ref $f))))
 (global $glob (ref $s) (struct.new $s
  (ref.func $f)
 ))
 (export "g" (global $glob))
 (func $f (type $f) (param $0 (ref eq)) (result (ref eq))
  (unreachable)
 )
)
```

This was tested on the current tree (https://github.com/WebAssembly/binaryen/commit/2c0fb8c513b3534576383d250c593a9bd28347e3)

**Comment by kripken** [comment]
I believe this is due to our current closed-world assumption (assuming a closed world, without any `call_ref` to the type of `$f`, it must be unreachable code). We've been planning to add a flag to turn that on and off, but so far haven't had use cases which require it. If it's necessary now perhaps we should prioritize that.

Can you describe your use case here? (what are you compiling to wasm GC, and how the outside code - JS? - wants to interact with it)

**Comment by chambart** [comment]
This is an hand written example, but this is a pattern expected to happen from compiling OCaml.
This would be just one module out of a whole program, and I don't plan for the compiler to require a whole program linking phase. The closed-world assumption would not hold in my use case.

**Comment by kripken** [comment]
Interesting, thanks for the info!

How would the separate modules communicate? We don't have any wasm GC toolchains that do that atm, so I'd like to learn more about that, if you have specific ideas there. Were you thinking to link the wasm modules together using imports and exports, or something involving JS?

**Comment by chambart** [comment]
The plan is just to use exports and imports. The reason for doing it like that would mainly be simplicity because it correspond more closely to what the native compiler does and the ability to dynamically link modules afterwards.

**Comment by kripken** [comment]
I see, sounds good. In spec discussions there were various questions about how that would work in terms of communicating types between separately-compiled modules, so I'm curious to see how that ends up looking in practice.

As for the immediate issue here, after thinking on it I wonder if the simplest solution is to use the `--nominal` flag as an indication of closed world. That might make sense since the point of the isorecursive type system is to share types between modules, while nominal mode assumes no such sharing. Concretely, we would disable certain passes or parts of passes when in isorecursive mode and not nominal. So nominal would mean "nominal types + no sharing of GC or function references with the outside." @tlively what do you think?

**Comment by tlively** [comment]
`--nominal` Is unusable when there are multiple WasmGC modules trying to work together, but I think we should add a separate option for controlling how we expect data to be observed outside the module. Even if it doesn’t in the MVP, we do expect in the long run for the JS API to have richer access to GC data, so parts of external types may need to be preserved even when there is only one Wasm module.

**Comment by kripken** [comment]
Ok, let's move forward with a new flag now then. How about `--closed-world`, which is default off? Or in theory we could have separate flags for "GC data does not escape" (`--closed-world-gc`?) and "functions do not escape" (`--closed-world-funcs`?) (the latter is immediately relevant to this issue, but with separate modules both flags would be needed in general).

Another option might be to add an analysis to see if GC types and functions can escape or not. But passing `externref` is common, and I see j2wasm also passes `dataref` in one place, so I think we must add a flag?

**Comment by tlively** [comment]
> How about `--closed-world`, which is default off?

Sounds good, but the tricky part will be determining the right semantics for the flag and absence of the flag. We don't want to be unnecessarily pessimistic. There seems to be a spectrum/lattice of options here:

1. Maximally open world: make no assumptions. Any data that escapes can be arbitrarily converted, cast, inspected, and modified by the external environment. Optimizing types is only allowed if we can prove that no value of that type (or any of its subtypes) escapes the module, including as `externref`.'

2. Partially closed/open world (clopen world?): Open world except that data that escapes as `externref` (or possibly any other abstract type?) is assumed not be inspected, converted, or cast by the environment.

3. Readonly world: Assume the environment can arbitrarily convert, cast, and inspect data that escapes, but will never modify it. This allows us to preserve the original types on the boundary but use optimized versions of the types internally.

4. Maximally closed world: Assume that the external environment only holds data as abstract types (e.g. dataref), only inspects data via exported functions, and does not call any functions references (which would require casting).

In any of the open world scenarios, I would still expect us to perform an analysis to see what types escape and still try to optimize any types that we can prove do not escape. I expect that this will be worth the additional effort over just skipping optimizations, at least in the medium to long term.

I think it's reasonable for the `--closed-world` flag to have the "maximally closed world" semantics above and the absence of the `--closed-world` flag to have the "maximally open world" semantics above. (Although maybe we should ignore data escaping as `externref` by default?) In the long run, I hope we can support in-between options via fine-grained annotations on type definitions.

**Comment by kripken** [comment]
Sounds good, I think we're on the same page here. I'll get started with the maximally closed world flag.

**Comment by kripken** [comment]
@chambart After that last PR landed this should now be fixed. Let us know if you find any other issues!

**Comment by bashor** [comment]
> does not call any functions references (which would require casting).

@tlively @kripken could you please clarify this part?
Does it mean that functions leaked to JS through `ref.func` still could be removed by binaryen?

**Comment by kripken** [comment]
@bashor 

They cannot be removed, as the module would not validate (the `ref.func` has to refer to something valid).

However, in closed world, we assume the outside does not interact with the reference's contents - it only passes the reference around - which lets us modify the internals of types. For example, in closed world we can remove/refine parameters, which would not be possible if code outside the module called the function. A lot of the benefit of closed world comes from that.

Docs are here:

https://github.com/WebAssembly/binaryen/blob/90440820b0652ddf0450f9731d5076ab45b8ee4c/src/pass.h#L199-L209

(That is the current status. @tlively has some ideas for refining/improving this mode.)

**Comment by bashor** [comment]
We would like to use a reference to a function for calling `kotlin.FunctionN` implementations from JS side.
Currently, we are exporting these helper functions from the module, which "pollute" the module's exports and, more importantly, prevent some optimizations, even if the exported function is no longer reachable after binaryen optimizations.

**Comment by kripken** [comment]
@bashor what does the outside do - collect those functions, and call them on demand by an index, something like that?

If so, such outside calls are not compatible with closed-world atm, which assumes we see all the calls etc. in the single closed module. @tlively I remember you had ideas for per-type annotations for closed/open - perhaps we could consider something similar for functions, marking specific ones as "outside-called"?

**Comment by bashor** [comment]
@kripken I'm wondering if there is a way to mark a function, aside from export, so it prevents removing a function and modifying its signature.

**Comment by kripken** [comment]
@bashor atm there isn't a proper way to mark functions like that in closed world, we would need to design a new feature (which I think could be consistent with @tlively 's other ideas for extending closed world). But, if you want a workaround for now, then I think that is possible: we just need to make the function look callable by reference. This should be enough:
1. Take a `ref.func` of the function.
2. Write it to a non-fixed location in a table.
3. Do a call_indirect of that table with a non-fixed index.

For example,
```wat

(table $keep_unchanged funcref)

(func $keep_unchanged_1 (export "keep_unchanged_1") (param $x i32)
  (table.set $keep_unchanged (local.get $x) (ref.func $your_function))
)

(func $keep_unchanged_2 (export "keep_unchanged_2") (param $x i32)
  (drop (call_indirect $keep_unchanged (type $your_function_type) (local.get $x)))
)
```
Those two exports don't need to be called from the outside, but their existence is enough to prevent optimization.

(This pattern can be shortened, e.g. multiple functions could be handled at once, etc., but you do need to call_indirect each relevant signature.)
