### ISSUE TITLE
Debug Assertion Failed in binaryen-unitests.exe TestOracleMinimal

### ISSUE THREAD

**Issue by olivier-fs** [WebAssembly/binaryen#5312]
Platform : Microsoft Windows 10, Visual Studio Enterprise 2019, CMake 3.25.1

Having opened issue [#5291](https://github.com/WebAssembly/binaryen/issues/5291), and being unable to solve it in Release configuration, I switched to Debug build.

But now with binaryen-unittests I stumble on another issue way before the _LexerTest.LexNan_ test that failed in Release mode :
```
$ cd ~/build/cpp/www-git/binaryen/bin && ./binaryen-unittests.exe
Running main() from C:\Users\olivier\dev\cpp\www-git\binaryen\third_party\googletest\googletest\src\gtest_main.cc
[==========] Running 52 tests from 5 test suites.
[----------] Global test environment set-up.
[----------] 9 tests from PossibleContentsTest
[ RUN      ] PossibleContentsTest.TestComparisons
[       OK ] PossibleContentsTest.TestComparisons (5 ms)
[ RUN      ] PossibleContentsTest.TestHash
[       OK ] PossibleContentsTest.TestHash (2 ms)
[ RUN      ] PossibleContentsTest.TestCombinations
[       OK ] PossibleContentsTest.TestCombinations (4 ms)
[ RUN      ] PossibleContentsTest.TestOracleMinimal
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\xstring(1348) : Assertion failed: string_view subscript out of range
```

The problem is in TestOracleMinimal - possible-contents.cpp L275 :
```
  auto wasm = parse(R"(
    (module
      (global $null (ref null any) (ref.null any))
      (global $something i32 (i32.const 42))
    )
  )");
```

Tracing into parse() finally brings us into wasm-s-parser.cpp L1154 :
```
Type SExpressionWasmBuilder::stringToType(std::string_view str,
                                          bool allowError,
                                          bool prefix) {
  if (str.size() >= 3) {
    if (str[0] == 'i') {
      if (str[1] == '3' && str[2] == '2' && (prefix || str[3] == 0)) {
        return Type::i32;
      }
      if (str[1] == '6' && str[2] == '4' && (prefix || str[3] == 0)) {
        return Type::i64;
      }
    }
```

When str is "i32", size == 3.
Isn't the MSVC debugger (+ debug std library) rightfully choking on str[3] == 0 ?
Of course the byte at offset 3 is 00 as the string is null-terminated, but is the string_view allowed to peek "one byte further" ?

**Comment by olivier-fs** [comment]
Ran the test suite with your commit and I confirm you fixed it :-)

Now it seems something similar happens in another test :

[==========] Running 52 tests from 5 test suites.
[----------] Global test environment set-up.
[----------] 9 tests from PossibleContentsTest
[ RUN      ] PossibleContentsTest.TestComparisons
[       OK ] PossibleContentsTest.TestComparisons (2 ms)
[ RUN      ] PossibleContentsTest.TestHash
[       OK ] PossibleContentsTest.TestHash (0 ms)
[ RUN      ] PossibleContentsTest.TestCombinations
[       OK ] PossibleContentsTest.TestCombinations (1 ms)
**[ RUN      ] PossibleContentsTest.TestOracleMinimal
[       OK ] PossibleContentsTest.TestOracleMinimal (16 ms)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<====  FIXED !**
[ RUN      ] PossibleContentsTest.TestIntersection
[       OK ] PossibleContentsTest.TestIntersection (0 ms)
[ RUN      ] PossibleContentsTest.TestIntersectWithCombinations
[       OK ] PossibleContentsTest.TestIntersectWithCombinations (820 ms)
[ RUN      ] PossibleContentsTest.TestStructCones
[       OK ] PossibleContentsTest.TestStructCones (2 ms)
[ RUN      ] PossibleContentsTest.TestOracleManyTypes
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\xstring(1348) : 
Assertion failed: string_view subscript out of range


I hope this will be quite not too hard, alike this "buf[bufsize] == somebyte" pattern.
I don't want to harass you, so I'll investigate a bit at this one and try to report meaningful data in another issue, as this one is rightfully closed.

**Comment by tlively** [comment]
This is great, thanks for the bug reports!

**Comment by olivier-fs** [comment]
My pleasure to help in return a project that is helping me :-)

I'm trying to bring more WASM to projects I'm working on ; mostly Rust, because even if I'm working with cpp for a lonnng time I've never had the oppotunity to do real projects in emscripten :-(

I'll be pleased to report issues with MSVC/cl.exe, as FWIU it's not in the CI/CD toolchain for now.
