### ISSUE TITLE
Emit minimal rec groups?

### ISSUE THREAD

**Issue by askeksa-google** [WebAssembly/binaryen#5334]
Due to the [recent change in V8](https://chromium-review.googlesource.com/c/v8/v8/+/4079097) to require function types produced by `WebAssembly.Function` to be declared in singleton rec groups, I have added such a singleton rec group to the output of dart2wasm.

For optimizing the output of dart2wasm with wasm-opt, I usually use `--nominal` due to the extra type precision it confers compared to `--hybrid`. However, if I use `--nominal`, the output types are placed in a single rec group, breaking the use of `WebAssembly.Function`. The same thing happens with `--hybrid` combined with `--type-merging`.

Would it be feasible for Binaryen to (maybe optionally) generate minimal recursion groups from the set of types present in the output program, or in some other way preserve such singletons?

**Comment by tlively** [comment]
`--nominal` and `--hybrid` will be going away soon (in favor of implementing just the single standard type system) and will be superseded for these optimization purposes by the new `--closed-world` and `--open-world` flags. Right now any optimization that changes any type will produce a single large rec group containing all the types (irrespective of type system), so those passes aren't run at all with `--open-world`. What we need to do for your use case is provide a way to mark the singleton type as public so that it won't be modified by optimizations. cc @kripken.

**Comment by kripken** [comment]
To make sure I follow, is the issue that JS is making a new `WebAssembly.Function` and then passing that into wasm where it must have the same wasm type as an existing type? That is, we need a way for wasm to call new functions generated by JS. And the idea is that each such function's type is in a singleton rec group, so calling a type declared in the same way in the wasm would work (as the singleton rec group in wasm and in JS get merged).

If so then this is kind of a mixed scenario with closed and open, as @tlively said. Do we even have an idea of how to mark a type as public? My thinking was focused on a single global flag for closed/open.

**Comment by tlively** [comment]
Ultimately I'd love to have `@public` and `@private` attributes we can attach to types in the text format and corresponding annotations in the binary format. For now, maybe we could take a list of public or private type names on the command line (or via response files)? That requires types have names, but it might be good enough for now.

**Comment by tlively** [comment]
The general calculation of minimal rec groups would require finding the SCCs, then merging them back together as necessary to maintain distinct type identities. After optimizations like TypeSSA (if we extended it to support function types), dead argument elimination, etc. there would be no guarantee that a general function type would be unmodified and in a singleton group, so that might work for now, but it would also be a fragile solution.

**Comment by askeksa-google** [comment]
Yes, it's not a complete solution; it's just for unblocking this particular use case. For that, though, I don't see it as particularly fragile. Do you envision any Binaryen optimization (in the closed-world scenario) that would change the function type of an imported function whose signature only contains abstract ref types and non-ref types?

**Comment by askeksa-google** [comment]
Btw, I ran into another obstacle related to this change: importing functions exported from a separate module compiled from C++. With the recent V8 change, those imports also need to have types in singleton rec groups. That problem could be solved in the same way, since those signatures only contain non-ref types.

**Comment by kripken** [comment]
@askeksa-google I'd like to know more about the use case here. What type of functions are these on the JS side?

In particular, if performance is not absolutely critical for them, and they are known ahead of time, then another option meanwhile could be to emit wasm wrappers (where the wrapper does a call to an import).

**Comment by tlively** [comment]
Special casing import and export signatures with exclusively non-ref types is probably reasonable.

**Comment by askeksa-google** [comment]
> Special casing import and export signatures with exclusively non-ref types is probably reasonable.

If that would be expanded to also include abstract ref types (`externref` and `funcref` in particular), it would cover my use case.

**Comment by tlively** [comment]
After a lot of discussion, @kripken and I decided that we simply shouldn't modify any function type on the module boundary, even in closed world mode. To avoid accidentally inhibiting type optimizations, we're also adding extra validation in closed world mode that no types besides those function types appear on the boundary. This is implemented in https://github.com/WebAssembly/binaryen/pull/5347.

**Comment by tlively** [comment]
FWIW we now have a --minimize-rec-group pass that reconstructs minimial rec groups.
