### ISSUE TITLE
Does binaryen support `end` opcode?

### ISSUE THREAD

**Issue by yviansu** [WebAssembly/binaryen#5341]
If I manually add `end` opcode to the function in the wat file, when using `wasm-as` to convert the wat file to a wasm file, an error occurs `[parse exception: end (at 11:4)]Fatal: error in parsing input`. 

The origin wat file is a valid file, and can be convert to wasm file successfully, so I wonder does binaryen support `end` opcode?

**Comment by tlively** [comment]
No, Binaryen only supports the fully folded instruction format, which never uses `end`. I have an ongoing project to write a new parser for Binaryen that will support the full standard text format.
