### ISSUE TITLE
What's `array.new`'s opcode?

### ISSUE THREAD

**Issue by yviansu** [WebAssembly/binaryen#5348]
In the [gc proposal](https://github.com/WebAssembly/gc/blob/main/proposals/gc/MVP.md), I did not find the bytecode corresponding to `array.new`. When I run the wasm code containing `array.new` with WebAssembly runtime, the error prompts 'missing opcode 0xfb1b'. However, this bytecode corresponds to `array.new_canon_data` in the gc proposal, so I am very confused.

Are `array.new` and `array.new_canon_data` the same? How about `array.new_data` in binaryen and `array.new_canon ` in gc proposal?

**Comment by tlively** [comment]
The instruction names binaryen uses are slightly different from what the upstream spec docs use. If you remove "canon" from the upstream names, you should generally get the matching binaryen names, so binaryen's `array.new` is the same as the upstream `array.new_canon`.

**Comment by yviansu** [comment]
Got it, thanks~
