### ISSUE TITLE
Make operator bool explicit (and avoid potential silent failure in C++20 with operator<=>)

### ISSUE THREAD

**Issue by higher-performance** [WebAssembly/binaryen#5370]
`wasm::Name` has an implicit `bool` conversion operator:
https://github.com/WebAssembly/binaryen/blob/94a45c6aba605f0f7e0a2fac227a2dd7c03a391f/src/support/istring.h#L70

In general this is risky, so it would be great if it was made explicit. In particular, though, it appears that this may potentially break in C++20, as `std::pair<wasm::Name, wasm::Name>` is compared via `operator<` internally:
https://github.com/WebAssembly/binaryen/blob/94a45c6aba605f0f7e0a2fac227a2dd7c03a391f/src/passes/DuplicateImportElimination.cpp#L41

But `std::pair` internally attempts to use `operator<=>` where possible, meaning it would do so via the implicit conversion to `bool`, which seems like a bug. Adding `explicit` should avoid this.

**Comment by tlively** [comment]
Thanks for the report! Would you like to submit a PR for this?
