### ISSUE TITLE
Fuzz bug on "ref.cast null on non-nullable input not yet supported"

### ISSUE THREAD

**Issue by kripken** [WebAssembly/binaryen#5382]
```wat
(module
 (rec
  (type ${i32} (struct (field i32)))
  (type $none_=>_ref?|{i32}| (func (result (ref null ${i32}))))
 )
 (func $0 (type $none_=>_ref?|{i32}|) (result (ref null ${i32}))
  (local $0 (ref null ${i32}))
  (ref.cast null ${i32}
   (local.tee $0
    (ref.as_non_null
     (ref.null none)
    )
   )
  )
 )
)
```
STR:
```
$ bin/wasm-opt a.wat -all --coalesce-locals --roundtrip
[parse exception: ref.cast null on non-nullable input not yet supported (at 0:40)]
Fatal: error in parsing wasm binary
```

cc @tlively

**Comment by kripken** [comment]
Looks like that pass changes the cast input from nullable to non-nullable. I guess the issue is that your changes to `cast null` are in the middle atm @tlively ? Or do we need some kind of workaround here?

**Comment by tlively** [comment]
I'll look into a PR to have CoalesceLocals update the cast type so we don't lose type information. In the long run, `(ref.cast null (ref $X))` should be valid to parse, but we never want to emit it, so perhaps the validation error should stay.

**Comment by tlively** [comment]
Actually, it would be super unscalable if every pass that could convert a value from nullable to non-nullable. I'll look into a better solution.

**Comment by tlively** [comment]
Oh, this is a parse error from round trip, not a validation error. Then yes, this is just because we're half way through the transition to the new cast instructions.
