### ISSUE TITLE
How to access wasm2js bulk memory

### ISSUE THREAD

**Issue by willcohen** [WebAssembly/binaryen#5390]
In attempting to load a wasm2js-generated js file on graaljs, I hit the following error:

```
failed to compile wasm module: TypeError: Cannot read property 'buffer' of undefined
Execution error (PolyglotException) at <js>/asmFunc (src.js:493).
TypeError: Cannot read property 'buffer' of undefined
```

It's referring to these lines in the transpiled js, implying that the env.memory section is undefined.
```
function asmFunc(env) {
 var memory = env.memory;
 var buffer = memory.buffer;
```

This error occurs when using the shell environment, which I suppose graal isn't, but running the transpilation without setting an env fails with `Aborted(Assertion failed: shell environment detected but not enabled at build time.  Add 'shell' to `-sENVIRONMENT` to enable.)`

Should I be using a different environment, does this mean that the shell environment needs something else to generate a `WebAssembly.Memory`, or does there need to be an entirely new graal environment?

**Comment by willcohen** [comment]
I should note that graalwasm loads the wasm fine and can handle the bulk memory, but since graalwasm isn't available as a standalone item, being able to run a js file as a fallback still has a use case. The error continues with `-s SHARED_MEMORY=1`, which I assume is also needed.

**Comment by kripken** [comment]
Yes, if graaljs is not close enough to either the node or shell environments in Emscripten, then something will need to be done. One option might be to add some polyfills right before loading the js+wasm, to make it look like either node or a shell. See this related issue:

https://github.com/emscripten-core/emscripten/issues/12203

As mentioned there, web/worker/node/shell used to be enough, but these days there is also deno, bun, and more (like graaljs in fact) so we probably need a more scalable solution. The idea in that issue would make it hopefully simple to add such a "polyfill file" for something like graaljs.

**Comment by willcohen** [comment]
Excellent, many thanks -- I think this gets me much of the way there. Looks like this may actually be more of an emscripten issue, but before I open another issue there, seeing if I can find the precise issue. The graal stack trace is:
```
1. Unhandled org.graalvm.polyglot.PolyglotException
   TypeError: Cannot read property 'buffer' of undefined

                    src.js:  411  <js>/asmFunc
                    src.js:873854  <js>/instantiate
                    src.js:  342  <js>/Instance
                    src.js:874495  <js>/instantiateSync
                    src.js:874552  <js>/createWasm
                    src.js:879540  <js>/:program
```
Tracing through the -O0 file, the failures are as follows:
`asmFunc`'s env doesn't have a memory:
<img width="270" alt="Screenshot 2023-01-05 at 11 05 02 AM" src="https://user-images.githubusercontent.com/5185341/210825861-3513ae3e-3865-4893-ad71-8c094ec5dd1d.png">

The env is derived from `asmLibraryArg`:
<img width="348" alt="Screenshot 2023-01-05 at 11 06 10 AM" src="https://user-images.githubusercontent.com/5185341/210826100-7616bd08-5027-4380-b301-d85719fb6cb8.png">

`asmLibraryArg` comes from `instantiate`:
<img width="379" alt="Screenshot 2023-01-05 at 11 07 50 AM" src="https://user-images.githubusercontent.com/5185341/210826451-7fa1697e-38f0-4743-91d0-9380a06e1a54.png">

`asmLibraryArg`'s memory comes from `wasmMemory`:
<img width="458" alt="Screenshot 2023-01-05 at 11 11 51 AM" src="https://user-images.githubusercontent.com/5185341/210827400-79ad7bbd-c2ec-4969-ab03-e09e77655ce1.png">

This requires `WebAssembly.Memory`:
<img width="409" alt="Screenshot 2023-01-05 at 11 13 02 AM" src="https://user-images.githubusercontent.com/5185341/210827635-4add2744-5704-4f5d-b263-b56e5a8c7045.png">

Implying that something about the creation of the buffer by the emscripten js might be where the failure happens:
<img width="459" alt="Screenshot 2023-01-05 at 11 14 34 AM" src="https://user-images.githubusercontent.com/5185341/210827958-7d722f41-3c49-41e4-a3f3-fbaf7966b19d.png">

I am passing a Graal/native-backed-and-proxied-to js `ArrayBuffer` via `Module['buffer']` as pre-js (as noted [here](https://emscripten.org/docs/api_reference/module.html#Module.buffer)) which should be the graal-friendly way to do this, but it doesn't seem like it's being called or referenced anywhere. I do see the [changelog](https://emscripten.org/docs/api_reference/module.html#Module.buffer) mentioning a while back that `Module.buffer` was a removed internal detail a while back.

Do you know if there is another preferred way to pass a non-wasm `ArrayBuffer`?

**Comment by willcohen** [comment]
Using the emcc options at https://github.com/emscripten-core/emscripten/blob/a6e8d85e2a70aac8dfaa9e96e92491d4e350736e/test/test_browser.py#L4582 and adding an INITIAL_MEMORY to the pre-js Module per https://github.com/emscripten-core/emscripten/blob/main/test/test_preallocated_heap_shell.html#L79-L80, the error continues.

That said, given that the functionality seems to be present and actively tested, it's probably just an incantation problem on my end somewhere with the flags or options rather than a emscripten bug.

**Comment by willcohen** [comment]
Closing in favor of https://github.com/emscripten-core/emscripten/issues/18474.
