### ISSUE TITLE
failed to create a struct type with mutable fields

### ISSUE THREAD

**Issue by zhenweijin** [WebAssembly/binaryen#5468]
Hi,
I want create a struct type with mutable fields by using `TypeBuilderSetStructType`, `TypeBuilderBuildAndDispose`  as the code snippet below:

```typescript
export function initStructType(
    fieldTypesList: Array<binaryen.TypeRef>,
    fieldPackedTypesList: Array<binaryen.PackedType>,
    nullable: binaryen.bool,
): typeInfo {
    /* set mutable array list with 1, means all fields are mutable*/
    const fieldMutablesList = new Array<binaryen.u32>();
    for (let i = 0; i < fieldTypesList.length; ++i) {
        fieldMutablesList.push(1);
    }

    /*initialize necessary fields*/
    const fieldTypes = allocPtrArray(fieldTypesList);
    const fieldPackedTypes = allocU32Array(fieldPackedTypesList);
    const fieldMutables = allocU32Array(fieldMutablesList);

    /*create a type builder, and then create a struct type*/
    const tb: binaryen.TypeBuilderRef = binaryen._TypeBuilderCreate(1);
    binaryen._TypeBuilderSetStructType(
        tb,
        0,
        fieldTypes,
        fieldPackedTypes,
        fieldMutables,
        fieldTypesList.length,
    );

    const builtHeapType: binaryen.HeapTypeRef[] = new Array(1);
    const builtHeapTypePtr = allocPtrArray(builtHeapType);

    /* create a heaptype through _TypeBuilderBuildAndDispose API */
    binaryen._TypeBuilderBuildAndDispose(tb, builtHeapTypePtr.ptr, 0, 0);

    /* the created struct typeref */
    const structTypeRef = binaryen._BinaryenTypeFromHeapType(
        <binaryen.HeapTypeRef>binaryen.__i32_load(builtHeapTypePtr.ptr),
        nullable,
    );

    /* the created struct heap typeref */
    const structHeapTypeRef = binaryen._BinaryenTypeGetHeapType(structType);

    const structTypeInfo: typeInfo = {
        typeRef: structType,
        heapTypeRef: structRef,
    };

    binaryen._free(fieldTypes);
    binaryen._free(fieldPackedTypes);
    binaryen._free(fieldMutables);

    return structTypeInfo;
}
```

but the created struct type only the first field is `mutable`,  such as 

` (type ${mut:ref?|{}|_f64_ref?|{mut:i32_ref?|[mut:i32]|}|} (struct (field (mut (ref null ${}))) (field f64) (field (ref null ${mut:i32_ref?|[mut:i32]|}))))`

it seems because of the `fieldMutablesList ` doesn't work well, is it a bug or something I went wrong?

Thank.

**Comment by kripken** [comment]
It looks like you're calling directly to the C API. It would be good to add the API layer in `src/js/binaryen.js-post.js` for the TypeBuilder, which seems to be missing, and then to test and use that.

(Otherwise, there might be a bug in `allocU32Array()` or the other bits of code that you mention that are not from this repo.)

**Comment by zhenweijin** [comment]
> It looks like you're calling directly to the C API. It would be good to add the API layer in `src/js/binaryen.js-post.js` for the TypeBuilder, which seems to be missing, and then to test and use that.
> 
> (Otherwise, there might be a bug in `allocU32Array()` or the other bits of code that you mention that are not from this repo.)

thanks for your reply, `allocU32Array()` is indeed a bug, now I replace it by `allocU8Array()` and it works well to create mutable fields. I'll close the issue, Thanks.
