### ISSUE TITLE
Can't optimize code with imported table

### ISSUE THREAD

**Issue by dbezhetskov** [WebAssembly/binaryen#5476]
So, I have the next wat:

```
(module
    (import "spectest" "table" (table $tab 10 funcref))
    (func $main (result i32)
        (table.size $tab)
    )
)
```

It compiles into wasm without any issues:
`$wasm-as --enable-reference-types  main.wat`

But when I try to optimize it with wasm-opt I get:
`[parse exception: bad table index (at 0:49)]`

**Comment by kripken** [comment]
What optimization flags are you passing?

I tried `-O1, 2, 3` and none of them fail. But they also optimize the module into an empty one since there are no exports.

**Comment by dbezhetskov** [comment]
It was on the version_109 and it works well for the version 111, so sorry for the turbulence.
