### ISSUE TITLE
is there any APIs or methods to create a new opcode in binaryen?

### ISSUE THREAD

**Issue by zhenweijin** [WebAssembly/binaryen#5485]
Hi,
 We want to extend a new opcode for our project convenience through binaryen,  we want to add the new opcode through a patch or something, but haven't found provided APIs or methods to  add new opcode, Do you have plan to provide some APIs to help to extend new opcode for binaryen users?

Thanks.

**Comment by kripken** [comment]
You will need to patch Binaryen itself to add opcodes, starting from `wasm.h`. There isn't a plugin or extension mechanism.

For how to patch it, you can look at the git history of `wasm.h` and see how some recent opcode was added, that might be easiest.

**Comment by zhenweijin** [comment]
thank you for your reply, I'll try this way.
