### ISSUE TITLE
Implementation of cleanup WASM code, hit roadblock with validator error.

### ISSUE THREAD

**Issue by l1mey112** [WebAssembly/binaryen#5490]
Take this WAT pseudocode.

```wat
( $function
	stack.init ;; init stack memory
	( $__body (returns type)
		;; code
		;; code
		br $__body ( value ) ;; return value;
		;; code
		;; code
		br $__body ( value ) ;; return value;
		unreachable
	)
	stack.deinit ;; deinit stack memory
	;; return value here when function falls through
)
```

The code for subtracting the stack pointer/deallocating stack memory is quite large. Instead of placing it before every single return statement I have opted to place it at a central exit point in the function which is reached with a break. I want values returned from the body to "fall through" and be returned from the function, instead I get this error below.

```
[wasm-validator error in function main.reassign] unexpected false: non-final block elements returning a value must be drop()ed (binaryen's autodrop option might help you), on
(block $BLK3
 (global.set $__vsp
  (local.tee $1
   (i32.sub
    (global.get $__vsp)
    (i32.const 16)
   )
  )
 )
 (block $__body (result i32)
  (block $BLK2
   (block $STRUCTINIT1
    (i32.store
     (local.get $1)
     (i32.const 22)
    )
    (i64.store offset=8
     (local.get $1)
     (i64.const 0)
    )
   )
   (br $__body
    (i32.const 2)
   )
  )
 )
 (global.set $__vsp
  (i32.add
   (local.get $1)
   (i32.const 16)
  )
 )
)
(on index 1:
0xd1c210
), type: i32
```

Is there a workaround? Thank you in advance.

**Comment by kripken** [comment]
At index `1` in that block there is
```wat
 (block $__body (result i32)
```
That can't be in the middle of a block, as the error says. Add a `(drop )` around it to fix that.

**Comment by l1mey112** [comment]
What if i want the block at index one to carry it's value down to the enclosing block, `$BLK3`, to be returned. The block at the last index contains no side effects. This is a limitation of binaryen as it is valid WebAssembly.

**Comment by kripken** [comment]
Correct, Binaryen is more strict and structured in its IR than wasm is. See the "tree structure" notes in the [readme](https://github.com/WebAssembly/binaryen#binaryen-ir).
