### ISSUE TITLE
Asyncify overhead

### ISSUE THREAD

**Issue by iliakan** [WebAssembly/binaryen#5494]
Hello,

Thank you for the great project!

Did I get it right that Asyncify must instrument all WASM functions that form the call chain from the top to the one that needs to work asynchronously? 

Only these functions, or anything else?

I just to build `emcc -sASYNCIFY`, and the build size grew about +100%, so figuring out how to lessen the impact.

**Comment by kripken** [comment]
That is all correct. Sadly, indirect calls often force most of the program to be instrumented in a big project, see the section on indirect calls here:

https://kripken.github.io/blog/wasm/2019/07/16/asyncify.html

` -s ASYNCIFY_IGNORE_INDIRECT` in emcc (or the lower-level binaryen flag) disable that, but then you must be sure to add those code paths manually.
