### ISSUE TITLE
Incorrect debug location for call instruction with sourcemap

### ISSUE THREAD

**Issue by JesseCodeBones** [WebAssembly/binaryen#5503]
Currently I found the call instruction debug location is always incorrect even source map format is correct.
The call instruction always reuse the debug location of its latest parameter instruction.
this is the screen shot:
![image](https://user-images.githubusercontent.com/56120624/219599331-bb2f52f5-a4a6-4bab-a83d-8918299cb7d4.png)

I found the root cause is when binaryen write source map it take the sequence:
call -> param1 -> param2 (asume we have two parameter).
but when we read from the wasm and source map, it take the sequence:
param1 -> param2 -> call.
with the logic of functionality `WasmBinaryBuilder::readNextDebugLocation()`
* it firstly get the correct positon info of call instruction, but it drops the information because the pos of param1 is pointed to same offset location of wasm binaryen file.
* when it comes to call instruction, it will reuse the debug location if its latest parameter.

***below is my decode for debug locations of call of wasm
```
.....call location......
SAIT:
9
0
4
-9
.....param1 location......
AAAI:
0 <---the offset of wasm is 0, so it will drop the call location information
0
0
4
.....param2 location......
EAAE:
2
0
0
2
...........
```

**Comment by JesseCodeBones** [comment]
Proposal:  
For sourcemap generation, it should loop the parameters firstly, after that write the debug location of call instruction, is it correct?

**Comment by kripken** [comment]
Thanks for the report and investigation!

I'm not sure I understand the problem yet. Maybe I am not familiar enough with the sourcemap code in `wasm-binary.cpp`. Can you perhaps create a small standalone testcase that shows the issue? (like maybe a simple wat file that when roundtripped the source map locations change in a wrong way) Or, if that's simpler, can you write out the code you mean in the last comment?

**Comment by JesseCodeBones** [comment]
> Thanks for the report and investigation!
> 
> I'm not sure I understand the problem yet. Maybe I am not familiar enough with the sourcemap code in `wasm-binary.cpp`. Can you perhaps create a small standalone testcase that shows the issue? (like maybe a simple wat file that when roundtripped the source map locations change in a wrong way) Or, if that's simpler, can you write out the code you mean in the last comment?

No problem, I will let you knoe once I finished it😁

**Comment by JesseCodeBones** [comment]
> Thanks for the report and investigation!
> 
> I'm not sure I understand the problem yet. Maybe I am not familiar enough with the sourcemap code in `wasm-binary.cpp`. Can you perhaps create a small standalone testcase that shows the issue? (like maybe a simple wat file that when roundtripped the source map locations change in a wrong way) Or, if that's simpler, can you write out the code you mean in the last comment?

This is a reproduce project for this issue, please check.

**Comment by JesseCodeBones** [comment]
I provided a primary resolve for this issue, please kindly review and comment, thank you
