### ISSUE TITLE
omitted `rec` for recursive type definition?

### ISSUE THREAD

**Issue by wingo** [WebAssembly/binaryen#5506]
Consider `test.wat`:

```
(module
   (rec (type $t (struct (field (ref null $t)))))
   (func $f (param (ref $t)) (result (ref $t))
     (local.get 0)))
```

It assembles fine with `wasm-as -all -o test.wasm test.wat`.  However:

```
$ ~/src/v8/out/x64.release/d8 --experimental-wasm-gc
V8 version 11.2.0 (candidate)
d8> var mod = new WebAssembly.Module(read('test.wasm', 'binary'))
(d8):1: CompileError: WebAssembly.Module(): Type index 0 is out of bounds @+13
var mod = new WebAssembly.Module(read('test.wasm', 'binary'))
          ^
CompileError: WebAssembly.Module(): Type index 0 is out of bounds @+13
    at (d8):1:11
```

It would seem that the `rec` wrapper is getting dropped:

```
$ hexdump test.wasm
0000000 6100 6d73 0001 0000 0d01 5f02 6c01 0000
0000010 0160 006b 6b01 0300 0102 0a01 0106 0004
0000020 0020 000b                              
0000023
```
I would expect to see 0x4f before the 0x5f, i.e. to have a rec grouping before the struct.

**Comment by wingo** [comment]
Incidentally this is the `wasm-dis`:
```
$ ~/src/binaryen/bin/wasm-dis -all /tmp/test.wasm
(module
 (type ${ref?|...0|} (struct (field (ref null ${ref?|...0|}))))
 (type $ref|{ref?|...0|}|_=>_ref|{ref?|...0|}| (func (param (ref ${ref?|...0|})) (result (ref ${ref?|...0|}))))
 (func $0 (type $ref|{ref?|...0|}|_=>_ref|{ref?|...0|}|) (param $0 (ref ${ref?|...0|})) (result (ref ${ref?|...0|}))
  (local.get $0)
 )
)
```

Indeed, no `rec` here either, though I guess the binary is definitive!

**Comment by tlively** [comment]
This is a V8 bug. A type defined outside a rec group is identical to an equivalent type defined in a singleton rec group, and in particular is allowed to refer to itself.

cc @jakobkummerow

**Comment by jakobkummerow** [comment]
Please try updating V8 past [crrev.com/54d8cc0801bac22b028f88db56b267f88c095b70](https://crrev.com/54d8cc0801bac22b028f88db56b267f88c095b70), that should fix it.

**Comment by wingo** [comment]
Indeed!  Thanks for your patience with a bogus bug report.
