### ISSUE TITLE
Does `runAndDispose` only work in const value?

### ISSUE THREAD

**Issue by zhenweijin** [WebAssembly/binaryen#5508]
I have a struct type `i32_i32`,  its fields are all unmutable and initialized by const values such as 

``` wat
(local $0 struct new ${i32_i32}
  (i32.const 0)
  (i32.const 1)
)
```
and I want to know whether its fields equal something in compile time by using `runAndDispose`, for example

``` typescript
// ref is get variable opcode , for example, (local.get $0), and module is binaryen.Module
const filed0 = binaryen.StructGet(module, 0, ref, binaryen.i32, false);
const cond = module.i32.eq(filed0, module.i32.const(0));

// create a expression runner
const runner = new binaryen.ExpressionRunner(
    module,
    ExpressionRunnerFlags.Default,
    50,
    1,
);

// pre compile
const precomp = runner.runAndDispose(cond);
```

but the  `ExpressionId` of `precomp` is `Invalid` instead of `Const` or `LocalGet` or something.

So I wonder if `runAndDispose` only do work in `const` expression?

**Comment by kripken** [comment]
In general it is meant to be used on constant expressions. If the `ref` is a `StructNew` then I think that would work - everything is contained in the expression you are evaluating - but if it is a `LocalGet` then it would need to reason about locals and such, which is beyond the scope of `runAndDispose`.

**Comment by zhenweijin** [comment]
> In general it is meant to be used on constant expressions. If the `ref` is a `StructNew` then I think that would work - everything is contained in the expression you are evaluating - but if it is a `LocalGet` then it would need to reason about locals and such, which is beyond the scope of `runAndDispose`.

get it~, thank you for your reply, I'll close the issue.
