### ISSUE TITLE
Clang builds fail on travis

### ISSUE THREAD

**Issue by kripken** [WebAssembly/binaryen#553]
This happened spontaneously it seems, not connected to any changes we did. See e.g. https://travis-ci.org/WebAssembly/binaryen/builds/134321598

```
$ curl -sSL "http://llvm.org/apt/llvm-snapshot.gpg.key" | sudo -E apt-key add -

gpg: no valid OpenPGP data found.
```

Looks like it expects something on `llvm.org` that it doesn't find.

gcc still works though. Should we disable all clang builds for now?

**Comment by kripken** [comment]
Some binging shows this is a known issue with llvm.org sometimes not being available. I guess we can wait to see if it comes back.

**Comment by kripken** [comment]
Until this is resolved I think we should be very cautious about merging code to master.

**Comment by dschuff** [comment]
FWIW I build with clang locally. It's a newer version of clang than Travis has, but between that and the gcc build on Travis I'm not too worried about the coverage. It's a little annoying that the builds are all red, but we can give it a day or 2 and see if it gets fixed.

**Comment by kripken** [comment]
This looks like the cause: [LLVM disables apt for now](http://lists.llvm.org/pipermail/llvm-dev/2016-May/100303.html).

**Comment by kripken** [comment]
One option here is to use clang from the waterfall, see #557.
