### ISSUE TITLE
Why the type of BinaryenRefCast(ref.cast_static) has been changed in version 112

### ISSUE THREAD

**Issue by zhenweijin** [WebAssembly/binaryen#5532]
Hi,
We used to use version 110 of `binaryen`, for the case below it works well.

```wat
(module
 (type ${mut:i32_mut:ref?|[mut:i32]|} (struct (field (mut i32)) (field (mut (ref null $[mut:i32])))))
 (type ${} (struct ))

(func $foo (param $0 (ref null ${}))  (result (ref null ${mut:i32_mut:ref?|[mut:i32]|}))
 (local $1 (ref null ${mut:i32_mut:ref?|[mut:i32]|}))
 (local.set $1
  (ref.cast_static ${mut:i32_mut:ref?|[mut:i32]|}
   (local.get $0)
  )
 (local.get $1)
)
)
```
and the `resultType` of below 
``` typescript
const casted = binaryen._BinaryenRefCast(xxx, heaptype_of_$1);
const resultType = binaryen.getExpressionType(casted);
```
is equal to the heaptype of $1.

but now when we update the binaryen version to `112`. for the same case, the `resultType` is 0 or 1.
so the process in the below is failed
```wat
 (local.set $1
  (ref.cast_static ${mut:i32_mut:ref?|[mut:i32]|}
   (local.get $0)
  )
```
the error is 

```bash
Unexpected type
UNREACHABLE executed at /home/runner/work/binaryen.js/binaryen.js/binaryen/src/wasm/wasm-type.cpp:1091!
Aborted()
RuntimeError: Aborted(). Build with -sASSERTIONS for more info
```
Do we need some more steps to get expected heap type when using `binaryen._BinaryenRefCast`?

Thanks.

**Comment by kripken** [comment]
That sounds like a bug, but I don't have a guess to what could have caused it. I suggest bisecting on Binaryen commits, since this is a regression, that is probably the fastest way to find the problem.

**Comment by tlively** [comment]
Since I probably introduced the bug, I would also be happy to look into it if you can provide an example program I can run to observe the problem.

**Comment by zhenweijin** [comment]
> Since I probably introduced the bug, I would also be happy to look into it if you can provide an example program I can run to observe the problem.

Thank you very much for your help. It is likely that the parameters of the js API have changed instead of a bug.

I'm wondering why `ref.cast_static` was removed, and `ref.cast` and `ref.cast null`  were added. 

Thanks

**Comment by kripken** [comment]
Those changes are to update us to match the wasm GC spec, which has been changing. It is close to stable now I think, but more small changes might occur.

**Comment by zhenweijin** [comment]
thanks a lot, I'll close the issue
