### ISSUE TITLE
Basic block analysis may incorrect when there is `return` instruction 

### ISSUE THREAD

**Issue by JesseCodeBones** [WebAssembly/binaryen#5554]
Hi Maintainer,

If there is `return` instruction in `block` scope. the `block` will not be divided to a seperated basic block, but still combined with following instructions.
I suppose in the `CFGWalker::doEndBlock` function, we should consider the `return` instruction, WDYT?
or we do this with purpose? as return is quite difficult to analysis for the basic blocks.

### reproduce:
* source code:
```
(module
  (import "env" "printI" (func $pI(param i32)))
  ;;@ src.cpp:1:0
  (func $foo (param $a i32) (param $b i32)
    ;;@ src.cpp:1:1
    (block $b1
      ;;@ src.cpp:2:1
      (if
        ;;@ src.cpp:3:1
        (i32.le_s
          ;;@ src.cpp:4:1
          (local.get $a)
          ;;@ src.cpp:5:1
          (i32.const 1)
        )
        ;;@ src.cpp:6:1
        (return)
        ;;@ src.cpp:7:1
        (local.set $a
          ;;@ src.cpp:8:1
          (i32.const 1)
        )
      )
    )
    ;;@ src.cpp:9:1
    (drop
      ;;@ src.cpp:10:1
      (i32.const 1)
    )
  )
)
```
* outputs of basic block:
```
basic block ->
0-4-1
0-5-1
0-3-1
<- basic block

basic block ->
0-6-1
<- basic block

basic block ->
0-8-1
0-7-1
<- basic block

basic block ->
0-1-1
0-10-1
0-9-1
<- basic block
```

Regards

**Comment by kripken** [comment]
I'm not sure I follow you, sorry. But a Return is handled together with all unreachable instructions here:

https://github.com/WebAssembly/binaryen/blob/88b45a5a711678e789785f47701f9ae66131261f/src/cfg/cfg-traversal.h#L421-L422

That stops the current basic block and starts another right after, which I think is correct?

**Comment by JesseCodeBones** [comment]
@kripken 
Hi Alon, 
I did a small [reproduce project](https://github.com/JesseCodeBones/binaryen_test), and here is what I found:
`return` and `unreachable` will divide current basic block only, and could impact the CFG in out logic:
if the IR like:
```
(if
  (condition) ;; block 1
  (block
    (return);; block 2
    (i32.const 1);; block 3
  );;end block
  (i32.const 2);; block 4
);;endif
```
the in out relationship will be:
1->2, 1->3, 3->4
I think the correct one should be: 
1->2, 1->4, 2->3 (2->3 will not be reachable, but for CFG I think it is OK to keep this dead code)

### demo
```
(module
  (import "env" "printI" (func $pI(param i32)))
  ;;@ src.cpp:1:0
  (func $foo (param $a i32) (param $b i32)
    ;;@ src.cpp:1:1
    (block $b1
      ;;@ src.cpp:2:1
      (if
        ;;@ src.cpp:3:1
        (i32.le_s
          ;;@ src.cpp:4:1
          (local.get $a)
          ;;@ src.cpp:5:1
          (i32.const 1)
        )
        (block 
          ;;@ src.cpp:6:1
          (return)
          ;;@ src.cpp:7:1
          (local.set $a
            ;;@ src.cpp:8:1
            (i32.const 1)
          )
        )
        (local.set $a
          ;;@ src.cpp:9:1
          (i32.const 42)
        )
      )
    )
    ;;@ src.cpp:10:1
    (drop
      ;;@ src.cpp:11:1
      (i32.const 1)
    )
  )
)

```
CFG DUMP:
```
basic block ->0x557605edbe80
block out-0x557605edf600
block out-0x557605edece0
 block content ---
0-4-1
0-5-1
0-3-1
 --- block content 
<- basic block


basic block ->0x557605edf600
block in-0x557605edbe80
 block content ---
0-6-1
 --- block content 
<- basic block


basic block ->0x557605edece0
block in-0x557605edbe80
block out-0x557605edf690
 block content ---
0-8-1
0-7-1
 --- block content 
<- basic block


basic block ->0x557605edf690
block in-0x557605edece0
 block content ---
0-1-1
0-10-1
0-9-1
 --- block content 
<- basic block
```

**Comment by JesseCodeBones** [comment]
@kripken 
yes, you are right, I cannot reproduce the issue locally, maybe something wrong with my local environment and cannot reproduced.
