### ISSUE TITLE
setMemory fails for large data after update to v112

### ISSUE THREAD

**Issue by mnater** [WebAssembly/binaryen#5595]
Hi

I'm using binaryen.js to prepopulate memory with a larger amount of data. Since the update to v112 this doesn't work anymore.
Reduced testcase:
````javascript
import binaryen from "binaryen";

const dataLength = 100_000;
const mockData = new Uint8Array(dataLength);
for (let i = mockData.length - 1; i >= 0; i--) {
  mockData[i] = i & 255;
}

// Create a module and prepopulate memory
const myModule = new binaryen.Module();

myModule.setMemory(2, -1, "mem", [{
  "data": mockData,
  "offset": myModule.i32.const(0),
  "passive": false
}]);


const binary = myModule.emitBinary();
console.log(binary.length); // emits 100034 on v111
````
In v112 I get `Bus error: 10`
(Node v19.6.0 on macOS 12.6.3 )

The maximum `dataLength` where the code above still works in v112 is `67_312`.

I also tried to split data in several chunks but I hit the same issues:

````javascript
import binaryen from "binaryen";

const dataLength = 100_000;
const mockData = new Uint8Array(dataLength);
for (let i = mockData.length - 1; i >= 0; i--) {
  mockData[i] = i & 255;
}

// Create a module and prepopulate memory
const myModule = new binaryen.Module();

const memSegments = [];
const segmentSize = 50_000
const segmentCount = Math.ceil(dataLength / segmentSize);
for (let i = 0; i < segmentCount; i += 1) {
    memSegments.push({
        "data": mockData.subarray(i * segmentSize, ((i + 1) * segmentSize)),
        "offset": myModule.i32.const(i * segmentSize),
        "passive": false
    });
}

console.log(memSegments);

myModule.setMemory(
    2,
    -1,
    "mem",
    memSegments
);

const binary = myModule.emitBinary();
console.log(binary.length);
````

I think this is due the change from `allocate()` to `stackAlloc()` in https://github.com/WebAssembly/binaryen/blame/main/src/js/binaryen.js-post.js#L2572

How can I use `setMemory` with a larger amount of data?

**Comment by kripken** [comment]
Hmm, those should both allocate on the stack, but it's possible that an emscripten change to the default stack size affected this. To test that, building binaryen.js with `-sSTACK_SIZE=8MB` (added to CMakeLists along the other such flags) should fix it, if that's right.

**Comment by mnater** [comment]
Yes, that's right. Adding `target_link_libraries(binaryen_js "-sSTACK_SIZE=8388608")` in CMakeLists.txt fixed it.
Thanks for pushing me in the right direction.

Would you accept a PR that enables something like `emcmake cmake . -Dbinaryen_STACK_SIZE=8388608`?

**Comment by kripken** [comment]
@mnater Yes, I think such a PR makes sense. Binaryen isn't focused on optimizing its own memory usage, so a bigger stack is fine.

**Comment by mnater** [comment]
BTW: why is `stackalloc` used here and not `_malloc`?
I'm not sure if the rules for using stackalloc apply here too, but I learned that `stackalloc` should only be used for small, constant allocation lengths – and outside of loops (cf [Dos and Don'ts of stackalloc](https://vcsjones.dev/stackalloc/)). None of this holds true in this case.
Wouldn't we be better off using `_malloc`/`_free`?

**Comment by kripken** [comment]
Good point! We use `stackAlloc` for small allocations, but the memory can be of arbitrary size. I agree this should be `malloc`, let's change the PR to that.

**Comment by mnater** [comment]
https://github.com/WebAssembly/binaryen/pull/5625/commits/24290fc036ccd243473d61560737c1243bbe150b
