### ISSUE TITLE
wasm-as consume all memory and DIE on my code

### ISSUE THREAD

**Issue by drom** [WebAssembly/binaryen#570]
I am observing abnormal behavior of `wasm-as` tool on my JS code.
Running latest GIT master code over this code: https://github.com/drom/wast-diz/blob/master/lib/bytecode.js
Make `wasm-as` consume all available RAM 10G+ and makes my computer irresponsibly die.

**Comment by drom** [comment]
I know that I was stupid and I should use `asm2wasm` to go from `asm.js` to `wast` but why `wasm-as` dies on reasonably small text file. It is still mystery to me ;)

**Comment by kripken** [comment]
Thanks, yeah, we definitely shouldn't run out of memory even though the input is invalid. Looks like we allocated a lot of empty strings and got stuck in an infinite loop, when the input isn't valid. Fixing in #571.

**Comment by drom** [comment]
Great. It fixes my issue.
