### ISSUE TITLE
Optimization on unused passive data segments

### ISSUE THREAD

**Issue by ospencer** [WebAssembly/binaryen#5715]
Hiya! It seems like Binaryen doesn't currently optimize away passive data segments that have no corresponding `memory.init` instruction. This would be incredibly helpful for Grain, as the compiler wouldn't know what data segments could be removed until after linking, where we rely on Binaryen optimizations. This was not a huge issue for us before because we loaded string/binary data into memory via i64s, and so if a function were unused the data would be optimized away with it.

It's not necessarily easy to see, but I have a WIP Grain PR that moves over to data segments open here: https://github.com/grain-lang/grain/pull/1330

The last failing test is a regression test for module size, which went up with this change because a number of strings are left in the resulting wasm.

Let me know if that makes sense and if there's any additional information I can provide.

**Comment by kripken** [comment]
Makes sense to optimize this, thanks for the idea!

Probably `MemoryPacking` is the right place - @tlively how easy do you think it would be?

**Comment by ospencer** [comment]
Ah, I see. Exciting! It looks like that change hasn't been released yet and will be in the next version of Binaryen?

**Comment by ospencer** [comment]
And the indexes are now names; that's sweet!

**Comment by tlively** [comment]
Yes, I guess we should cut a new version of Binaryen with that change. Out of curiosity, would it be possible for you to use tip of tree Binaryen? What value do you get from using the released versions? I ask because we don't do anything particularly special for releases and Emscripten just uses tip of tree Binaryen.

**Comment by phated** [comment]
@tlively We (in the royal sense of the grain team, but I'm the team member that does it all) publish both an OCaml-toolchain-compatible build (native and JS) and OCaml bindings into OPAM and align versions with released versions. This is already a large undertaking to do for released versions and we wouldn't keep up with trunk.

**Comment by ospencer** [comment]
Thank you so much! I'll go ahead and close this. 😄
