### ISSUE TITLE
Asyncify Losing Data

### ISSUE THREAD

**Issue by martindevans** [WebAssembly/binaryen#5742]
I have built a system which uses asyncify to allow the host code to suspend and resume WASM execution. However at the moment it seems to be "losing" data when resumed.

Currently the process for building the wasm is:
1) compile WAT using wasmtime `wat2wasm` method
2) Run asyncify on the wasm
3) Execute wasm, calling the asyncify functions in the host code (never in WASM itself)

I'm testing with this simple test program:

```wat
(module

  (type $t0 (func (result i32)))
  (import "wasi_snapshot_preview1" "sched_yield" (func $wasi_snapshot_preview1.sched_yield (type $t0)))

  (type $t1 (func (result i32)))
  (import "" "get_number" (func $.get_number (type $t1)))
  
  (memory $memory 1)
  (export "memory" (memory 0))
  
  (func $run (result i32 i32)
  
	;;(local $var i32)
	(call $.get_number)
	;;(local.set $var)
  
        (call $wasi_snapshot_preview1.sched_yield) ;; async pause/resume here!
	
	;;(local.get $var)
	(call $.get_number)
  )
  (export "run" (func $run))
)
```

As you can see all this does is get two numbers, with a call to sched_yield in between. I've implemented sched_yield to pause execution the first time it is called, and to resume the next time.

Bug: **If I run the program as shown above then the first value returned is always zero**
Workaround: **If I comment in the three lines which save and restore the variable in $var then the value is preserved properly.**

Is this a known shortcoming of asyncify? Or am I likely doing something wrong in my setup?

**Comment by kripken** [comment]
This looks fairly basic aside from using multivalue. Perhaps try it without multivalue and see if that works?

**Comment by martindevans** [comment]
I modified the method by adding `(i32.add)` to the end and removed `--enable-multivalue` from the initial wasm-opt command. Still the same result :/

**Comment by kripken** [comment]
I'm not sure what the problem could be, then, but it should be very simple to debug, if you can attach the failing wasm file both before and after asyncify, I can take a look.

**Comment by kripken** [comment]
(Oh, and also the JS to run the wasm file. If you are running it in a VM directly, though, then maybe the bug is there - I'd try several VMs to see that they all behave the same.)

**Comment by martindevans** [comment]
Here are the files. 

The original input WAT file: [AsyncWat.txt](https://github.com/WebAssembly/binaryen/files/11569812/AsyncWat.txt)

And here are [two wasm files (zipped)](https://github.com/WebAssembly/binaryen/files/11569832/wasm.zip), `pretransform.wasm` is the output of wasmtime wat2wasm, `posttransform.wasm` is after passing that file through binaryen with these flags: 

`-O0 --strip-dwarf --asyncify --quiet --enable-multivalue --enable-simd --enable-reference-types --enable-mutable-globals --enable-bulk-memory`

> and also the JS to run the wasm file

The host side is quite complex (and I'm beginning to suspect that's where the bug probably is). This is running in a Unity application using wasmtime and with a custom implementation of WASI (which uses asyncify to suspend and resume for things like `sched_yield`). I am perfectly happy to give you a free copy of the asset if you want to see it for debugging purposes (but I don't really expect you to do my debugging for me either!).

Can you think of any things I could be doing wrong on the host side which could cause something like this? For example passing in the wrong stack pointer when resuming (although I assume there are already checks in place to detect something like that)?

**Comment by kripken** [comment]
The input file doesn't look valid to wabt:

```
$ wasm2wat pretransform.wasm 
pretransform.wasm:0000070: error: type mismatch at end of function, expected [] but got [i32]
```

When binaryen reads it it doesn't error - that's a bug in our validator I guess - and it prints this:

```wat
(module
 (type $t1 (func (result i32)))
 (import "wasi_snapshot_preview1" "sched_yield" (func $wasi_snapshot_preview1.sched_yield (result i32)))
 (import "" "get_number" (func $.get_number (result i32)))
 (memory $memory 1)
 (export "memory" (memory $memory))
 (export "run" (func $run))
 (func $run (result i32)
  (drop
   (call $.get_number)
  )
  (i32.add
   (call $wasi_snapshot_preview1.sched_yield)
   (call $.get_number)
  )
 )
)
```
So the first number it gets is just dropped. And it is adding the result from yield to the second get. I think that might explain what you are seeing?

(Side note, adding `-g` in the command that emits the post file would be good, so it has names for things. But given the above I think it might not be needed.)

**Comment by kripken** [comment]
(Maybe you are missing a `drop` after the call to `sched.yield`?)

**Comment by martindevans** [comment]
Ahat that's the issue. I had totally forgotten that `sched_yield` returns a value (and it's always zero in this particular case). That means my function has _three_ values on the stack and then either returns 2 (in the original code) or adds two together (in the final code), always leaving one extra value behind. For some reason the wasmtime `Wat2Wasm` doesn't report that as an error!

So the bug is not yours, really sorry about that. Thank you very much for looking into this so quickly!
