### ISSUE TITLE
struct.get error when target is a call_ref

### ISSUE THREAD

**Issue by zhenweijin** [WebAssembly/binaryen#5750]
For the case below:

```c++
class A {
 int x;
}
class B {
 foo() {
   return new A(10);
 }
}
B b = new B();
int res = b.foo().x;
```
I want to generate corresponding wasm like:

```wat
(type ${} (struct))
(type $A (struct_subtype (field $x (mut f64)) ${})
(type $B|foo (func (result (ref null $A)))
(type $B (struct_subtype (field $foo (ref $B|foo)) ${})
(func $$func_B|foo (result (ref null $A)
   (struct.new $A
    (f64.const 10)
   )
)
(global.set $b
 (struct.new $B
  (ref.func $func_B|foo)
 )
)
;; struct.get (call_ref ...)
(global.set $res
 (struct.get $A 0
  (call_ref $B|foo
   (global.get $b)
  )
 )
)
```
the related APIs are `BinaryenCallRef` and `BinaryenStructGet`, it report error:
`Aborted(Assertion failed: isStruct(), at: /home/runner/work/binaryen.js/binaryen.js/binaryen/src/wasm/wasm-type.cpp,1330,getStruct). Build with -sASSERTIONS for more info`

but if I wrote those .wat manually, it do work.

I have read the related binaryen source APIs, for example:
```c++
void StructGet::finalize() {
  if (ref->type == Type::unreachable) {
    type = Type::unreachable;
  } else if (!ref->type.isNull()) {
    type = ref->type.getHeapType().getStruct().fields[index].type;
  }
}
```
if the `ref` is a `call_ref`, seems `.getStruct()` will assert in `assert(isStruct())` because its heaptype is `signature`

Is it because binaryen doesn't support `call_ref` as the target of `struct.get`?

Thanks.

**Comment by kripken** [comment]
The reference to `struct.get` must be a struct according to the wasm spec, but your wat has the output of `call_ref` going into `struct.get`, which can be ok if the output is a struct. And that is what you have in that wat code.

So I would guess that either the C API has a bug, or your code using the C API has a mistake.

**Comment by zhenweijin** [comment]
> The reference to `struct.get` must be a struct according to the wasm spec, but your wat has the **output** of `call_ref` going into `struct.get`, which can be ok if the output is a struct. And that is what you have in that wat code.
> 
> So I would guess that either the C API has a bug, or your code using the C API has a mistake.

thanks for your replay.
I think maybe because of I'm wrongly use the `BinaryenCallRef`, if I pass signature's return type as `type`, then it works, but if I pass the signature type as `type`, it will report an error.
