### ISSUE TITLE
wasm-as fails on testsuite/start.wast

### ISSUE THREAD

**Issue by drom** [WebAssembly/binaryen#578]
I am running the following test from the official testuite: https://github.com/WebAssembly/testsuite/blob/master/start.wast
And it fails with error message that is hard to interpret.

```
wasm-as: /home/drom/work/github/WebAssembly/binaryen/src/wasm-s-parser.h:270: wasm::SExpressionWasmBuilder::SExpressionWasmBuilder(wasm::Module&, wasm::Element&): Assertion `module[0]->str() == MODULE' failed.
Aborted (core dumped)
```

P.S.
Second test that fails is: https://github.com/WebAssembly/testsuite/blob/master/if_label_scope.fail.wast
The name of the test is strange so. Not offence.

**Comment by kripken** [comment]
What specific command are you running?

**Comment by drom** [comment]
`../../WebAssembly/binaryen/bin/wasm-as testsuite/start.wast`

**Comment by kripken** [comment]
Is `testsuite` the wasm test suite?

`start.wast` in the test suite contains multiple wasm modules, and `assert_invalid` stuff. It's a format for the test suite, basically. So there isn't a way to run wasm-as on it and get a module. Instead, in `check.py` we break up such files into individual modules and run binary format tests on them.

**Comment by drom** [comment]
@kripken OK. I understand. I was confused because only 2 tests form the `testsuite` are consumed by the `wasm-as`; and the failure reason, and the error message where cryptic. Sort. of. Closing. so.

**Comment by binji** [comment]
@drom You might try sexpr-wasm for this. If you run `sexpr-wasm --spec foo.wast` where `foo.wast` has multiple modules, it will generate a JSON file called `foo.json` with information about the assertions, as well as modules named `foo.0.wasm`, `foo.1.wasm`, etc.

**Comment by drom** [comment]
@binji O! great. I gonna try it.

**Comment by binji** [comment]
No, it's a separate codebase: https://github.com/WebAssembly/sexpr-wasm-prototype/

**Comment by drom** [comment]
@binji I see. Generated binary code does look way different. So I need to find a way comparing these tools.

**Comment by binji** [comment]
sexpr-wasm does no optimization on the AST. Not sure if binaryen does by default, but I think you can disable it. Also, sexpr-wasm uses canonicalized LEB128 values by default, but I think binaryen writes out 5-byte LEB values. You can pass `--no-canonicalize-leb128s` to make sexpr-wasm do the same. That should get them pretty close, I think.
