### ISSUE TITLE
Format of target type in `ref.cast`

### ISSUE THREAD

**Issue by patrick96** [WebAssembly/binaryen#5795]
From what I can tell, binaryen uses the following format for `ref.cast` in its text parser:

```wast
(ref.cast null $t0 (...)) (; Nullable ;)
(ref.cast $t0 (...)) (; Non-null ;)
```

However, the current version of the gc spec uses:

```wast
(ref.cast (ref null $t0) (...)) (; Nullable ;)
(ref.cast (ref $t0) (...)) (; Non-null ;)
```

*See the spec's [testcases](https://github.com/WebAssembly/gc/blob/942c77f128a689bc09dac72059d392769ee71dde/test/core/gc/ref_cast.wast)*

**Comment by patrick96** [comment]
I have just seen #5591, which implies that the binaryen's text format is not necessarily supposed to be the same as the Wasm text format. If so, feel free to close this.
Is there a tracking issue for the new text parser tlively is working on one could subscribe to?

**Comment by tlively** [comment]
At this rate we will want to update Binaryen's legacy parser to use the standard GC text format as well since the new parser won't be finished before the GC spec is finalized. There's been some work in this vein already: #5515
