### ISSUE TITLE
add the license header comment to all the new files

### ISSUE THREAD

**Issue by ashleynh** [WebAssembly/binaryen#5818]
LGTM! As a follow-up, it would be good to add the license header comment to all the new files.

_Originally posted by @tlively in https://github.com/WebAssembly/binaryen/pull/5810#pullrequestreview-1528903682_

**Comment by tlively** [comment]
Looks like this can be closed now, unless there are more files to fix. For the future, if you add "Fixes #5828" or "Closes #5818" on a line of its own in the commit message, GitHub will close the issue automatically.
