### ISSUE TITLE
rec group's signature type

### ISSUE THREAD

**Issue by zhenweijin** [WebAssembly/binaryen#5826]
Hi,

```wat
 (rec
  (type $cls-struct1 (struct_subtype (field (mut (ref null $array0))) ${}))
  (type $array0 (array (mut (ref null $cls-struct1))))
  (type $function0 (func (param (ref null $cls-struct1))))
  (type $vt-struct0 (struct_subtype (field (ref null $function0)) ${}))
 )
```

I have generate a rec group by using `TypeBuilderCreateRecGroup` API, as you can see, the field of `$vt-struct0` accept  a `$function0` signature.

But when I want to add a function which has type `$function0` by using `BinaryenAddFunction` API, it actually generate a new type with a new index in type section, such as 

```wat
 (type $ref?|$cls-struct1|_=>_none (func (param  (ref null $cls-struct1))))
 (func $foo (type $ref?|$cls-struct1|_=>_none)  (param $0 (ref null $cls-struct1))
  ...
)
```

So when I want to create new struct of type `$vt-struct0`, for example,

```wat
(struct.new $vt-struct0
 (ref.func $foo)
)
```

I will meet some issues, because the type `vt-struct0`'s field type's index in type section is not equal to `$foo`'s signature type:

```bash
[wasm-validator error in function test|start] struct.new operand 0 must have proper type, on 
(struct.new $vt-struct0
 (ref.func $foo)
)
```

So I wonder if there has any approach to assign specified type for wasm function in binaryen?

Thanks~

**Comment by kripken** [comment]
This is a current limitation in the C API. There is a TODO to fix it, by passing in a HeapType:

https://github.com/WebAssembly/binaryen/blob/f61bf9f46addc0b6885b60b3e0f1c4ccc7e64473/src/binaryen-c.cpp#L4921

**Comment by zhenweijin** [comment]
> This is a current limitation in the C API. There is a TODO to fix it, by passing in a HeapType:
> 
> https://github.com/WebAssembly/binaryen/blob/f61bf9f46addc0b6885b60b3e0f1c4ccc7e64473/src/binaryen-c.cpp#L4921

Thank you for your reply. Do you have any plans to improve or fix this issue recently?

**Comment by kripken** [comment]
I could try to find time for this.

Can you give some more details on your situation? I mean, how urgent is this for your project, and what your project is. That might help me know how to prioritize my time.

**Comment by xujuntwt95329** [comment]
Hi @kripken, thanks for your reply, we are developing the `ts2wasm-compiler`, it is not open-sourced yet because we are working on some internal processes, there is a [basic introduction](https://github.com/WebAssembly/meetings/blob/main/gc/2023/presentations/2023-05-16-jun-typescript.pdf) about the general idea.

It would be really helpful if you can fix this issue, but if this is not high priority from your side, do you know if there are any workaround about this?

**Comment by kripken** [comment]
I see, thanks @xujuntwt95329 

Ok, that makes sense, and this seems important to fix as I realize that it will affect all WasmGC users of the C API like it does you, so it could block Grain or AssemblyScript etc. as well. And I can't think of a workaround. So I spent some time on it now and opened a PR, #5829

**Comment by zhenweijin** [comment]
> I see, thanks @xujuntwt95329
> 
> Ok, that makes sense, and this seems important to fix as I realize that it will affect all WasmGC users of the C API like it does you, so it could block Grain or AssemblyScript etc. as well. And I can't think of a workaround. So I spent some time on it now and opened a PR, #5829

thanks a lot, it helps a lot
