### ISSUE TITLE
AssemblyScript version of binaryen

### ISSUE THREAD

**Issue by abflow** [WebAssembly/binaryen#5834]
To have a javascript version of binaryen is quite nice, but wouldn't it be better to generate an AssemblyScript version ?

This way we could have the whole compilation workflow compiled to wasm for use in the browser.

**Comment by MaxGraey** [comment]
This doesn't make sense. Binaryen written on C++ and compiled to WebAssembly which uses in binaren.js

**Comment by abflow** [comment]
AssemblyScript also compiles to WebAssembly, and makes use of Binaryen to compile itself to WASM.

If we had an AssemblyScript version of Binaryen, we could code everything in AssemblyScript and not have to switch to javascript.

After all, AssemblyScript is more tailored to WebAssembly than Javascript...

**Comment by tlively** [comment]
Binaryen is written in C++, not JavaScript. There's no way to compile C++ to AssemblyScript, so having an AssemblyScript version of binaryen would mean manually porting all the C++ code to AssemblyScript, which is not something we would want to do.

**Comment by abflow** [comment]
Alright, that makes sense. It would require to recode the whole project in AssemblyScript instead of C++. Though there is wasm2js, so there could also be wasm2as, as AS anJS are very similar in syntax.
