### ISSUE TITLE
wasm-ctor-eval doesn't seem to play well with >2gb memories.

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/binaryen#5893]
Looks like it runs out of memory maybe?

```
./test/runner core_2gb.test_eval_ctors_no_main --skip-slow --cores=4  
...
em++: error: '/root/emsdk/upstream/bin/wasm-ctor-eval --ctors=_initialize --kept-exports=_initialize test_ctors_no_main.wasm -o test_ctors_no_main.wasm -g --mvp-features --enable-mutable-globals --enable-sign-ext' failed (received SIGKILL (-9))
```

**Comment by sbc100** [comment]
Actually on my local machine I see:

```
trying to eval __wasm_call_ctors
  ...partial evalling successful, but stopping since could not eval: trap: final > memory: 18446744071562135456 > 2306867188
  ...stopping
```

**Comment by kripken** [comment]
OOM seems plausible. In ctor-eval we use a `std::vector` to represent memory, and grow it on demand. So if you do a read of address 2GB, it will take 2GB... we could use a sparse array I suppose, but I think maybe this will only be an issue for your "start memory at 2GB mode" @sbc100 ? In real-world code ctor-eval only executes operations on very low addresses.

**Comment by sbc100** [comment]
What about ` trap: final > memory: 18446744071562135456 > 2306867188`?   That looks a little suspicious.. maybe an integer overflow?

**Comment by kripken** [comment]
Yeah, that might be a separate issue. Let's keep this open for that. Very possibly ctor-eval only uses 32-bit indexes (maybe signed?).

Also, perhaps we can fix both by just disallowing all memory accesses above say 100MB. Even that is a huge amount of memory to use in this tool, and again, in the normal cases only very low addresses will be taken. It feels a little arbitrary but it seems better than an OOM.

**Comment by sbc100** [comment]
Yup.. that sounds very reasonable.

**Comment by sbc100** [comment]
This is still an issue.  I can't currently run the `test_eval_ctors_no_main` test in `wasm_2gb` or `wasm64_4gb` modes because of this.
