### ISSUE TITLE
LocalSubtyping does not handle self-assignments optimally

### ISSUE THREAD

**Issue by tlively** [WebAssembly/binaryen#5908]
Assigning a local to itself should not affect how it can be refined, but it does:

```
(module
 (func $test (param $eq (ref eq))
  (local $x anyref)
  
  ;; $x is refinable to (ref eq)
  (local.set $x (local.get $eq))
  
  ;; But this self-assignment inhibits the optimization
  (local.set $x (local.get $x))
 )
)
```

**Comment by kripken** [comment]
Hmm, such self-assignments are removed by other passes anyhow, so I don't think is limiting us overall?

**Comment by tlively** [comment]
Yeah, I guess you're right. I was surprised about this when testing, but that's ok.
