### ISSUE TITLE
Treatment of finality in TypeSSA is too conservative

### ISSUE THREAD

**Issue by askeksa** [WebAssembly/binaryen#5933]
When support for final types was introduced in https://github.com/WebAssembly/binaryen/commit/73f24c0af330578e9fa01e3d5fc6391619baaa9e, The TypeSSA pass was adjusted to not create subtypes for final types.

I believe this is more strict than it needs to be when using `--closed-world`.

In a closed-world scenario, the finality marker is redundant. There is no reason to set it to anything other than final if the type has no subtypes. Thus, the following strategy should be sound:
1. On input, ignore the finality markers and treat all types as non-final (in particular in TypeSSA).
2. On output, mark types final that have no subtypes.

To test this strategy, I did a comparison between the same module with and without finality markers on struct types, optimized with
```
wasm-opt -all --closed-world -tnh -O3 --type-ssa --gufa -O3 --type-merging -O1
```
(using https://github.com/WebAssembly/binaryen/commit/b9f4e3609312473315cc401a2d8501e7a7731b04 to avoid the issue reported in https://github.com/WebAssembly/binaryen/issues/5932)
| Module | Size | Struct types | `call` | `call_ref` | `call_indirect` |
| :- | -: | -: | -: | -: | -: |
| [With final](https://github.com/WebAssembly/binaryen/files/12584550/ff.wasm.gz) | 1540124 | 55859 | 23507 | 257 | 3604 |
| [Without final](https://github.com/WebAssembly/binaryen/files/12584483/fs.wasm.gz) | 1520024 | 55008 | 23540 | 250 | 3538 |

As can be seen, ignoring the finality markers will reduce the eventual number of struct types and also improve the devirtualization of `call_ref` and `call_indirect` into `call`.

**Comment by kripken** [comment]
Thanks for the data! Sounds promising.

I like the point that finality is really redundant in closed world. @tlively what do you think about us adding a new pass to remove finality from all types, and another that adds finality to all those that happen to be leaf types? Then a user workflow could be `--remove-finality -O3 [..] -O3 --auto-finality`

**Comment by tlively** [comment]
Yes, we should do that. We should also continue to make sure each pass is correct with respect to finality of types when run individually.

**Comment by kripken** [comment]
The passes for this landed now. So far they are not run by default anywhere, and I am a little uncertain if we should. I wrote some notes here:

https://github.com/WebAssembly/binaryen/wiki/GC-Optimization-Guidebook#type-finalizing

It seems like opening is risky, but perhaps closing at the end of the pipeline is always beneficial? otoh if we close ourselves at the end of `-O3` then users that want to only close after several more operations might suffer. So I lean towards leaving this for users to do.

**Comment by askeksa** [comment]
I agree that this should not be done inside the default pipeline for any `-O` options. The usual use case would be to open as the very first thing in the pipeline and close as the very last. So it makes sense to keep these manual. One thing to consider could be to do this automatically when `--closed-world` is specified. This would be sound, but could still be a surprising behavior to some users.
