### ISSUE TITLE
src/tools/binaryen-shell.cpp fails to compile with Visual Studio 2015

### ISSUE THREAD

**Issue by lqd** [WebAssembly/binaryen#594]
The build currently fails with this errror:
binaryen\src\tools\binaryen-shell.cpp(204): error C2668: 'wasm::make_unique': ambiguous call to overloaded function.

Is there something I can do to help fix it ?

**Comment by kripken** [comment]
Thanks for reporting, this is actually being discussed right now [here](https://github.com/WebAssembly/binaryen/pull/593#issuecomment-227790718) - feel free to join the discussion there. We are still trying to figure out what the best solution is.

**Comment by lqd** [comment]
Confirmed fixed by #595 :+1:
