### ISSUE TITLE
Please update license of ConvertUTF.cpp

### ISSUE THREAD

**Issue by apoleon** [WebAssembly/binaryen#5947]
The file third_party/llvm-project/ConvertUTF.cpp  contains the old Unicode license which is considered to be non-free because it does not allow modifications. Fortunately the Unicode project changed the license and the following one can be used now:

[Unicode license]( https://www.unicode.org/license.txt)

AFAIK the llvm project already uses the new license, so all you have to do is copy&paste their changes.

This is also Debian bug [#1029064](https://bugs.debian.org/1029064)

**Comment by kripken** [comment]
Interesting, I hadn't heard of this licensing issue.

PR with an updated to LLVM upstream: #5954
