### ISSUE TITLE
Are there any support for data count section in Binaryen?

### ISSUE THREAD

**Issue by mobsceneZ** [WebAssembly/binaryen#5976]
Hey there, WebAssembly Specification added data count section to support one-time validation recently, which causes the binary module rendered by Binaryen through "BinaryenModuleAllocateAndWrite" invalid, is there any API support for adding this section manually or can we add this section as custom section but with specific section id 😕 ?

**Comment by kripken** [comment]
Binaryen has support for the data count section, for example here is where it is written:

https://github.com/WebAssembly/binaryen/blob/87bcf76c33356d3603e0e2721d54f6e450762627/src/wasm/wasm-binary.cpp#L592

Perhaps you have not enabled the feature flag for bulk memory, which enables it? `--enable-bulk-memory`

Or perhaps we are missing a C API for data segment manipulation?

**Comment by mobsceneZ** [comment]
> Binaryen has support for the data count section, for example here is where it is written:
> 
> https://github.com/WebAssembly/binaryen/blob/87bcf76c33356d3603e0e2721d54f6e450762627/src/wasm/wasm-binary.cpp#L592
> 
> Perhaps you have not enabled the feature flag for bulk memory, which enables it? `--enable-bulk-memory`
> 
> Or perhaps we are missing a C API for data segment manipulation?

Thanks kripken, I'm using Binaryen's C API for manipulating wasm binaries and `BinaryenModuleSetFeatures()` with `BinaryenFeatureBulkMemory()` works perfectly for me :+1:.
