### ISSUE TITLE
More readable wasm-dis output?

### ISSUE THREAD

**Issue by juj** [WebAssembly/binaryen#5978]
Peeking into https://github.com/emscripten-core/emscripten/issues/20325 made me dream again of wasm-dis output that would be more familiar for myself to read 😅

Case at point: wasm-dis disassembly that reads

```wast
 (func $__original_main (result i32)
  (local $0 i32)
  (local $1 i32)
  (local $2 i32)
  (local $3 i32)
  (local $4 i32)
  (local $5 i32)
  (local $6 i32)
  (local $7 i32)
  (local $8 i32)
  (local.set $0
   (i32.const 0)
  )
  (local.set $1
   (i32.load8_u offset=65536
    (local.get $0)
   )
  )
  (local.set $2
   (i32.const 24)
  )
  (local.set $3
   (i32.shl
    (local.get $1)
    (local.get $2)
   )
  )
  (local.set $4
   (i32.shr_s
    (local.get $3)
    (local.get $2)
   )
  )
  (local.set $5
   (i32.const 0)
  )
  (local.set $6
   (i32.sub
    (local.get $5)
    (local.get $4)
   )
  )
  (local.set $7
   (i32.const 1)
  )
  (i32.store8 offset=65541
   (local.get $6)
   (local.get $7)
  )
  (local.set $8
   (i32.const 0)
  )
  (return
   (local.get $8)
  )
 )
```
is for some reason a bit difficult to parse even after all these years. I tend to end up playing with whitespace to make it a bit more bearable, and end up with

```wast
 (func $__original_main (result i32)
  (local $0 i32)
  (local $1 i32)
  (local $2 i32)
  (local $3 i32)
  (local $4 i32)
  (local $5 i32)
  (local $6 i32)
  (local $7 i32)
  (local $8 i32)
  (local.set $0 (i32.const 0) )
  (local.set $1 (i32.load8_u offset=65536 (local.get $0) ) )
  (local.set $2 (i32.const 24) )
  (local.set $3 (i32.shl (local.get $1) (local.get $2) ) )
  (local.set $4 (i32.shr_s (local.get $3) (local.get $2) ) )
  (local.set $5 (i32.const 0) )
  (local.set $6 (i32.sub (local.get $5) (local.get $4) ) )
  (local.set $7 (i32.const 1) )
  (i32.store8 offset=65541 (local.get $6) (local.get $7) )
  (local.set $8 (i32.const 0) )
  (return (local.get $8) )
 )
```
That looks cleaner to my mind. I wonder if it might make sense to experiment with some kind of smart print layouting that would display short stack expressions as one-liners like that?

Although I wish there would exist a tool that would go a bit further and provide a C-like linearized disassembly. The above code could be printed out in C-style as

```c++
i32 $__original_main() {
  i32 i0, i1, i2, i3, i4, i5, i6, i7, i8;
  i0 = 0;
  i1 = MEM8[i0 + 65536];
  i2 = 24;
  i3 = i1 << i2;
  i4 = (i32)i3 >> i2;
  i5 = 0;
  i6 = i5 - i4;
  i7 = 1;
  MEM8[i6 + 65541] = i7;
  i8 = 0;
  return i8;
}
```
That would make wasm disassembly super-readable in my perspective. Anyone know if such a tool would already exist, or maybe different print options might have been considered for wasm-dis before?

**Comment by kripken** [comment]
`wabt` has `wasm-decompile`: https://webassembly.github.io/wabt/doc/wasm-decompile.1.html

Another option is `emcc -sWASM=0` and to read the JS.

Improvements to `wasm-dis` also sound good to me in general. I don't think there has been discussion about that before.

**Comment by juj** [comment]
Great, looks like wasm-decompile does the trick. (although it gives some odd output, but that's another story)
