### ISSUE TITLE
libbinaryen linking

### ISSUE THREAD

**Issue by kripken** [WebAssembly/binaryen#598]
Currently it is a dynamic library. Part of that was due to linking issues, but we resolved those with explicit pass registration. So I think we are ok to do either static or dynamic at this point.

For Rust it might be simpler to have it static instead. Thoughts?

Or we could build both or have it as an option? (Not sure if that can be done in cmake, but probably?)

**Comment by eholk** [comment]
Having dynamic by default with the option to build static seems like the right approach to me.
