### ISSUE TITLE
`select` optimization of a conditional is causing significantly reduced performance, in some cases

### ISSUE THREAD

**Issue by rotemdan** [WebAssembly/binaryen#5983]
I [originally reported this at the AssemblyScript repository](https://github.com/AssemblyScript/assemblyscript/issues/2754), but I was told I must report it here instead.

This AssemblyScript code is 6x slower in release mode (optimization level 3 - `1415ms`) than in debug mode (optimizations disabled - `220ms`) in Node.js `20.8.0` (Windows 10 x64):

```asc
export function test(): i32 {
	let x = 23847

	for (let i = 0; i < 100000000; i++) {
		if (x == 53498923) {
			x += ((x - i) * x) / 13
		}
	}

	return x
}
```

Here is the emitted WAT for both versions:

`debug.wat`:
```wat
(module
 (type $none_=>_i32 (func (result i32)))
 (global $~lib/memory/__data_end i32 (i32.const 8))
 (global $~lib/memory/__stack_pointer (mut i32) (i32.const 32776))
 (global $~lib/memory/__heap_base i32 (i32.const 32776))
 (memory $0 1000)
 (table $0 1 1 funcref)
 (elem $0 (i32.const 1))
 (export "test" (func $assembly/index/test))
 (export "memory" (memory $0))
 (func $assembly/index/test (result i32)
  (local $x i32)
  (local $i i32)
  i32.const 23847
  local.set $x
  i32.const 0
  local.set $i
  loop $for-loop|0
   local.get $i
   i32.const 100000000
   i32.lt_s
   if
    local.get $x
    i32.const 53498923
    i32.eq
    if
     local.get $x
     local.get $x
     local.get $i
     i32.sub
     local.get $x
     i32.mul
     i32.const 13
     i32.div_s
     i32.add
     local.set $x
    end
    local.get $i
    i32.const 1
    i32.add
    local.set $i
    br $for-loop|0
   end
  end
  local.get $x
  return
 )
)
```

`release.wat`:
```wat
(module
 (type $none_=>_i32 (func (result i32)))
 (memory $0 1000)
 (export "test" (func $assembly/index/test))
 (export "memory" (memory $0))
 (func $assembly/index/test (result i32)
  (local $0 i32)
  (local $1 i32)
  i32.const 23847
  local.set $0
  loop $for-loop|0
   local.get $1
   i32.const 100000000
   i32.lt_s
   if
    local.get $0
    local.get $0
    local.get $1
    i32.sub
    local.get $0
    i32.mul
    i32.const 13
    i32.div_s
    i32.add
    local.get $0
    local.get $0
    i32.const 53498923
    i32.eq
    select
    local.set $0
    local.get $1
    i32.const 1
    i32.add
    local.set $1
    br $for-loop|0
   end
  end
  local.get $0
 )
)
```

Here is the AssemblyScript test project as a zip file:
[AssemblyScriptTest.zip](https://github.com/WebAssembly/binaryen/files/12775167/AssemblyScriptTest.zip)

Unfortunately I can't provide the exact intermediate representation passed by AssemblyScript, which causes this code to be emitted. I will need some collaboration with them in order to provide this information since I don't have the knowledge to do so.

**Edit**: updated with slightly different test case.

**Comment by kripken** [comment]
How was this optimized? If it used `wasm-opt -Oz` (or `--shrink-level=2`) then that means it optimizes for size at all cost (even at the cost of making it run much slower), which looks like what happens here. That is, this is expected at that level.

**Comment by rotemdan** [comment]
`asconfig.json`:

```json
{
  "targets": {
    "debug": {
      "outFile": "build/debug.wasm",
      "textFile": "build/debug.wat",
      "sourceMap": true,
      "debug": true
    },
    "release": {
      "outFile": "build/release.wasm",
      "textFile": "build/release.wat",
      "sourceMap": true,
      "optimizeLevel": 3,
      "shrinkLevel": 0,
      "converge": false,
      "noAssert": false
    }
  },
  "options": {
    "bindings": "esm",
    "initialMemory": 1000
  }
}
```

These are the default settings of AssemblyScript. Other than that, I don't know more internal details.

**Comment by kripken** [comment]
It says shrinkLevel 0, so I assume that means my theory was wrong.

I can investigate this, but I'd need something I can run directly through wasm-opt as I'm not familiar with AssemblyScript. That is, if you can work with that toolchain to get a testcase that is a wat or wasm file that wasm-opt processes (and with the right flags for it etc.), then I could reproduce the problem using that, and investigate.

**Comment by rotemdan** [comment]
I have very limited knowledge of AssemblyScript myself, and of WebAssembly (I only started studying it in depth 3 days ago, although I've been using it for years). The AssemblyScript developers insisted The problem is with Binaryen, not with them. I asked for them for some cooperation to provide the exact internal representation sent to the Binaryen optimizer (which I'm not familiar with), but they didn't seem interested. (more details in the linked issue).

Fundamentally, the issue I noticed is that the `select` operation, which if understand correctly, is effectively performing unnecessary computations, and then possibly discarding them (by its design) is being emitted even when there is only one branch in the conditional, that is a pattern like `if (something) { x = someFormula }`.

I don't completely understand what this is beneficial for. It looks like some sort of speculative optimization that tries to take advantage of pipelining etc. (not an area I am deeply familiar with), but I don't see how it helps in this case. I would expect something of this sort to happen on the JIT or VM level, when the properties of the underlying architecture is known. Here it seems a bit out-of-place.

Maybe it's just me but I personally prefer the optimizer to produce faster code in almost all cases (sort of what it's supposed to do, at least in the eyes of most programmers). It came as a surprise to me, I became a bit confused, and later I decided to run a benchmark and realized  it was actually producing slower code in some cases. Not much more to say about that.

**Comment by kripken** [comment]
If you can't get their help to get a reducible testcase, one thing that might work is to provide us with the unoptimized build (which you say is faster). I might be able to reproduce the problem with that.

**Comment by rotemdan** [comment]
I'm not sure what you mean? I included the full emitted `debug.wat` and `release.wat` source files in the message. They show exactly what operations are emitted. Is there any other information I'm missing? (I probably don't think the `.wasm` files are that useful for you? What else is needed?)

**Comment by kripken** [comment]
Oh, sorry, I missed that those were the complete files - I thought they were just specific functions.

Ok, I can reproduce this now locally. The issue is that the if's arms total to a cost of 7 while we have a limit there of 9. I'm working on a PR.

**Comment by rotemdan** [comment]
If there's only one branch, then the only advantage I can see in optimistically evaluating the assignment (and possibly discarding it) is maybe in the case the predicate is known to be about the same computational cost as the body (the assignment), and only then it might seem reasonable, in some specific cases, where I'd have confidence it would have significant net positive effect on performance.

Anyway, lots of heuristic involved. Some questionable assumptions. It honestly feels like premature optimization. I would expect something like this when the architecture is known, not earlier.

If I wrote an optimizer, I may put this under a separate "speculative" option. I wouldn't turn it on by default, but that's just me.

**Comment by kripken** [comment]
> I would expect something like this when the architecture is known, not earlier.

I tend to agree, but there is also some assumption by VMs that tools decide here, so that VMs can be simpler and just do what the tools say. For example, regarding inlining. (Though this may be changing.) So we can't just stop trying our best here, I think.

> If I wrote an optimizer, I may put this under a separate "speculative" option.

Interesting idea to have an option to not do any speculative stuff. However, that would be very limiting, as pretty much every inlining decision is speculative, for example, and even "obvious" choices like `if => select` in "simple" cases are speculative since the actual cost depends on pipelining and branch prediction and more. Compilers are, unfortunately, in the business of speculation :smile: In principle a smart JIT could adapt at runtime and do the optimal thing, but wasm does try to do a good job ahead of time, which means we speculate, for better or for worse.

Anyhow, #5989 fixes this benchmark, and is an improvement in these heuristics I think, but it is quite hard to get everything right.

**Comment by rotemdan** [comment]
I wrapped the assignment with two additional nested conditionals and still got no `if` instructions emitted, only a single flattened out `select`:

```asc
export function test(): i32 {
	let x = 23847

	for (let i = 0; i < 100000000; i++) {
		if (x > 100) {
			if (x < 500) {
				if (x < 450) {
					x += ((x - i) * x) / 13
				}
			}
		}
	}

	return x
}
```

`debug.wat`:
```wat
(module
 (type $none_=>_i32 (func (result i32)))
 (global $~lib/memory/__data_end i32 (i32.const 8))
 (global $~lib/memory/__stack_pointer (mut i32) (i32.const 32776))
 (global $~lib/memory/__heap_base i32 (i32.const 32776))
 (memory $0 1000)
 (table $0 1 1 funcref)
 (elem $0 (i32.const 1))
 (export "test" (func $assembly/index/test))
 (export "memory" (memory $0))
 (func $assembly/index/test (result i32)
  (local $x i32)
  (local $i i32)
  i32.const 23847
  local.set $x
  i32.const 0
  local.set $i
  loop $for-loop|0
   local.get $i
   i32.const 100000000
   i32.lt_s
   if
    local.get $x
    i32.const 100
    i32.gt_s
    if
     local.get $x
     i32.const 500
     i32.lt_s
     if
      local.get $x
      i32.const 450
      i32.lt_s
      if
       local.get $x
       local.get $x
       local.get $i
       i32.sub
       local.get $x
       i32.mul
       i32.const 13
       i32.div_s
       i32.add
       local.set $x
      end
     end
    end
    local.get $i
    i32.const 1
    i32.add
    local.set $i
    br $for-loop|0
   end
  end
  local.get $x
  return
 )
)
```

`release.wat`:
```wat
(module
 (type $none_=>_i32 (func (result i32)))
 (memory $0 1000)
 (export "test" (func $assembly/index/test))
 (export "memory" (memory $0))
 (func $assembly/index/test (result i32)
  (local $0 i32)
  (local $1 i32)
  i32.const 23847
  local.set $0
  loop $for-loop|0
   local.get $1
   i32.const 100000000
   i32.lt_s
   if
    local.get $0
    local.get $0
    local.get $1
    i32.sub
    local.get $0
    i32.mul
    i32.const 13
    i32.div_s
    i32.add
    local.get $0
    local.get $0
    i32.const 500
    i32.lt_s
    local.get $0
    i32.const 450
    i32.lt_s
    i32.and
    local.get $0
    i32.const 100
    i32.gt_s
    i32.and
    select
    local.set $0
    local.get $1
    i32.const 1
    i32.add
    local.set $1
    br $for-loop|0
   end
  end
  local.get $0
 )
)
```

I suspected this would happen since I assumed that it's evaluating the statements recursively.

It seems to flatten out all the nested conditional statements, then applying logical `and` between the nested predicates (which makes it even more speculative, given the rough general heuristic that the more conditionals are included, the less likely they are to succeed in practice).

Wrapping the assignment with another conditional seems to fall back to emit nested `if`s, even if I change the assignment to `x += 1`.
