### ISSUE TITLE
Mutual recursive GC WAT example from proposal errors with "Heap type has an undeclared child at type $tree"

### ISSUE THREAD

**Issue by jayphelps** [WebAssembly/binaryen#5986]
[This example from the GC proposal](https://github.com/WebAssembly/gc/blob/main/proposals/gc/Overview.md#:~:text=Mutual%20recursion%20is%20possible%20as%20well%3A) errors in wasm-shell `Fatal: Invalid type: Heap type has an undeclared child at type $tree`. Discovered while trying to do effectively similar things.

```wast
(module
  (type $tree (struct (field i32) (field (ref $forest))))
  (type $forest (struct (field (ref $tree)) (field (ref $forest))))
)
```

**Comment by jayphelps** [comment]
Ah. Discovered from the tests that you have to wrap them in a `(rec ...)`. Since this isn't mentioned in the GC proposal (yet?) I'll leave this open to at least get clarity on the plan.

**Comment by patrick96** [comment]
The document you linked to is outdated:

> WARNING: Some contents of this document may have gotten out of sync with the [MVP](https://github.com/WebAssembly/gc/blob/main/proposals/gc/MVP.md) design, which is more up-to-date.

The main overview is in [MVP.md](https://github.com/WebAssembly/gc/blob/main/proposals/gc/MVP.md) and the actual spec is [here](https://webassembly.github.io/gc/core/)

**Comment by jayphelps** [comment]
@patrick96 Bingo. Thanks!
