### ISSUE TITLE
makeStructNewDefault with the C API

### ISSUE THREAD

**Issue by tshort** [WebAssembly/binaryen#6011]
Is it possible to use `makeStructNewDefault` with the C API? 

I couldn't find a `BinaryenStructNewDefault`. If not, any suggestions on workarounds? I need something like this to handle nested mutable structs that are circular.

**Comment by kripken** [comment]
I think you can pass is an empty `operands` for that. In the IR, when there are no operands, the fields are given their defaults, so it is `struct.new_default`.
