### ISSUE TITLE
expected version 0a 00 00 00, found 0b 00 00 00 @+4

### ISSUE THREAD

**Issue by tiancode** [WebAssembly/binaryen#604]
undefined:1 Uncaught (in promise) WASM.instantiateModule(): Result = expected version 0a 00 00 00, found 0b 00 00 00 @+4

**Comment by kripken** [comment]
What binaryen was used, and in what browser was it tested? Binaryen emits 0xb (the "found" result there), and current nightlies should support that, if you have 0xa then perhaps you're on an older nightly?

**Comment by ramiro1234** [comment]
I write the wasm output to a file and set the version manually. The browsers are not always up to date

**Comment by chrisber** [comment]
Same problem here:
- Chrome `Version 54.0.2840.100 (64bit)`:
    - `Uncaught (in promise) WebAssembly.compile(): Result = expected version 0b 00 00 00, found 0d 00 00 00 @+4
`
- Chromium: `Version 53.0.2785.143 Built on Ubuntu , running on Ubuntu 16.04 (64-bit`:
    - `Uncaught (in promise) WebAssembly.Instance(): Result = expected version 0b 00 00 00, found 0d 00 00 00 @+4`
- Node: `v7.1.0`:
    - `WebAssembly.Module(): Result = expected version 0b 00 00 00, found 0d 00 00 00 @+4`

Any workaround to compile to the correct target version?

**Comment by kripken** [comment]
You can use an old tag of binaryen for each of those binary versions. But, it is better to just use the very latest chrome canary or firefox nightly, which support 0xd (the `0d` you see in the `found` versions in those messages).

Closing this issue as it isn't a problem in binaryen. Perhaps we should document this better somehow though?

**Comment by sebpiq** [comment]
So this is just a problem of browser version right?
