### ISSUE TITLE
`Unknown option '-0'` when attempting default optimize

### ISSUE THREAD

**Issue by secondl1ght** [WebAssembly/binaryen#6041]
I am using the `wasm-opt --help` command to view the available options and I am attempting to optimize a file with the `-0` (default) optimizations. However I get `Unknown option '-0'` as the response. Am I missing something from the docs to get this working? Thanks!

**Comment by MaxGraey** [comment]
It should be `-O` (letter) instead `-0` (zero digit)

**Comment by secondl1ght** [comment]
Whoops, thank you. 😄
