### ISSUE TITLE
no native wasm support detected- hello_world.c

### ISSUE THREAD

**Issue by parulkhanna** [WebAssembly/binaryen#607]
Hi,

I am using Binaryen & Emscripten on MACOSX. Whenever I try to compile with native-wasm method. I get following error at time of execution.

```
`Paruls-MacBook-Pro:incoming parulkhanna$ ./emcc hello_world.c -s BINARYEN=1 -s 'BINARYEN_METHOD="native-wasm"' -s 'BINARYEN_SCRIPTS="spidermonkify.py"' 
Paruls-MacBook-Pro:incoming parulkhanna$ node a.out.js 
trying binaryen method: native-wasm
no native wasm support detected

/Users/parulkhanna/Desktop/emsdk_portable/emscripten/incoming/a.out.js:425
      throw ex;
      ^
no binaryen method succeeded
```

Also, if I generate .wasm .wast using simple BINARYEN=1 flag. How I can use polyfil to execute wasm files in browser. 

Any help will be appreciated, Thanks.

**Comment by kripken** [comment]
Node.js doesn't have wasm support yet. When it gets a recent enough v8 it might work with a flag. Otherwise, you can use trunk builds of v8 or spidermonkey, or use a nightly build of firefox or chrome with a flag.

**Comment by parulkhanna** [comment]
Hi, 

Thanks for the reply. Can you please provide me the steps how to do that. I am unable to find a method. 

> Otherwise, you can use trunk builds of v8 or spidermonkey, or use a nightly build of firefox or chrome with a flag.

Thanks,

**Comment by kripken** [comment]
For example, you can get firefox nightly [here](https://nightly.mozilla.org/), and then open `about:config` and look for a pref with `wasm` in the name, and turn it on.

**Comment by parulkhanna** [comment]
Hi,

Thanks for the reply. I have changed the settings and tested the browser with demo given on web assembly's website. I am really not able to understand the details given in [](https://github.com/WebAssembly/polyfill-prototype-1/). How can I execute my ./emcc hello_world.c -s BINARYEN=1...... wasm output file in the browser. 

Thanks,

**Comment by parulkhanna** [comment]
Hi, 

Can you provide me with the steps on how I can run wasm file in browser. I am not getting the explanation on this link https://github.com/WebAssembly/polyfill-prototype-.
thanks,

**Comment by kripken** [comment]
Instead of running the js file in node, you can run it in a browser by creating an html file that contains a script tag whose source is that js file.

**Comment by parulkhanna** [comment]
Hi, I used the following command and still got the same error. (*screenshot attached*)

`./emcc hello_world.c -s BINARYEN=1 -s "BINARYEN_METHOD='native-wasm'" -s 'BINARYEN_SCRIPTS="spidermonkify.py"' -o helloworldy.html


<img width="1275" alt="screen shot 2016-06-28 at 5 58 01 pm" src="https://cloud.githubusercontent.com/assets/6426212/16433797/fa59524e-3d59-11e6-9479-e61c849ade12.png">

**Comment by kripken** [comment]
Is that with firefox nightly, and with the pref I mentioned?

If it is, then something else must be wrong but I have no idea what. You can debug in the source code, search for that error message, then read the code around it, and you will see what it is looking for that it can't find, that leads to the error being printed.
