### ISSUE TITLE
What's the BinaryenType of ref.func instruction?

### ISSUE THREAD

**Issue by mobsceneZ** [WebAssembly/binaryen#6090]
Hello developers, I have a question related to the BinaryenType of `ref.func` instruction, give following code as an example:

```C
...
BinaryenExpressionRef test_expr = BinaryenRefFunc(mod, "$test1", BinaryenTypeFuncref());
printf("%lu\n", BinaryenExpressionGetType(test_expr));
printf("%lu\n", BinaryenTypeFuncref());
```

To my understanding, `BinaryenExpressionGetType(test_expr)` should give the same value as the output of `BinaryenTypeFuncref()`, however, it doe not. Why it's behaved this way? My current Binaryen version is commit 4f1295a96d.

**Comment by kripken** [comment]
The type of a `ref.func` is more specific than `funcref`. `funcref` is a generic type that can be null or it can be a reference to any possible function. A particular `ref.func` cannot be null, and it includes type information about the function signature (parameters and return values).

For more information see the Typed Function References proposal which is where those types are specced: https://github.com/WebAssembly/function-references/blob/main/proposals/function-references/Overview.md

**Comment by mobsceneZ** [comment]
> References

Thanks, kripken, that's pretty clear 👍.
