### ISSUE TITLE
Test output on CI is extremely noisy

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/binaryen#6104]
Its really hard to see the wood for the tree.  For example these strings seem to appear hundreds of times in the output:
```
warning: no output file specified, not emitting output
warning: no passes specified, not doing any work
```

For example: https://github.com/WebAssembly/binaryen/actions/runs/6815175181/job/18533714847?pr=6091

**Comment by kripken** [comment]
I think this can be closed after #6109, or at least I can't find any more spam to remove :smile:
