### ISSUE TITLE
Some Questions Related To `BinaryenType` in C API

### ISSUE THREAD

**Issue by mobsceneZ** [WebAssembly/binaryen#6129]
Hi developers, this issue is related to the `BinaryenType` in C API. Specifically, there are two separate questions:

- How to retrieve each specific type from a multi-value type? For example, suppose we define a block with result type `(i32 i32 i64)`, when we use `BinaryenExpressionGetType` to get the type of this block, it returns a run-time type id. How can we retrieve the corresponding type arrays in C API, in the form similar to `BinaryenType*` that we pass to `BinaryenTypeCreate` ?

- In issue #6090 , I asked about the the reason why the type returned by `ref.func` instruction is different from the generic `BinaryenTypeFuncref()`, but another question arises that how can we determine whether a run-time type id is a `funcref` or `externref` in C API? (I mean, since I can not know whether the instruction returns a `funcref` type or not by directly comparing `BinaryenExpressionGetType(expr)` with  `BinaryenTypeFuncref()`)

Thanks in advance and please forgive my ignorance about rather new proposals since I am now referencing only core specification.

**Comment by mobsceneZ** [comment]
It seems like the first question can be addressed by `BinaryenTypeExpand` C API, but I still cannot figure out how to solve the second question, can anybody help 😕  ?

**Comment by kripken** [comment]
I think you can do direct comparisons? You can check if a type is `i32` by comparing it to `BinaryenTypeInt32()`, and to `funcref` with `BinaryenTypeFuncref()`, etc.

**Comment by mobsceneZ** [comment]
> I think you can do direct comparisons? You can check if a type is `i32` by comparing it to `BinaryenTypeInt32()`, and to `funcref` with `BinaryenTypeFuncref()`, etc.

Hey kripken, what I mean is that suppose we have a `drop` instruction and since `drop` produces no value on stack, so when we want to deduce what type `drop` instruction is dropping, we have to check the child instruction's type by `BinaryenDropGetValue` API, so here comes the question: what if child node is a `ref.func` instruction which returns more specific function reference type rather than the generic `BinaryenTypeFuncref()`, how can we determine it actually returns a `funcref`?

**Comment by kripken** [comment]
A `ref.func` will always return a more specific function type than `funcref`.

You can also check if a type is a specific function type using `BinaryenHeapTypeIsSignature` (signatures is the formal name for specific function types, that are all subtypes of the basic type `funcref`).

**Comment by mobsceneZ** [comment]
> A `ref.func` will always return a more specific function type than `funcref`.
> 
> You can also check if a type is a specific function type using `BinaryenHeapTypeIsSignature` (signatures is the formal name for specific function types, that are all subtypes of the basic type `funcref`).

Thanks for your response, kripken. That helps a lot ;)
