### ISSUE TITLE
Measure execution time for wasm binary

### ISSUE THREAD

**Issue by parulkhanna** [WebAssembly/binaryen#613]
Hi,

I have converted my c program into asm.js (native-wasm and interpret binary method) using emscripten/ Binaryen.  I want to calculate the execution time for evaluation.  

1. For interpret binary file I am using 

> time node.js filename.js 
Output
 ```
real	0m1.728s
user	0m2.145s
sys	0m0.269s
```
(Please suggest if there is a better way to measure this)

 **For native-wasm** I cannot execute it in node as it is not supported yet. 
I can run the file in Firefox Nightly by linking it with my html.

Is there any way to measure execution time. I want to see the performance difference by measuring the time of execution for regular asm.js produced by emscripten  vs webassembly asm.js .

Thanks,
P

**Comment by kripken** [comment]
On small program probably most of that time is starting up node and compiling the JS. If you want just execution time, it might be best to do it in the program itself: note the time before doing some work, then note it again after and print the difference to see how much passed.
