### ISSUE TITLE
lack of stringref support docs for javascript for host language

### ISSUE THREAD

**Issue by ericvergnaud** [WebAssembly/binaryen#6144]
Hi,

I'm trying to leverage the 0-copy stringref spec using Node 21.3.
I'm struggling to understand how to pass a js string to the string functions:

When I write:
```
...
const constref = binaryen._BinaryenStringConst(module, "Hello world!");
...

```
I get the following when emitting text:

```
(module
 (type $0 (func (result stringref)))
 (export "stuff" (func $stuff))
 (func $stuff (result stringref)
  (return
   (string.const "")
  )
 )
)

```
Note the empty string after `string const`.
When I call `emitBinary`, it fails with _it != stringIndexes.end(), at: .../wasm-binary.cpp,691,getStringIndex_  ...

The same happens when I write:

```
...
const stringref = binaryen._BinaryenStringNewWTF16("Hello world!");
const constref = binaryen._BinaryenStringConst(module, stringref);
...

```

I haven't been able to locate a working sample for using stringref from js.
@wingo thanks for the great spec. Am I missing something from the docs ? If not, would it be worth providing examples for passing strings back and forth in a language that supports wasm-gc ?

**Comment by tlively** [comment]
This definitely seems like a Binaryen bug, but note that stringref is essentially deprecated for the moment in favor of [JS string builtins](https://github.com/WebAssembly/js-string-builtins/blob/main/proposals/js-string-builtins/Overview.md).

**Comment by ericvergnaud** [comment]
Ah. Thanks for the information. Is this documented ? Is that a WebAssembly or Binaryen deprecation ?

**Comment by ericvergnaud** [comment]
Ok I found the wasm committee meeting minutes. 
Very poor decision if you ask me. IMHO the primary driver for WASM is the ability to run in the web code written in languages not specific to the web. The 'silent' requirement is that the same code can still run outside the Web. 
The JS String decision is incompatible with that.
I was a bit shocked to read that strings are an 'exotic' feature. EVERY programming language has built-in support for strings, notably string literals. Sure, they have a very different implementation from one platform to another, but they all mean the exact same thing. 
Very sad.
