### ISSUE TITLE
Questions Related to BinaryenTypeAuto

### ISSUE THREAD

**Issue by mobsceneZ** [WebAssembly/binaryen#6183]
Hey developers, when browsing through the `binaryen-c.h` I see a C API called `BinaryenTypeAuto`, which as the comment claims "**Used as the last parameter to BinaryenBlock to let the API figure out the type instead of providing one**". That's pretty interesting so that I write a simple test file to check its actual effect: 

```C
#include <stdio.h>
#include <stdlib.h>
#include <binaryen-c.h>

int main(int argc, char* argv[]) {

    BinaryenModuleRef module = BinaryenModuleCreate();

    BinaryenType ii[2] = {BinaryenTypeInt32(), BinaryenTypeInt32()};
    BinaryenType params = BinaryenTypeCreate(ii, 2);
    BinaryenType results = params;

    BinaryenExpressionRef x = BinaryenLocalGet(module, 0, BinaryenTypeInt32()),
                          y = BinaryenLocalGet(module, 1, BinaryenTypeInt32());
    BinaryenExpressionRef* block_list = calloc(2, sizeof(BinaryenExpressionRef));
    block_list[0] = x;
    block_list[1] = y;
    BinaryenExpressionRef block = BinaryenBlock(module, "test", block_list, 2, BinaryenTypeAuto());

    BinaryenFunctionRef test = BinaryenAddFunction(module, "1", params, results, NULL, 0, block);

    BinaryenModulePrint(module);

    BinaryenModuleDispose(module);
    free(block_list);

    return 0;

}
```
I expect that it should emit a block with result type `i32 i32`, however when compiling above program and running it, it gives following output:
```wasm
(module
 (type $0 (func (param i32 i32) (result i32 i32)))
 (func $1 (param $0 i32) (param $1 i32) (result i32 i32)
  (block $test (result i32)
   (local.get $0)
   (local.get $1)
  )
 )
)
```
So my questions are:
- Why `BinaryenTypeAuto` gives type `i32` instead of `i32 i32`?
- Should I use `BinaryenTypeAuto` in development process? Is it a good practice?

Thanks in advance for any kind response.

**Comment by kripken** [comment]
Binaryen IR is not in "stack machine" form, that is, two local.gets after the other do not push two values on the stack. Binaryen is [more structured](https://github.com/WebAssembly/binaryen#binaryen-ir), like LLVM IR, and so to create multivalues you need to use a tuple type. This is how such a block should look:
```wat
(block (result i32 i32)
  (tuple.make 2
    (local.get $x)
    (local.get $y)
  )
)
```
If that is not convenient for you then another option is to write out stack machine-style code in text format and parse that. (Atm you must use another parser but soon Binaryen's parser will support that form as well, and generate tuples from it.)

**Comment by mobsceneZ** [comment]
> Binaryen IR is not in "stack machine" form, that is, two local.gets after the other do not push two values on the stack. Binaryen is [more structured](https://github.com/WebAssembly/binaryen#binaryen-ir), like LLVM IR, and so to create multivalues you need to use a tuple type. This is how such a block should look:
> 
> ```webassembly
> (block (result i32 i32)
>   (tuple.make 2
>     (local.get $x)
>     (local.get $y)
>   )
> )
> ```
> 
> If that is not convenient for you then another option is to write out stack machine-style code in text format and parse that. (Atm you must use another parser but soon Binaryen's parser will support that form as well, and generate tuples from it.)

Aha I see, that's very clear explanation, thanks kripken!
