### ISSUE TITLE
Take advantage of the wider range of expressions in wasm.

### ISSUE THREAD

**Issue by JSStats** [WebAssembly/binaryen#62]
Seeing code that could eliminate uses of intermediate local variables. These might be an effect of the conversion from asm.js to wasm given that wasm supports a wider range of expressions. Perhaps the llvm backend will do a better job here, or perhaps it also needs some help. Just filing this to put it on the radar, plus some other potential simplifications.

1. Can the `(eq <> 0)` be remove, flipping the order of the `if_else` branches, or is there locality or likely path semantics to preserve?  See a few of these in the code.

2. It seems possible to hoist the `set_local $i3` repeated in each `if_else` branch out of the `if_else`.

3. It might then be clearer that the `set_local $i3` `get_local $i3` can be eliminated.

4. This would fee the `$i3` local which could be removed.

5. The `block $topmost` still seems unnecessary - see https://github.com/WebAssembly/binaryen/issues/32

6. See a few uses of `if_else` with a `(i32.const 0)` branch. Could/does `if` return 0 when not taken? If so then this code could be further simplified to use just `if` and remove the `(i32.const 0)` branch.

```
(func $_wctomb (param $i1 i32) (param $i2 i32)
 (result i32)
 (local $i3 i32)
  (block $topmost
    (if_else (i32.eq (get_local $i1) (i32.const 0))
     (set_local $i3 (i32.const 0))
     (set_local $i3 (call $_wcrtomb (get_local $i1) (get_local $i2) (i32.const 0))))
    (get_local $i3)))`
```

Could be simplified to:
```
(func $_wctomb (param $i1 i32) (param $i2 i32)
 (result i32)
 (if_else (get_local $i1)
     (call $_wcrtomb (get_local $i1) (get_local $i2) (i32.const 0))
     (i32.const 0)))

**Comment by kripken** [comment]
Where is that `wctomb` from? I see it in `test/emcc_hello_world.wast`, where it is in unoptimized form (there is an optimized version with `_O2_` in the name, but it lacks that method - might have been inlined).

**Comment by JSStats** [comment]
Managed to get the `set_local` hoisted out of the `if_else`, but it looks like a smarter pass (dominator analysis) might be needed in general to then optimize away the local variable. Shall assume these are asm.js artifacts and will follow up if there are still similar issues with llvm.
