### ISSUE TITLE
Binaryen crashes when containing a call to _BinaryenArraySet

### ISSUE THREAD

**Issue by ericvergnaud** [WebAssembly/binaryen#6215]
When a block contains a _BinaryenArraySet statement, Binaryen crashes during validation and emission.
This happens with both the wasm and the js targets.
It looks like a required value is null, here is the assert log:
Aborted(Assertion failed: *currp, at: /Users/ericvergnaud/Development/binaryen/src/wasm-traversal.h,313,pushTask).

**Comment by kripken** [comment]
I don't see anything obviously wrong in the C++ for that method, and we have a passing test using it in `test/example/c-api-kitchen-sink.c`.

I assume you've made sure you are not passing in a null somehow? If you have a small testcase showing the issue I can also take a look.

**Comment by ericvergnaud** [comment]
I also don't see anything obviously wrong in the C++ for that method.
My understanding is that `test/example/c-api-kitchen-sink.c` calls entry points, but does not actually attempt to generate code ?
To clarify, the crash does not happen when calling _BinaryenArraySet, it happens when validating or generating wasm from code that contains a call to _BinaryenArraySet. This might explain why it's not caught by the tests.
That said, I'm putting together an example to reproduce the issue.

**Comment by kripken** [comment]
> My understanding is that test/example/c-api-kitchen-sink.c calls entry points, but does not actually attempt to generate code ?

Hmm, I see it doesn't generate a wasm binary, but it does validate and print the module, so it is checking it and using it. I added a write to binary locally and that works too.

**Comment by ericvergnaud** [comment]
I'm not able to reproduce this by hand-coding the equivalent code... frustrating, but if there's a bug it's not what this issue says. Closing, thanks for your attention.
