### ISSUE TITLE
API inconsistency with data segments

### ISSUE THREAD

**Issue by ericvergnaud** [WebAssembly/binaryen#6247]
Segments used for memory initialization do not have a name.
However, APIs that load data from segments require a segment name.
That "name" is actually the textual form of the 0-based segment index.
That makes the API misleading. Why not have the API receive the segment index instead ?

**Comment by kripken** [comment]
All module elements have a name, though the API might allow you to create one without specifying what it will be, and then it will typically be a number that happens to correspond to the order in which it was added.

Internally you can see this in `wasm.h`: data segments are listed in the vector `dataSegments` and also there is a map of name to data segment in `dataSegmentsMap`.

All APIs should take names to identify items - the index should not really be used anywhere except where it absolutely must (like when writing the binary format). A benefit of using names is that they add an indirection, meaning the names can be stable even if the order of items changes, which e.g. allows us to sort globals (say, by frequency, to shrink LEB sizes) without needing to modify offsets in every `global.get` in the whole module.

**Comment by ericvergnaud** [comment]
I agree in principle but then shouldn’t the API for setting memory data segments accept named segments rather than anonymous ones ?

**Comment by kripken** [comment]
Do you mean `BinaryenMemoryInitGetSegment`? It returns a `const char*` name, though I see the comment looks out of date as it mentions an index?

**Comment by ericvergnaud** [comment]
I'm referring to `BinaryenSetMemory` which does not require/accept segment names.
Rather it generates them from their index: `auto curr = Builder::makeDataSegment(Name::fromInt(i)...`.
Looking at other APIs, I see that `BinaryenGetMemorySegmentByteOffset`, `BinaryenGetMemorySegmentByteLength`, `BinaryenGetMemorySegmentPassive` and `BinaryenCopyMemorySegmentData` also require an index, not a name...

But `BinaryenArrayNewData` requires a name in order to wrap `makeArrayNewData`. Should I change that to an index and call `Name::fromInt(i)` within the function ? It can be a struggle to guess what the name should be, hence this issue.

Or should we accept segment names for all above APIs ?

**Comment by tlively** [comment]
All the APIs should be updated (or have new variants introduced?) that take names. Binaryen IR used to refer to segments by index, but that was fixed so that internally it uses names everywhere. The C API was not updated at the same time.

**Comment by ericvergnaud** [comment]
Happy to provide the corresponding PR but that will definitely break for consumers of the API. Are we ok with that ?

**Comment by kripken** [comment]
I think this is a reasonable breaking change, given the old API was not that usable anyhow.
