### ISSUE TITLE
Validator yells at stack-based block

### ISSUE THREAD

**Issue by ericvergnaud** [WebAssembly/binaryen#6269]
Hi,
I'm compiling a `x++` like expression, which requires returning the value of a local before it is incremented.
The generated wasm looks like this:
```
(block (result i32)
 (local.get $2)
 (local.set $2
  (i32.add
   (local.get $2)
   (i32.const 1)
  )
 )
)

```
I believe the block _body_ is valid wat.
But it's in a block, and binaryen yells with 2 errors:
`[wasm-validator error in function fromUTF8] unexpected false: non-final block elements returning a value must be drop()ed (binaryen's autodrop option might help you)`
and
`[wasm-validator error in function fromUTF8] none == none: block with value must not have last element that is none`

I understand the messages, but I would expect the validator to detect that since there is an i32 on the stack, it's ok for the last instruction (`local.set $2`) to return `none`...

Is the current behavior:
1.  an issue with the validator ?
2.  a binaryen limitation ?
3.  a WebAssembly limitation ?

If it's 2., then what are my options for generating the above snippet ? 
(I know I can simply create a temp variable but that's very ugly, especially since WebAssembly doesn't support scoped locals)

**Comment by kripken** [comment]
This is "unstructured/stacky" code that binaryen's current text format doesn't support. It only supports the structured form, where all children are nested in their parents.

The new parser will fix that eventually, but BinaryenIR is structured, so it will use a temp local. We can optimize those away in some cases, but it is just a minor code size issue (when the code executes it may well need a temp register for such code anyhow).

**Comment by ericvergnaud** [comment]
Thanks, closing.

**Comment by ericvergnaud** [comment]
BTW curious question: since binaryen does not support "unstructured/stacky" code, how does it deal with it when it originates from a binary being loaded ?

**Comment by kripken** [comment]
It adds locals as needed (and often optimizes them away later).

**Comment by kripken** [comment]
Hmm, I can't think of why it would work - it should error, but maybe the validator is missing something. But it's easy to see what's going on by printing the IR to see, is it valid?

**Comment by ericvergnaud** [comment]
Yes, here is the code being compiled:
`@ModuleExport function stuff(v: i32): i32 { const a: i32 = v++; const b: i32 = v++; return b; }`

Here is the corresponding IR. It runs as _desired_, but maybe that's not expected...
I would be tempted to adjust the validator logic, but I don't know enough about binaryen internals to form a useful opinion.
```
(module
 (type $0 (func (param i32) (result i32)))
 (memory $0 1)
 (export "stuff" (func $stuff))
 (func $stuff (type $0) (param $0 i32) (result i32)
  (local $a i32)
  (local $b i32)
  (local.set $a
   (block (result i32)
    (local.get $0)
    (local.set $0
     (i32.add
      (local.get $0)
      (i32.const 1)
     )
    )
   )
  )
  (local.set $b
   (block (result i32)
    (local.get $0)
    (local.set $0
     (i32.add
      (local.get $0)
      (i32.const 1)
     )
    )
   )
  )
  (return
   (local.get $b)
  )
 )
)
```

**Comment by kripken** [comment]
I don't think it validates:
```
$ bin/wasm-opt a.wat -all
[wasm-validator error in function stuff] unexpected false: non-final block elements returning a value must be drop()ed (binaryen's autodrop option might help you), on 
(block (result i32)
 (local.get $0)
 (local.set $0
  (i32.add
   (local.get $0)
   (i32.const 1)
  )
 )
)
(on index 0:
0x55b01c6f4a10
), type: i32
[wasm-validator error in function stuff] none == none: block with value must not have last element that is none, on 
(block (result i32)
 (local.get $0)
 (local.set $0
  (i32.add
   (local.get $0)
   (i32.const 1)
  )
 )
)
[wasm-validator error in function stuff] unexpected false: non-final block elements returning a value must be drop()ed (binaryen's autodrop option might help you), on 
(block (result i32)
 (local.get $0)
 (local.set $0
  (i32.add
   (local.get $0)
   (i32.const 1)
  )
 )
)
(on index 0:
0x55b01c6f4b20
), type: i32
[wasm-validator error in function stuff] none == none: block with value must not have last element that is none, on 
(block (result i32)
 (local.get $0)
 (local.set $0
  (i32.add
   (local.get $0)
   (i32.const 1)
  )
 )
)
Fatal: error validating input
```
It's possible that it happens to get emitted as valid wasm despite not being valid Binaryen IR, but I would not depend on that. In particular anything non-valid will be at very high risk of getting optimized incorrectly.

**Comment by kripken** [comment]
Indeed, I tried to optimize it and it fails:
```
$ bin/wasm-opt a.wat -all --no-validation -O1
wasm-opt: Vacuum.cpp:72: wasm::Expression* wasm::Vacuum::optimize(wasm::Expression*, bool, bool): Assertion `!resultUsed || curr->type != Type::none' failed.
Aborted
```

**Comment by ericvergnaud** [comment]
Yes, not surprising since I opened this issue because the validator was yelling.
I'm just wondering now if it would be worth considering blocks as a special case in the validator, the optimizer and other tools ? After all, it is valid wasm, so _in principle_ it would be an improvement of binaryen...
Another idea I came up with would be to implement push/pop commands as follows:
```
(block (result i32)
 (push
    (local.get $0)
  )
  (local.set $0
  (i32.add
   (local.get $0)
   (i32.const 1)
  )
  (pop i32)
 )
)

```
but that would require evolving the wat spec

**Comment by kripken** [comment]
> I'm just wondering now if it would be worth considering blocks as a special case in the validator, the optimizer and other tools ?

Unfortunately that would be a pretty massive change in the IR, requiring changes across many passes and utilities. Also it would remove a lot of the current efficiency we have, where if you have a `Binary` `AddInt32` then you just do `curr->left|right` to get the left and right operands, but if they could be outside of the current node then you need to go to the parent block and look there. There would be benefits too of course, but overall in Binaryen IR we've chosen a different set of tradeoffs.

**Comment by tlively** [comment]
Closing this since the problem was explained and this is WAI.

**Comment by chharvey** [comment]
> The new parser will fix that eventually

@kripken Can you point me to any announcements / where I can learn more about the “new parser”? This is the first I’m hearing about it (though I’m not super involved). What changes should we expect and when? Thanks

**Comment by tlively** [comment]
The new parser has been landed for a while now. The main change is that we can now parse any standard WebAssembly text. So the block in the opening post will now parse just fine, for example, although Binaryen now just automatically adds the temp locals that had to be manually added before.

**Comment by chharvey** [comment]
Thanks @tlively . Do you know what version it’s been added in or can you point me to the changelog? I’m still using (AssemblyScript’s) binaryen.js v125.0.0, which is the latest version on npm as of currently, and still seeing the same exact error OP posted.

**Comment by tlively** [comment]
The new parser was included in v118: https://github.com/WebAssembly/binaryen/blob/main/CHANGELOG.md#v118. I'd be happy take a look at a reproducer for your issue and see what's going on.

**Comment by chharvey** [comment]
Thanks for taking a look. I reduced mine down to a minimal reproducible example, very similar to OP’s code. The weird thing is, with regular WAT it works fine, but only with binaryen.js’s interface I see the error.

```js
import * as assert from 'node:assert';
import {suite, test} from 'node:test';
import binaryen from 'binaryen';

suite('testing #6269.', () => {
	test('passes when parsing text.', () => {
		const mod = binaryen.parseText(`
			(module
				(global $i (mut i32) (i32.const 0))
				(func $i++ (result i32)
					(block (result i32)
						(global.get $i)
						(global.set $i (i32.add (global.get $i) (i32.const 1)))
					)
				)
			)
		`);
		assert.ok(mod.validate());
	});

	test.expectFailure('fails when coding programmatically.', () => {
		const mod = binaryen.parseText(`
			(module)
		`);
		mod.addGlobal('j', binaryen.i32, true, mod.i32.const(0));
		mod.addFunction('j++', binaryen.none, binaryen.i32, [], mod.block(null, [
			mod.global.get('j', binaryen.i32),
			mod.global.set('j', mod.i32.add(mod.global.get('j', binaryen.i32), mod.i32.const(1))),
		]));
		assert.ok(mod.validate());
	});
});
```

Error report:

```
[wasm-validator error in function j++] unexpected false: non-final block elements returning a value must be dropped, on 
(block
 (global.get $j)
 (global.set $j
  (i32.add
   (global.get $j)
   (i32.const 1)
  )
 )
)
(on index 0:
0x551590
), type: i32
[wasm-validator error in function j++] function body type must match, if function returns, on 
(block
 (global.get $j)
 (global.set $j
  (i32.add
   (global.get $j)
   (i32.const 1)
  )
 )
)
```

**Comment by kripken** [comment]
@chharvey The new parser will handle the "stacky" pattern of `get, set` (the get is the value that flows out after the set), but the binaryen.js API does not. binaryen.js's API is basically direct access to Binaryen IR, which is more structured than wat, and does not support such stacky code (see "stacky" notes in [the docs](https://github.com/WebAssembly/binaryen?tab=readme-ov-file#binaryen-ir)).
