### ISSUE TITLE
Access to DOM APIs

### ISSUE THREAD

**Issue by heapwolf** [WebAssembly/binaryen#628]
I see access to [`DOM APIs`](https://github.com/WebAssembly/design/blob/master/GC.md) in "Future versions" (listed on the [`roadmap`](http://webassembly.github.io/)), does anyone know how far away this is? Maybe there is some kind of undocumented primitive that can be used today?

**Comment by sajjadarashhh** [comment]
@heapwolf hi heapwolf i dont know :DDDD

**Comment by tlively** [comment]
[ESM integration](https://github.com/WebAssembly/esm-integration) is probably the closest thing that's currently in progress, but it's unclear when it will be standardized. This would be a better question for that repo or for the [design repo](https://github.com/WebAssembly/design).
