### ISSUE TITLE
wasm-opt failed when build qt's project use emscripten

### ISSUE THREAD

**Issue by Gaobo-Hp1** [WebAssembly/binaryen#6340]
Hello, 
I got an error when build qt's project use emscipten, the console log is :
>  D:/App/Qt/Tools/emsdk-main/upstream\bin\wasm-opt --strip-dwarf --post-emscripten -O2 --low-memory-unused --asyncify --pass-arg=asyncify-imports@env.qt_asyncify_suspend_js,env.qt_asyncify_resume_js,env.invoke_*,wasi_snapshot_preview1.fd_sync,env.__wasi_fd_sync,env.__asyncjs__*,env.emscripten_idb_load,env.emscripten_idb_store,env.emscripten_idb_delete,env.emscripten_idb_exists,env.emscripten_idb_load_blob,env.emscripten_idb_store_blob,env.emscripten_sleep,env.emscripten_wget,env.emscripten_wget_data,env.emscripten_scan_registers,env.emscripten_lazy_load_code,env._load_secondary_module,env.emscripten_fiber_swap,env.SDL_Delay,env._emval_await --zero-filled-memory --pass-arg=directize-initial-contents-immutable --strip-debug --strip-producers VIEW.wasm -o VIEW.wasm --mvp-features --enable-threads --enable-bulk-memory --enable-mutable-globals --enable-sign-ext' failed (returned 3221226505)

This error occurs when compiling with Release. I think the reason is that my computer memory is not enough，but even i increase the memory to 32GB, it also failed.

Is there have a log file that i can know the reason?

**Comment by tlively** [comment]
Closing this since the original question was answered. Feel free to reopen if there are follow-up questions.
