### ISSUE TITLE
availability of version 116 via apt-get on Ubuntu

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [WebAssembly/binaryen#6342]
I have come across an issue in a wasm file I am generating (only when I ask cargo to strip the file BTW) that exists in 115, but seems fixed in 116.
However, my CI GH Action runs on ubuntu-latest and installs binaryen via apt-get.
this is still installing 105 still and so it fails.
```
/usr/bin/wasm-opt
wasm-opt version 105
```
When will the ubuntu package be updated do you think?
Is there an alternative (easy) way to install 116 from GH Action?
thanks

**Comment by kripken** [comment]
You can download it here, and then just need to unpack it (and add to path etc. if you want): https://github.com/WebAssembly/binaryen/releases/tag/version_116

(We don't work on the Ubuntu packaging of this software, so when they intend to update to 116 is something they would only know on the Ubuntu side.)

**Comment by andrewdavidmackenzie** [comment]
Thanks. I'll install manually.
I see that even their latest in "Active Development" release still plans to bundle a pretty old version of binaryen!
