### ISSUE TITLE
Error compiling web assembly 

### ISSUE THREAD

**Issue by parulkhanna** [WebAssembly/binaryen#636]
Hi everyone,

I am getting following error when I am trying to run emcc with Binaryen Backend.
I have installed fastcomp compiler from source and have updated the .emscripten config file too.
I am using incoming sdk. 

> /home/User/Downloads/emsdk_portable/myfastcomp/emscripten-fastcomp/build/bin/lli: error creating EE: No available targets are compatible with this triple, see -version for the available targets.
> FAIL: Running the generated program failed!
> Traceback (most recent call last):
>   File "/usr/bin/emcc", line 1864, in <module>
>     final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
>   File "/usr/share/emscripten/tools/shared.py", line 1276, in emscripten
>     assert os.path.exists(filename + '.o.js') and len(open(filename + '.o.js', 'r').read()) > 0, 'Emscripten failed to generate .js: ' + str(compiler_output)
> 

Thanks

**Comment by kripken** [comment]
What is the full command that you run? And what is the full debug output (with `EMCC_DEBUG=1` in the env)?
