### ISSUE TITLE
Cannot compile simple C program to webassembly/asm.js

### ISSUE THREAD

**Issue by parulkhanna** [WebAssembly/binaryen#639]
Hi,

```
This is my C code which I am trying to compile using 
Paruls-MacBook-Pro:sample parulkhanna$ emcc helloworld.c -s BINARYEN=1 
Paruls-MacBook-Pro:sample parulkhanna$ node a.out.js 
trying binaryen method: native-wasm
no native wasm support detected
trying binaryen method: interpret-binary
binaryen method succeeded.
Hello world
Paruls-MacBook-Pro:sample parulkhanna$ 
```
**It does not creates text file as specified in my C code** 
```
This is the code for C file
#include <stdio.h>

int main()
{
  FILE *test;
  test = fopen("parul.txt", "w");
  fprintf(test, "%s", "hello world");
  fclose(test);
  printf("Hello world\n");
  return 0;
}
```
Is it normal, 
<img width="1240" alt="screen shot 2016-07-15 at 2 39 55 pm" src="https://cloud.githubusercontent.com/assets/6426212/16884924/07963c04-4a9a-11e6-9dac-d7db0e7b4ba0.png">

Thanks,

**Comment by kripken** [comment]
Yes, this is normal. While node.js does have APIs for local file access, JS environments in general are sandboxed, and cannot do such things. Instead, emscripten generates a virtual file system, see http://kripken.github.io/emscripten-site/docs/getting_started/Tutorial.html?highlight=filesystem#using-files

Emscripten also has node-specific ways to access local files, see NODEFS. But note that most development effort is on running emscripten code on the web, using web APIs, and not node.

**Comment by parulkhanna** [comment]
Thank you  for the information. Really helped.
