### ISSUE TITLE
Support block-type parameters

### ISSUE THREAD

**Issue by wingo** [WebAssembly/binaryen#6407]
Binaryen does not currently support block / if / loop / try parameters, which were added to the standard a few years ago via the multi-value proposal.

The [Hoot Scheme compiler](https://gitlab.com/spritely/guile-hoot) emits blocks with parameters, which works fine in browsers, but we cannot use wasm-opt on our binaries for this reason:

```
$ bin/wasm-opt --all-features ~/src/guile-hoot/out.wasm
[parse exception: control flow inputs are not supported yet (at 0:83175)]
Fatal: error parsing wasm (try --debug for more info)
```

See also https://github.com/WebAssembly/binaryen/pull/5962 and https://github.com/WebAssembly/binaryen/issues/5950.

**Comment by tlively** [comment]
Thankfully once we switch to the [new wat parser](#6208) (and also rewrite the binary parser to use the new `IRBuilder` utility), it will be easy to add support for block parameters by having the parsers implicitly lower them away and use locals instead.

Unfortunately having more in-depth support for block parameters than that is not really feasible with the structure of Binaryen IR, but it's plausible that in the future we could use an alternative IR to do late-stage optimizations that could reintroduce them before module writing.

**Comment by jayphelps** [comment]
Moonbit compiler also emits these. Btw I much appreciate that you all added error checking for this situation and now emit a clear error when encountered. I was at first using an old version of wasm-opt that didn't emit that error and I was confused what was wrong, but once I updated I was happy to see a clear answer.
