### ISSUE TITLE
Keep unused types

### ISSUE THREAD

**Issue by womeier** [WebAssembly/binaryen#6419]
### Intention
We're looking into verifying (in Coq) a validation of the `CoalesceLocals` optimization for our [certicoq-wasm compiler](https://github.com/womeier/certicoqwasm).
I.e., we'd like to run `wasm-opt --coalesce-locals` and then have a verified check, that the optimized module behaves the same.

### Problem
When running `wasm-opt --coalesce-locals` on such a module, binaryen removes unused types, which also renames type indices.
Our compiler generates a wasm module that contains some unused types (to make compilation easier).

To make the validation work (easier), it would help if the binary produced by `wasm-opt` was exactly the same as the input except for instructions like `local.get` and `local.set` etc, and the list of locals.

### Question
Is there a way to keep unused types around?
I expected that `wasm-opt` would only do the specified pass and nothing else.

`wasm-opt --coalesce-locals` also adds some `unreachable` instructions at unreachable places :), which would also be nice if they weren't generated in the first place, but we may be able to get rid of them in some other way

### Example
for a quick glance, see the diff of these two files, in particular we care about reducing the locals of function 5:
input program: [foo.wat.txt](https://github.com/WebAssembly/binaryen/files/14704479/foo.wat.txt)
after `wasm-opt --coalesce-locals`: [foo-final.wat.txt](https://github.com/WebAssembly/binaryen/files/14704474/foo-final.wat.txt)

**Comment by kripken** [comment]
Unfortunately, no - the design of wasm-opt is not focused on precise round-tripping like that. Just reading and writing a binary will do a few things while we convert wasm into our internal IR and then back to wasm. That is, the internal IR is not identical to wasm (it is designed for optimization), so you can notice changes happening.

Specifically, our IR doesn't actually store a list of types on the module. That would require updating every time we add a type, for example. Instead we store types globally, and only compute a list of types when converting from our IR to wasm. To do that we scan for used types and sort those, so unused types are not emitted.

However, a way you might work around this is to use the rec group structure from the GC proposal. We do not normally modify rec groups (not unless `--closed-world`) as they are part of the ABI. However, that means assuming GC is enabled, and there are other roundtripping artifacts you may notice aside from types.

**Comment by womeier** [comment]
Thanks for the quick reply!
We don't want to depend on WasmGC for now, seems we'll have to do sth. else.
