### ISSUE TITLE
Problem with ModuleReader read in empty module

### ISSUE THREAD

**Issue by qilinO-o** [WebAssembly/binaryen#6432]
I came across with some problems when using binaryen's ModuleReader in my project:
```cxx
wasm::ModuleReader reader;
this->module_ = BinaryenModuleCreate();
reader.read(this->config_.filename, *(this->module_));
std::cout << sizeof(*(this->module_)) << " " << sizeof(*BinaryenModuleCreate()) << std::endl;
if (!this->module_->functions.empty()) {
    ......
}
```
And the result is that the module read is just an empty module identical to `new wasm::Module()`.
I also tried:
```cxx
std::ifstream in(this->config_.filename, std::ios_base::in | std::ios_base::binary);
if (!in.is_open()) {
    return InstrumentResult::file_path_error;
}
in.seekg(0, std::ios::end);
int input_size = in.tellg();
in.seekg(0, std::ios::beg);
char* input = new char[input_size];
in.read(input, input_size);
in.close();
this->module_ = BinaryenModuleRead(input, input_size);
```
The result of it is the same.
Noted that my filename is of a `.wasm` file and I also tried a `.wat` file and `terminate called after throwing an instance of 'wasm::SParseException' Aborted` showed up.
The certain `.wasm` file is pretty simple, compiled by emscripten with cpp code:
```cxx
#include <emscripten.h>
EMSCRIPTEN_KEEPALIVE
int add(int a, int b) {
    return a + b;
}
```
and the `.wat` file is converted by wasm2wat.
If anyone used to encounter such problems or if you know how to fix it, please tell me! Thanks a lot anyway!

**Comment by kripken** [comment]
It might be helpful to look at the working examples in our test suite, specifically under `test/example/` there are a few C++ testcases that use `BinaryenModuleRead`.

**Comment by qilinO-o** [comment]
Thanks for your suggestion! But I found that all these examples follow the pattern:
```cxx
BinaryenModuleRef module = BinaryenModuleCreate();
... // which do operations on module
char buffer[N];
size_t written = BinaryenModuleWrite(module, buffer, buffer_size);
...
BinaryenModuleRef readModule = BinaryenModuleRead(buffer, written);
```
So there is no example about reading real file with BinaryenModuleRead.

**Comment by qilinO-o** [comment]
I have found out that the problem with `.wat` file lies in the S-expression. Take `add` as an example:
```
(func (;1;) (type 1) (param i32 i32) (result i32)
    local.get 0
    local.get 1
    i32.add)
```
This was generated by wasm2wat, but `ModuleReader.readText`, or say the parser in it requires a strictly formed S-expression:
```
(func (;1;) (type 1) (param i32 i32) (result i32)
    (local.get 0)
    (local.get 1)
    (i32.add))
```
Which is a little bit strange as WABT is also used as a third party module of Binaryen.

**Comment by tlively** [comment]
FWIW, we plan to switch to a new text parser that parses the standard text format soon. That new parser will be able to parse the wat file WABT produces.
