### ISSUE TITLE
How do you actually run emscripten wasm?

### ISSUE THREAD

**Issue by facekapow** [WebAssembly/binaryen#646]
I compiled a simple little `fib.cpp` with emscripten's master branch (`incoming` branch wasn't activating correctly), and when I tried to run it using V8 5.4.9, I got:
```
WasmModule::Instantiate(): Import #0 module="s" function="s" error
```
Based on the disassembled `.wast`, I'm guessing this is because it was expecting some emscripten runtime environment functions, like `abort`, `_emscripten_memcpy_big`, etc.

Could I run the code by providing the functions as globals to `Wasm.instantiateModule`? If I could, are the functions defined anywhere so I could use them, or would I just have to guess some implementations?

`fib.cpp`:
```cpp
#include <emscripten.h>
#include <stdint.h>

extern "C" {

uint64_t EMSCRIPTEN_KEEPALIVE fibonacci(uint64_t i) {
  uint64_t a[2] = {1, 1};
  while (i-- > 2) a[i & 1] = a[0] + a[1];
  return a[0];
}

}
```

`index.js`:
```js
const compileWasm = (u8) => {
  const globals = {};
  const module = Wasm.instantiateModule(u8, globals);
  return module.exports;
};

// `code` is a Uint8Array containing `fib.wasm`
const fibWasm = compileWasm(code);

console.log(fibWasm._fibonacci(3));
```

Steps to compile:
```bash
# I've installed the binaryen utils to /usr/local/bin
# I also had to add `BINARYEN='path-to-built-binaryen'` to ~/.emscripten
EMCC_WASM_BACKEND=1 emcc fib.cpp -s BINARYEN=1
# emscripten errored `AttributeError: 'int' object has no attribute 'endswith'`,
# it managed to generate a.out.asm.js, so I'm assuming that it errors when trying
# to run asm2wasm itself
asm2wasm a.out.asm.js > fib.wast
wasm-as fib.wast > fib.wasm
```

**Comment by kripken** [comment]
You definitely need `incoming` for wasm - `master` is just too old.

I'm not sure about the v8 version, you need a very recent one there as well.

**Comment by binji** [comment]
V8 5.4.9 is from earlier this month: https://github.com/v8/v8/tree/5.4.9, it should be new enough.

**Comment by facekapow** [comment]
Basically what I'm asking is, what globals do I need to provide to `Wasm.instantiateModule`? (sorry if that got lost in the additional info) Thanks for the quick response, btw.

**Comment by kripken** [comment]
You can see what is passed there [in the code](https://github.com/WebAssembly/binaryen/blob/master/src/js/wasm.js-post.js#L203), right above that link. Looks like it's an object whose elements are objects, and they are the imports for the wasm module. So something like

````
{
  env: {
    func: function() { ..}
  }
}
````

would let the wasm module import `env.func` (module is `env`, property is `func`).

**Comment by facekapow** [comment]
Well, I kind of got it to work. Basically, I copy pasted a regular `a.out.js`, and instead of `asm = (function(global, asm, ...`, I did `asm = Wasm.instantiateModule(u8, { env: Module.asmLibraryArg })`. I copied everything except the `asm` function and the `real__*` functions. The *kind of* part comes from the fact that it'll be parsed and work, but when trying to use `fibonacci`, `abort()` is called. Is there even any documentation on how to *use* the C/C++ compiled WebAssembly?

**Comment by kripken** [comment]
What kind of docs are you looking for?

Docs for `instantiateModule` etc. would be on the wasm design repo.

Otherwise, people don't normally call those low-level APIs, they just compile programs and let the runtime call `main` for them. Or, if you want to call methods directly from JS, emscripten has some [apis for that](http://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html).

**Comment by facekapow** [comment]
All that I'm trying to do is see how to include compiled C/C++ code with WebAssembly. Whether or not I use a `main`, I would have to provide the globals for `instantiateModule`, and I was just wondering where they would be defined so I could include them. Is they environment provided and I'm just not getting it because I'm using master instead of incoming?

I'm not using incoming, because with incoming, when I do `emcc -v`, I get:
```
WARNING:root:generating system asset: is_vanilla.txt...
WARNING:root:                                          ok
ERROR:root:Emscripten, llvm and clang repo versions do not match, this is dangerous (1.36.5, 1.36.0, 1.36.0)
ERROR:root:Make sure to use the same branch in each repo, and to be up-to-date on each. See http://kripken.github.io/emscripten-site/docs/building_from_source/LLVM-Backend.html
INFO:root:(Emscripten: Running sanity checks)
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.36.5
clang version 3.9.0 (https://github.com/kripken/emscripten-fastcomp-clang/ 4fddcbc67c8950a54b169030ad9b2d66288d5d5f) (https://github.com/kripken/emscripten-fastcomp/ 21f1267bad4d8c523fae483104d4348cfb279cfe) (emscripten 1.36.5 : 1.36.5)
Target: x86_64-apple-darwin15.4.0
Thread model: posix
InstalledDir: ~/opt/emsdk/clang/fastcomp/build_incoming_64/bin
ERROR:root:Emscripten, llvm and clang repo versions do not match, this is dangerous (1.36.5, 1.36.0, 1.36.0)
ERROR:root:Make sure to use the same branch in each repo, and to be up-to-date on each. See http://kripken.github.io/emscripten-site/docs/building_from_source/LLVM-Backend.html
INFO:root:(Emscripten: Running sanity checks)
```
I was also getting this before installing master. And llvm and clang and emscripten are always compiled from source, so I don't understand why there'd be a version mismatch.

**Comment by kripken** [comment]
> All that I'm trying to do is see how to include compiled C/C++ code with WebAssembly

Sorry, I don't understand what that means? Compiled C/C++ code *becomes* WebAssembly.

That emcc error might be that the emscripten repo is incoming (1.36.5) while the llvm and clang repos are master (1.36.0), or perhaps incoming but without pulling changes. You need to have all three repos on the same branch.

**Comment by kripken** [comment]
And yes, on incoming the compiler will emit code that calls `initiantiateModule` automatically. You should not need to look inside the code, it should handle all the wasm integration details for you. Just `emcc -s BINARYEN=1 [..]` should emit some JS and side files that work when you run that JS.

**Comment by facekapow** [comment]
> Sorry, I don't understand what that means? Compiled C/C++ code becomes WebAssembly.

Sorry for all the confusion, I understand that the compiled code becomes WebAssembly, but the second part of your comment solves all this. I knew there had to be something I was missing. I'll remove the whole emsdk and reinstall from `incoming` later today and hopefully close this issue.

**Comment by facekapow** [comment]
Ok, this time for some reason the `incoming` branch worked perfectly! Thanks for all the help!

**Comment by alexanderby** [comment]
This tutorial can help to understand what properties should environment have https://codelabs.developers.google.com/codelabs/web-assembly-intro/index.html?index=..%2F..%2Findex#3
