### ISSUE TITLE
[Question] How to do type evaluation in Binaryen?

### ISSUE THREAD

**Issue by hungryzzz** [WebAssembly/binaryen#6476]
Hi, I found that when I use `WasmBinaryReader` to parse a type-mismatched `wasm` file, it would not raise error messages. So I just wonder could I do the type evaluation in Binaryen? i.e., Simulate execution on an abstract stack to determine whether there is a type mismatch. Thank you!

```wasm
(; example of type-mismatched code ;)
global.get 0
i32.const 32
i64.sub
```

**Comment by kripken** [comment]
To check if the module is valid you also need to run validation,

https://github.com/WebAssembly/binaryen/blob/main/src/wasm-validator.h

**Comment by tlively** [comment]
Closing because the question is answered, but I will also note that Binaryen does not currently have a fully-spec compliant validator. It will validate some modules that the spec says should be invalid.
