### ISSUE TITLE
Calculate execution time of build file functions

### ISSUE THREAD

**Issue by parulkhanna** [WebAssembly/binaryen#655]
Hi,

I am trying to calculate the execution time of my javascript file generated with emcc/binaryen. 
I am using a simple WebAPI call which is as follows

```
var t0 = performance.now();
{
MY ALL OF THE CODE  
}
var t1 = performance.now();
console.log("Call to do Execute all the code took " + (t1 - t0) + " milliseconds.")
```
However, Whenever I See console output all the emscripten functions are called after the time is measured. Can anyone suggest any fixes. It will be really helpful(screenshot attached)

![screen shot 2016-07-28 at 12 46 42 pm](https://cloud.githubusercontent.com/assets/6426212/17221313/5c06554a-54c1-11e6-8127-90ce064e7858.png)

**Comment by kripken** [comment]
If `ALL THE CODE` is synchronous code then it must execute there in the middle, and that measurement approach is valid. The only risk is if you have something async like `setTimeout`.
