### ISSUE TITLE
Allow multiple patterns for noinline

### ISSUE THREAD

**Issue by DirtyHairy** [WebAssembly/binaryen#6646]
I have multiple function patterns that I would like to exclude from inlining. Unfortunately, the noinline pass only allows a single pattern, which does not allow any conditionals. It would be great if there were a way to specify multiple patterns, either by extending the pattern syntax or by allowing multiple instances of the noinline pass.

I can provide a PR for either of these options if desired 😏

**Comment by kripken** [comment]
Sounds reasonable to me. Maybe see if there's a simple way to allow multiple instances of the noinline pass, as that sounds best (but I'm not sure how simple it would be, offhand - we'd need to track the pass argument per instance of the pass, I guess).

**Comment by DirtyHairy** [comment]
Alright, I'll look into it.

**Comment by DirtyHairy** [comment]
I opened #6687 .
