### ISSUE TITLE
Assertion when assembling `ref.cast` with a no ref type

### ISSUE THREAD

**Issue by hgruniaux** [WebAssembly/binaryen#6655]
When using `wasm-as` on the following file:
```wat
(module
    (func (local $a anyref)
        (ref.cast i32 (local.get $a))))
```
An assertion fail in the code:
```
Assertion failed: isRef() (/src/src/wasm/wasm-type.cpp: getHeapType: 996)
```
I believe the assembler should print an error (the above wasm code is, of course, invalid) instead of crashing.

I tested the last version 117. I haven't tested the main branch, maybe the problem do not exist anymore.

**Comment by kripken** [comment]
Testing on latest `main`, I see
```
Fatal: 3:18: error: expected folded instruction
```
That location `3:18` is between the `ref.cast` and the `i32`. @tlively what does it mean by "folded instruction" that it expects there?

**Comment by tlively** [comment]
This does still look like a bug with the new parser. The error message should say something about expecting a reftype. The current behavior is that it incorrectly accepts that the `ref.cast` has no reftype immediate, then goes to parse the next instruction starting from `i32 (local.get $a...`. That does not start with the expected opening paren for a folded instruction, so it produces the current error message.
