### ISSUE TITLE
Can not use BinaryenStringref in C API

### ISSUE THREAD

**Issue by alexdovzhanyn** [WebAssembly/binaryen#6712]
Apologies if this isn't the correct place to ask (please point me to the correct place if it isn't). I am trying to use the Binaryen C api as a backend target for my programming language. 

Looking at the [kitchen-sink example](https://github.com/WebAssembly/binaryen/blob/cdf8139a441c27c16eff02ccee65c463500fc00f/test/example/c-api-kitchen-sink.c#L1205) I see support for strings and string concatenation. I am trying to create a very simple module which just adds 2 constant strings together. 

Using binaryen, I've been able to generate the following module (as displayed by `BinaryenModulePrint(module)`:

```wat
(module
 (type $0 (func (result stringref)))
 (export "main" (func $main))
 (func $main (result stringref)
  (string.concat
   (string.const "hi")
   (string.const "hi")
  )
 )
)
```

However, when I try to write the module using `BinaryenModuleWrite`, I get the following error:

```
Assertion failed: (it != stringIndexes.end()), function getStringIndex, file wasm-binary.cpp, line 748.
```

I've also tried validating the module using `BinaryenModuleValidate(module)`, which produces the following output:

```
[wasm-validator error in function main] unexpected false: string operations require reference-types [--enable-strings], on
(string.const "hi")
[wasm-validator error in function main] unexpected false: string operations require reference-types [--enable-strings], on
(string.const "hi")
[wasm-validator error in function main] unexpected false: string operations require reference-types [--enable-strings], on
(string.concat
 (string.const "hi")
 (string.const "hi")
)
[wasm-validator error in function main] unexpected false: all used types should be allowed, on
main
```

I looked for documentation to see if there is a flag to toggle `--enable-strings` but I haven't been able to find anything.

I'm assuming I'm just doing something wrong and this isn't actually a bug, but any insight would be incredibly helpful.

**Comment by kripken** [comment]
For validation, you need something like
```c
BinaryenModuleSetFeatures(m, BinaryenFeatureStrings());
```
That might fix the other error, I'm not sure (if it does, then we should have a clearer error).

**Comment by alexdovzhanyn** [comment]
Thats exactly what I needed! Thanks so much for the quick reply!!
