### ISSUE TITLE
wasm-opt doesn't drop some stack shuffling instructions before `unreachable`

### ISSUE THREAD

**Issue by osa1** [WebAssembly/binaryen#6715]
When I optimize the attached .wasm with the current main branch (9792f2c1fd311c3ffd2036288c6e7614a0486481) using this invocation:

```
wasm-opt \
      -g \
      --all-features \
      --closed-world \
      --traps-never-happen \
      --type-unfinalizing \
      -Os \
      --type-ssa \
      --gufa \
      -Os \
      --type-merging \
      -Os \
      --type-finalizing \
      test.wasm -o test.opt.wasm
```

The generated .wasm has 34 instruction sequences of `drop; unreachable`.

In those cases the `drop` instruction could be dropped.

[test.wasm.zip](https://github.com/user-attachments/files/16107322/test.wasm.zip)

**Comment by kripken** [comment]
Thanks @osa1 , that was indeed a missed optimization. I opened #6719 to add it.
