### ISSUE TITLE
TypeBuilder Error Forward Child Reference. What condition will it trigger?

### ISSUE THREAD

**Issue by Guo-yyds** [WebAssembly/binaryen#6723]
**When I write the test case, I want to test the type builder, but the above error occurs, and I don't understand it.**

![image](https://github.com/WebAssembly/binaryen/assets/75302171/a189b987-0f71-4aa1-af9e-b9e5a4a7b08a)
![image](https://github.com/WebAssembly/binaryen/assets/75302171/61f7ff6b-757a-4516-a9dd-013f9f9e1f78)

**Comment by kripken** [comment]
In general that means a type was not defined yet (not in a previous rec group, nor in the current one). But I can't tell from the screenshots why that happens in this case. If you can provide the source code of a full example that shows the issue that would help.

Another thing you can try is to make sure you are using a build of Binaryen with assertions enabled (as some internal error might be ignored, if assertions are off).

**Comment by kripken** [comment]
Hmm, I can't seem to find anything wrong here. The code seems reasonable and what it is doing is basically
```wat
(module
  (rec
    (type $struct (sub (struct (field (mut (ref null $struct)))
                               (field (mut (ref null $field))))))
    (type $field  (sub (struct (field (mut (ref null $field))))))
  )
)
```
Which is valid. But it does error as you said @Guo-yyds 

@tlively is there some way to debug the TypeBuilder API? To get more detailed an error, or perhaps have it print out what it is building?

**Comment by tlively** [comment]
There's a `dump()` method on `TypeBuilder`, but it's not currently exposed in the C API.

**Comment by Guo-yyds** [comment]
So, this is Binaryen's fault?How should I handle this?

**Comment by kripken** [comment]
Thanks @tlively !

I added a call to `dump()` in `binaryen-c.cpp`'s `TypeBuilderBuildAndDispose` method, right before the `build` command. It prints
```wat
(type $0 (; temp ;) (sub (struct (field (mut (; temp ;) (ref null $0))) (field (mut (; temp ;) (ref null $1))))))
(type $1 (; temp ;) (sub (struct )))
```
Which is as expected. When I put it in a wat file surrounded by a rec group it validates.

But that reminded me that you do need to explicitly create rec groups, and that was the problem here. This fixes the testcase (before the build command):
```c
TypeBuilderCreateRecGroup(builder, 0, 2);
```
