### ISSUE TITLE
Assertion failed in wasm-as when casting to externref

### ISSUE THREAD

**Issue by hgruniaux** [WebAssembly/binaryen#6738]
The following WAT code:
```.wat
(module
    (func (param eqref) (result externref)
        (ref.cast externref (local.get 0))))
```
crash the assembler with the following message:
```
Assertion failed: isRef() (/src/src/wasm/wasm-type.cpp: getHeapType: 930)
```
The problem is the cast to `externref`. The assembler should probably print an error message.

The crash was reproduced on the main branch (commit 22c28bd5a108f9bdacd1b60468e312903bcdf451).

**Comment by kripken** [comment]
Thanks @hgruniaux , I opened #6741 with a fix.
