### ISSUE TITLE
Scratch local always used for br_if with value?

### ISSUE THREAD

**Issue by kripken** [WebAssembly/binaryen#6747]
```wat
(module
  (func $func
    (block $out
      (drop
        (br_if $out
          (i32.const 12)
          (i32.const 13)
        )
      )
    )
  )
)
```

```wat
$ bin/wasm-opt a.wat --print
(module
 (type $0 (func))
 (func $func
  (local $scratch i32)
  (block $out
   (drop
    (block (result i32)
     (local.set $scratch
      (i32.const 12)
     )
     (br_if $out
      (i32.const 13)
     )
     (local.get $scratch)
    )
   )
  )
 )
)
```
I wouldn't expect to see a scratch local used in either the text or the binary format for a simple `br_if` with a value, but it seems even the text format adds one? @tlively is this a bug in the new parser?

**Comment by tlively** [comment]
This parse is correct because block `$out` does not return a value, so the `(i32.const 12)` is not carried by the `br_if` and should not be its child in the IR.

**Comment by kripken** [comment]
Oh, wow, thanks, I missed that. Wat format is weird... sorry for the noise.
