### ISSUE TITLE
GUFA miscompilation with shared i31 cast

### ISSUE THREAD

**Issue by tlively** [WebAssembly/binaryen#6776]
```
(module
 (table $0 3 3 (ref null (shared any)))
 (elem $0 (table $0) (i32.const 0) (ref null (shared i31)) (item (ref.i31_shared (i32.const 999))))
 (func $0 (export "get") (param $0 i32) (result (ref null (shared any)))
  (ref.cast (ref null (shared i31))
   (table.get $0
    (i32.const 0)
   )
  )
 )
)
```

Running `wasm-opt -all -tnh --gufa-cast-all test.wast -S -o -` optimizes the function body to just `(ref.null (shared none))`, which is not correct. I tried debugging this and I figured out that there is an intermediate state where the `ref.cast` type has been changed to `(ref null (shared none))`, but I haven't been able to figure out why it's doing that.

**Comment by kripken** [comment]
As a quick guess, perhaps one of the first four methods [here](https://github.com/WebAssembly/binaryen/blob/a8066e6618b93ea101e82b64690b9b62d7562609/src/ir/possible-contents.cpp#L44) (`combine, intersect, haveIntersection, isSubContents`) need updating for shared types? Might be easiest to verify if that is the case by adding some cases to the existing test.
