### ISSUE TITLE
s2wasm creating code with out-of-bounds memory accesses

### ISSUE THREAD

**Issue by wibblymat** [WebAssembly/binaryen#683]
I have [created a gist](https://gist.github.com/wibblymat/29ef5aed4c34b119c926ecd1bc673030) that has three steps of a compilation.

My build process is:
```
~/llvm/build/bin/clang -emit-llvm --target=wasm32 -S test.c
~/llvm/build/bin/llc test.ll -march=wasm32
~/binaryen/build/bin/s2wasm -o test.wast test.s
```

As you can see in the `.wast`, there are no data segments defined. The pseudo-code for lines 9 - 19 is:
```
memory[0+4] = $0 = (memory[0+4] - 16)
```
which always results in `$0` being `-16`. Lines 20 - 23 are:
```
memory[$0+12] = 0
```
but `$0+12` is always `-4`, and therefore out of bounds.

This happens with tag `version_11` as well as with `master`.

**Comment by kripken** [comment]
The wasm backend doesn't emit fully standalone code. The supported code path is to use [`emcc` to invoke that backend](https://github.com/kripken/emscripten/wiki/New-WebAssembly-Backend), then it will generate a JS file as well that does all the gluing necessary around the wasm file.

The specific glue problem here is that the stack pointer is initialized by code from outside, Without that glue, memory is indeed 0 and decreasing it gives an invalid pointer.

**Comment by wibblymat** [comment]
Thanks @kripken, got it. Is the stack pointer always at offset 4?

**Comment by kripken** [comment]
Currently yes, but now that wasm has proper globals, the nice thing would be for the wasm backend/s2wasm to use a global for the stack pointer (as asm2wasm now does on the `stack` branch).
