### ISSUE TITLE
Are there any limits on nested blocks/loops in binaryen ?

### ISSUE THREAD

**Issue by hgruniaux** [WebAssembly/binaryen#6830]
The question is in the title.

I searched in the code, and I found nothing. I am curious to know if there are any limits in the parser or the static analyzer for the depth of nested blocks or loops.

Also, do you know if such limits exist in current engines?

Thanks in advance.

**Comment by kripken** [comment]
I don't believe there is a specific limit for such nesting. Here is the V8 file with such limits:

https://github.com/v8/v8/blob/main/src/wasm/wasm-limits.h

I don't recall this being an issue in the past, either in V8 or Binaryen or elsewhere. It is common to have many thousands of nested blocks in practice for various switch constructs, for example.

**Comment by hgruniaux** [comment]
Thanks for your answer!
