### ISSUE TITLE
GC feature and anyref/nullref? (fuzzer error)

### ISSUE THREAD

**Issue by kripken** [WebAssembly/binaryen#6839]
```wat
(module
 (func $0
  (local $0 (ref null none))
 )
)
```
This validates without GC, but we round-trip it into an anyref, which does not:
```
$ bin/wasm-opt a.wat -all --disable-gc --print --roundtrip --print
(module
 (type $0 (func))
 (func $0
  (local $0 nullref)
  (nop)
 )
)
(module
 (type $0 (func))
 (func $0
  (local $0 anyref)
  (nop)
 )
)
[wasm-validator error in function 0] unexpected false: all used types should be allowed, on 
0
```
`getFeatures()` suggests we are fudging things a little:

https://github.com/WebAssembly/binaryen/blob/0c84afe87ea67239c4d7bf885b43b5c4f52322af/src/wasm/wasm-type.cpp#L1504-L1509

And I think the change from nullref to anyref happens during writing, here:

https://github.com/WebAssembly/binaryen/blob/0c84afe87ea67239c4d7bf885b43b5c4f52322af/src/wasm/wasm-binary.cpp#L1621-L1626

@tlively should we fudge things even more in the validator, or modify the binary writing here..?

**Comment by tlively** [comment]
Oh right, because the original reference types only included extern and func refs. The fix would be to make uses of `HeapType::none` require GC so that the original module would not validate without GC. I'll make a quick PR.
