### ISSUE TITLE
Mirror bugs for LLVM wasm backend

### ISSUE THREAD

**Issue by dschuff** [WebAssembly/binaryen#685]
@jgravelle-google and I have been doing more triage of bugs and issues with the emscripten+wasm-backend pipeline, and of course there are issues relating to all the different parts (emscripten, s2wasm, the backend itself). Even though emscripten and binaryen (and tool-conventions etc) are different repos, it's reasonably easy to search across them on github. But that notably excludes LLVM which is a different system, and that makes organization harder.

I had the idea of mirroring LLVM wasm backend bugs onto github somewhere. It would probably be just a link to the LLVM bugzilla (the actual discussion and canonical status would be on bugzilla, to make it visible to the LLVM community).
 The advantage would be that we would have everything on github (even if it's just a link) for easier searching, tracking, tagging, assignment, etc. The disadvantages would be that we would have to file 2 bugs for each backend bug. Furthermore we can't expect anyone other than us to do that, so when folks  (e.g. LLVM community) file bugs in the LLVM backend, someone has to be watching the LLVM bug tracker anyway (probably via email updates) and do the mirroring. I could probably handle that.

Is this something that you think you'd find useful?
@kripken @sunfishcode @flagxor @s3ththompson

**Comment by kripken** [comment]
I think this would be useful, but the overhead for doing the mirroring is a concern. I know there are automatic systems for this, like e.g. [launchpad](https://launchpad.net/), but not sure if there is something for github.

**Comment by dschuff** [comment]
Yeah, it could be done with a script. e.g. https://github.com/mozilla/fxa-bugzilla-mirror looks potentially promising.

**Comment by sunfishcode** [comment]
Same here. This sounds ok if it doesn't end up being a lot of overhead for folks involved.

Another possible approach is to just use binaryen's tracker for these kinds of bugs for now. The LLVM community doesn't require all bugs be filed in bugzilla (and indeed, large numbers of LLVM contributors work for companies that utilize private bug trackers).

**Comment by dschuff** [comment]
Good point; mabye we can just go with binaryen or some other WebAssembly GH repo for our own bugs for now. I'll additionally try to subscribe to wasm backend bugs and mirror those to GH if they get filed externally. For those bugs I guess we should try to keep most of the activity on bugzilla so it's visible to the reporter.

**Comment by dschuff** [comment]
For now we'll just use Binaryen's tracker for LLVM bugs. I'll mirror any reports that we get on the upstream bugzilla.
