### ISSUE TITLE
Misparsing of catch clauses within the `try_table` instruction

### ISSUE THREAD

**Issue by vouillon** [WebAssembly/binaryen#6854]
When parsing the `try_table` instruction, the catch clauses are wrongly parsed outside of the context of the `try_table`. So, parsing the following module fails with the error `Fatal: unexpected label 'label'`.
```wasm
(module
 (tag $e)
 (func $f
  (try_table $label
   (catch $e $label)
  )
 )
)
```
Also, numeric indices within catch clauses will refer to the wrong control-flow block.

**Comment by kripken** [comment]
cc @aheejin @tlively , not sure if this is more of a parser issue or a `try_table` issue.

**Comment by tlively** [comment]
This is WAI. The catch clauses are [validated](https://webassembly.github.io/exception-handling/core/valid/instructions.html#xref-syntax-instructions-syntax-instr-control-mathsf-try-table-xref-syntax-instructions-syntax-blocktype-mathit-blocktype-xref-syntax-instructions-syntax-catch-mathit-catch-ast-xref-syntax-instructions-syntax-instr-mathit-instr-ast-xref-syntax-instructions-syntax-instr-control-mathsf-end) in the original context, not the context extended with the `try_table` label.

**Comment by vouillon** [comment]
Oh, indeed! I did not expect that. I should have checked the spec.

**Comment by vouillon** [comment]
This is discussed here, by the way: https://github.com/WebAssembly/exception-handling/issues/286
