### ISSUE TITLE
Generating an if control flow with a result type?

### ISSUE THREAD

**Issue by alexdovzhanyn** [WebAssembly/binaryen#6868]
Hi -- I'm trying to generate an if statement that will place its return value onto the stack. According to the [Mozilla WASM documentation](https://developer.mozilla.org/en-US/docs/WebAssembly/Reference/Control_flow/if...else), to do this, we need to add a `result` type to the if statement.

Looking through the binaryen-c.h file I am unable to ascertain a way to do this. As a matter of fact, I'm getting some unexpected behavior when using the `BinaryenModuleAutoDrop` function:

```cpp
 BinaryenIf(
  module,
  BinaryenUnary( // Check if the arity is equal to 0
    module,
    BinaryenEqZInt32(),
    BinaryenBinary( // Add 4 to the closure pointer address to get the arity address
      module,
      BinaryenAddInt32(),
      BinaryenLocalGet( //  The local thats storing the pointer to the function we want to call
        module,
        scope.lookup(refIdentifier).value()->getMappedBinaryenIndex(),
        BinaryenTypeInt32()
      ),
      BinaryenConst( 
        module,
        BinaryenLiteralInt32(4)
      )
    )
  ),
  BinaryenCallIndirect( // If the above check is true, execute_indirect
    module, 
    FN_TABLE_NAME.c_str(), 
    BinaryenLoad(
      module,
      4,
      false,
      0,
      0,
      BinaryenTypeInt32(),
      BinaryenLocalGet(
        module,
        scope.lookup(refIdentifier).value()->getMappedBinaryenIndex(),
        BinaryenTypeInt32()
      ),
      MEMORY_NAME.c_str()
    ),
    loadArgsExpressions,
    BinaryenTypeArity(functionParamType),
    functionParamType,
    functionReturnType
  ),   
  NULL
)
```

seems to generate the following:

```wat
(if
 (i32.eqz
  (i32.add
   (local.get $1)
   (i32.const 4)
  )
 )
 (then
  (drop
   (call_indirect (type $0)
    (i64.load offset=8
     (local.get $1)
    )
    (i64.load offset=12
     (local.get $1)
    )
    (i32.load
     (local.get $1)
    )
   )
  )
 )
)
```

All of this is correct, except the (drop) thats being wrapped around the `then` clause in the if statement.

Am I missing something here?

**Comment by kripken** [comment]
`BinaryenIf()` will automatically add a result type, if the two arms have concrete types. That is, there is nothing special that you need to do here, aside from creating the if with two arms with result types.

That isn't a Binaryen requirement, but how the wasm spec works: an if with a result must flow that result out of both arms.

It looks like your if here, however, has just one arm, so it doesn't need a result type.

**Comment by alexdovzhanyn** [comment]
@kripken Thanks for the quick reply. That makes sense -- I figured it was probably something I missed. I am going to make a PR to add that to the documentation for the binaryen-c.h file in case anyone else runs into the same issue in the future.
