### ISSUE TITLE
Storing / loading stringref in memory

### ISSUE THREAD

**Issue by alexdovzhanyn** [WebAssembly/binaryen#6883]
I am trying to store a stringref in memory for usage later in a `call_indirect`, but am having trouble figuring out the right way to go about loading it.

I am storing the stringref like so:

```wasm
    (i32.store
     (i32.const 0)
     (string.const "hello")
    )
```
which doesn't work because `string.const` is not an i32, though it should be an i32 address. I've also tried calling
`BinaryenRefCast(stringConst, BinaryenTypeInt32())`, which generates this invalid WAT:

```wasm
    (i32.store
     (i32.const 0)
     (block ;; (replaces unreachable RefCast we can't emit)
      (drop
       (string.const "hello")
      )
      (unreachable)
     )
```

My issue is I can't seem to find the correct Binaryen call to load that string back in from memory. I have considered using `BinaryenStringNew` but that doesn't seem like it'll do what I want. It seems like that will create a new stringref, rather than use an existing one.

Assuming I have the i32 stringref pointer from an existing stringref, and I do an `i32.load` to get it from memory like so:

```wasm
    (i32.load
     (i32.const 0) ;; Assuming we stored at memory address 0
    )
```

How could I then go about converting this basic i32 into a stringref pointer again?

**Comment by kripken** [comment]
Strings are references, so they cannot be stored to linear memory which can only store numeric data. This is for security reasons: the reference is opaque, like say the address of an object in JS/Java/C#/Go (and anything stored in linear memory can be read out as a number, which would break opaqueness).

What people usually do is store references in a table, and refer to them by index. That can be a literal wasm Table, which is how function references are handled in MVP wasm programs: the Table maps i32 indexes to function references. But it could also be a GC Array.

**Comment by alexdovzhanyn** [comment]
@kripken Ah, I was afraid that was the case. That complicates things a bit for me, but it is workable. Thank you for the suggestion!
