### ISSUE TITLE
Create tag version 119

### ISSUE THREAD

**Issue by gracicot** [WebAssembly/binaryen#6907]
The current emscripten version (3.1.64) Can use the cmd arguments `--no-stack-ir` of binaryen. This is problematic since the latest tag (118) don't expose this cmd argument. This use has been introduced by commit https://github.com/emscripten-core/emscripten/commit/3905550b49c2e0a7ddff53e9a798713f0f50c637

The result is that the latest emscripten is not compatible with the latest binaryen, since that cmd argument has been added after the tag 118. This particularly affects linux distributions and package managers packaging emscripten.

My current workaround is to compile with `ASSERTIONS=1` on release too.

**Comment by kripken** [comment]
The tag is building, but looks like not all builds are done yet. You might be able to test it already though, anything but the linux-aarch64 which is still in progress.

**Comment by gracicot** [comment]
Thank you so much! I'll package it in nixpkgs as soon as I can

**Comment by kripken** [comment]
(Builds finished successfully; 119 is now marked as the latest release.)
