### ISSUE TITLE
Bug in the handling of an "if" block with parameters

### ISSUE THREAD

**Issue by verbessern** [WebAssembly/binaryen#6929]
The following code compiles without errors by wasm-as, but it is not valid:
```
(module 
  (func (export "main") (result i32)
    i32.const 1
    i32.const 1
    if (param i32 i32 i32 i32 i32 i32)
    end
  )
)
```
And the following code is valid (I think), but it does not compile:
```
(module 
  (func (export "main") (result i32)
    i32.const 1
    i32.const 1
    if (param i32) (result i32)
    end
  )
)
```

**Comment by kripken** [comment]
Block/If parameters are not supported in the parser yet, but I thought we had an error for that? Looks like we don't. cc @tlively
