### ISSUE TITLE
Assert  (!contents.isMany()), function updateContent on kotlin/wasm generated wasm file

### ISSUE THREAD

**Issue by igoriakovlev** [WebAssembly/binaryen#6955]
We are getting CPP Assert in binaryen:
`Assertion failed: (!contents.isMany()), function updateContents, file possible-contents.cpp, line 2405.`

Binaryen: 119
PC: Appel M1
OS: Sonoma 14.5
File: [kotlin.zip](https://github.com/user-attachments/files/17041555/kotlin.zip)

Command: wasm-opt --enable-gc --enable-reference-types --enable-exception-handling --enable-bulk-memory --enable-nontrapping-float-to-int --inline-functions-with-loops --traps-never-happen --fast-math --gufa -O3 -O3 --gufa -O3 -O3 -Oz kotlin-wasm-benchmarks-wasm-wasmBenchmark.wasm -o x.wasm

The original .wasm is loaded and runned with d8 and jsShell just fine.

**Comment by kripken** [comment]
Thanks for the report, fix is in https://github.com/WebAssembly/binaryen/pull/6956
