### ISSUE TITLE
Wasm_Rust_link_up

### ISSUE THREAD

**Issue by imgaurav249** [WebAssembly/binaryen#6962]
I have genrerated wasm module from rust and try to execute by using the WAMR. although WAMR runtime is not created yet but still i have tried to run it by using executale file of wamr so  for this purpose i m using the wasm_lookup_funtion which is responsible for searching a perticular fun which will run in wasm. but wasm_lookup_funtion  is unable to find that function in wasm file and each time  i am gettiing error like "Error: Function 'wasm_main' not found in WASM module.

**Comment by kripken** [comment]
@imgaurav249 did you mean to file this issue on the wamr or rust repos perhaps?

**Comment by imgaurav249** [comment]
yes on wamr

**Comment by kripken** [comment]
Ok, I am unable to transfer this, so you'll need to open a ticket there:

https://github.com/bytecodealliance/wasm-micro-runtime/issues

I'll close this one.
