### ISSUE TITLE
Missing documented feature --multi-memory-lowering

### ISSUE THREAD

**Issue by KaruroChori** [WebAssembly/binaryen#6978]
From the official readme:

>  (As a workaround for such older VMs you can run wasm-opt --multi-memory-lowering to lower multiple memories into a single one.)

However this option is reported as unknown by `wasm-opt`. Is there any alternative or has it just be renamed?

**Comment by kripken** [comment]
It is still there:

https://github.com/WebAssembly/binaryen/blob/fcd8dfe7ddd1a4a3ce1be40c674fdd60bbec73d1/src/passes/pass.cpp#L316-L318

https://github.com/WebAssembly/binaryen/blob/fcd8dfe7ddd1a4a3ce1be40c674fdd60bbec73d1/test/lit/help/wasm-opt.test#L303-L305

Perhaps you are using an older version? It should be in 111 and later.

**Comment by KaruroChori** [comment]
That is strange, I just compiled all tools from the `main` branch yesterday, but the version number is 108, not 111. Am I supposed to use a different branch?

**Comment by kripken** [comment]
Perhaps you have an older wasm-opt in your path, or something like that? Make sure you are running the right binary.

**Comment by KaruroChori** [comment]
Possibly, I am going to sort this out.
In any case the option is there on the released binaries, so I will be closing this issue.
