### ISSUE TITLE
WebAssembly native build slower than asm.js

### ISSUE THREAD

**Issue by parulkhanna** [WebAssembly/binaryen#701]
Hi I just compiled few code samples in native(exe) format, asm.js, native-wasm and interpret binary, However, the time to execute native wasm is slower than asm.js. 
The methodology I used to compile the code is as follows.

1) I used simple emcc command 
emcc -O2  input.cpp input.cpp input.cpp -s BINARYEN=1 -s "BINARYEN_METHOD='native-wasm'" -o native.html

2) I execute the file with my html in the browser (firefox nightly).

There rate of compression of file-size is 3.x which is quite amazing. However, I am not getting expected output in terms of execution time.  I followed to methods to calculate time. 
     

- I used java method to calculate time by just doing 

> var t0 = performance.now();
> XXXXX my code XXXXXXXXX
> var t1 = performance.now();
> console.log("Call to doSomething took " + (t1 - t0) + " milliseconds.")

-  I hardcode my C code with simple formula to save system time

My code performs aes encryption/decryption on the plaintext input.
However the speed is 2.x times slower following are the results.  The input plaintext size is 60MB

**asm.js**	             
Encryption	3.95 MB/s	
Decryption	4.57 MB/s	

**native-wasm**	             
Encryption	0.95 MB/s	
Decryption	0.90 MB/s	

**interpret-binary**	             
Encryption	12.25 KB/s	
Decryption	11.46 KB/s	

I also compiled Tiny-AES 128 from Github and it also executes slower in wasm format.
(https://github.com/kokke/tiny-AES128-C)

**Tiny AES-128-C**(fixed input)

asm.js                 6.0ms  
wasm-native      77.8ms

The speed is relatively very slow. Can anyone correct me, if I am doing something wrong in terms of commands or any help will be appreciated to evaluate the wasm ecosystem.

Thanks,
Parul

**Comment by kripken** [comment]
Your process looks correct. The next thing to check is to run the browser profiler on the asm.js and wasm cases, and look if there is something obviously different. (Build with `--profiling` for this.)

In general, my guess is that you are hitting something not yet optimized in wasm. Due to how wasm works, it has a slightly different libc, for example. That should show up in the profiler if so.
