### ISSUE TITLE
0xc update strategy

### ISSUE THREAD

**Issue by kripken** [WebAssembly/binaryen#702]
Over the last two days I've been working to get us to pass the 0xc tests, from the current state which supported the stack branch. This is on `spec-update`. Going in alphabetic order, I got up to imports.wast. However, this is hitting some problems, as the wast format and wasm itself changed much more than I realized. The main issues for binaryen are:

 * The s-expression language has changed in the obvious way that it now has stacky stuff, but we've agreed to ignore that. That still leaves a lot of cosmetic evolution in the language. In particular, there are now multiple ways to do many things, such as imports (do a func with an import clause inside it, or an import with a func inside that), and plenty of new syntactic sugar (e.g. `(elem` can mean quite different things in different cases). The binaryen s-expression language parser isn't really a good fit for that - it's not a grammar-based parser, it literally just goes through the s-expression tree manually. Which was great until now since the language was super-simple, but handling all the new syntactic sugar is a mess. You can see attempts to refactor out shared code in my work on the branch, but it's all quite tricky. It would probably be best to scrap it and write a new parser for what is really a new language at this point - and we might as well get it to accept the stacky stuff too (by adding locals where our AST requires it).
 * `wasm.h`, where we define our core structures, hard-codes numbering in ways that I didn't expect to change - which did change, with implemented functions and function imports sharing a single space, for example. We currently have a separate counter for each of globals, imports, functions, exports, which is just wrong now. In addition, tables and memories are in an in-between state in wasm now, it seems, with only one supported but they can be referred to by name as if there are multiple; we currently just hardcode one of each in a wasm module, so that's an awkward fit as well. Overall, we should probably redesign and rewrite a significant part of `wasm.h`, which would mean a project-wide refactoring.

For both of these we might be able to find some kind of hacks to keep us going for now, but maybe it's better to just pause and do all this refactoring properly, even if it takes a while. Thoughts?

**Comment by rossberg-chromium** [comment]
Don't know if that helps, but I feel your pain. 0xc import/exports were a big change in the interpreter as well, and took longer than the entire stack machine rewrite. Quite a few basic assumptions were changing and required restructuring various types and interfaces.

**Comment by kripken** [comment]
Yeah, I actually did all the import/export stuff I could earlier, before stack merged to 0xc, to try to save time now. But it was still quite a lot left, turns out...

Anyhow, I did part of the 2nd item from before (`wasm.h` refactoring), and it finally gets us to pass `imports.wast`. Now things pass up to `labels.wast`. I'm not sure what's wrong there yet, so still hard to estimate how much work is left here. But hopefully we can leave of further major refactoring for later.

**Comment by kripken** [comment]
Spec tests now seem to all pass, except for some I disabled like `stack.wast` and `typecheck.wast`.

**Comment by dschuff** [comment]
I pushed my WIP binary format section branch to
https://github.com/WebAssembly/binaryen/tree/binary-sections

**Comment by kripken** [comment]
Ok, PR with 0xc spec test support, and PR with that 0xc binary support have both landed.

@dschuff, are you planning to continue work on finishing binary support?

**Comment by dschuff** [comment]
Yeah, I think i can finish that up.

**Comment by kripken** [comment]
This basically done, closing.

**Comment by dschuff** [comment]
The only thing left is use of the new JS API for `native-wasm`. I don't think the JS engines support importing tables yet, and I think we still need to do things like instantiate `WebAssembly.Memory` instead of just passing ArrayBuffers around.

**Comment by kripken** [comment]
Yeah, I didn't read the current JS API yet, but you're probably right. Easiest to debug this with functional VMs, I'll look into that when it's feasible (current attempts hit issues in VMs, which I filed and am waiting on).
