### ISSUE TITLE
s2wasm emits invalid drops or types

### ISSUE THREAD

**Issue by kripken** [WebAssembly/binaryen#708]
e.g. in `test/dot_s/alias.wast`,

````
  (type $FUNCSIG$v (func))
  (func $__exit (type $FUNCSIG$v)
    (return
      (i32.add [..])
    )
  )
  (func $__needs_exit (result i32)
    (drop
      (call $__exit)
    )
````

So `__exit` is declared as not returning, but does have a return for some reason, and is dropped in `__needs_exit`. I'm not sure if the drop is wrong or the type is wrong or both (not sure how to read the `.s` file to tell).

cc @dschuff @sunfishcode

**Comment by dschuff** [comment]
from `alias.s` it looks like `__exit` is void (i.e. no `.result`) but it also has `return $pop4`.  Also the drop for the call to `__exit` isn't in the .s, so I'm not sure exactly where it came from. It's also a known (to me) issue that s2wasm emits a bunch of redundant drops (the code I added in the last update to put them in for 0xc is really dumb) so I had already planned to look into the drop code once Binaryen's 0xc stabilized, so I'll look at this too.

**Comment by kripken** [comment]
I did some poking around,

 * Manually adding `.result i32` to `__exit` helps, it then prints out a proper wast when drop validation is ignored. This suggests the wasm backend is emitting it wrong?
 * However, it *still* doesn't validate properly in memory with drop validation, as the type of the call node is `none` (and it is dropped, which is wrong). One odd thing there is that the call isn't dropped in the `.s` file, which maybe it should? Anyhow, somehow s2wasm needs to know the type of the function called and set the type of the call node properly. Perhaps this can be done in a post-pass (asm2wasm does it that way), but explicit drop in the `.s` file (with the type) would be another way.
