### ISSUE TITLE
Reaching "unreachable" `unexpected expression type` when building Godot with `wasm-opt --asyncify`

### ISSUE THREAD

**Issue by adamscott** [WebAssembly/binaryen#7141]
Hi there! I'm the Godot Web Team lead, and I'm trying to understand why we cannot build our software using `-sASYNCIFY` with emscripten.

The build fails with this error:
```plain
unexpected expression type
UNREACHABLE executed at /Users/adamscott/dev/builds/binaryen/src/passes/Asyncify.cpp:1142!
em++: error: '/Users/adamscott/dev/builds/binaryen/bin/wasm-opt --strip-target-features --post-emscripten -Os --low-memory-unused --asyncify --pass-arg=asyncify-propagate-addlist --pass-arg=asyncify-imports@env.invoke_*,env.__asyncjs__*,*.fd_sync,*.emscripten_promise_await,*.emscripten_idb_load,*.emscripten_idb_store,*.emscripten_idb_delete,*.emscripten_idb_exists,*.emscripten_idb_clear,*.emscripten_idb_load_blob,*.emscripten_idb_store_blob,*.emscripten_sleep,*.emscripten_wget_data,*.emscripten_scan_registers,*.emscripten_lazy_load_code,*._load_secondary_module,*.emscripten_fiber_swap,*.SDL_Delay --zero-filled-memory --pass-arg=directize-initial-contents-immutable --no-stack-ir bin/godot.web.template_debug.wasm32.nothreads.wasm -o bin/godot.web.template_debug.wasm32.nothreads.wasm -g --mvp-features --enable-bulk-memory --enable-exception-handling --enable-multivalue --enable-mutable-globals --enable-reference-types --enable-sign-ext' failed (received SIGABRT (-6))
```

The error matches with this code:
https://github.com/WebAssembly/binaryen/blob/729ea41d145d369b203dca6f70b251ea365cb3d0/src/passes/Asyncify.cpp#L1138-L1142

> so there should be nothing that can reach here

Definitely, we're able to reach this part while compiling the engine.

We do not get any issues compiling normally without `--asyncify`.

### Steps to reproduce

1. Clone the [godotengine/godot](https://github.com/godotengine/godot) repo.
2. Apply this patch to force Asyncify:

```diff
diff --git a/platform/web/detect.py b/platform/web/detect.py
index 25a5bbe5a5..f4090e3f2f 100644
--- a/platform/web/detect.py
+++ b/platform/web/detect.py
@@ -287,3 +287,6 @@ def configure(env: "SConsEnvironment"):
     # This workaround creates a closure that prevents the garbage collector from freeing the WebGL context.
     # We also only use WebGL2, and changing context version is not widely supported anyway.
     env.Append(LINKFLAGS=["-sGL_WORKAROUND_SAFARI_GETCONTEXT_BUG=0"])
+
+    # Asyncify
+    env.Append(LINKFLAGS=["-sASYNCIFY"])
```

3. [Follow the steps of the manual](https://docs.godotengine.org/en/stable/contributing/development/compiling/compiling_for_web.html) to setup the environment to build for the Web. (should be really simple)
4. Compile using this (core build) command:

```bash
scons target=template_debug platform=web modules_enabled_by_default=no
```

5. You should be getting the unreachable error.

**Comment by tlively** [comment]
Do you build with Wasm exceptions enabled? Asyncify doesn't support exception handling, so that would be my first guess for what's going wrong.

**Comment by adamscott** [comment]
> Do you build with Wasm exceptions enabled?

It doesn't seem so. emscripten docs say that it's disabled by default, and the build command that fails don't seems to indicate that exceptions are enabled. I even tried disabling `-sASSERTIONS` and it doesn't seem to influence the build.

```bash
em++ -o bin/godot.web.template_release.wasm32.nothreads.js -sASSERTIONS=1 -sINITIAL_MEMORY=32MB -sMAX_WEBGL_VERSION=2 -sOFFSCREEN_FRAMEBUFFER=1 -sGL_ENABLE_GET_PROC_ADDRESS=0 -sSTACK_SIZE=5120KB -sWASM_BIGINT -sENVIRONMENT=web,worker -sMODULARIZE=1 -sEXPORT_NAME='Godot' -sSUPPORT_LONGJMP='wasm' -sALLOW_MEMORY_GROWTH=1 -sINVOKE_RUN=0 -sEXPORTED_RUNTIME_METHODS=['callMain','cwrap'] -sEXIT_RUNTIME=1 -sGL_WORKAROUND_SAFARI_GETCONTEXT_BUG=0 -sASYNCIFY -s -Os --js-library /Users/adamscott/dev/builds/godot/platform/web/js/libs/library_godot_audio.js --js-library /Users/adamscott/dev/builds/godot/platform/web/js/libs/library_godot_display.js --js-library /Users/adamscott/dev/builds/godot/platform/web/js/libs/library_godot_fetch.js --js-library /Users/adamscott/dev/builds/godot/platform/web/js/libs/library_godot_os.js --js-library /Users/adamscott/dev/builds/godot/platform/web/js/libs/library_godot_runtime.js --js-library /Users/adamscott/dev/builds/godot/platform/web/js/libs/library_godot_input.js --js-library /Users/adamscott/dev/builds/godot/platform/web/js/libs/library_godot_webgl2.js --js-library /Users/adamscott/dev/builds/godot/platform/web/js/libs/library_godot_javascript_singleton.js platform/web/audio_driver_web.web.template_release.wasm32.nothreads.o platform/web/display_server_web.web.template_release.wasm32.nothreads.o platform/web/http_client_web.web.template_release.wasm32.nothreads.o platform/web/javascript_bridge_singleton.web.template_release.wasm32.nothreads.o platform/web/web_main.web.template_release.wasm32.nothreads.o platform/web/os_web.web.template_release.wasm32.nothreads.o platform/web/web_runtime.web.template_release.wasm32.nothreads.o main/libmain.web.template_release.wasm32.nothreads.a modules/libmodules.web.template_release.wasm32.nothreads.a platform/libplatform.web.template_release.wasm32.nothreads.a drivers/libdrivers.web.template_release.wasm32.nothreads.a scene/libscene.web.template_release.wasm32.nothreads.a servers/libservers.web.template_release.wasm32.nothreads.a core/libcore.web.template_release.wasm32.nothreads.a -lidbfs.js
```

**Comment by mtb0x1** [comment]
The steps to reproduce yields the full `wasm-opt` command causing the issue: 

 `$ /home/xyz/apps/emsdk/upstream/bin/wasm-opt  [...] --enable-exception-handling [...] `

Running the command after removing `--enable-exception-handling` results into a bunch of errors like below :

```
[wasm-validator error in function 4173] unexpected false: try requires exception-handling [--enable-exception-handling], on 
(try $label$8
 ```

So the wasm **was** built with exceptions enabled. 

<details>
  <summary>confirmation of Asyncify fails because of exceptions</summary>

```
 
  $ cp /home/xyz/apps/binaryen/build-debug/bin/wasm-opt /home/xyz/apps/emsdk/upstream/bin/wasm-opt.debug
  
  (gdb) LD_LIBRARY_PATH=/home/xyz/apps/binaryen/build-debug/lib:$LD_LIBRARY_PATH gdb /home/xyz/apps/emsdk/upstream/bin/wasm-opt.debug
  
  (gdb) b /home/xyz/apps/binaryen/src/passes/Asyncify.cpp:1142
  
  (gdb) r --strip-target-features --post-emscripten -Os [...rest of flags]
   ...break
  (gdb) print *curr	
   $9 = {_id = wasm::Expression::TryId, type = {id = 0, static _last_basic_type = wasm::Type::v128}}

 ```
</details>



The docs indeed [mention](https://emscripten.org/docs/optimizing/Optimizing-Code.html#other-optimization-issues) that exceptions are disabled for -O1 and above, but it seems there are [2 options](https://emscripten.org/docs/porting/exceptions.html#emscripten-javascript-based-exception-support) (one for JS and the other for WASM and they need to be [synched](https://github.com/emscripten-core/emscripten/blob/c08204e56de44a66763ed58c161622850b1da91a/emcc.py#L879) ?).

I tried to rebuild after appending these options to `platform/web/detect.py`, results in same issue.
``` # Exceptions
    env.Append(LINKFLAGS=["-sDISABLE_EXCEPTION_CATCHING=1"])
    env.Append(CCFLAGS=["-sDISABLE_EXCEPTION_CATCHING=1"])
    env.Append(LINKFLAGS=["-fno-exceptions"])
    env.Append(CCFLAGS=["-fno-exceptions"])
    env.Append(CXXFLAGS=["-sDISABLE_EXCEPTION_CATCHING=1"])
    env.Append(CXXFLAGS=["-fno-exceptions"])
```

my guess is either your own build scripts down stream override the flags or the flags above are not the ones needed ?

**Comment by adamscott** [comment]
I'm gonna investigate then. Happy to know that it isn't related to a compiler issue. Thank you so much @mtb0x1 !

**Comment by adamscott** [comment]
Found the culprit. It was settings `-sSUPPORT_LONGJMP='wasm'`, which forced exceptions handling. Reverting it to `-sSUPPORT_LONGJMP='emscripten'` made it "asyncifiable".

**Comment by tlively** [comment]
@aheejin, is there a way to use new EH in `-sSUPPORT_LONGJMP`? Also, does Asyncify support new EH yet?

**Comment by aheejin** [comment]
> @aheejin, is there a way to use new EH in `-sSUPPORT_LONGJMP`?

Mixing Wasm EH with Emscripten SjLj is possible but not recommended. We used to use it as an interim measure, but there is a restriction that you can't use setjmp call with exceptions within the same function. Even though you don't use C++'s `try`-`catch` in that function, stack-allocated objects can generate EH instructions because of destructor calls.

> Also, does Asyncify support new EH yet?

No not yet. It hasn't supported the old EH either.
