### ISSUE TITLE
WebAssembly buffer error 

### ISSUE THREAD

**Issue by parulkhanna** [WebAssembly/binaryen#716]
Hi,

I am trying to compile small programs in in web-assembly format. When, I run the html file I get following error

```
Trying binaryen method: native-wasm  arcnative.html:1249:13
14:20:33.763 **the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here**  arcnative.html:1249:13
	Module.printErr file:///Users/Documents/Games/crypto-algorithms/arcfour/arcnative.html:1249:13
	mergeMemory file:///Users/Documents/Games/crypto-algorithms/arcfour/arcnative.js:87:7
	doNativeWasm file:///Users/Documents/Games/crypto-algorithms/arcfour/arcnative.js:197:5
	integrateWasmJS/Module.asm file:///Users/Documents/Games/crypto-algorithms/arcfour/arcnative.js:295:23
	<anonymous> file:///Users/Documents/Games/crypto-algorithms/arcfour/arcnative.js:2069:10
14:20:33.768 **RangeError: invalid array length[Learn More]**
```

I have tried ALLOW_MEMORY_GROWTH flag also, but the error is same 

`emcc 1.c 2.c -s ALLOW_MEMORY_GROWTH=1 -s BINARYEN=1 -s "BINARYEN_METHOD='native-wasm'" -o out.html`

`emcc 1.c 2.c -s BINARYEN=1 -s "BINARYEN_METHOD='native-wasm'" -o out.html`.

Please help me resolve this error. 

TIA

**Comment by kripken** [comment]
Which version of emscripten is that, and which version of binaryen? Development is going on on emscripten incoming and binaryen master, so if you aren't already there I would try to reproduce the problem there.

**Comment by parulkhanna** [comment]
emcc 1.36.5 (commit e2276a93cde6af63dcf425626c29ee40d2a8bb88)
binaryen version, I don't know how to retrieve that.

I am using Mac OS X. and trying to compile following programs. in native-wasm format. 

[](https://github.com/B-Con/crypto-algorithms)

They work perfectly fine in asm.js format and also Interpret-binary format. The error is only displayed in case of native-wasm build in all cases.

Thanks,

**Comment by kripken** [comment]
Ok, then this just isn't stable enough yet, I'm afraid. wasm is changing a lot and binaryen is changing with it. To try to build stuff that works, you should use emscripten incoming, now at 1.36.11. Note though that even with that, native wasm support doesn't work yet (browsers just updated the wasm binary version, and emscripten is not quite up to date yet, but should be soon).

In a few months things should be a lot more stable though.

**Comment by parulkhanna** [comment]
Ok. Thank you for the quick response. I should probably wait then for a stable version.
