### ISSUE TITLE
s2wasm outputs incorrect reinterpret operator

### ISSUE THREAD

**Issue by binji** [WebAssembly/binaryen#73]
See 20020227-1.c.wast:
```
...
        (block $BB2_4
          (br_if
            (f32.ne
              (f32.reinterpreti32
                (i32.or
                  (i32.shl
...
```

Should be ``f32.reinterpret/i32``

**Comment by kripken** [comment]
Fixed, thanks.

Interesting, I guess the spec tests don't have this, otherwise it should have been caught...

**Comment by jfbastien** [comment]
Is that a spec bug then?

**Comment by kripken** [comment]
Hmm no, I do see this in `conversions.wast`.

I think the issue is that `check.py` just runs the spec tests and looks for failed asserts, it doesn't verify that the printed wast is correct.

Anyhow, we now have testing for this through some of the .s tests.
