### ISSUE TITLE
Asm2wasm generates invalid if condition

### ISSUE THREAD

**Issue by dschuff** [WebAssembly/binaryen#741]
asm2wasm has a test in `wasm-only.asm.js` (new since the i64 work I assume)
```
  function ifValue64($4, $6) {
   $4 = i64($4);
   $6 = i64($6);
   var $$0 = i64(), $9 = i64(), $10 = i64();
   if ($6) {
     $9 = i64(call2($4));
     $$0 = $9;
   } else {
     $10 = i64(call2($4));
     $$0 = $10;
   }
   return i64($$0);
  }
```
Whose output is this
```
  (func $ifValue64 (param $0 i64) (param $1 i64) (result i64)
    (if i64
      (get_local $1)
      (call $call2
        (get_local $0)
      )
      (call $call2
        (get_local $0)
      )
    )
  )
```
But that's invalid because the type of the condition (the `get_local $1`) is i64 and not i32. I guess asm2wasm should truncate the condition. (Also, apparently Binaryen's type checker didn't catch it?). I found it during roundrip testing with wabt.

**Comment by kripken** [comment]
Thanks, fixed by #742.
