### ISSUE TITLE
std::chrono::high_resolution_clock is not steady

### ISSUE THREAD

**Issue by rongjiecomputer** [WebAssembly/binaryen#766]
According to https://solarianprogrammer.com/2012/10/14/cpp-11-timing-code-performance/ , we should use monotonic clock to measure code execution time even though it might be less sensitive than `high_resolution_clock` so that the result is more consistent and reproducible.

Test to see if the clocks are monotonic

```cpp
#include <stdio.h>
#include <chrono>

int main() {
	printf("system clock: %d\n", std::chrono::system_clock::is_steady);
	printf("steady clock: %d\n", std::chrono::steady_clock::is_steady);
	printf("high resolution clock: %d\n", std::chrono::high_resolution_clock::is_steady);
	return 0;
}
```

Only MSVC 2015 guarantees that `high_resolution_clock` is monotonic (older versions are not), clang's might be monotonic depending on `_LIBCPP_HAS_NO_MONOTONIC_CLOCK`, gcc's is always not monotonic.

- https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/include/std/chrono#L869
- https://github.com/llvm-mirror/libcxx/blob/master/include/chrono#L1073

Consider to switch to `std::chrono::steady_clock`?

**Comment by kripken** [comment]
Yeah, good idea, we should use the monotonic one.
