### ISSUE TITLE
s2wasm doesn't generate correct result type for call_indirect

### ISSUE THREAD

**Issue by binji** [WebAssembly/binaryen#77]
See 20030714-1.c.wast from torture-tests:
```
  (type $FUNCSIG_ii (func (param i32)))
  (table $RenderBox_isTableCell)
  (func $RenderBox_setStyle (param $$0 i32) (param $$1 i32)
  ...
              (br_if
                (call_indirect $FUNCSIG_ii
                  (i32.load offset=28 align=4
                    (get_local $$0)
                  )
                  (get_local $$0)
                )
                $BB0_6
              )
  ...
  (func $RenderBox_isTableCell (param $$0 i32) (result i32)
  ...
```
br_if requires its first argument to be of type i32, but `$FUNCSIG_ii` has a result type of void. Note that it must be calling `$RenderBox_isTableCell` which has a result type of i32 as well.

**Comment by kripken** [comment]
One more thanks, this is fixed as well. Was some old code that just handled params there, I made it use the new more general logic.
