### ISSUE TITLE
When importing a memory/table, do not define a memory/table section

### ISSUE THREAD

**Issue by bnjbvr** [WebAssembly/binaryen#772]
As stated in https://github.com/WebAssembly/design/blob/master/Modules.md#linear-memory-section:

    In the MVP, every memory is a default memory and thus there may be at most
    one linear memory import or linear memory section.

So to my understanding, it is incorrect to write a memory section when a memory is imported, and ditto for tables.

edit: the table section has the same kind of wording:

    In the MVP, every table is a default table and thus there may be at most one table import or table section.

**Comment by bnjbvr** [comment]
Ha, I see https://github.com/WebAssembly/binaryen/commit/56c6ca407f3232ede398b78e7f284f6ed80c9f00 fixed the issue for tables two days ago; the same thing has to be done for memory.

**Comment by dschuff** [comment]
Was just about to say, I did that for tables and thought "hey I should make the memory code the same even if the JS engines apparently don't care".

**Comment by bnjbvr** [comment]
For what it's worth, I am working on a PR right now, and it's almost ready.

**Comment by bnjbvr** [comment]
@dschuff, for what it's worth, Spidermonkey rejects wasm programs which repeat the memory/table section after a memory/table has been imported.

**Comment by dschuff** [comment]
Yeah it makes sense; V8 and the other tools should probably do that too. I haven't tried with WABT, maybe @binji knows.

**Comment by binji** [comment]
Yes, wabt should reject multiple memories or tables, whether imported or defined.
