### ISSUE TITLE
Cleaning up the s2wasm output.

### ISSUE THREAD

**Issue by JSStats** [WebAssembly/binaryen#82]
Looking at the output of `s2wasm strncmp-1.c.s` shows wast code such as the following
```
(block $BB1_5
      (br_if (i32.eq (get_local $$0) (i32.const 0)) $BB1_5)
          (loop $BB1_4 ...))
```
which appears to be
```
(if (i32.eq (get_local $$0) (i32.const 0))
  (loop ...))
```

Are there any plans to clean up the output? Would this be a job on the llvm side? It looks more than just a pattern matching exercise, and might need some understanding of the CFG? Perhaps the block structure will help here and lead to some simpler strategies.

**Comment by kripken** [comment]
Yes, I think that could easily be optimized in s2wasm. But it does seem like the backend would be the better place. @sunfishcode, is this just not yet optimized, or is there some bigger issue here?

**Comment by sunfishcode** [comment]
Yeah, `if`/`if_else` formation is just something that hasn't yet been implemented in the LLVM wasm backend.

Other than that, the output should be fairly clean, and I'd be interested in any areas where it can be improved.

**Comment by kripken** [comment]
Ok, in that case it sounds like there's nothing to be done in binaryen, so closing.
