### ISSUE TITLE
binaryen.js issue on windows

### ISSUE THREAD

**Issue by ramiro1234** [WebAssembly/binaryen#823]
Binaryen.compileWast throws an exception in Windows under Node.js

This happens because you are trying to convert a BufferWithRandomAccess to a raw Buffer. 
Works under Linux but not Windows. 

Not really sure what the bug really is. the following is my workaround.
var debug=false;
var buf0 = new Binaryen.BufferWithRandomAccess(debug);

var wasmWriter = new Binaryen.WasmBinaryWriter(module,buf0,debug);
wasmWriter.write();
var b = Buffer(buf0.size());
for (var i=0; i<buf0.size(); i++)
    b[i]= buf0.at(i);

return b;

**Comment by kripken** [comment]
Not sure I understand. What are the steps to see the problem?

**Comment by ramiro1234** [comment]
// The following works in Linux but not in Windows using Node.js
// throws exception at Binaryen.compileWast
var Binaryen = require("./binaryen");
var fs = require("fs");
var  input ='(module\n' +
  '  (export "add" $add)\n' +
  '  (func $add (param $x f32) (param $y f32) (result f32)\n' +
  '    (f32.add\n' +
  '      (get_local $x)\n' +
  '      (get_local $y)\n)))';
var b = Binaryen.compileWast(input);
fs.writeFile("a.wasm", b);




// Workaround for Windows 
var Binaryen = require("./binaryen");
var fs = require("fs");
var  input ='(module\n' +
  '  (export "add" $add)\n' +
  '  (func $add (param $x f32) (param $y f32) (result f32)\n' +
  '    (f32.add\n' +
  '      (get_local $x)\n' +
  '      (get_local $y)\n)))';
var module = new Binaryen.Module();
var parser = new Binaryen.SExpressionParser(input);
var s_module = parser.get_root().getChild(0);
var builder = new Binaryen.SExpressionWasmBuilder(module, s_module);
var debug=false;
var buf0 = new Binaryen.BufferWithRandomAccess(debug);
var wasmWriter = new Binaryen.WasmBinaryWriter(module,buf0,debug);
wasmWriter.write();
var b = Buffer(buf0.size());
for (var i=0; i<buf0.size(); i++)b[i]= buf0.at(i);
fs.writeFile("a.wasm", b);

**Comment by kripken** [comment]
This might be a node.js bug? Or perhaps it depends on the node.js version, which do you have on those two setups?

**Comment by ramiro1234** [comment]
You were right. It was a Node.js bug. Sorry about that. Buffers are such a core part of Node I didn't think that would be the problem.
