### ISSUE TITLE
s2wasm failed to translate an invalid stack reference in an unreachable branch

### ISSUE THREAD

**Issue by tzik** [WebAssembly/binaryen#828]
llc in LLVM (r286082) translates attached [foo.ll](https://gist.github.com/tzik/37b7fee7391380ef2923727f915f8cda#file-foo-ll) into [foo.s](https://gist.github.com/tzik/37b7fee7391380ef2923727f915f8cda#file-foo-s), and s2wasm in Binaryen (033b5e161e677173) failed to translate it to wast.
It hits an assertion failure at [foo.s:25](https://gist.github.com/tzik/37b7fee7391380ef2923727f915f8cda#file-foo-s-L25):
```s2wasm: /home/tzik/dev/binaryen/src/s2wasm.h:713: auto wasm::S2WasmBuilder::parseFunction()::(anonymous class)::operator()() const: Assertion `!estack.empty()' failed.```
Note that L25 is unreachable, and LLVM seems to emit an invalid operation at the unreachable branch.

I'm not sure on which we should fix it, but IMO, we can fix it in Binaryen. We can just put an unreachable instruction to the wast tree when s2wasm hits the empty stack.

WDYT?

**Comment by kripken** [comment]
Hmm, this question is about the `.s` format itself, I think - not sure what is intended there. cc @sunfishcode 

But reading the code, I don't understand. On Line 25 I see a `return`, and before it a `br_if`, so L25 is not unreachable?

**Comment by sunfishcode** [comment]
I'm not sure what you meant by "L25". Also, br_if is a conditional branch, so code after it can still be reachable.

**Comment by tzik** [comment]
I meant "the 25th line of foo.s".
Though the previous line of it is br_if, its condition ($pop6) is always true.

**Comment by kripken** [comment]
Does changing things so that that condition ($pop6) is always false (or not always true nor always false) change things? (I ask because I don't think the condition always being true has an effect here - s2wasm doesn't know that, unless you run the optimizer, but s2wasm doesn't.)

**Comment by tzik** [comment]
That changes the output of llc, and unbreaks it.
And adding -O0 to llc also changed the situation, probably one of the default optimization passes in WebAssembly CodeGen in LLVM.

**Comment by kripken** [comment]
How about if you change the `.s` code (to make that condition always false, or variable)?

**Comment by tzik** [comment]
s2wasm still hits the assertion even after I replaced the condition to always false.

**Comment by tzik** [comment]
Took a look to LLVM code.
I think the issue happens when we store an uninitialized value into `$pushX=` and use it as `$popX`. LLVM holds the initialization as an IMPLICIT_DEF instruction, which seems an internal instruction to reserve an register. Then the code generator drops the instruction at [AsmPrinter](https://github.com/llvm-mirror/llvm/blob/master/lib/CodeGen/AsmPrinter/AsmPrinter.cpp#L886), and leaves the dangling `$popX`.

**Comment by sunfishcode** [comment]
Ah, thanks for tracking that down. Yes, there's a $pop0 and no corresponding $push0, so it's an LLVM bug. I'll look into it.

**Comment by sunfishcode** [comment]
This is now fixed in LLVM in r286274, by adding explicit "i32.const 0" to provide an explicit $push in such situations.

**Comment by kripken** [comment]
Great.
