### ISSUE TITLE
asm2wasm bad subtract types

### ISSUE THREAD

**Issue by aidanhs** [WebAssembly/binaryen#829]
When trying to compile a project with emscripten with the emterpreter:

> bad subtract types ["assign", true, ["sub", ["name", "HEAPF64"], ["binary", ">>", ["binary", "+", ["name", "sp"], ["binary", "<<", ["name", "lx"], ["num", 3]]], ["num", 3]]], ["call", ["name", "Math_fround"], [["unary-prefix", "+", ["sub", ["name", "HEAPF64"], ["binary", ">>", ["binary", "+", ["name", "sp"], ["binary", "<<", ["name", "ly"], ["num", 3]]], ["num", 3]]]]]]]

which comes from inside this block: https://github.com/WebAssembly/binaryen/blob/5af71eea09abfa9078c62633cea89b121ec4ec08/src/asm2wasm.h#L1209

In addition to it crashing, might be worth noting that `sub` is indexing, not subtraction.

**Comment by kripken** [comment]
Heh, the `subtraction` part is a funny typo.

Thanks, fix is in #830.

**Comment by kripken** [comment]
Merged.
