### ISSUE TITLE
Remove `br` at a block tail.

### ISSUE THREAD

**Issue by JSStats** [WebAssembly/binaryen#84]
Not sure if the intention was to address this case, but s2wasm seems to generate this following redundant pattern.

```
(module
  (memory 0 4294967295)
  (export "add" $add)
  (func $add (param $$0 i32) (param $$1 i32) (result i32)
    (block $fake_return_waka123
      (block
        (br $fake_return_waka123
          (i32.add
            (get_local $$1)
            (get_local $$0)))))))
```

binaryen-shell -print-after -remove-unused-brs -remove-unused-names -merge-blocks add.wast

```
(module
  (memory 0 18446744073709551615)
  (export "add" $add)
  (func $add (param $$0 i32) (param $$1 i32) (result i32)
    (block $fake_return_waka123
      (br $fake_return_waka123
        (i32.add
          (get_local $$1)
          (get_local $$0)
        )))))
```

Could still optimize away the `block br`. An extension for follow tailing expressions and remove `br`'s from them too.

**Comment by kripken** [comment]
Thanks, RemoveUnusedBrs was not handling values. But it definitely can, as you say, I added this now.
