### ISSUE TITLE
Silent abort

### ISSUE THREAD

**Issue by rongjiecomputer** [WebAssembly/binaryen#840]
I am not sure how Linux/Mac handle `abort/assert` calls, but those calls can be very annoying for Windows.

When `abort/assert` are called (not running inside a debugger), it will cause a program crash. A pop-up message window appears and human intervention (click a button) is required to close it. Then Windows Error Reporting service will be busy sending crash report to Microsoft even though it is not their fault.

I suggest instead of using `abort/assert` provided in `assert.h` and `stdlib.h` directly, we can use something like https://gist.github.com/rongjiecomputer/c060e1736c7a7fbe5ddcd75496a05bc3 (adapted and simplified from V8 source). The extra `raise(SIGABRT)` call ensure that the program is aborted silently.

**Comment by dschuff** [comment]
There are a lot of places in binaryen where we have `abort()` where it really should result in `exit(-1)` or something like that instead. `abort()` and assertion failures do (and and are intended to) behave more like crashes, things that only happen if there is a bug in the program. For example, bad input should never call abort, it should just print an error message and exit (e.g. Binaryen has `Fatal` for this https://github.com/WebAssembly/binaryen/blob/master/src/support/utilities.h#L62). That would leave just a few places where there are real asserts or aborts, and those can be silent if we want.

**Comment by rongjiecomputer** [comment]
I use binaryen to learn how to hand-write `wast` and `asm.js`, I often get assertion failures because syntax error in my input file, so much until I decided to run binaryen only in `gdb` even though I am not debugging the program.

**Comment by binji** [comment]
@rongjiecomputer You may want to try the spec interpreter or wabt for learning the text format. Binaryen currently only supports the s-expression style for functions, which is non-canonical.

**Comment by rongjiecomputer** [comment]
In the end I use `d8 --validate_asm` to check `asm.js`, compile it to `wast` with `asm2wasm`. Use `wast2wasm` to check hand-written/compiled `wast`, compile it to `wasm`, then interact with it using `d8 --expose_wasm`.
