### ISSUE TITLE
SDL tests give "no native wasm support detected" error

### ISSUE THREAD

**Issue by qog314** [WebAssembly/binaryen#844]
I'm on sdk-incoming-64bit; when I compile any test that contains SDL code, I get a 
`no native wasm support detected` error, and nothing shows up. 
I'm on debian, using Nightly. 

I compile it with "/emcc tests/sdl_canvas_palette.c -O2 -s USE_SDL=2 -s BINARYEN=1 -o pal_sdl.html" 

How can I resolve this issue?
Thanks.

**Comment by kripken** [comment]
Do other things work with wasm, that don't use SDL?

If it's a general issue, make sure your browser [supports wasm](https://github.com/kripken/emscripten/wiki/WebAssembly#testing-native-webassembly-in-browsers).

If not, is there a stack trace or larger error message perhaps? And which emscripten version is it with?

**Comment by qog314** [comment]
Correct, things that don't use SDL work just fine. 
Yes, I have set the wasm flag in Nightly. 
The emscripten version is emsdk-1.35.0-portable-64bit. 
The program compiles without incident; the error shows in developer tools when I try to access the html page. 
This is the only thing I can find resembling a stack trace:
`no native wasm support detected pal_sdl.html:1249:13`	
`Module.printErr http://localhost:8000/pal_sdl.html:1249:13`
`doNativeWasm http://localhost:8000/pal_sdl.js:197:7`
`integrateWasmJS/Module.asm http://localhost:8000/pal_sdl.js:328:23`
`<anonymous> http://localhost:8000/pal_sdl.js:11477:10`

**Comment by ramiro1234** [comment]
technically the latest version of  Nightly does not support wasm, it supports Web Assembly

**Comment by kripken** [comment]
@qog314: perhaps the problem is you need a more recent emscripten version. The wasm spec changed since then, maybe on something that a small program doesn't hit but an SDL-using one does. I am guessing that is the case because when I run your command on latest emscripten incoming (1.36.14), it does run ok in firefox nighty.

**Comment by ramiro1234** [comment]
The latest versions of Chrome Canary and Nightly support the latest updates to Web Assembly in terms of version and JS API. You will get an error message saying if the version is not up-to-date  but for the latest JS API it will simply say wasm not supported.  Only the latest tools are guaranteed to work as far as the latest browsers are concerned. 

For those working on s-expressions there are some differences in the Web Assembly Toolkit and binaryen with the Web Assembly Toolkit being a little more up-to-date.  The makes a difference mostly for compiler writers of which I am one.

You can't work on the bleeding-edge without bleeding a little bit.

**Comment by frededk** [comment]
When I try out (Latest versions of Canary & Nightly) the /test/binaryen.js/ on a local webserver I get the "No WASM support detected" error message in the browser.html webpage. The WASM flags are activated. Does this mean that the current browsers do not yet support the binaryen.js example or have I forgotten anything? Using emsdk to compile C code to wasm and loading it using JS/HTML works fine. Does it have something to do with the fact that the module "Wasm" is called and not "WebAssembly"?

**Comment by qog314** [comment]
I updated to the latest version by doing
`./emsdk update latest`
`./emsdk activate latest`
`source ./emsdk_env.sh`

Now, none of the tests will compile. Here is the traceback:
`Traceback (most recent call last):`
 ` File "./emcc", line 13, in <module>
    emcc.run()`
  `File "/opt/emsdk_portable/emscripten/master/emcc.py", line 1777, in run
    binaryen_bin = os.path.join(shared.Settings.BINARYEN, 'bin')`
  `File "/usr/lib/python2.7/posixpath.py", line 77, in join
    elif path == '' or path.endswith('/'):`
`AttributeError: 'int' object has no attribute 'endswith'`

Have I missed a step?

**Comment by kripken** [comment]
I think that updated you to `master`, and you need `incoming`. Specifically, that error shows that it is using `BINARYEN`, which was an old form, and now we use `BINARYEN_ROOT`. I think [these are the commands](http://kripken.github.io/emscripten-site/docs/tools_reference/emsdk.html#how-do-i-track-the-latest-emscripten-development-with-the-sdk) you need.

**Comment by qog314** [comment]
I have updated incoming according to those commands. I am still getting the "no native wasm support detected" error.
Is it possible that this is a linux only issue? My colleague, who is on windows, is not having this issue.

**Comment by ramiro1234** [comment]
Just checked, Nightly on Linux is not as current as windows.  If you set up a quick and dirty server on node you should be able to check your code on the windows computer. Besides you may have to do that anyway if you want to stay current.  Nightly on linux looks like it is way behind.

**Comment by ramiro1234** [comment]
Forget my previous message. Nightly on Linux is fine. I downloaded and forget to set the config. Anyway it should not be a wasm issue as far as Nightly is concerned. It does the current version and the new JS API.

**Comment by kripken** [comment]
@qog314: worth checking you and that colleague have the same versions of browsers and emscripten. One possible issue is chrome has canary on windows, but not in linux, so linux builds are always delayed.

Also worth checking other wasm demos on the web, like one on the main website. That'll help narrow down if it's the browser or the toolchain. Also, can test a build your colleague makes.

**Comment by qog314** [comment]
The angry bots demo works fine. 

My colleague is on 1.36.5; I am on 1.36.14, but was on 1.36.0 before. I was wrong before - he is also on linux, but doesn't know which version. 

I tested a build he compiled and it runs fine on my nightly. 

This would indicate there's something specifically wrong with my toolchain, yes?

**Comment by kripken** [comment]
Actually, if you are on 1.36.14, then the browser might be at fault. A problem is that I remember now that the main demo website will run earlier versions of wasm binaries (something that is indeed possibly confusing).

I would create a hello world binary in 1.36.14, then add some debug output in the JS, search for "no native wasm support" in the code. It checks for the existence of `WebAssembly` and some other things, I believe, so you can find out what specifically it is not finding in your browser.

**Comment by kripken** [comment]
We should also find a way to improve that output when an error occurs.

**Comment by qog314** [comment]
I am not sure what fixed this, but I restarted the nightly browser and suddenly I am not getting that error anymore. 

I didn't make any other changes. Weird.

**Comment by kripken** [comment]
Possibly the restart made it use a more updated version.
