### ISSUE TITLE
don't abort on custom sections

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/binaryen#857]
I'm experimenting with writing out object files using the [linking scheme](https://github.com/WebAssembly/tool-conventions/blob/master/Linking.md). Binaryen's wasm-dis currently aborts when it sees a reloc section, which is inconvenient.

```
$ wasm-dis test.o 
unfamiliar section: $reloc
Aborted (core dumped)
```

**Comment by kripken** [comment]
Thanks, PR in #858.
