### ISSUE TITLE
asm2wasm, assert fails

### ISSUE THREAD

**Issue by cr88192** [WebAssembly/binaryen#873]
trying to compile a project, I get this error:
<---
asm2wasm: /home/bgb/.emscripten_ports/binaryen/binaryen-version_23/src/asm2wasm.h:2138: wasm::Asm2WasmBuilder::processFunction(cashew::Ref)::__lambda15: Assertion `index >= 0' failed.
Traceback (most recent call last):
  File "/home/bgb/emsdk_portable/emscripten/incoming/emcc", line 13, in <module>
    emcc.run()
  File "/home/bgb/emsdk_portable/emscripten/incoming/emcc.py", line 2129, in run
    subprocess.check_call(cmd, stdout=open(wasm_text_target, 'w'))
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[u'/home/bgb/.emscripten_ports/binaryen/binaryen-version_23/bin/asm2wasm', 'deeptail0.asm.js', '--total-memory=536870912', '-O3', '--mem-init=deeptail0.html.mem', '--mem-base=1024', '--wasm-only']' returned non-zero exit status -6
--->

it still occurs as long as WASM is enabled, and does not seem to care about optimization settings.

it appears related to switch statements, but I have not been able to reproduce it as of yet with a smaller self-contained example, nor have much idea for the cause (nothing obvious stands out to me).

the project in some places uses a decent number of switches, including some large switches (~ 8k cases). there are also some switches within switches, etc...

**Comment by kripken** [comment]
Yeah, the assertion is switch-related. Hard to tell what's going wrong, though - can you provide the bitcode or `.asm.js` file, to reproduce the issue?

**Comment by cr88192** [comment]
[deeptail0.asm.zip](https://github.com/WebAssembly/binaryen/files/700178/deeptail0.asm.zip)

hopefully this works...

**Comment by kripken** [comment]
Thanks, #877 should fix this.

**Comment by froydnj** [comment]
@kripken, can we close this now?

**Comment by kripken** [comment]
Yes, thanks.
