### ISSUE TITLE
--pre-js acts differently in WASM=1 then in ASMJS

### ISSUE THREAD

**Issue by briangavin** [WebAssembly/binaryen#875]
When using linker flag --pre-js acts differently in WASM=1 then in ASMJS.   The .js file does not appear at the top of the generated file like it does when compiling to ASMJS and generating .js file.

--post-js does not have this problem and puts the attached file at the end of the .js file.

**Comment by kripken** [comment]
Yeah, we should clean that up. I need to change some things for async compilation too anyhow, so I can do it while doing that.

**Comment by kripken** [comment]
Ok, that should be fixed by that PR, which merged.

**Comment by briangavin** [comment]
Wow that was fast!   Your fix works great :)
