### ISSUE TITLE
Hitting assert in asm2wasm FinalizeCalls::visitCallImport()

### ISSUE THREAD

**Issue by lukester1975** [WebAssembly/binaryen#879]
Hi

I've been getting an assert (sometimes, see issue 874) in asm2wasm (binaryen version 23):

```Assertion failed: type->params[i] == f64, file C:\Users\luke\.emscripten_ports\binaryen\binaryen-version_23\src\asm2wasm.h, line 963```

Instead of the assert, I've put in a bit of logging:
```			
if (type->params[i] != f64)
{
    std::cerr << "type->params[i] == " << type->params[i] << " (" << printWasmType(type->params[i]) << ")\n";
    std::cerr << "curr->operands[i]->type == " << curr->operands[i]->type << "\n\n";
}
```

Which gives:
```
type->params[i] == 1 (i32)
curr->operands[i]->type == 5 (unreachable)
```

I'm not sure how to reproduce this with a small example and can't really post the code that tripped the assert. Hopefully this is enough to go on though. Does the assert just need to check for (curr->operands[i]->type == unreachable) maybe, given the following switch is a noop for unreachable?

Thanks in advance!

Luke.

**Comment by kripken** [comment]
Hmm, so what I am guessing happens is that we see that param of that import is used as i32 once, and as unreachable another time. We don't handle such overloading, so it crashes. The problem with that theory is I can't think of how a param could be unreachable - this is asm.js, we can't e.g. do a return instead of a parameter to a function call. So something really weird is happening here.

If you can't share the code, I'd try to reduce it - find the function (`--debug` to asm2wasm will print func names as it works, so the last is the crucial one) and then remove stuff from the function while the bug persists, until you are left with the interesting part.

If you can share the code privately, I can do that for you.

**Comment by lukester1975** [comment]
Hi

OK I ran myu build with EMCC_DEBUG=1 to see the asm2wasm invocation, than ran that (I couldn't see a way to get asm2wasm --debug passed from emcc directly):

`/home/luke/.emscripten_ports/binaryen/binaryen-version_23/bin/asm2wasm ../../../../bin/Amsio_asm_js_emcc137_cxx11_mds.asm.js --total-memory=16777216 -O3 --mem-init=../../../../bin/Amsio_asm_js_emcc137_cxx11_mds.html.mem --mem-base=1024 --wasm-only --debug`

But it didn't appear to help at the point of the assert:

```
<big snip>

[PassRunner]   (validating)
[PassRunner]   running pass: precompute...                     0.105964 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: vacuum...                         0.22301 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: duplicate-function-elimination... 0.235529 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: remove-unused-module-elements...  0.10914 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: memory-packing...                 1.118e-06 seconds.
[PassRunner]   (validating)
[PassRunner] passes took 12.9433 seconds.
[PassRunner] (final validation)
[PassRunner] running passes...
[PassRunner]   running pass: finalize-calls...
asm2wasm: /home/luke/.emscripten_ports/binaryen/binaryen-version_23/src/asm2wasm.h:964: void wasm::Asm2WasmBuilder::processAsm(cashew::Ref)::FinalizeCalls::visitCallImport(wasm::CallImport*): Assertion `type->params[i] == f64' failed.
```

So poking around in the code I saw CallImport::target. Dumping that out before the assert:

```          if (type->params[i] != f64)
            std::cerr << "Oops. Failed in: " << curr->target << std::endl;
```

Gives:

`Oops. Failed in: $___cxa_throw`

This is a C++ codebase that will throw various places - I'm just ignoring that for now, and haven't enabled catching (built with -O3).

Hopefully that makes some sense, from what you said above I could see it might given exception catching is disabled!

I'll try to see if I can replicate with some simple exception throwing.

Regards

Luke.

**Comment by lukester1975** [comment]
I have a bit more info: the code is built with ASYNCIFY=1 and it doesn't trip the assert if built without ASYNCIFY.

No luck with a simple example yet, however!

**Comment by kripken** [comment]
Perhaps also print out `getFunction()->name` to see where the bad call appears. That plus the called function that you already have should pinpoint the failing line. Then you can see how it gets an unreachable for the param. Maybe print out the type to confirm that as well.

**Comment by lukester1975** [comment]
Ah that's nice, thanks - it's caused by a throw in a default case of a switch that can never be reached. I'll see if I can get it down to a few lines...

As an aside, if it's OK to ask, since ASYNCIFY is deprecated is there another way to implement coroutines? emscripten_coroutine_create, emscripten_coroutine_next and emscripten_yield are perfect for my use case and I'm not really sure of the relationship with emterpreter and wasm, if there is any (or indeed how to use emterpreter to get similar functionality...).

Thanks!

Luke.

**Comment by kripken** [comment]
The emterpreter should be able to do those things. Hopefully it would be fairly straightforward, but I don't remember enough of those details to be sure. Maybe read `src/library_async.js` and see how other async things are done in the emterpreter, then try to do it for the coroutine methods.

**Comment by lukester1975** [comment]
[wasm-assert.tar.gz](https://github.com/WebAssembly/binaryen/files/711035/wasm-assert.tar.gz)

OK attached is as minimal a demo of the assert as I can get (bearing in mind the asserts don't fire on a VC++ build!).

`em++ Main.cpp -o Main.html -s ASYNCIFY=1 -O3 -s WASM=1 -I ./boost -I .`

Seems to be somewhat related to using BOOST_THROW_EXCEPTION (the archive has the relevant bits of boost in it): changing that for a regular throw removes the assert. Then again, changing any line left in the example does similar - e.g. removing the throw on the default switch case; removing the if statement in BadThrow() so it always throws; removing either the STATE_1 or STATE_2 cases...

Hope that's of some help if it needs fixing!

Regards

Luke.

PS thanks, I'll take a look at library_async.js though I suspect it's way over my head!

**Comment by kripken** [comment]
Thanks, I tracked that down to #885, which should fix things for you.

**Comment by lukester1975** [comment]
Cool, I'm glad it was a simple fix.

Thanks

**Comment by kripken** [comment]
Fixed by that PR landing.
