### ISSUE TITLE
s2wasm conversion seems incorrect

### ISSUE THREAD

**Issue by kf2093** [WebAssembly/binaryen#883]
I'm trying s2wasm and am receiving incorrect translation for a simple C function.  The C function code is:
```
void test() {
        int i = 6;
}
```

this is compiled to llvm .ll correctly:
```
define hidden void @test() #0 {
entry:
  %i = alloca i32, align 4
  store i32 6, i32* %i, align 4
  ret void
}
```

When I compile to .s using the wasm32 architecture, it adds in some instructions that I cannot make ends of
```
test:                                   # @test
# BB#0:                                 # %entry
        i32.const       $push1=, 0
        i32.load        $push2=, __stack_pointer($pop1)
        i32.const       $push3=, 16
        i32.sub         $push4=, $pop2, $pop3
        i32.const       $push0=, 6
        i32.store       12($pop4), $pop0
```

Then I get the following wast:
```
(module
  (table 0 anyfunc)
  (memory $0 1)
  (export "memory" (memory $0))
  (export "test" (func $test))
  (func $test
    (i32.store offset=12
      (i32.sub
        (i32.load offset=4
          (i32.const 0)
        )
        (i32.const 16)
      )
      (i32.const 6)
    )
  )
)
```

Is this correct behaviour?   What I find odd is that a local variable assignment becomes a memory i32.store (rather than a set_local).

**Comment by sunfishcode** [comment]
Yes, this is common in unoptimized code produced by LLVM. Notice how the store is present even in the LLVM IR. If you compile with optimization, eg. -O2, LLVM will avoid emittings stores and loads for most variables.

**Comment by kf2093** [comment]
thanks, I'll keep playing around then :)

**Comment by jonas-db** [comment]
@kf2093 can you tell me all the commands to compile the C function to Wasm?

**Comment by tlively** [comment]
s2wasm no longer exists.
