### ISSUE TITLE
Native WebAssembly and __syscall221

### ISSUE THREAD

**Issue by facekapow** [WebAssembly/binaryen#887]
Hi, I'm having some problems trying to run some emscripten-to-webassembly-compiled C++ library tests (specifically, libsodium's tests). It keeps complaining about not being able to find `__syscall221`, and inspecting the WebAssembly helper JavaScript module generated by Emscripten shows that it's right, there is *no* `__syscall221` defined anywhere.

I guess the first question to ask would be, what is `__syscall221`? What does it do? It's important to note that the same code was working with a previous version of Emscripten/Binaryen.

The specific error I'm getting is:
```
failed to compile wasm module: LinkError: WebAssembly.Instance(): Import #12 module="env" function="___syscall221" error: function import requires a callable
```

Not sure if this'll help but, here's my WebAssembly interpreter specs:
  - Chrome Canary 58.0.2988.0 64bit...
  - with V8 5.7.492...
  - on macOS Sierra 10.12.1

And emsdk versions:
  - `emcc (Emscripten gcc/clang-like replacement) 1.37.1 (commit 62dfd0f886bfc0a4bf7fb0663ba164dcda6ba253)`
  - `clang version 3.9.0 (https://github.com/kripken/emscripten-fastcomp-clang/ 7372fbdc769db28fd534454268f4b008e629464f) (https://github.com/kripken/emscripten-fastcomp/ f63a464e84eb84f1bdf62c08df9d2c38d69e7434)`

I'm also not sure whether this is an issue I should be opening on Binaryen or Emscripten, but I would appreciate any help.

**Comment by kripken** [comment]
Looking in `src/library_syscall.js`, it appears syscall 221 is `fcntl64`. That's known to work in general, so something odd must be happening in your case.

Since it worked in a previous version, perhaps the fastest thing is to just bisect to find where that changed? Another option, if it works in asm.js but not wasm, is these debugging tips: https://github.com/kripken/emscripten/wiki/WebAssembly#debugging

**Comment by facekapow** [comment]
Just recompiled today and this seems to be gone now. Weird. Anyways, thanks for the help.
