### ISSUE TITLE
asm2wasm - compile result not right

### ISSUE THREAD

**Issue by qdwang** [WebAssembly/binaryen#901]
Here is the asm.js code
```javascript
function Test() {
    'use asm';

    var a = new stdlib.Int32Array(10);
    var b = new stdlib.Int32Array(10);

    function inner() {
        a[1] = 1;
        b[1] = 3;
    }
};
```

Here is the output wast code
```
(module
  (import "env" "memory" (memory $0 256 256))
  (import "env" "table" (table 0 0 anyfunc))
  (import "env" "memoryBase" (global $memoryBase i32))
  (import "env" "tableBase" (global $tableBase i32))
  (func $inner
    (i32.store
      (i32.const 4)
      (i32.const 1)
    )
    (i32.store
      (i32.const 4)
      (i32.const 3)
    )
  )
)

```

In wast code, the int `1` and int `3` are store in the same address in memory .
But clearly, they are set in different arrays in asm.js.

**Comment by kripken** [comment]
I believe that's not valid asm.js. asm.js can only create arrays on the singleton buffer that arrives from the outside.

asm2wasm doesn't have much in terms of input validation (it is mostly just tested on emscripten asm.js output), so it misses this problem. But for error checking, you can run it in spidermonkey with `-w` to check for asm.js validation, which gives this error:
````
a.js:4:12 warning: asm.js type error: cannot create array view without an asm.js global parameter:
a.js:4:12 warning:     var a = new stdlib.Int32Array(10);
````
