### ISSUE TITLE
Binary Downloads

### ISSUE THREAD

**Issue by Horcrux7** [WebAssembly/binaryen#931]
If you create a new release then you should make a binary version available. It is a pain to build it under Windows.

**Comment by kripken** [comment]
I think https://wasm-stat.us/console has binaries for windows (see "archive binaries" step).

**Comment by Horcrux7** [comment]
I can't see any binary download on this page.

**Comment by kripken** [comment]
I think you need to switch to the 'waterfall' tab, https://wasm-stat.us/waterfall . Then the 'archive binaries' step has a download (looks like it's everything all together, the binaryen binaries are in bin/).

**Comment by Horcrux7** [comment]
Thank you very much. I have it.
