### ISSUE TITLE
Assertion failed: (isAssignName()), function asAssignName file simple_ast.cpp

### ISSUE THREAD

**Issue by Durisvk** [WebAssembly/binaryen#941]
Hello,

I am having a trouble trying to compile my javascript source into wasm. I am using command `./bin/asm2wasm`.

This is my javascript:

```javascript
function calculator(global) {
	"use asm";
	function add(x, y) {
		"use asm";
		x = x | 0;
		y = y | 0;
		return x + y | 0;
	}
	
	return { add: add };
}
```

here is the full error:

```
Assertion failed: (isAssignName()), function asAssignName, file /Users/jurajcarnogursky/Documents/binaryen/src/emscripten-optimizer/simple_ast.cpp, line 79.
fish: './bin/asm2wasm /Users/jurajcarn…' terminated by signal SIGABRT (Abort)
```

what am I doing wrong?

**Comment by pipcet** [comment]
I'm not sure how it's causing that error, but removing the second "use asm"; appears to fix things.

**Comment by Durisvk** [comment]
If I remove the second "use asm"; I get this error:

```
bad parseExpression state:
==========
function add(x, y) {
		x = x | 0;
```

**Comment by pipcet** [comment]
Can you post your entire input file? This one works for me, with all semicolons and such:
```
function calculator(global) {
	"use asm";
	function add(x, y) {
		x = x | 0;
		y = y | 0;
		return x + y | 0;
	}
	return { add: add };
}
```

**Comment by Durisvk** [comment]
aah yes this one works for me too.. thank you, you can close the issue :)

**Comment by kripken** [comment]
Yeah, our error handling could be a lot better - we only really test on fastcomp asm.js output, so that works, but no guarantees otherwise. Would be nice if someone looked into improving the error reporting.
