### ISSUE TITLE
Static linking fails with undefined references

### ISSUE THREAD

**Issue by rjw57** [WebAssembly/binaryen#948]
#598 contained a rationale for allowing static linking with binaryen and #610 implemented it. Configuring as suggesting in #610  with ``cmake -DBUILD_STATIC_LIB=ON`` and then attempting to compile the following trivial program within the repo root directory fails.

```cpp
// test.cpp
// compile with: g++ test.cpp -Llib -Isrc -lbinaryen
#include "src/binaryen-c.h"

int main() {
	return BinaryenNone();
}
```
The first few lines of the error log are as follows. The full log can be provided if required:

```
lib/libbinaryen.a(binaryen-c.cpp.o): In function `fromBinaryenLiteral(BinaryenLiteral)':
binaryen-c.cpp:(.text+0x329): undefined reference to `wasm::Literal::castToF64()'
binaryen-c.cpp:(.text+0x33f): undefined reference to `wasm::Literal::castToF32()'
lib/libbinaryen.a(binaryen-c.cpp.o): In function `BinaryenLiteralFloat32Bits':
binaryen-c.cpp:(.text+0x4d7): undefined reference to `wasm::Literal::castToF32()'
lib/libbinaryen.a(binaryen-c.cpp.o): In function `BinaryenLiteralFloat64Bits':
binaryen-c.cpp:(.text+0x508): undefined reference to `wasm::Literal::castToF64()'
lib/libbinaryen.a(binaryen-c.cpp.o): In function `BinaryenModulePrint':
binaryen-c.cpp:(.text+0xdb0): undefined reference to `vtable for wasm::Printer'
binaryen-c.cpp:(.text+0xdc7): undefined reference to `wasm::PassRunner::doAdd(wasm::Pass*)'
```

Compilation of ``test.cpp`` succeeds with the same command line if binaryen is built as a shared library.

**Comment by kripken** [comment]
When I run that command g++ links without an error, but that's when binaryen was built normally, not with BUILD_STATIC_ON. cc @lqd who added that feature.

**Comment by rjw57** [comment]
Yup, the test case succeeds for me when binaryen built as a shared library and I'd have expected it to when binaryen was built as a static library. AFAICT building as a static library is not tested for in CI?

**Comment by lqd** [comment]
@kripken AFAICT some of the layout changed since that PR (some of the src was moved from "binaryen sources" into different libs) but I don't think even back then that command would have worked, since there were multiple libs already right ?

BUILD_STATIC_ON does not change the layout/dependencies or number of libraries in binaryen: it only builds 7 static libs instead of 7 shared libs. Building with BUILD_STATIC_ON results in these libraries being built today:
- libasmjs.a
- libast.a
- libbinaryen.a
- libemscripten-optimizer.a
- libpasses.a
- libsupport.a
- libwasm.a

(and not a single libbinaryen :)

Adding each of those to the given command would solve the problem — even though they are not all strictly required for this particular example, eg this builds correctly for me:
`g++ test.cpp -Llib -Isrc -lbinaryen -lwasm -last -lasmjs -lsupport -lpasses`

**Comment by rjw57** [comment]
It still fails for me:

```
$ g++ test.cpp -Llib -I../ -lbinaryen -lwasm -last -lasmjs -lsupport -lpasses -pthread
lib/libpasses.a(RemoveUnusedBrs.cpp.o): In function `wasm::RemoveUnusedBrs::doWalkFunction(wasm::Function*)::FinalOptimizer::visitBlock(wasm::Block*)':
RemoveUnusedBrs.cpp:(.text._ZZN4wasm15RemoveUnusedBrs14doWalkFunctionEPNS_8FunctionEEN14FinalOptimizer10visitBlockEPNS_5BlockE[_ZZN4wasm15RemoveUnusedBrs14doWalkFunctionEPNS_8FunctionEEN14FinalOptimizer10visitBlockEPNS_5BlockE]+0x1bb): undefined reference to `wasm::ExpressionManipulator::spliceIntoBlock(wasm::Block*, unsigned int, wasm::Expression*)'
RemoveUnusedBrs.cpp:(.text._ZZN4wasm15RemoveUnusedBrs14doWalkFunctionEPNS_8FunctionEEN14FinalOptimizer10visitBlockEPNS_5BlockE[_ZZN4wasm15RemoveUnusedBrs14doWalkFunctionEPNS_8FunctionEEN14FinalOptimizer10visitBlockEPNS_5BlockE]+0x4af): undefined reference to `wasm::ExpressionManipulator::spliceIntoBlock(wasm::Block*, unsigned int, wasm::Expression*)'
collect2: error: ld returned 1 exit status
```

**Comment by rjw57** [comment]
> BUILD_STATIC_ON does not change the layout/dependencies or number of libraries in binaryen: it only builds 7 static libs instead of 7 shared libs. 

When BUILD_STATIC_LIB is OFF I get 6 static libs an one shared:

```
$ ls -l lib/
total 7604
-rw-r--r-- 1 rjw57 rjw57   37098 Mar 15 22:10 libasmjs.a
-rw-r--r-- 1 rjw57 rjw57   98126 Mar 15 22:10 libast.a
-rwxr-xr-x 1 rjw57 rjw57 2464328 Mar 15 22:10 libbinaryen.so
-rw-r--r-- 1 rjw57 rjw57  215228 Mar 15 22:10 libemscripten-optimizer.a
-rw-r--r-- 1 rjw57 rjw57 4054642 Mar 15 22:10 libpasses.a
-rw-r--r-- 1 rjw57 rjw57   98764 Mar 15 22:10 libsupport.a
-rw-r--r-- 1 rjw57 rjw57  805028 Mar 15 22:10 libwasm.a
```

This is consistent with the way CMake seems to like to do things BTW.

**Comment by lqd** [comment]
Weird

```
$ ls -l lib/
total 5984
-rw-r--r--  1 rrakic  staff    22808 Mar 15 22:30 libasmjs.a
-rw-r--r--  1 rrakic  staff    43568 Mar 15 22:30 libast.a
-rw-r--r--  1 rrakic  staff   403448 Mar 15 22:33 libbinaryen.a
-rw-r--r--  1 rrakic  staff    90032 Mar 15 22:31 libemscripten-optimizer.a
-rw-r--r--  1 rrakic  staff  1815288 Mar 15 22:31 libpasses.a
-rw-r--r--  1 rrakic  staff   101552 Mar 15 22:31 libsupport.a
-rw-r--r--  1 rrakic  staff   573512 Mar 15 22:30 libwasm.a
```

```
$ g++ test.cpp -Llib -I../ -lbinaryen -lwasm -last -lasmjs -lsupport -lpasses -pthread && ./a.out && echo $?
printf I added to your test.cpp
0
```

**Comment by rjw57** [comment]
> Adding each of those to the given command would solve the problem

I'm not sure that's true since all of the mentioned libraries are linked into libbinaryen.a via CMakeLists.txt:140

```
TARGET_LINK_LIBRARIES(binaryen ${all_passes} wasm asmjs ast support)
```

But I confess I'm not sure off the top of my head if this will cause all the objects in libwasm et al to be linked into libbinaryen.a.

**Comment by rjw57** [comment]
> Weird

Weird indeed. Is this Linux or OS X? My static binaries are a lot larger when compiled with BUILD_STATIC_LIB=ON and no other configuration.

```
$ ls -l lib/
total 5860
-rw-r--r-- 1 rjw57 rjw57   37098 Mar 15 22:23 libasmjs.a
-rw-r--r-- 1 rjw57 rjw57   98126 Mar 15 22:23 libast.a
-rw-r--r-- 1 rjw57 rjw57  677130 Mar 15 22:23 libbinaryen.a
-rw-r--r-- 1 rjw57 rjw57  215228 Mar 15 22:23 libemscripten-optimizer.a
-rw-r--r-- 1 rjw57 rjw57 4054642 Mar 15 22:23 libpasses.a
-rw-r--r-- 1 rjw57 rjw57   98764 Mar 15 22:23 libsupport.a
-rw-r--r-- 1 rjw57 rjw57  805028 Mar 15 22:23 libwasm.a
```

**Comment by rjw57** [comment]
Here's a full fresh build log:

```
rjw57@thor:binaryen (master)
$ git show-ref master
a407b989ecc0c57ed4862ceaaa25acb0a41af63c refs/heads/master
a407b989ecc0c57ed4862ceaaa25acb0a41af63c refs/remotes/origin/master
rjw57@thor:binaryen (master)
$ mkdir build; cd build; cmake -DBUILD_STATIC_LIB=ON ..; make -j2 2>&1 >/dev/null
-- The C compiler identification is GNU 6.2.0
-- The CXX compiler identification is GNU 6.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- No build type selected, default to Release
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Building with -std=c++11
-- Building with -msse2
-- Building with -mfpmath=sse
-- Building with -Wall
-- Building with -Werror
-- Building with -Wextra
-- Building with -Wno-unused-parameter
-- Building with -fno-omit-frame-pointer
-- Building with -fPIC
-- Building with -O2
-- Building with -UNDEBUG
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rjw57/projects/binaryen/build
rjw57@thor:build (master)
$ cat >test.cpp
// test.cpp
// compile with: g++ test.cpp -Llib -Isrc -lbinaryen
#include "src/binaryen-c.h"

int main() {
        return BinaryenNone();
}
rjw57@thor:build (master)
$  g++ test.cpp -Llib -I../ -lbinaryen -lwasm -last -lasmjs -lsupport -lpasses -pthread && ./a.out && echo $?
lib/libpasses.a(RemoveUnusedBrs.cpp.o): In function `wasm::RemoveUnusedBrs::doWalkFunction(wasm::Function*)::FinalOptimizer::visitBlock(wasm::Block*)':
RemoveUnusedBrs.cpp:(.text._ZZN4wasm15RemoveUnusedBrs14doWalkFunctionEPNS_8FunctionEEN14FinalOptimizer10visitBlockEPNS_5BlockE[_ZZN4wasm15RemoveUnusedBrs14doWalkFunctionEPNS_8FunctionEEN14FinalOptimizer10visitBlockEPNS_5BlockE]+0x1bb): undefined reference to `wasm::ExpressionManipulator::spliceIntoBlock(wasm::Block*, unsigned int, wasm::Expression*)'
RemoveUnusedBrs.cpp:(.text._ZZN4wasm15RemoveUnusedBrs14doWalkFunctionEPNS_8FunctionEEN14FinalOptimizer10visitBlockEPNS_5BlockE[_ZZN4wasm15RemoveUnusedBrs14doWalkFunctionEPNS_8FunctionEEN14FinalOptimizer10visitBlockEPNS_5BlockE]+0x4af): undefined reference to `wasm::ExpressionManipulator::spliceIntoBlock(wasm::Block*, unsigned int, wasm::Expression*)'
collect2: error: ld returned 1 exit status
rjw57@thor:build (master)
$ uname -a
Linux thor 4.8.0-41-generic #44-Ubuntu SMP Fri Mar 3 15:27:17 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by lqd** [comment]
I'm not sure either, and I thought it didn't add them to libbinaryen.a but I'm less experienced with cmake than you.

(sorry, I did mean to say I was on osx and had updated the previous comment)

**Comment by rjw57** [comment]
> I'm not sure either, and I thought it didn't add them to libbinaryen.a but I'm less experienced with cmake than you.

I'm not entirely sure what happens in this case either so let's just assume one has to list all the various .a archives :).

>  I did mean to say I was on osx and had updated the previous comment

Ah, perhaps that's the wrinkle.

**Comment by lqd** [comment]
In any case it seems listing all the .a does not help you compile as much as it did help me :)

**Comment by rjw57** [comment]
No, indeed. It's a bit late to investigate more here but at least we've got it down to one undefined reference. I'll look a bit more later on since I want to get static linking to work so I can package some Python bindings nicely. (Static linking libbinaryen.a into a .so with the Python module makes things easier in this regard.)

**Comment by pipcet** [comment]
Have you tried grouping the libraries with `-Wl,-(` and `-Wl,-)`? That appears to fix the issue here (and there might not be a correct order to specify the libraries in anyway):

```
$ g++ test.cpp -Llib -I../ -Wl,-\( -lbinaryen -last -lasmjs -lsupport -lpasses -lwasm -Wl,-\) -pthread && ./a.out && echo $?
0
```

**Comment by rjw57** [comment]
Yes, this fixes it for me too. Thanks, @pipcet. I'll just have to find a way to translate that magic into a form Python's C-module building stuff understands.

**Comment by lqd** [comment]
@pipcet thanks for the help !

**Comment by dschuff** [comment]
There is a distinction between the constituent libs (`libasmjs.a`, `libsupport.a` etc) and `libbinaryen.{a,so}`. I think the former are really more implementation/factoring details, and the latter should be what are actually exported/installed from the build. I think the intent of `libbinaryen.so` is that it be freestanding (with no dependence on the static libs) and `libbinaryen.a` should be also. Also I think we should probably just build and install both of them with an INSTALL step, and none of the intermediate libraries.

**Comment by rjw57** [comment]
CMake has a handy "OBJECT" veriant of add_library() which might also be helpful: https://cmake.org/cmake/help/v3.0/command/add_library.html

**Comment by rjw57** [comment]
Re-opening assuming people want to discuss @dschuff 's point

**Comment by dschuff** [comment]
Yeah; unfortunately the CMake on Travis is *ancient* and doesn't support "OBJECT".

**Comment by davidalbertonogueira** [comment]
I support @pipcet 's recommendation. For anyone with the same problem, in this repo or other, this
```
-Wl,-\( -l<lib#1> -l<lib#2> (...) -Wl,-\) 
```
fixes the problem.

**Comment by sbc100** [comment]
I think @dschuff is correct.   Application should only link against libbinaryen (.a or .so) not the constituent libraries.    This is why we don't install the constituent libraries are part of the install phase.
