### ISSUE TITLE
`make install` should not put `.js` files in `.../bin/`

### ISSUE THREAD

**Issue by alexreg** [WebAssembly/binaryen#951]
These files are specifically `wasm.js` and `binaryen.js`.

**Comment by kripken** [comment]
Why? And where would you suggest instead?

**Comment by alexreg** [comment]
Thanks for your prompt response.

Because a) they don't belong in places like `/usr/local/bin/`, since they are not executable, b) the Homebrew package manager complains about this.

I would suggest they go in one of the `.../share/` or `.../libexec/` directories, personally. e.g. `/usr/local/share`

**Comment by kripken** [comment]
Sounds ok to me. I don't quite understand how cmake decides to install files - I suppose files in our local `bin/` go to `/usr/local/bin`? So we'd need to create a `share` directory which installation would copy to `/usr/local/share`?

**Comment by alexreg** [comment]
Yeah, I think so. Though I don't understand cmake very well either. In any case, I'm sure cmake is capable of doing this...
