### ISSUE TITLE
[HELP NEEDED] Compile C to WebAssembly with C library Dependency.

### ISSUE THREAD

**Issue by liul8258** [WebAssembly/binaryen#952]
Is there anyway I can do static link when compiling C code to WebAssembly when using the llvm back-end and s2wasm.

More details to the question:
I was trying to compile the following C code into WebAssembly using llvm backend and s2wasm:
````c
#include <math.h>
int doSomeMath(int input) {
    double output;
    output = cosh(input);
    return output;
}
````

I compile the above C code using:
````bash
clang -emit-llvm --target=wasm32 -O0 input.c -c -o output.bc 
llc -asm-verbose=false -o output.s input.bc
s2wasm input.s > output.wast
````

I get the output .wast file as:
````
(module
  (type $FUNCSIG$dd (func (param f64) (result f64)))
  (import "env" "cosh" (func $cosh (param f64) (result f64)))
  (table 0 anyfunc)
  (memory $0 1)
  (data (i32.const 4) " \'\00\00")
  (export "memory" (memory $0))
  (export "doSomeMath" (func $doSomeMath))
  (func $doSomeMath (param $0 i32) (result i32)
    (local $1 f64)
    (local $2 i32)
    (i32.store offset=4
      (i32.const 0)
      (tee_local $2
        (i32.sub
          (i32.load offset=4
            (i32.const 0)
          )
          (i32.const 16)
        )
      )
    )
    (i32.store offset=12
      (get_local $2)
      (get_local $0)
    )
    (f64.store
      (get_local $2)
      (tee_local $1
        (call $cosh
          (f64.convert_s/i32
            (get_local $0)
          )
        )
      )
    )
    (i32.store offset=4
      (i32.const 0)
      (i32.add
        (get_local $2)
        (i32.const 16)
      )
    )
    (i32.trunc_s/f64
      (get_local $1)
    )
  )
````
The .wast code would require me to import "cosh" into environment. Is there anyway I can statically link "cosh" function so I don't need to import "cosh"?

(Thank you for reading this. If this is not the best place to ask for help, please let me know where I should post this and I will appreciate it very much)

**Comment by kripken** [comment]
When you use [emcc with the wasm backend](https://github.com/kripken/emscripten/wiki/New-WebAssembly-Backend), it will link in system libraries for you, so it would generate the compiled code for that method and link it in statically.

**Comment by liul8258** [comment]
@kripken Thank you for the reply. Will try it right now.
