### ISSUE TITLE
ams2wasm.h assert when using emscripten_coroutine_next()

### ISSUE THREAD

**Issue by lukester1975** [WebAssembly/binaryen#955]
Hi

I'm not sure if this a new issue or not, but I tripped over the following trying to create a minimal test case for another issue. Interestingly, my regular code builds OK - I have the coroutine code in a separate library, maybe that's why?

Anyway, this:

```
#include <emscripten.h>

void Coro(void *)
{
}

int main()
{
	emscripten_coroutine coro = ::emscripten_coroutine_create(&Coro, 0, 0);

	::emscripten_coroutine_next(coro);

	return 0;
}
```

Fails to build:
```
em++ main.cpp -std=c++11 -o main.html -O3 -s ASYNCIFY=1 -s WASM=1
___async
Assertion failed: mappedGlobals.find(name) != mappedGlobals.end() ? true : (std::cerr << name.str << '\n', false), file C:\Users\luke\.emscripten_ports\binaryen\binaryen-version_30\src\asm2wasm.h, line 1604
Traceback (most recent call last):
  File "C:\Program Files\Emscripten\emscripten\incoming\\em++", line 16, in <module>
    emcc.run()
  File "C:\Program Files\Emscripten\emscripten\incoming\emcc.py", line 2170, in run
    subprocess.check_call(cmd)
  File "C:\Program Files\Emscripten\python\2.7.5.3_64bit\lib\subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[u'C:\\Users\\luke\\.emscripten_ports\\binaryen\\binaryen-version_30\\bin\\asm2wasm', 'main.temp.asm.js', '--total-memory=16777216', '--emit-jsified-potential-traps', '-O3', '--mem-init=main.html.mem', '--mem-base=1024', '--wasm-only', '-o', 'main.wasm']' returned non-zero exit status -1073740791
```

With binaryen v30, emscripten incoming 951d6f29357a14582cd006fc9468d39fab0cb6e9, fastcomp 055978fe41e35b302fc75661346c0e61adf65dd4. It's OK without -s WASM=1.

Note I changed the assert from 

```assert(mappedGlobals.find(name) != mappedGlobals.end())```
to
```assert(mappedGlobals.find(name) != mappedGlobals.end() ? true : (std::cerr << name.str << '\n', false));```

to get a bit more info. I know ASYNCIFY is pretty much unsupported but thought I'd mention it!

Regards

Luke.

**Comment by kripken** [comment]
Looks like a bug in asyncify in emscripten, when running with asm.js validation it says

````
a.out.js:5:22736 warning: asm.js type error: '___async' not found in local or asm.js module scope:
````

A dependency issue, coroutine create/next don't pull in all of asyncify. Fixed in https://github.com/kripken/emscripten/commit/6b6396e5714b4c4c4c965d6dbc24e673b5f65a2d (although I don't even know if coroutines should work without the other stuff... but this fix can't hurt!).
