### ISSUE TITLE
Build failure on ARM

### ISSUE THREAD

**Issue by H-Plus-Time** [WebAssembly/binaryen#965]
This seems (well, _is_) down to the inclusion of the SSE flags in [CMakeLists.txt](https://github.com/WebAssembly/binaryen/blob/0f3102d13617e70b598e7d82f12684d8fa01969b/CMakeLists.txt), line 98-99. Removing those two lines resolves the problem.

As far as I'm aware, cmake does not provide an architecture flag (though WIN32, MSVC evidently work), though executing `uname -m` should be sufficient.

How central are SIMD operations to binaryen's performance?  Ideally I'd like to keep SIMD and support ARM, but given the...weirdness of gcc/g++ flags (see [Stackoverflow|Detect neon availability](http://stackoverflow.com/questions/37050532/detect-arm-neon-availability-in-the-preprocessor)), it would be considerably more expedient to provide degraded performance (no neon instructions) on ARM, followed by a more complete solution at a later date.

**Comment by kripken** [comment]
I'd guess it doesn't matter much. In a few tests I ran now I see no difference. So we can just remove those.

**Comment by binji** [comment]
IIRC, using sse2 is required on x86 32-bit so it performs the correct floating point arithmetic. This is why I turned it on in wabt, anyway.

**Comment by kripken** [comment]
Oh, right! This was a correctness fix for the interpreter, thanks @binji.

So not so easy to remove...

**Comment by dschuff** [comment]
Surely it shouldn't be too hard to include the SSE flags conditionally on the target architecture though.

**Comment by binji** [comment]
Perhaps there's a clever way to do this, but I ended up having to do some tricky logic to do this in wabt: https://github.com/WebAssembly/wabt/blob/master/CMakeLists.txt#L116

**Comment by H-Plus-Time** [comment]
Compiling a dummy executable probably _is_ the clever way of doing it, since file is a fair bit more stable than uname. [PR 978](https://github.com/WebAssembly/binaryen/pull/978) is pretty much identical to the linked wabt implementation.

**Comment by froydnj** [comment]
Looks like #978 got fixed, so this can be closed now?
